### ISSUE TITLE
Should  a type`T[M][N]` mean `(T[M])[N]` or `(T[N])[M]`?

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-spec#1001]
**Description:**
According to spec 

> `array-type-descriptor := member-type-descriptor [ [ array-length ] ]` 

which implies `int[1]` as the member-type-descriptor of `int[1][2]` but in java and in the current implementation the member type is `int[2]` which causes the following to be a compilation error.

```bal
  int[1][3] array = [[45], [444], [7]];
```
If we follow the spec we will also need to mention dimensions in member access expression in reverse order.

ie: 
```bal
int[Diamention1][Diamention2] a;
```
Needs to be accessed as
```bal
a[Diamention2][Diamention1]
```

So my question is which one should we preserve the behavior of the spec or behavior of java which is also in the current implementation?

**Related Lang Issue:**
https://github.com/ballerina-platform/ballerina-lang/issues/32282

**Comment by rdulmina** [comment]
@jclark @hasithaa @MaryamZi @rdhananjaya WDYT?

**Comment by rdhananjaya** [comment]
1. I think the current behavior is a spec deviation. 
`int[1][3] is (int[1])[3]`

2. This access pattern look fine to me. 

```
int[1][3] a = []; // array of arrays
int[1] inner = a[2];
int member = inner[1]; // we can also write this as a[2][1]

type IA1 int[1];
IA1[3] b = [];
int[1] inner2 = b[2];
```

**Comment by hasithaa** [comment]
We try to keep familiarity with C family languages. Here is Java spec https://docs.oracle.com/javase/specs/jls/se7/html/jls-10.html.

**Comment by rdhananjaya** [comment]
But we don't have an array initializer similar to the Java right?

**Comment by jclark** [comment]
`int[1][2]` is not a type in Java.  From https://docs.oracle.com/javase/specs/jls/se7/html/jls-10.html#jls-10.1

> An array type is written as the name of an element type followed by some number of empty pairs of square brackets []

`T[]` in Ballerina means an array of T and `T[N]` means length N array of T.

So a type `int[1][3]` has to mean length 3 array of (length 1 arrays of `int`). 

Neither Java nor Ballerina have multi-dimensional arrays: they have nested arrays (arrays of arrays).

This does create counter-intuitive result that if you have a variable `x` of type `string[2][3]` and you access it with an expression `x[i][j]` then i must be < 3 and j must be < 2.  This is consequence that we have borrowed C syntax but used it in a different context.

I don't understand what jBallerina has implemented. In the jBallerina implementation are these definitions of T the same?

``
type T1 int[1];
type T T1[3];

type T int[1][3];
```

**Comment by manuranga** [comment]
Yes they are different. `int[1][3]` is interpreted as `(int[3])[1]`. Which is more ergonomic. Some languages (Go, ect) get round this by doing `[1][3]int`, but it feels awkward.

**Comment by jclark** [comment]
That's definitely not what the spec says: to make that work, the syntax tree for an array-type-descriptor would need to have multiple pairs of square brackets following the member type.

**Comment by jclark** [comment]
Interpreting `int[1][3]` as `(int[3])[1]` is pretty strange (although I understand the motivation). I can't think of any case in any C-family language where adding parentheses reorders things like this.

My conclusion is that our fixed-length array syntax is bad: if reasonable people who are very familiar with C/Java languages can interpret it in completely different ways, then it's just not a good design.

We already have the situation that `int[3]` is the same as `[int,int,int]`, so one approach might be to build on that e.g. `[int*3]`.

**Comment by manuranga** [comment]
Let's consider following line of C code.
`int y[4][3] = { { 1 }, { 0, 1 }, { }, { 0, 0, 0, 1 } };`
It's internally different since Ballerina has to provide storage identity for inner arrays, but under current jBallerina implementation following works.
`int[4][3] y = [[1],  [0, 1], [], [0, 0, 1]];`

**Comment by jclark** [comment]
I have edited the title to correspond to what I think the actual issue is: the spec grammar makes`T[M][N]` means `(T[M])[N]`; but jBallerina (for understandable reasons) makes it mean `(T[N])[M]`.

My view is

- I don't like the consequences of what the spec does, but
- I find interpreting `T[M][N]` as `(T[N])[M]` deeply weird

**Comment by hasithaa** [comment]
Here is my view, 

**Case 1**: If `T[N][M][O]` means `( ( T[O] )[M] )[N]` - Current JBallerina behavior

* Member access expression. 
  - Current `expr[i][j][k]` where i< N, j<M, k<O, It preserved the length order same as the type descriptor.
  - `expr[i]` give a type of T[M][O]
  - Semantics are easy to understand with type descriptor
* List Constructor
  - `[ N elements [ M elements  [ O elements ] ] ]`
  - It also preserved the length order same as the type descriptor.
* Problem 1: Recursive type definitions syntax will not work with grouping.	
* Problem 2: Mixing type descriptors leads to complex semantics
e.g.
```
type Tn int[N];
type Tm Tn[M];
type T2 Tm[O]; // int[O][M][N];

type T int[N][M];
type T3 T[O]; // (int[N][M])[0] => int[O][N][M];
```

**Case 2:** If `T[N][M][O]` means `( ( T[N] )[M] )[O]`
* Type descriptors are consistent.
* Index access expression - need to change the JBallerina semantics.
* List Constructor expression - need to change the JBallerina semantics. 
* Will be a breaking change.
* Will be a problem for those who are familiar with C and Java semantics. 

I am kind of OK with Case 2. Even though it's a breaking change, usage of closed array and an array of array cases are not much.

**Comment by jclark** [comment]
@hasithaa I don't understand why case 2 needs any change in jBallerina semantics for index access expressions or list constructor expressions.  As far as I can tell, the only issue here is what the type descriptor means. In other words, can I not make jBallerina behave in a spec-compliant way just by transforming every `T[M][N][O]` to `((T[O])[N])[M]`?

**Comment by hasithaa** [comment]
Yes, You are right. We don't need to change the semantics in Case 2. I interpreted it differently.

>  In other words, can I not make jBallerina behave in a spec-compliant way just by transforming every T[M][N][O] to ((T[O])[N])[M]?

Yes, we can.

**Comment by rdulmina** [comment]
Adding to @hasithaa's view

For **Case 2** Current `expr[i][j][k]` where` i< O, j<M, k<N`, Does not preserve the length order as the type descriptor.

**Comment by jclark** [comment]
@hasithaa Great! That also means it is straightforward to change the spec to match jBallerina's behaviour. The array-type-descriptor grammar would allow multiple pairs of square brackets.  Then the spec just has to say that `T[D1]...[Dn-1][Dn]` means `(T[Dn])[D1]...[Dn-1]`.

**Comment by lochana-chathura** [comment]
> The array-type-descriptor grammar would allow multiple pairs of square brackets

If we do the above,

```
int[N][M][O]; // means ((int[O])[M])[N];
```

```
type Tn int[N];
type Tm Tn[M];
type T2 Tm[O]; // means ((int[N])[M])[O]
```
Isn't that confusing?

I am a bit lean towards case 2. Although it will be a problem for those who are familiar with C and Java semantics, as @rdhananjaya originally said in https://github.com/ballerina-platform/ballerina-spec/issues/1001#issuecomment-982511187, that access pattern looks fine to me also.

**Comment by hasithaa** [comment]
Even though Case 2 is consistent with other type descriptor syntax, for a person familiar with C and Java, case 1 makes more sense. Also, breaking change at this level is not good IMO.  +1 to change the spec to match jBallerina's behavior.

**Comment by jclark** [comment]
Both alternatives will be confusing, but  I'm leaning towards the jBallerina behaviour.

We can imagine three groups of users with different levels of knowledge of Ballerina

1. low - don't really know what's going on; haven't read little or no docs; trying to use Ballerina based on what they know from C/Java
2. medium - have some understanding of how it all works
3. high - experts who have read the docs and know all the details

If we go with the current spec behaviour, level 1 will be confused; levels 2 and 3 won't be.

If we go with the jBallerina behaviour, level 2 will be confused, but levels 1 and 3 won't be.

I think it's better to favour group 1.  I expect a significant percentage of users will never get beyond level 1.  Users who have got to level 2 are willing to learn and can be taught the jBallerina behaviour, which can be explained simply.

**Comment by jclark** [comment]
I will go ahead and change the spec accordingly.
