### ISSUE TITLE
Add array:some/every langlib function

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#1005]
JavaScript has these. We should too.

These are particularly important because they cannot be done nicely with query expressions (because we do not have aggregation #441)

**Comment by jclark** [comment]
User request on Slack for these: https://ballerina-platform.slack.com/archives/C47EAELR1/p1638816547142000

**Comment by jclark** [comment]
Another reason this is important is that Ballerina does not provide a way to work around this yourself: see #1006

**Comment by jclark** [comment]
These would look like:

```ballerina
// lang.array
public isolated function some(Type[] arr, @isolatedParam function(Type val) returns boolean func) returns boolean = external;
```

**Comment by KavinduZoysa** [comment]
@jclark, regarding the `array:every` function, if the array is empty, do we need to return `false`? In JavaScript it returns `true`.

**Comment by jclark** [comment]
It says to return

   true if func returns true for every member of `arr`

This applies when the array is empty. But let me make it more explicit.
