### ISSUE TITLE
Add langlib function to dynamically call a function

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#1006]
We really need a way to dynamically call a function. For example, if you try to workaround #1005 in Ballerina, you will fail because there is no way to write a type-unsafe function call.

```ballerina
function every(any[] v, boolean(any) returns boolean testFunc) {
   foreach var x in v {
     if !testFunc(x) {
        return false;
     }
  }
  return true;
}

function isEmployee(Person p) returns boolean {
  //..
}

function allEmployees(Person[] persons) returns boolean {
   // call will get type-check error for 2nd argument (because of contravariance)
   return every(persons, isEmployee); 
}
```

The workaround (which is painful) would be to write a cast at each call site:

```ballerina
  return every(persons, x => isEmployee(<Person>x));
```

With dynamic call, we can make it work:

```ballerina
function every(any[] v, function testFunc) {
   foreach var x in v {
     if <boolean>testFunc.call(x) {
        return false;
     }
  }
  return true;
}
```

Separately it would be useful to be able to write a function type where the arguments are unconstrained but the return type is constrained, so above can be improved to:

```ballerina
function every(any[] v, function returns boolean testFunc) {
   foreach var x in v {
     if testFunc.call(x) {
        return false;
     }
  }
  return true;
}
```

**Comment by jclark** [comment]
The langlib function would look like this:

```
// module lang.function
@typeParam
type Type any|error;

public function call(function returns Type func, any|error... args) returns Type;
```

**Comment by jclark** [comment]
@hasithaa We should prioritize this: it's pretty fundamental. Would it be hard to implement?

**Comment by jclark** [comment]
Need to investigate right choice of name: this is `apply` in Scheme.

**Comment by hasithaa** [comment]
This is doable, We already have a runtime API to invoke dynamic functions at runtime. This function should be isolated. isn't it. 

We need to implement the type checking part to support "function returns T".

**Comment by jclark** [comment]
We need to use @isolatedParam here.

**Comment by jclark** [comment]
Revised function definition with `isolated`:

```ballerina
// module lang.function
@typeParam
type Type any|error;

// This panics if the arguments are not of the right type for the function
// (need to define precisely what this means)
public isolated function call(@isolatedParam function returns Type func, any|error... args) returns Type = external;
```
I think `call` is the right name for this. It is similar to `Function.call` in JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call

`apply` would be similar but would take a list:

```
public function apply(function returns T func, (any|error)[] argList) returns Type;
```

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply

**Comment by jclark** [comment]
This needs the `function returns T` syntax also.

**Comment by jclark** [comment]
@hasithaa @gimantha There's a problem with `function returns T` syntax.  Usually omitting `returns T` means `returns ()`, but `function` currently means any function. So it would be inconsistent to:

1. allow `function`
2. allow `function returns T`
3. but make meaning of `function` not the same as `function returns ()`

**Comment by jclark** [comment]
So, for now, I have not messed added the new function type descriptor syntax, so the return type of `call` is `any|error`.

**Comment by hasithaa** [comment]
1. `function`  - any function
2. `function returns T` - any function with return type `T`
3. `function (...)` - any function with some parameter and return type ()
4. `function (...) returns T` - any function with some parameter and return type T

I think 2 is consistence (since 1 is not the same as omitting `return T` as we discussed when we introduced it). For a beginner seeing the difference between the above can be a problem. But most of the time, library developers need this.

**Comment by jclark** [comment]
> I think 2 is consistence (since 1 is not the same as omitting `returns T` as we discussed when we introduced it).

I don't understand.  We didn't introduce `function returns T`, so `function` wasn't the same as omitting `returns T` from anything.  If we now introduce `function returns T`, then `function` will be `function returns T` without the `returns T` i.e. `function` will be `function returns T` with `returns T` omitted by definition, and omitting `returns T` will be different in this case than in other cases.  How is that consistent?

> `function (...)`

I am not sure if you are proposing this as a new syntax.  But it would be a consistent approach:

* `function (...)` - a function taking any arguments and returning nil
* `function (...) returns T` - a function taking any arguments and returning T

Then `function` would be short for `function (...) returns any|error`.  Note that `function (....)` is different from `function (any|error...)` because of contravariance.

**Comment by jclark** [comment]
Separated out function type syntax into a separate issue #1112.  For now, we will just use `function` to declare the type of the `call` function.

**Comment by jclark** [comment]
In import you should not have to quote `function`: it needs to be added to https://ballerina.io/spec/lang/master/#predeclared-prefix

**Comment by jclark** [comment]
@chiranSachintha The key point is that it is the caller's responsibility to provide defaults not the callee's.  Your example is arguably OK, because `value` is declared with a type descriptor that has defaults.
