### ISSUE TITLE
Clarification on constant-reference-expr

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#1008]
**Description:**
Depending on where it is used, a constant-reference-expr could mean either the value or the typedesc, right?

The spec does say

> A compile-time constant can be used like a variable, and can also be referenced in contexts that require a value that is known at compile-time, such as in a type-descriptor or in a match-pattern.

Would appreciate confirmation that where we have

```ballerina
const map<int> M = {a: 1};
```

1. referring to `M` would mean a typedesc only in contexts where a type-descriptor known at compile-time is expected.

e.g.,
```ballerina
public function main() {
    any a = 1;

    if a is M { // as the type-descriptor in a type test

    }

    M _ = {a: 1}; // as the type-descriptor of a variable declaration
    M[] _ = [M, {a: 1}]; // in the type-descriptor of a variable declaration
}
```

2. in other contexts, it would mean the value, which would mean

using it in the match statement is possible (where M means the value)

```ballerina
function fn(any a) {
    match a {
        M => { // `M` is used here
        }
    }
}

```

Also

```ballerina
map<int> _ = M;
```

is OK but 

```ballerina
typedesc _ = M;
```

will result in an error?

**Comment by jclark** [comment]
Does

   https://ballerina.io/spec/lang/2021R1/#singleton-type-descriptor

not answer your question?

**Comment by MaryamZi** [comment]
It does, thank you.
