### ISSUE TITLE
Explicit initialization function for modules 

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#101]
Should we allow developers to declare an explicit module init function?  The module init function can be used to initialize module-level variables. Sometimes it is hard to initialize them in the initializer expression. Another use case would be to initialize the final variables conditionally.

**Comment by jclark** [comment]
I think this would be a useful feature to add a some point. Is the function called `init` like `main` or `__init` like an object initializer?

**Comment by sameerajayasoma** [comment]
I think we should make this `__int`, because it is similar to the object initializer. It is a function with module-level visibility which cannot be called by the module code.

**Comment by sanjiva** [comment]
+1.

**Comment by jclark** [comment]
Return value would need to be subtype of `error?` like __init on objects. Must not have public visibility
