### ISSUE TITLE
Short-circuit evaluation in nil lifting operations 

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#1013]
**Description:**
Nil lifting section doesn't specify whether the evaluation of operands should be short-circuiting or not. JBallerina seems to perform a short-circuit when one operand is nil.

```ballerina
import ballerina/io;
public function main() {
    int? r = foo() + bar(); // only evaluate foo
}

function foo() returns int? {
    io:println("foo");
    return ();
}

function bar() returns int? {
    io:println("bar");
    return ();
}
```

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
> A nil-lifted-expr is evaluated by evaluating the subexpressions for each operand. If the result of any of these evaluations is nil, then the result of the nil-lifted-expr is nil. 

Isn't that clearly saying that there is no short-circuiting?

(It doesn't short-circuit because the general rule in C-like languages is that only specific operators have short-circuiting behaviour.)

**Comment by rdhananjaya** [comment]
To me, it feels like it's implied that there is no short-circuiting, but I like to have it more directly stated.

**Comment by jclark** [comment]
Would changing "each" to "every" make it clearer?

Something like 0*foo() isn't short-circuited either, so I don't think this is the place to say more. We could add something elsewhere saying that expression evaluation always evaluates subexpressions except where explicitly stated not to.

**Comment by rdhananjaya** [comment]
I like "every", I think it conveys the idea stronger than "each".
