### ISSUE TITLE
Improve read-only difference using limited expressiveness of inherent types

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#1014]
#828 makes something like this an error:

```ballerina

type R record {|
    int x;
|};

type S record {|
    string x;
|};

function f(R|S v) {
    if v is R { }
    else {
      S _ = v; // error
    }
}
```

It is not safe to narrow the type of c to S in the else branch, because the inherent type of v could be `record {| string|int x; |}` in which case the inherent type of v would be a subset of R|S but neither a subset of R nor a subset of S.

But suppose R and S were defined like this:

```ballerina

type R record {|
    int x;
|};

type S record {|
    int y;
|};
```

Suppose our record types had a `oneof` feature (like protobuf). Then you could use this to create a value for v that would make the narrowing of `v` to `S` be incorrect for this case:

```ballerina
type RS {|
   oneof {
      int x;
      int y;
   }
|};
```

However, we don't actually have `oneof`, and if we are willing to commit to not having it, then we could potentially make use of that.

**Comment by jclark** [comment]
This relates to https://github.com/ballerina-platform/ballerina-lang/issues/33722

**Comment by jclark** [comment]
The general situation is that we have

- a variable v with static type T
- a mapping type R
- an if statement `if v is R { } else { }`
- we need to compute a type for v in the else branch
- assume v is mutable mapping with inherent type V
- if `v is R` fails, we know that V is not a subset of R
- we know that V is a subset of T
- we want to compute the smallest set S such that V is a subset of S

The idea is to make use of the fact that V must be describable using a record type.

In this case:

```ballerina
type R record {|
    int x;
|};

type S record {|
    int y;
|};

type T R|S;

function f(T v) {
    if v is R { }
    else {
      S _ = v; // error
    }
}
```
- T is mappings with one member named x or y, with type int
- R is mappings with one member named x, with type int

We know that V is non-empty and is a subset of T but not a subset of R.  If V is described by a record type descriptor, what must that look like:

The fact that it is a subtype of T means
- it cannot have a `...` field 
- it can only have x and y fields
- it cannot have both x and y fields
- the type of any field must be a subtype of int
- the fields cannot be optional

This means there are only two possibilities for V

```ballerina
type V1 record {| M x; |}
type V2 record {| M y; |}
```

where in both cases M is a subtype of `int`. But since V1 is a subtype of R, the only possibility left for the else branch is V2, and every V2 is a subtype of S.

**Comment by jclark** [comment]
When computing T -<sub>ro</sub> R, what we need to do it to widen R  to a type R', such that any inherent type V that is a subset of T and overlaps R is a subset of R'.

**Comment by jclark** [comment]
Here's a way of thinking about it visually. This doesn't deal with the expressiveness that optional types give, but I think it's helpful anyway.

Imagine a Venn diagram where the universe is T, and there is a circle for every field x that is distinguished by T that contains mappings that have a field x. Then an inherent type (not involving optional types) must be wholly within one region of that Venn diagram: it cannot cross two regions.  So we can find R' just by expanding it to filling out any regions of that Venn diagram partially occupied by R.

**Comment by jclark** [comment]
cc @rdhananjaya

**Comment by jclark** [comment]
Another potential direction to improve read-only difference is #1017.

**Comment by jclark** [comment]
Another way to approach the problem is to ask what are the conditions on T and R, such that we can safely make T -<code>ro</code> R be T - R?

The condition must ensure that there can be no inherent type that is contained in T and contains some but not all of R. So the condition must be sufficient to prove that for any inherent type V that is a subset of T, the intersection of V and R is either empty or R.

**Comment by jclark** [comment]
This needs to go in the spec if jBallerina is going to implement it for GA.

**Comment by sanjiva** [comment]
This sounds more understandable to me ...

**Comment by jclark** [comment]
Unfortunately I have made a mistake: the rule in https://github.com/ballerina-platform/ballerina-spec/issues/1014#issuecomment-1005306096 is simple but wrong; it doesn't work because of optional fields.

```
type  X record {|
   int x;
|};

type R record {|
   int x;
   int y;
|};

type T R|X;

function foo(T v) {
    if v is R { }
    else {
       X _ = v;
    }
}

type V record {|
    int x;
    int y?;
|};

function bar() {
   V v = { x: 0 };
   foo(v);
}
```

We need a condition that ensures that it is impossible for there to be an inherent type V that contain values both from R and from T - R. This means you cannot have a set of fields F in T and F' in T - R such that F is a subset of F' or vice-versa.

**Comment by jclark** [comment]
For Swan Lake, @MaryamZi implemented a more elaborate version of https://github.com/ballerina-platform/ballerina-spec/issues/1014#issuecomment-1005306096 by partitioning T into disjoint sets based on the field names. This has the same problem with optional fields.

The idea of partitioning based on field names is still a good one, but we have to partition in such a way that for every shape all the field names belong to a single partition.

**Comment by jclark** [comment]
Conclusion from discussion with @hasithaa and @MaryamZi is that it is too late to do anything about this for Swan Lake. It doesn't create a problem for jBallerina because jBallerina does not recognize V as being a subtype of T. It will only create a problem when jBallerina implements semantic subtyping.

In the meantime, we can try to devise a better approach to solving this problem.

**Comment by jclark** [comment]
This is now irrelevant with new approach to cells.
