### ISSUE TITLE
Typo max positive value for int:Signed32 is wrong

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/ballerina-spec#1038]
In [spec](https://ballerina.io/spec/lang/2021R1/#built-in_subtypes) max positive value of int:signed32 is given as  2,147,483,6487 (extra 8 before 7)

**Comment by jclark** [comment]
You are looking at the old version of the spec It is fixed in the current version https://ballerina.io/spec/lang/2022R1/#built-in_subtypes
