### ISSUE TITLE
Allow annotations within type cast expression

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#105]
**Description:**
It was discussed [1] to use type conversion operator to replace `untaint` unary operator as follows.
```ballerina
var ut = <@untainted> taintedVal;
```

In order to do that, we need a source only annotation attach point within type conversion operator.

[1] - [https://docs.google.com/document/d/1ZVSOpsiv2vewk8HL9jcbNZIVqI06OZJzxG4CeE9WVwE/edit#](https://docs.google.com/document/d/1ZVSOpsiv2vewk8HL9jcbNZIVqI06OZJzxG4CeE9WVwE/edit#)

**Comment by jclark** [comment]
At the moment the syntax for type-cast-expr is:

```
type-cast-expr := < type-descriptor > expr
```

and type-descriptor does not allow annotations.

Also I think

```
string us = <@untainted string> ts;
```

should be equivalent to

```
@untainted
type UntaintedString string;
string us = <UntaintedString>ts;
```
So I think this should use the `type` attachment point.

Thus I see the changes you actually need as:

1. allow annotations before the type descriptor in type-cast-expr
2. say that the `type` attachment point covers this case as well as module-type-defn
3. allow type-cast-expr not to have a type-descriptor

I don't see any problems with the first two. I need to think a bit more about the last.

**Comment by jclark** [comment]
After thinking about it some more, I think `<@untainted>` is fine.  I think the same pattern will also work for immutability, with e.g. `immutable` in the language or as an annotation.
