### ISSUE TITLE
Order of execution of named workers

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-spec#1058]
**Description:**

In the spec, the order of execution of named workers within same thread cannot be found. It only says,
```
When a function has named workers, the function's default worker executes in three stages, as follows:
  The statements in default-worker-init are executed.
  All the named workers are started. Each named worker executes its statement-block on its strand.
  The statements in default-worker are executed. This happens without waiting for the termination of the named workers started in stage 2.
```
And also in the current implementation it is after both the `default-worker-init` and `default-worker` statements in all function calls execute, the named workers in the same thread start.

**Suggested Labels:**

   
**Code sample that shows issue:**
https://github.com/ballerina-platform/ballerina-lang/issues/35058#issuecomment-1050616109

**Related Issues:**

https://github.com/ballerina-platform/ballerina-lang/issues/35058

**Comment by jclark** [comment]
The named workers run in parallel. The order in which they start is not defined. Does it need to be?

**Comment by manuranga** [comment]
jBallerina's current Scheduler is LIFO, this was chosen by performance numbers (by @vinok88). Last in is warm in memory so it's faster to run. In this case it shouldn't matter since all are cold.

Should the overall strategy be changed or just this specific case?

**Comment by vinok88** [comment]
At the time of implementing this, it was said that we only guarantee that all the workers Wil run in same thread. Even if we schedule them in the order they appears, it does not guarantee that it will finish the same order due to blocking actions. Imo we should not define such a constraint.

**Comment by vinok88** [comment]
Additionally, if we make sure each worker executes one after the other, then what is the difference in defining a worker and just writing it sequencially.

**Comment by jclark** [comment]
Thinking about it some more, I don't think the spec needs to say anything about the order in which the named workers are started: when you `start` a function, there's no guarantee that the function will run immediately before yielding.

**Comment by vinok88** [comment]
@jclark, exactly ! I think we commented the same thing same time 😊
