### ISSUE TITLE
Clarification on `lang.value:substring` method

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-spec#1061]
**Description:**

`lang.value:substring` creates a substring from the start index (inclusive) to the end index (exclusive).

https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.string/src/main/ballerina/string.bal#L64

Currently when "effective end index - startIndex"
* is -1 : returns empty string
* is < -1 : panics

As details regarding what should be the correct behaviour is not found in the spec, is the current behaviour correct or what should be the behaviour in the above two cases?

**Suggested Labels:**

   
**Code sample that shows issue:**
```bal
import ballerina/io;

public function main() {
    string str = "ABCDEF";
    io:println(str.substring(1, 1)); // empty string - start index 1, effective end index - 0
    io:println(str.substring(2, 1)); // panics - "message":"invalid substring range. Length:'6' requested: '2' to '1'"
                                     //            start index 2, effective end index - 0
}
```

**Related Issues:**

https://github.com/ballerina-platform/ballerina-lang/issues/27474

**Comment by jclark** [comment]
Not sure what you mean by "effective end index".

If endIndex == startIndex, then the result is the empty string.

Generally in Ballerina, when indices are out of bounds the result is a panic, so the following should all panic:

* `startIndex > endIndex`
* `startIndex < 0` 
* `endIndex > length()`

**Comment by Nadeeshan96** [comment]
Got it, Thank you!!
