### ISSUE TITLE
Run strands safely on a separate thread

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#1068]
Currently the [spec says](https://ballerina.io/spec/lang/2022R1/#section_7.2):

>There are two language constructs whose execution causes the creation of new strands: named-worker-decl and start-action. These constructs may use annotations to indicate that the newly created strand should be in a separate thread from the current strand. In the absence of such annotations, the new strand must be part of the same thread as the current strand.

The platform provides the `@strand` annotation. It's only public definition is this: https://ballerina.io/learn/by-example/strands.html

We can and should do better than this:
- we have no way to *safely* run a strand on a separate thread
- we have no way in the language to run a strand on a separate thread
- `@strand` won't work for nballerina (in nballerina, it is not desirable to allow threads to have concurrent access to mutable structures since that would lead to either losing memory safety or having to lock every operation on a mutable structure)
- we can do much better by leveraging `isolated` (the concept of using the `@strand` annotation predates the `isolated` feature)
- we want to write the dispatcher in Ballerina; the language should make it possible to write the dispatcher so that the strands that it creates automatically use multiple threads when this is safe

The `isolated` feature already provides much of what we need. In particular, when a `start-action` is applied to a function that has isolated type and all the function arguments are isolated expressions, then the newly created strand can be safely run on a separate thread. (I am fairly confident about this, but need to double check.)

The other aspect of this is to extend the `isolated` concept to named workers.  The way this would work is that when a named worker is isolated:
- its body would have similar restrictions to an isolated function and
- it would be safe for the named worker's strand to be run on a separate thread from the function's strand

A related problem is that there is currently a restriction that isolated functions are not allowed to start new strands (this prevents use of both named workers and `start`). This limitation will be a major obstacle to using named workers to implement services.

In this issue, we will deal just with strands created using `start`.  Strands created with named workers will be handled in #1095.

**Comment by jclark** [comment]
One key issue to think about here is what are semantics of an isolated function that creates a strand that continues to execute after the isolated function returns.

**Comment by jclark** [comment]
Related to this is #883.

**Comment by jclark** [comment]
Separate out isolated named worker part into another issue.

**Comment by jclark** [comment]
For this issue, define a start-action to be *isolated*, if

- the method or function being called is isolated
- the expression for every argument is an isolated expression
- for a method-call or client-remote-method-call-action the expression for the object is an isolated expression

Then there are two changes for this issue:

1. the strand created by an isolated start-action can run in a different thread from the current strand
2. an isolated function can contain an isolated start-action

**Comment by lasinicl** [comment]
> It should be an error to use @strand on a start-action or named worker that occurs in a function explicitly declared as `isolated`. Apart from that, not sure.

Also, need to consider what the behavior should be when isolation is inferred for a start-action or a named worker. 

> Has `@strand` been documented for public use? I seem to remember not. Are we using it internally?
> 

We have a BBE for strands: https://ballerina.io/learn/by-example/strands.html

**Comment by jclark** [comment]
We need a strategy for moving away from `@strand`, which predates the work on `isolated`.

**Comment by hasithaa** [comment]
When we find a conflict, the following are the options we can take.

1. Make it a compile-time error. 
2. Ignore Strand annotation and create strand based on isolated analysis. (But we give a compile-time warning)
3. Always Obey Strand annotation.

We can rule out option 3 since we are moving away from the `@strand` annotation. Option 1 is correct IMO, but it breaks backward compatibility. Hence, Option 2 is a better option in both cases where `isolated` is explicit and inferred.

**Comment by jclark** [comment]
We had a discussion today. Summary is that when `@strand` is used on a `start` action or a named worker:

1. if the containing function is explicitly declared as `isolated`, it will be a compile-time error (this situation is a compile-time error today)
2. otherwise
      1. the containing function will not be inferred to be `isolated` (the spec will need to explicitly allow the annotation to affect inference)
      2. the existing `@strand` runtime semantics will continue as now
      3. there will be a deprecation warning saying not to use `@strand`, but instead use the safe features introduced by this issue

**Comment by jclark** [comment]
I am wondering about defaulted arguments in the call in the start-action.

We currently say

> If the function-type-descriptor includes an isolated-qual, then an expression used as a default-expression must meet the requirements for an isolated function

Is that enough?
