### ISSUE TITLE
`on fail` should not require variable to be declared

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#1071]
In an `on fail` clause, you shouldn't need to declare and use a variable (here `err`) if you don't want to.

```
  do {
        http:Client hc = check new (url);
        http:Response _ = check hc->get("/");
        return url + " is up";
    } on fail var err {
        return url + " is down, with error: " + err.message();
    }
```

`_` as a binding pattern doesn't match `error`, so that doesn't work here.

**Comment by jclark** [comment]
We could just make the typed binding pattern optional, so you can say `on fail {`

**Comment by hasithaa** [comment]
This will make it easy to ignore errors.

**Comment by jclark** [comment]
All Ballerina can do is force a programmer to be explicit when they are ignoring an error. If you put "on fail" you are already being explicit, just as if you said "if result is error { }" (which is also allowed).

**Comment by sanjiva** [comment]
Optional typed binding pattern would be ideal.
