### ISSUE TITLE
`ToString` representation of some basic types are not mentioned

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-spec#1072]
**Description:**

In the spec in section https://ballerina.io/spec/lang/master/#ToString information about the `ToString` representation of some of the basic types are not mentioned. Following the section https://ballerina.io/spec/lang/master/#section_5.1.4, `ToString` representation of `function`, `future`, `typedesc`, `handle`, `stream` basic behavioural types are missing. If the information on `tuple` and `record` types are the same as `array` and `map` types respectively, that can be also mentioned, if necessary.

**Suggested Labels:**

   
**Code sample that shows issue:**
```bal
public function main() {
    string funcStr = func.toString();
}

isolated function func(boolean|float firstarg, string secondarg="default", int... thirdarg) returns string {
    return "val";
}
```

**Related Issues:**

https://github.com/ballerina-platform/ballerina-spec/issues/499

**Comment by jclark** [comment]
The table should say `list` and `mapping` rather than `array` and `map`.

**Comment by jclark** [comment]
`toString` used to say

```
- if `v` is any other behavioral type, then the identifier for the behavioral type
#   (`function`, `future`, `service` or `handle`)
#   followed by some implementation-dependent string
```

but that got lost in https://github.com/ballerina-platform/ballerina-spec/commit/b59a88ee4f4699f1053d9d10caa93d592ff57fc5

Is that what jBallerina currently does?

**Comment by Nadeeshan96** [comment]
> Is that what jBallerina currently does?

For the `function`, `future`, `typedesc`, `stream` types - yes.
For `handle` type, it gives the java object.toString() value without having the prefix `handle`.

**Comment by jclark** [comment]
> it is expected to be `typedesc` with some implementation-dependent string representing its describing type

Yes.

> In that case, do we need the spec to mention the `ToString` for types?

Hard to do in general, and will probably change in jBallerina when it implements semantic subtyping. So best just to leave as implementation-dependent for now.

**Comment by HindujaB** [comment]
> > it is expected to be `typedesc` with some implementation-dependent string representing its describing type
> 
> Yes.
> 
> > In that case, do we need the spec to mention the `ToString` for types?
> 
> Hard to do in general, and will probably change in jBallerina when it implements semantic subtyping. So best just to leave as implementation-dependent for now.

Ack. Thanks.
