### ISSUE TITLE
How to handle negative values in `fractionDigits` for `round`

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-spec#1074]
**Description:**

Do we need to panic in `decimal:round` and `float:round` if `fractionDigits` is less than 0.
Spec update : https://github.com/ballerina-platform/ballerina-spec/commit/3ad58130de40f7f829e958032b9c0f85cd7a3906

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
No.  The behaviour is well defined for negative fraction digits: closest decimal value to `x` that is an integral multiple of 10 raised to the power of `-fractionDigits`.
