### ISSUE TITLE
Allow client objects to have resource methods

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#1080]
Currently, resource methods are only allowed for service objects, but they should also be allowed for client objects.

This implies:

1. there needs to be a syntax to call resource methods on clients (which will syntactically be an action)
2. a client object constructor or client class needs to be able to define resource methods
3. a client object type needs to be able to include resource methods

Note that service object types do not currently include resource methods, because there is no way in the language to call the resource method of a service object, but if we allow client object types to include resource methods, we may also want to allow service object types to include resource methods.

In this issue, we do not add resource methods on clients with full generality. In particular:

- hierarchical client resource objects are not support, i.e. resource methods of client objects are not allowed to return client objects
- there is no query concept: a single action will perform a single resource method call

This is sufficient to be useful for HTTP but is not enough for GraphQL.

**Comment by jclark** [comment]
Call syntax

```
resource-method-call-action :=
   expression "->" "/" [resource-access-path] ["." method-name] ["(" arg-list ")"]

resource-access-path :=
   resource-access-segments ["/" resource-access-rest-segment]
   | resource-access-rest-segment

resource-access-segments :=
   resource-access-segment ("/" resource-access-segment ")* 

resource-access-segment :=
   resource-path-segment-name  // same as for definition
   | computed-resource-access-segment

computed-resource-access-segment := "[" expression "]"

resource-access-rest-segment := "[" "..." expression "]"
```

**Comment by rdulmina** [comment]
What is type type of `expression` in `resource-access-rest-segment := "[" "..." expression "]"` should be? Is it a list of strings?

**Comment by jclark** [comment]
In `[...x]`, x has to be a list i.e. a subtype of `T[]` for some T. As to what T must be, it must be the same as what is allowed for `[x]`.  And that in turn is determined by what is allowed by the type descriptor in a resource-path-segment-param.  If the client object defines a remote function with a segment `[T x]` then the call to function needs to provide a value that is a subtype of T.

You can think of the type of the path in the resource definition as being a tuple type, where identifiers correspond to singleton strings. Then the resource-access-path is constructing a list (similar to a list constructor) and the list constructed has to belong to the tuple type (just like the argument list has to match the params). A resource-path-segment-name corresponds to a list member that is a string.

**Comment by rdulmina** [comment]
> 

Got it thank you

**Comment by rdulmina** [comment]
Can we consider  `"->" "/"` as a single token `->/` or should it be two separate tokens allowing `ws`?

**Comment by jclark** [comment]
I prefer two tokens: `->` and `/` .

**Comment by jclark** [comment]
Typing with path params is non-obvious to me. Consider

```
type S1 service object {
   resource function get ["foo"|"bar"]() returns string;
};

type S2 service object {
   resource function get foo() returns string;
   resource function get bar() returns string;
};
```

I think S1 and S2 are arguably the same. They both permit the same resource access: a get of /foo or /bar. The "parameterness" if the path segment is internal to the service.

Now consider the corresponding case on the client:

```
type C1 client object {
   resource function get ["foo"|"bar"]() returns string;
};

client class C2 {
   resource function get foo() returns string { return "foo"; }
   resource function get bar() returns string { return "bar"; }
};

function baz("foo"|"bar" foobar, C1 c) returns string {
   return c->/[foobar];
}

function main() {
  string _ = baz("foo", new C2);
}
```

If this is going to work, then the client remote method call would have to choose the function to be called at runtime (just like a service call does).

**Comment by jclark** [comment]
There's another subtle point about typing. Consider

```ballerina
client object {
    resource function get [string] () returns int;
    resource function get foo () returns boolean;
};
```

The semantics we have for services at the moment is that this is fine and that although a path /foo matches both resource path of `foo` and resource path `[string]`, the former is preferred. So the type of  `c->/foo` will be `boolean`.  This is going to have a big impact on typing.

**Comment by rdulmina** [comment]
If we have something like `c->/[foo]`. We cannot say exactly which type at compile time right? in that case type would be `int|boolean`?

**Comment by jclark** [comment]
> We cannot say exactly which type at compile time right?

Usually not. But you could in a case like:

```
function get(string x) returns int {
  return x == "foo" ? 0 :  c->/[x];
}
```

**Comment by rdulmina** [comment]
Yes, currently in the implementation when we narrow `x - "foo"` type type of `x` still will be string. I think the ideal sample would be 
```bal
function get(string x) returns boolean {
  return x == "foo" ? c->/[x] :  false;
}
```

**Comment by rdulmina** [comment]
resource-path-segment-param := [[[annots](https://ballerina.io/spec/lang/master/#annots)] [type-descriptor](https://ballerina.io/spec/lang/master/#type-descriptor) [[param-name](https://ballerina.io/spec/lang/master/#param-name)]]

In here the param name is optional only in `object-type-decl` right? it's compulsory in `object-type-defn`?. same as param name in function signature for `function-type` and `function-defn`?

**Comment by jclark** [comment]
@rdulmina Right  - same as in function signatures

**Comment by jclark** [comment]
@rdulmina I just thought of this:

```
const FOO = "some long segment name";

service class S {
   resource function get [FOO]() returns string;
      return FOO;
   }
}
```

This is like record constructors `{ [FOO]: "value of foo" }`.

**Comment by rdulmina** [comment]
So in here `[FOO]` is the same as `[FOO FOO]`?. I wonder is there any practical usage of this

**Comment by jclark** [comment]
Well, it's not exactly the same: `[FOO]` wouldn't declare a parameter name, so it's more like `[FOO _]` except that we don't allow that.

Yes: I can certainly see this being practical useful.  It's not hard to imagine cases where you want to use constants in path.

**Comment by rdulmina** [comment]
Got it

**Comment by jclark** [comment]
@hasithaa @rdulmina @shafreenAnfar I've rewritten most of what the spec says about resources.  See:

- https://ballerina.io/spec/lang/master/#section_5.5.3.5 (types)
- https://ballerina.io/spec/lang/master/#resources_defn (object constructor)
- https://ballerina.io/spec/lang/master/#client-resource-access-action (actions)

I still need to say a bit more about how hierarchical resources work (where there's an XXX)

**Comment by jclark** [comment]
Current draft allows this, but shouldn't:

```
service object {
   resource function put x();
   resource function get x() returns service object {
          resource function put .();
   }
}
```

A delegating method needs to be considered as conflicting no matter what the resource method name is.

**Comment by jclark** [comment]
@rdulmina @hasithaa I think have now got the semantics for paths right. Please check.

**Comment by hasithaa** [comment]
> clientRef->/'1; // Note the quoted identifier

The compiler treats identifiers as strings; if we consider `'1` as int `1` that is like a conversion. So this is a compile-time error. 
For this, We can use computed resource name syntax `[1]`

**Comment by jclark** [comment]
@hasithaa I agree.

The listener implementation may do conversions but that is listener-dependent.

**Comment by hasithaa** [comment]
JBallerina implementation disallows external service resource functions. But when it comes to the client resource functions, allowing it makes sense, because `inferred-typedesc-default` requires the functions to be external.  This is required for the http module.

**Comment by jclark** [comment]
@hasithaa  Does this affect the spec?  The spec allows service resource functions to have an external body regardless of whether they are client or service, which I think is the right thing.

**Comment by hasithaa** [comment]
No, it doesn't affect the spec. IIRC, we didn't support this to reduce implementation scope. I think we should support this in jBallerina.

**Comment by rdulmina** [comment]
This is the related spec isse https://github.com/ballerina-platform/ballerina-spec/issues/32 . jBallerina currently does not allow external service resource methods.
