### ISSUE TITLE
Convenient lifting of errors with chained method calls

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#109]
In a chained method call e.g. `x.foo().bar().baz()`, we do not have a convenient syntax for handling the case when foo and/or bar returns an error. We would have to write

```
(check (check x.foo()).bar()).baz()
```

We have discussed a syntax `E!foo()`, which is like `E.foo()`, except that if evaluating E results in an error e, the result of the expression is e and the foo method is not called.

**Comment by hasithaa** [comment]
Moved the comment from, #85, 

------------------
Implementation support error lifting operator `!`. i.e `x!y` Here, `x` is an expression whose type is a  T1|error or T1?|error (supports sub-type of error as well) and `y` is a field of T1 which is the type of `T2`.

```balerina
T1|error|() x = getT1Value();
T2|error|() y = x!y
```

Which is desugared into, 

```
T1|error|() x = getValue();
T2|error|() y = {
  T2|error|() $var;
  if ( x is T1)
    $var = x.y;
  } else {
    $ var = x;
  }
  $var // result of statement-expression.
};
```

The same expression is extended to support function calls as well. `x!y()`

**Comment by sanjiva** [comment]
+1 or retaining `!` as previously done.

**Comment by jclark** [comment]
We are dealing with this in #195
