### ISSUE TITLE
Render the sequence diagram using PlantUML

### ISSUE THREAD

**Issue by gvlx** [ballerina-platform/ballerina-spec#1093]
**Description:**

Following the suggestion on https://github.com/ballerina-platform/ballerina-dev-website/issues/1926#issue-821019618 (closed - proprietary) how difficult would be to use [PlantUML's](https://plantuml.com/sequence-diagram) rendering engine to output the sequence diagram in a format that more closely resembles UML?

~~I'm sorry to say but one of the reasons people walk away of my demos of Ballerina is the fact the visual description does not follow any standard. In fact it resembles the old 60's flowcharts, which only makes it worse.~~

Business Analysts and Technical Architects will mostly favor diagrams under a known and widely accepted standard as UML, so the current graphical representation does not appeal to that audience.

Given the fact PlantUML is a well established Open Source project ([GPL-3](https://github.com/plantuml/plantuml)), with direct integration in several design tools (JetBrains, Visual Studio, Eclipse, etc) and that its syntax for sequence diagrams is quite succinct, it could be a good fit for Ballerina.

Does the Ballerina parser outputs an interim, textual, representation which could be converted into PlantUML format?

Which Ballerina's artifacts do not have a correspondence in UML or PlantUML?

**Suggested Labels:**
New Feature, UML
   
**Code sample that shows issue:**

This example (taken from https://medium.com/it-dead-inside/a-beginners-guide-to-plantuml-be1760c8fdaf ) [live editor](https://www.plantuml.com/plantuml/uml/VOr1IWD144NtTOhlAXjpWIn280PSA0G63r2PBcD3JTTONQsPssiS48QWcrxqU__LhWPxj47HvM5KGIVlJKelUCXyTXueSgZyHN6uy1KGSH_csBzvhdIoLXBxXADoYPVdfqxyGvpe1w-to-yD3Yd7hukz9Q6bSZivklLIwoopndnvjQmWLtowbJC1m3A1zNRUR81kAi4NYBlvFSvchoTMlIFHAZVXNAz6-Z_vA2whYicQOtI9c33cFfeBIKcq-txQe5y0) :

![imagem](https://user-images.githubusercontent.com/67311/167915137-3e886d6f-7c9a-429b-9fa9-0d3ea2d780f1.png) 

Is the result of parsing this code:

```
@startuml
title Simple Sequence Diagram Example

actor Chris
boundary PlantUMLServer

Chris->PlantUMLServer: Edit PlantUML Code
PlantUMLServer->PlantUMLServer: Process Code
alt Chris' PlantUML Code is wrong
    PlantUMLServer -> Chris:  Syntax error, goofball!
else Chris' PlantUML is good
    PlantUMLServer -> Chris: Here's your pretty picture
end
@enduml
```

Another site with even more examples: https://real-world-plantuml.com/

**Related Issues:**
https://github.com/ballerina-platform/ballerina-dev-website/issues/1926#issue-821019618

**Comment by jclark** [comment]
@sameerajayasoma Can you move this to a more appropriate repository? Not sure which that would be.

**Comment by sameerajayasoma** [comment]
@gvlx Can you please create this issue in https://github.com/wso2/ballerina-plugin-vscode?

It looks like I can't transfer this issue across organization boundaries.

**Comment by gvlx** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/187
