### ISSUE TITLE
Extend isolated concept to named workers

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#1095]
This follows on from #1068.

The goal is to address two limitations:
- a named worker always runs on the same strand as the function worker, unless there's an annotation; but use of this annotation is not safe, and will be problematic for Ballerina
- an isolated function cannot use named workers

The idea is that when a named worker is isolated:
- its body would have similar restrictions to an isolated function
- it would be safe for the named worker's strand to be run on a separate thread from the function's strand
- an isolated function would be able to have named workers provided they are isolated

**Comment by jclark** [comment]
Need particularly to consider https://github.com/ballerina-platform/ballerina-spec/issues/1068#issuecomment-1067575029

**Comment by jclark** [comment]
Nasty case is if there is a named worker and the function worker panics before doing a wait for the named worker. This means there is always a possibility that a named worker will outlive the function worker.

**Comment by jclark** [comment]
Note that this

> A function-call-expr is isolated if the type of the function being called is isolated and the expression for every argument is isolated

won't be true if a named worker in an isolated function can outlive the function worker and can refer to mutable parameters.  It can return a mutable value which is also being referred to by a named worker.

**Comment by jclark** [comment]
Also note that lock doesn't help with accessing mutable parameters.

**Comment by jclark** [comment]
So I think the simple fix is as follows:

- In [7.3.5](https://ballerina.io/spec/lang/2022R1/#isolated_functions), which defines isolated functions,
    - do not prohibit named-worker-decl
    - but require that within a named-worker-decl in an isolated function a reference to a local variable outside the named-worker-decl satisfy the same requirements as in the captured variable bullet point
 - say that a named worker in an isolated function can run on a separate thread

This makes the rules for named workers very similar to those for start-action in #1068. The named worker would be equivalent to something that you could with a start-action (except that it also allows inter-worker communication).

We could generalize this to allow an isolated worker in a non-isolated function, but I suspect that is not very useful and would need a syntax change also.

**Comment by jclark** [comment]
@MaryamZi Please review. Is this doable for Update 2?

**Comment by jclark** [comment]
I added #1095 that would improve upon this by making it possible to have a named worker that is guaranteed not to outlive its function.

**Comment by jclark** [comment]
I optimistically moved this to Update 2, so we can discuss whether this is viable. If not, I'll move it back to Update 3.

**Comment by MaryamZi** [comment]
> @MaryamZi Please review. Is this doable for Update 2?

Yes, I believe this should be possible.

**Comment by jclark** [comment]
The same rule needs to apply to a fork-stmt.
