### ISSUE TITLE
Import non-Ballerina IDL as a module that defines a client

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#1097]
The idea is to that it should be possible to import an interface definition written in a language that is not Ballerina, with the effect that it behaves like

1. generating from the IDL a Ballerina module that defines a client
2. importing the generated module

Tentative syntax is

```
client import "http://example.com/blah.yaml" as blah;
```

~~With this kind of import, it is useful to be able to have annotations to control how the Ballerina module is generated from the URL #1099.~~

**Comment by jclark** [comment]
Discussion ideas:

- make this entirely a platform feature
- could also use for interop (URL refers to a jar file)

**Comment by sameerajayasoma** [comment]
We discussed doing something like this. The import statement is a regular import defined in the language that imports the submodule `blah` in the current package "foo." In the default case (with no annotations), there should be a directory called `modules/blah` at the root of the package `foo'. But in this case, the annotation(s) instructs the platform on how to generate the module at compile time.  
```
@http:Client{url:"http://example.com/blah.yaml"}
import foo.blah;
```

We also discussed another variation: 
```
@http:Client
import "http://example.com/blah.yaml" as blah
```

**Comment by jclark** [comment]
We discussed

```
@client {
    url: "http://example.com/blah.yaml"
}
import foo.blah;
```

**Comment by sameerajayasoma** [comment]
@jclark Ack. We will work with the Choreo team to figure out the best DX. 

Here is a proposal that I think will work nicely with the current package design. 

We interpret the import statement `import foo.blah;` as importing the submodule `blah` in the current package `foo`. There MUST be a directory named `blah` inside the `modules/` directory for this to work. 

We can indicate that the module `blah` is a module that needs to be generated by the compiler by placing  `blah.toml` inside the `modules/` directory. The contents of the `blah.toml` should indicate how to generate the module sources. 
 ```
$ cat modules/blah.toml 
[client]
url = "http://example.com/blah.yaml"
```
This is a tentative design. We need to figure out the details. 

The DX for Choreo low code developers: My gut feeling is that they would search for the HTTP service using the UI and add it to the package. Here is the current DX for adding a connector to the package. 
<img width="1018" alt="Screen Shot 2022-05-18 at 2 01 48 PM" src="https://user-images.githubusercontent.com/2637328/169156147-3d07f2b7-69b6-458b-b039-0a226075861b.png">

**Comment by jclark** [comment]
I discussed this yesterday with @sameerajayasoma, and I think a few points emerged about doing this as a purely platform feature:

1. the module should be described by a directory containing a TOML file, rather than just a TOML file; this
    1. allows it to work for the default (root) module of a package
    2. provides a place to put the IDL source from the Ballerina is generated
    3. provides a place for other related files (e.g. the queries for GraphQL)
    4. allows for a `tests` subdirectory
2. we can approach this as being an enhancement to the build system
    1. a uniform way for the on-disk package structure to represent Ballerina modules that are generated from some other source
    2. enhancing `bal build` to be know about this and be able to automatically perform the step of building the generated Ballerina modules from their source (e.g. OpenAPI)
3. this would be useful not just for clients generated from IDL, but also for interop (generating modules from jar files in the jBallerina case, or from C header files in the nBallerina case); this could also be used to potentially solve #1100 (the static "resources" can be viewed a module exporting final/readonly variables, with a file in non-Ballerina syntax initializing each variable)

Is this enough? If so, then we should not do a language feature.

**Comment by hasithaa** [comment]
> 1. the module should be described by a _directory_ containing a TOML file, rather than just a TOML file; this
>    
>    1. allows it to work for the default (root) module of a package
>    2. provides a place to put the IDL source from the Ballerina is generated
>    3. provides a place for other related files (e.g. the queries for GraphQL)
>    4. allows for a `tests` subdirectory feature.

I think, we should keep generated source, outside (in target) or under a subdirectory of this directory.  Usually, the user wants to clean and/or re-generate the IDL ballerina source.

**Comment by jclark** [comment]
> I think, we should keep generated source, outside (in target) or under a subdirectory of this directory. Usually, the user wants to clean and/or re-generate the IDL ballerina source.

I prefer subdirectory of the module directory to `target`. I think these generated source files are a bit different from `target` in that the user may want to look at the generated Ballerina code in order to understand how to use the module; similarly, VS Code may want to provide a view that shows the Ballerina code (e.g. for debugging).

**Comment by jclark** [comment]
Consider the case of a wanting a client to interact with a Ballerina-defined service.  Thinking of this as importing the module or modules that define the service isn't right.

- we don't want the module that defines the service to be part of the program that uses the client
- there isn't a convenient name for the service: there's a path or string given in the service declaration and there's a listener (which may not have a separate declaration or may be declared in another module)

So I think it's better to conceptualize what we are trying to do in this case as constructing a client that accesses an endpoint provided by a Ballerina program. Since the endpoint is defined with a semantics known by the Ballerina platform, the Ballerina platform can construct a client that has matching semantics.

In the OpenAPI case, we have a URL of a YAML file that describes an endpoint. To handle the Ballerina case in a similar way, we would need a URL of a description of an endpoint of a Ballerina program (this is something that the Ballerina platform or Choreo could provide).

This suggests that what we need is a new kind of declaration (or variant of an existing declaration) that

- includes a URL that refers to the description of an endpoint
- has the semantic that the URL is dereferenced and then using to construct a client class, which is associated with an identifier specified in the declaration
- provides a way to reference types associated with the client class
- can be annotated to provide control over how the client class is constructed

Each such declaration creates its own class (just like a class declaration).  If you have two declarations in different modules that reference the same URL (possibly with different annotations), then there are two classes. Compatibility between the types used in the classes is determined using normal structural typing rules (i.e. they can be be compatible unless you use `distinct`).

I can see two syntactic approaches.

**`client` declaration similar to `xmlns` declaration**

Have a `client` declaration similar to an `xmlns` declaration e.g.

```
client "http://www.example.com/apis/myapi.yaml" as myapi;
```

Like an `xmlns` declaration, the `client` declaration it would be allowed anywhere (even at statement level).  An associated type T would be referenced as `myapi:T`.  The client itself could be referenced as `myapi:client` (using the keyword `client` here).

**New kind of `client class` declaration**

Have a special kind of class declaration e.g.

```
client class MyApiClient "http://www.example.com/apis/myapi.yaml";
```

In this case the client class is referenced using the identifier `MyApiClient`, and an associated type T would be referenced using `MyApiClient.T`.

Under the surface, these could both be implemented by constructing a module and then importing that. Each occurrence of the declaration would result in a separate module (or you could hash the generated source code, and use the hash as the identifier). In each case, the compiler would need to create the appropriate symbols from the imported module.

**Comment by hasithaa** [comment]
My preference is to go with Option 1 (xmlns like syntax).

**Comment by jclark** [comment]
Consensus is for the `xmlns`-like approach.

**Comment by MaryamZi** [comment]
> The client itself could be referenced as `myapi:client` (using the keyword `client`).

Wouldn't this depend on how the client class is generated? For example, the OpenAPI tool currently generates a client class named `Client`.

**Comment by jclark** [comment]
@MaryamZi This feature isn't importing an arbitrary module. See https://github.com/ballerina-platform/ballerina-spec/issues/1097#issuecomment-1139248092

> Thinking of this as importing the module or modules that define the service isn't right.

This is *not* defined as a two step process
1. generate an arbitrary module and
2. import the module

Rather, it is defined as a single process: create a set of symbols with a specified prefix that represent a client that can access an endpoint identified by a URL.  Note that `client` is a keyword here. The implementation is required to make prefix:client refer to the client object.

**Comment by jclark** [comment]
Need to figure out how `distinct` works.

**Comment by jclark** [comment]
Probably need separate annotation attachment point (perhaps restricted to `anydata` so that they can be compared with `==`).

**Comment by azinneera** [comment]
We would need to introduce a new directory to add the generated modules containing the IDL Client code. The suggested directory is `<package-root>/generated/` and for each client, there will be a separate directory generated. Each such directory would be identified as a module.

```
myPackage
├── Ballerina.toml
├── generated
│   └── client1
│       └── client1.bal
├── modules
│   └── mod1
│       └── mod1.bal
└── main.bal


```

**Comment by MaryamZi** [comment]
> The client itself could be referenced as `myapi:client` (using the keyword client).

Just to confirm, this would also mean that we should be allowing using `client` without the quote when it is part of a qualified identifier? (Related to https://github.com/ballerina-platform/ballerina-spec/issues/34, https://github.com/ballerina-platform/ballerina-spec/issues/34#issuecomment-992351453)

> Probably need separate annotation attachment point i.e. `client` (perhaps restricted to `anydata` so that they can be compared with `==` and `const`).

This would also be a source-only attachment point, right?

**Comment by jclark** [comment]
> Just to confirm, this would also mean that we should be allowing using client without the quote when it is part of a qualified identifier? 

Yes, the grammar will explicitly allow this. (I see 'client and client as referring to different things.)

**Comment by jclark** [comment]
> This would also be a source-only attachment point, right?

Yes.

**Comment by jclark** [comment]
@mohanvive Asks to prioritize grammar changes since this will be used for the basis of the sematic API.

**Comment by MaryamZi** [comment]
Just to confirm, given that `service-uri` is `simple-const-expr`, the following will be valid and will require some reordering (between constants and client declarations) to resolve the constants and client declarations since a constant may depend on a client declaration and vice versa?

```ballerina
client baz:URI as foo;

client URI as bar;

const URI = baz:URI;

client "http://www.example.com/apis/myapi.yaml" as baz;
```

**Comment by jclark** [comment]
@MaryamZi Yes. This is the same as `xmlns`, right?

**Comment by MaryamZi** [comment]
> @MaryamZi Yes. This is the same as `xmlns`, right?

Yes, it is similar.

Just wanted to confirm because (in the implementation) we initially allowed only string literals and resolved the module-level client declarations immediately after the imports (and before other constructs including constants) which we cannot do since client declarations may refer to constants.

**Comment by jclark** [comment]
I am OK with restricting to string literal if it would significantly simplify implementation.

**Comment by MaryamZi** [comment]
+1 to restrict to string literal.

Also, at least in the initial iteration, the project API uses the syntax tree to extract the URI and generate the code for the client, which also wouldn't work with constant reference expressions. If we do allow constant reference expressions, the plan was to log an error saying only string literals are supported at the moment.

**Comment by MaryamZi** [comment]
@jclark, would it be possible to confirm the grammar changes related to annotations too?

We have allowed the following in the implementation at the moment.
- `client` as a `source-only-attach-point-ident`
- `[annots]` on `client-decl`

**Comment by jclark** [comment]
I copied `xmlns-decl` which doesn't allow `annots`, but I think that's a bug in `xmlns-decl`.

**Comment by jclark** [comment]
@MaryamZi I made the grammar changes you suggest.

Not sure whether annotations make sense for xmlns-decl.

**Comment by jclark** [comment]
@MaryamZi We will also need grammar changes to allow `foo:client` as an identifier, which references the client class.

**Comment by gayalkuruppu** [comment]
Are we planning to mention the behaviour of the `module-prefix` of `client-decl` in the `module-prefix` definition? currently we have [mentioned](https://ballerina.io/spec/lang/master/#import-declaration) about the usage of `module-prefix` in `import-decl` and `xmlns-decl`

**Comment by jclark** [comment]
Need to deal with https://github.com/ballerina-platform/ballerina-spec/commit/003cd73a77d45580f8fac75cd0c3ff8393cd917a#commitcomment-84679195

**Comment by jclark** [comment]
> Are we planning to mention the behaviour of the `module-prefix` of `client-decl` in the `module-prefix` definition? currently we have [mentioned](https://ballerina.io/spec/lang/master/#import-declaration) about the usage of `module-prefix` in `import-decl` and [xmlns-decl](https://ballerina.io/spec/lang/master/#xmlns-decl-stmt)

Yes.  Only the grammar changes have been integrated into the spec so far. Text is also needed.

**Comment by sanjiva** [comment]
We showed this feature to some folks in WSO2 yesterday and there was feedback that it makes better sense to only allow client import statement at the top level only.

The reason is that this does primarily a "one-time" task (like import). It has some syntactic analogy to xmlns but the behaviour is more like import.

**Comment by jclark** [comment]
I don't have a problem with allowing it only at top-level. I would say the semantic analogy is more like a class or type declaration, which we only allow at top-level. I think the important thing from a usability perspective is that it is not required to be declared at the beginning of a file, like an import is.

**Comment by jclark** [comment]
@sameerajayasoma asks elsewhere why `foo:client` rather than `foo:Client`.

The spec places no requirements on the identifiers in the module constructed by a `client` decl. The language doesn't interfere with module-level symbol spaces: that is not in-scope for the language; choices of module-level names are for other layers to make.

It is important to understand here that in `foo:client`, `client` is a keyword not an identifier. When the platform layer constructs modules it has *complete* freedom in the identifiers that it uses both for any client classes that it creates and for any types/constants. The platform can choose to name the client class foo:Client or foo:FooClient or foo:ClientyMcClientFace: it is entirely a decision for the platform.

So if you want to make `foo:Client` work, there's no problem as far as the language is concerned.

All the language requires is that the compiler arrange that the `client` keyword (which is an existing keyword) refers to the main client class constructed. I think it is useful to have a language-defined way to refer to the type constructed by the external client declaration - otherwise the feature feels incomplete at the language level - and that needs to use a keyword: it's the language's domain to say what keywords mean. And `client` is the obvious choice of keyword, especially since we cannot add new keywords.

**Comment by jclark** [comment]
Spec still needs better text for qualified-identifier. It's currently defined in the import declaration section, which doesn't really make sense.

**Comment by sameerajayasoma** [comment]
The other concern raised during the demonstrations is that if this is a one-time generation, why do we add it to the code? Why can't we pre-generate the code and use it?

**Comment by jclark** [comment]
We decided today to get rid of this on the basis that putting this in the language provides insufficient value compared to doing it as a platform feature that provides general support for generating Ballerina code.
