### ISSUE TITLE
Supporting GraphQL Interfaces in Ballerina

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-spec#1101]
**Description:**
We are to implement GraphQL interface support in Ballerina. As per the last discussion, we agreed to implement the GraphQL interfaces using the distinct service types. 

Ideally, we thought the following is the way to define a GraphQL interface in Ballerina.

```ballerina
type Person distinct service object {
    resource function get name() returns string;
};

distinct service class Student {
    *Person;

    resource function get name() returns string {
        return "Student";
    }
}
```

But since the [resource functions are not considered as a part of the service type](https://github.com/ballerina-platform/ballerina-spec/issues/669) yet, we are thinking about the following approach to define interfaces.

```ballerina
distinct service class Person {
    resource function get name() returns string {
        return "";
    }
}

distinct service class Student {
    resource function get name() returns string {
        return "Student";
    }
}
```

We can validate the interface implementation using a compiler plugin to check whether the implementations contain the same resource function signatures as the interface type. 

But the issue with this approach is that the interface type can have instances of its own, which violates the interface concept. 

@jclark WDYT? Is there another way to implement this, or shall we go ahead with the mentioned approach?

Related issues: #559 #669

**Comment by ThisaruGuruge** [comment]
Thanks, @jclark for the update.

Having resource method declarations as a part of the service type descriptors will be ideal for GraphQL interface support. Can we have this feature for the SwanLake update 2?

**Comment by jclark** [comment]
@hasithaa Do you think this aspect of #1080 is doable for Update 2?

**Comment by jclark** [comment]
Thinking about this some more, this would add quite a lot of typing complexity: the typing should make paths in resource methods equivalent to returning a service object, but Update 2 is only handling the subset in #1080 which does not support the hierarchical semantics needed for GraphQL (i.e. in Update 2 client object resource methods will not be able to return service objects).

So I don't think this is doable for Update 2.

**Comment by ThisaruGuruge** [comment]
Yes, I understand. But, for the basic functionality, we can work without the hierarchical resource paths first. In that case, will we be able to have that subset for update 2? 

If this is still not possible for update 2, would that be okay to proceed with the approach we mentioned in the issue (using service classes with compiler plugin validations) as a temporary solution? I'm asking this since the interfaces are now the only missing main feature in the GraphQL package.

**Comment by shafreenAnfar** [comment]
The GraphQL listener already knows how to handle returned services from resource functions. Therefore, if we can have support for something simple as follows, that could help us make significant progress in supporting GraphQL interfaces. 

```ballerina
type Person distinct service object {
    resource function get name() returns string;
    resource function get address() returns Address; // a service object
};
```

**Comment by jclark** [comment]
I think allowing the return type to be a service object type is hard (because the spec has to say when a service object, which may define hierarchical methods, belongs to the type).  Do you need to allow `obj is Person` for a type so defined?

**Comment by shafreenAnfar** [comment]
Okay. In that case maybe we can start without allowing the return type to be a service object type.

Following is how the rough usage of resource functions would look like in the context of GraphQL interface support.

```ballerina
import ballerina/io;

type Person distinct service object {
    resource function get name() returns string;
};

distinct service class Student {
    *Person;

    resource function get name() returns string {
        return "Frank";
    }

    resource function get fee() returns decimal {
        return 250.00;
    }
}

distinct service class Teacher {
    *Person;

    resource function get name() returns string {
        return "Jo";
    }

    resource function get salary() returns decimal {
        return 1000.00;
    }
}

public function main() returns error? {
    Person p = getPerson();
    if p is Teacher {
        io:println(p.salary());
    }
}

function getPerson() returns Person {
    Teacher t = new();
    return t;
}
```
If possible, from the GraphQL interface support point of view following subset would be fine.
- No support for hierarchical methods
e.g.

```ballerina
type Person distinct service object {
    resource function get name/first() returns string;
    resource function get name/last() returns string;
};
```
- No support for optional arguments (as in HTTP)
- No support for optional methods
- Only get accessor is supported

**Comment by jclark** [comment]
This has been dealt with in #1080.
