### ISSUE TITLE
Allow annotations for each type in a tuple

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-spec#1104]
**Description:**
We have got this use case while we were designing the service based approach. 
In our use case, Azure functions can have return multiple types. To facilitate that we chose tuples in ballerina. 
We have this requirement to annotate each value of the tuple in the return type descriptor so that way we can process that accordingly to the format required by the azure platform. 

Sample Code. 
```
remote function onMessage (@af:Payload string inMsg) returns [@af:QueueOutput string, @af:HTTPOutput string] {
           return "helloo "+ inMsg;
}
```

Currently the above code gives an complication error. Will it be possible to support this requirement?

**Comment by sanjiva** [comment]
In Azure Functions the AF engines takes each of these outputs and processes them as advised. So one will go to a queue (details of which must be given - the sample skips that) and the other is going as the HTTP response (which presumably means this was an HTTP triggered function .. can't have an HTTP response without that).

(Just giving more context)

**Comment by jclark** [comment]
Seems reasonable.

**Comment by jclark** [comment]
Another reason this is good is that it is consistent with how we allow annotations on function parameters.

**Comment by jclark** [comment]
@hasithaa @gimantha For now, I've used `type` as the annotation attachment point for this case. But it feels like it should have its own attachment point since we are using `field` for record fields and `parameter` for function parameters. However, I don't see an obvious good name. And I don't want to introduce new keywords, so we need to make annotation attachment point names not be keywords, which requires more progress on #34.

**Comment by hasithaa** [comment]
Allowing in an annotation in places like [`type-parameter`](https://ballerina.io/spec/lang/master/#type-parameter) is useful. i.e. `map<@constraint:Int { minValue: 18 } int>` . 

One option is to utilize the `type` annotation attachment point for the above cases as well. Or we will need multiple attachment points for different types.

**Comment by hasithaa** [comment]
> Allowing in an annotation in places like [`type-parameter`](https://ballerina.io/spec/lang/master/#type-parameter) is useful. i.e. `map<@constraint:Int { minValue: 18 } int>` .
> 
> One option is to utilize the `type` annotation attachment point for the above cases as well. Or we will need multiple attachment points for different types.

Created separate issues https://github.com/ballerina-platform/ballerina-spec/issues/1111 for this.

**Comment by jclark** [comment]
Conclusion from today's discussion:

- use `field` rather than `type` as the attachment point: neither `field` nor `type` are great, but semantically `field` is a better fit
- don't put annotations on the tuple-rest-descriptor, since they are not on the record-rest-descriptor
