### ISSUE TITLE
Specify regular expression syntax and semantics

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#1125]
A major part of #130 is defining the syntax and semantics of a regular expression dialect.

**Comment by jclark** [comment]
```
RegExp := ReDisjunction

ReDisjunction := ReSequence ("|" ReSequence)*
ReSequence := ReTerm*
ReTerm :=
   ReAtom [ReQuantifier]
   | ReAssertion
ReAssertion := "^" | "$"

ReQuantifier := ReBaseQuantifier ["?"]

ReBaseQuantifier :=
   "*"
  | "+"
  | "?"
  | "{" Digit+ ["," Digit*] "}"

ReAtom :=
   ReLiteralChar
   | ReEscape
   | "."
   | "[" ["^"] [ReCharSet] "]" 
   | "(" ReDisjunction ")"

ReLiteralChar := ^ ReSyntaxChar

ReSyntaxChar :=
  "^" | "$" | "\" | "." | "*" | "+" | "?"
  | "(" | ")" | "[" | "]" | "{" | "}" | "|"

ReEscape :=
   NumericEscape
   | ControlEscape
   | ReQuoteEscape
   | ReUnicodePropEscape
   | ReSimpleCharClassEscape

ReQuoteEscape := "\" ReSyntaxChar
ControlEscape := "\r" | "\n" | "\t"

ReSimpleCharClassEscape := "\" ReSimpleCharClassCode

ReSimpleCharClassCode := "d" | "D" | "s" | "S" | "w" | "W"

ReUnicodePropertyEscape := "\" ("p" | "P") "{"ReUnicodeProperty "}"

ReUnicodeProperty :=  ReUnicodeScript | ReUnicodeGeneralCategory

ReUnicodeScript := "sc=" ReUnicodeScriptName

ReUnicodeScriptName := AsciiUpper AsciiLower AsciiLower AsciiLower

ReUnicodeGeneralCategory := ["gc="] ReUnicodeGeneralCategoryName

ReCharSetAtom :=
  ReCharSetLiteralChar
  | ReEscape
  | "\-"

ReCharSetLiteralChar := ^ ("\" | "]" | "-")

ReCharSet :=
  ReCharSetAtom
  | ReCharSetRange [ReCharSet]
  | ReCharSetAtom ReCharSetNoDash

ReCharSetRange := ReCharSetAtom "-" ReCharSetAtom

ReCharSetNoDash :=
  ReCharSetAtom
  | ReCharSetRangeNoDash [ReCharSet]
  | ReCharSetAtomNoDash ReCharSetNoDash
  
ReCharSetRangeNoDash := ReCharSetAtomNoDash "-" ReCharSetAtom
```

**Comment by jclark** [comment]
The semantics are as defined by ECMAScript standard, subject to following notes:

- the semantics are as defined by ECMAScript with the `u` RegExp flag and no others
- requirements not in grammar are as in ECMAScript spec
- semantics of `\p` depend on specific Unicode version; for Swan Lake, this should be Unicode 10, since Swan Lake is using JDK 11, which uses Unicode 10

**Comment by jclark** [comment]
Issues:

1. Need a way to enable `m`, `s` and `i` flags
2. In the future we will likely want allow nested character classes (not in ECMAScript currently); grammar should be stricter so that this can be done without compatibility problems

**Comment by jclark** [comment]
This will be implemented by parsing the regexp syntax and then translating it to Java syntax.  Almost everything defined above works the same in Java., except for a few differences, including the following:

- how character classes are parsed; specifically Java provides `&&` which we do not yet support; and I suspect there are differences in when `-` and perhaps `[` are recognized as metacharacters in classes rather than being treated literally (need to improve grammar here also)
- `\s` is different: it allows two additional ASCII whitespace characters (vertical tab and line feed); so it needs to be translated (or should we fix Ballerina to allow these everywhere?)
- with multiline flag, Java recognizes additional characters as terminating a line; there's a flag to turn these off but this recognizes only newline which is not enough; may not be practical to implement the specified semantics here

There may be others.

Implementor needs to see if there are other cases where semantics differ for the defined subset.

**Comment by jclark** [comment]
@lasincl See #1132. Regular expressions are constructed using backtick syntax:

```
re`x|y|z`
```

like with XML. The part surrounded with backticks is first parsed as a https://ballerina.io/spec/lang/master/#BacktickString. This gives a sequence consisting of characters and interpolations, which is then parsed against the grammar for RegExp given in this issue, with an interpolation being allowed where an ReAtom is allowed.

There will also be a langlib `fromString(RegExp)` function, which will also use the grammar in this issue, but in this case without interpolations.

**Comment by jclark** [comment]
@lasinicl You correctly observe that the productions starting with upper-case means that there is no implicit whitespace. This doesn't meant whitespace is not allowed: whitespace will be treated as a literal character matching ReLiteralChar. But note that the `x` flag means that whitespace is ignored outside character classes.

**Comment by jclark** [comment]
@lasinicl In the implementation, you may want to do what I believe is done for XML: effectively you combine the grammar for RegExp (given here) and the grammar for BacktickString in the spec into a single grammar and then parse using that combined grammar. This will make it easier to ensure that RegExp syntax errors are correctly associated with the right range in the source file.  The disadvantage of this is that it will maker it harder to reuse that parser for the `fromString` runtime function.  For reusability, you could make the regexp parser accept a `string[]` with the same semantics as object:RawTemplate, and then report errors using a locations that index into that array of strings.

**Comment by lasinicl** [comment]
`ReUnicodeGeneralCategoryName` is not defined in the above grammar?
`ReUnicodePropEscape` and `ReUnicodePropertyEscape` refers to the same right?

**Comment by jclark** [comment]
ReUnicodeGeneralCategoryName is from the one or two character value of the Unicode General Category property. See e.g. https://unicode.org/reports/tr18/#General_Category_Property

**Comment by jclark** [comment]
> ReUnicodePropEscape and ReUnicodePropertyEscape refers to the same right?

Right. I fixed the grammar accordingly.

**Comment by jclark** [comment]
>  ReCharSetAtomNoDash are not defined in the above grammar?

I fixed ReCharSetAtom and ReCharSetAtomNoDash in the grammar.

**Comment by jclark** [comment]
Still to incorporate in the spec:

- specify how insertions work
- explain what ECMAScript semantics gives us (i.e. an abstract function that says whether, and if so, how, a function matches at a particular index) so we can tie it to #1130
- define ReUnicodeGeneralCategoryName  
- the point [here](https://github.com/ballerina-platform/ballerina-spec/issues/1125#issuecomment-1161925661): in the future we will likely want allow nested character classes (not in ECMAScript currently); grammar should be stricter so that this can be done without compatibility problems

**Comment by jclark** [comment]
The `Cs` category shouldn't be allowed because those those code points cannot occur in a Ballerina string.
