### ISSUE TITLE
Add langlib functions using regular expressions

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#1130]
Part of #130 is to add functions to langlib that make use of the regular expression type.

Some of these will take a regexp as the first parameter, and will live in the regexp module.  There may be other convenience functions that take a string as the first parameter that will live in the string module.  We will need to see if there are difficulties avoiding a dependency cycle between these two modules.

Current design is in this comment https://github.com/ballerina-platform/ballerina-spec/issues/1130#issuecomment-1166409311

**Comment by jclark** [comment]
One key aspect of the design is how to represent the result of a match.  The minimal information that is needed is

1. the start and end index of the substring that matched the regexp
2. for each capturing group in the regexp, was it matched, and if so the start and end index of the substring it matched

For point 2, in a regexp like `(a)|(b)`, there are two capturing groups and it is guaranteed only one of them will be matched. But in a regexp like `(a)(b)`, it is guaranteed that both of them will be matched.

Usually capturing groups are referenced by number, starting from 1, with group 0 referring to the match of the entire regexp. 

Note that if the regexp is known at compile-time, then the compiler can know how many capturing groups there are, and which are guaranteed to match.

This means that we design the type for the result of the match so that we can easily subtype it to specify which capturing groups there will be.

One possibility is like this:

```
type MatchItem readonly & record {|
   string substring;
   int startIndex;
   int endIndex;
|};

type Match readonly & [MatchItem, MatchItem?...];
```

But this won't extend to named capture groups in the future. So maybe

```
type MatchData record {|
    string substring;
    int startIndex;
    int endIndex;
|};

type Match readonly & record {|
    *MatchData;
    [MatchData,MatchData?...] groups;
|};
```

**Comment by jclark** [comment]
There are three fundamental operations that we need on the regexp, which for now I will call:

1. matchAt
2. search
3. matchFull

```
function matchAt(RegExp, string, int) returns Match;
```

This is the primitive in terms of which ECMAScript defines the semantics of pattern matching.  It tests whether the RegExp matches at index i of the string, and, if so, what it matches.  So

```
matchAt(r`y|yz`, "xyz", 1) => { startIndex: 1, endIndex: 2, substring: "y", groups: [{startIndex: 1, endIndex: 2, substring: "y"} }
matchAt(r`y`, "xyz", 0) => ()
matchAt(r`^(?:y|yz)`, "xyz", 1) => ()
// same as r`(?:^y)|(?:yz)`
matchAt(r`^y|yz`, "xyz", 1) => { startIndex: 1, endIndex: 3, substring: "yz", groups: [{startIndex: 1, endIndex: 3, substring: "yz"} }
```

Note that alternation prefers the first match `y` rather than the longest match `yz`.

**Comment by jclark** [comment]
Languages differ in whether they adopt a search or fullMatch semantic for regular expressions.

- The pattern facet in XML Schema as a fullMatch semantic.
- The pattern facet in JSON Schema has a search semantic
- Traditional Unix tools generally have search semantic
- JavaScript generally has a search semantic e.g. for regexp.test and string.match
- Python's re module provides
   - `search` with search semantic
   - `fullmatch` with fullmatch semantic
   - `match` with lookingAt semantic with index 0
 - Java's regex provides
   - `matches` with fullMatch semantic
   - `lookingAt` with lookingAt semantic
   - `find` with search semantic
- Rust provides
   - `is_match` returning boolean with `search` semantic
   - `find` with our `search` semantic
 - Go provides
   - `Find` with `search` semantic
   - `Match` with `search` semantic returning boolean

**Comment by jclark** [comment]
I think it's important to pay some attention to efficiency, since regexps are likely to be the main way of doing string processing in Ballerina.

```
type Span readonly & object {
   int startIndex;
   int endIndex;
   isolated function substring() returns string;
};

type Groups [Span,Span?...];

function find(RegExp, string, int = 0) returns Span?;
function findGroups(RegExp, string, int = 0) returns Groups?;

function matchAt(RegExp, string, int = 0) returns Span?;
function matchGroupsAt(RegExp, string, int = 0) returns  Groups?;

function fullyMatches(RegExp, string) returns boolean;
function fullMatchGroups(RegExp, string) return Groups?;
```

**Comment by jclark** [comment]
We can combine the lookingAt and fullMatch operations into a single operation

```
function substringMatches(RegExp re, string str, int startIndex, int? endIndex) returns boolean;
```

**Comment by pcnfernando** [comment]
For `replace` and  `replaceAll` two functions; we will need the original string as a parameter.

```ballerina
// Replaces the first occurrence if any.
function replace(RegExp re, string str, Replacement replacement, int startIndex = 0) returns string;
// Replace all non-overlapping occurrences.
function replaceAll(RegExp re, string str, Replacement replacement, int startIndex = 0) returns string;
```

**Comment by pcnfernando** [comment]
For `findAllGroups`, can you please confirm whether the return type should be `Groups?`
```
function findAllGroups(RegExp re, string str, int startIndex = 0) returns Groups[]
```

**Comment by jclark** [comment]
> For `replace` and `replaceAll` two functions; we will need the original string as a parameter.

Yes: thanks for the correction.

**Comment by jclark** [comment]
> For `findAllGroups`, can you please confirm whether the return type should be `Groups?`

No. It should be `Groups[]`. A single `Groups` provides the information about a index at which the regexp matched the string: not just what the whole regexp matched, but what each parenthesized group matched. findAllGroups returns an array where each entry represents a distinct index at which the regexp matched the string, so it needs to return `Groups[]` not `Groups?`.

**Comment by jclark** [comment]
We should use @isolatedParam for the replacement parameter rather than declared ReplacerFunction as isolated. This is for consistency with how other langlib functions that take function arguments behave.

**Comment by jclark** [comment]
Still to add to spec:
- add docs to definitions explaining semantics; this needs to tie up to semantics defined in #1125
- `split` function
- functions in `string` module

**Comment by pcnfernando** [comment]
Typo in `matches` and `includesMatch` functions and should be updated as below

```ballerina
function matches(string str, RegExp re) returns boolean {
   return re.fullyMatches(str);
}

function includesMatch(string str, RegExp re, int startIndex = 0) returns boolean {
   return re.find(str, startIndex) != ();
}
```

**Comment by jclark** [comment]
@pcnfernando Thanks, I updated https://github.com/ballerina-platform/ballerina-spec/issues/1130#issuecomment-1166409311 accordingly.

**Comment by pcnfernando** [comment]
Since the `regexp` type is a builtin subtype of `any`; we'll have to change `value:fromBalString` as well isn't it?

From https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/value.bal#L107
```
public isolated function fromBalString(string s) returns anydata|error = external;
```

**Comment by jclark** [comment]
@pcnfernando It's a subtype of both `anydata` and `any`, so there's no need to change `fromBalString`. I'm using `any` with `@builtinSubtype`, just because `anydata` is defined using `regexp:regexp`, whereas `any` is a primitive: there's no change in meaning.

**Comment by pcnfernando** [comment]
Regarding the parameter names, since now `re` is a reserved keyword; we'll have to prefix it with a single quote as below. Is it better to use another parameter name maybe?
eg:
`
public isolated function find(RegExp 're, string str, int startIndex = 0) returns Span? = external;
`

**Comment by pcnfernando** [comment]
Furthermore, regarding the `@isolatedParam` annotation in the below function parameters; since `Replacement` type's members are not all function types, we'll be unable to mark it as a `@isolatedParam` as per https://ballerina.io/spec/lang/master/#section_11.1
> A parameter of a function definition can be annotated with an @isolatedParam annotation; this is allowed when the function is declared as isolated and the type of the parameter is a function type...

```ballerina
public type ReplacerFunction function(Groups groups) returns string;
public type Replacement ReplacerFunction|string;

# Replaces the first occurrence of a regular expression.
public isolated function replace(RegExp re, string str, @isolatedParam Replacement replacement, int startIndex = 0) returns string = external;
# Replaces all occurrences of a regular expression.
public isolated function replaceAll(RegExp re, string str, @isolatedParam Replacement replacement, int startIndex = 0) returns string = external;

```

**Comment by pcnfernando** [comment]
Few function documentations are not available
![Screenshot 2022-10-31 at 11 03 41](https://user-images.githubusercontent.com/15815199/198938833-0f34ba14-42dc-4846-ae4c-69d8687f5b77.png)

**Comment by jclark** [comment]
I missed this:

> since now `re` is a reserved keyword

No, `re` is not a reserved word, since it is handled by https://ballerina.io/spec/lang/master/#tagged-data-template-expr

It would be a breaking change to add a new keyword, so we didn't do that.

**Comment by jclark** [comment]
>  the @isolatedParam annotation in the below function parameters; since Replacement type's members are not all function types, we'll be unable to mark it as a @isolatedParam

The right fix to the problem is to loosen the restriction on use of `@isolatedParam` to allow this.  Instead of "the type of the parameter is a function type", we should something like "the type of the parameter includes function types".

**Comment by jclark** [comment]
@pcnfernando I have added docs to lang.regexp. Please check.

**Comment by jclark** [comment]
I have made the point about `isolated` be a separate issue #1181..

We can (safely) postpone this by making ReplacerFunction be isolated for now.
