### ISSUE TITLE
Add regular expression type to language

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#1132]
This is part of #130.

**Comment by jclark** [comment]
This depends to some extent on whether we do #1098 first. If we do, then they would be a special case of this. But in either case, most things work the same:

- the regular expression type (which I will refer to as RegExp) is a subtype of anydata, but does not belong to any existing basic type
- RegExp is a subtype of readonly
- RegExp does not have storage identity (so is like string)
- `==` equality is based on the original string from which the regexp was parsed
- `===` is the same as `==`
- ordering is not defined (or should we define it based on string)
- RegExp values can be created using a regexp-constructor-expr that uses backtick syntax
   - tag is TBD: could be `regexp`, `re` or `r`; current preferences is for `re` 
   - this uses a two-phase parse, like with xml constructor
   - regexp syntax errors are detected at compile time
   - second phase is parsed against grammar given in #1125 
   - insertions are allowed at the same point that an atom is allowed
   - insertions are wrapped in a non-capturing group `(?:re)`
   - XXX handling of flags for insertions is TBD: should they apply to inserted regexp or not?

**Comment by lasinicl** [comment]
>   * this expression is a const expression (so `` const R = re`x|y`; `` needs to work without requiring type to be specified)

Constant expressions are limitedly supported by the compiler ATM. 
https://github.com/ballerina-platform/ballerina-lang/issues/13944

**Comment by jclark** [comment]
> Constant expressions are limitedly supported by the compiler ATM.

That's why I added this bullet point...
