### ISSUE TITLE
Add langlib functions for aggregation

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#1135]
Part of #441.

At least:

-  `avg` (at least to lang.float and lang.decimal); probably int:avg should return a decimal (as in XQuery)
- `count` (probably to lang.value)
- `some`, `every` (to lang.boolean) 

Notes here https://github.com/ballerina-platform/ballerina-spec/issues/441#issuecomment-1046180360

**Comment by jclark** [comment]
More details:

All the functions here are `public isolated` and `= external`. 
```
// lang.int
function avg(int n, int... ns) returns decimal;

// lang.decimal
function avg(decimal x, decimal... xs) returns decimal;

// lang.float
// Returns NaN with no args
function avg(float... xs) returns float;

// lang.boolean
// Returns false if no args
function some(boolean... bs) returns boolean;
// Returns true if no args
function every(boolean... bs) returns boolean;
```

**Comment by jclark** [comment]
When min/max/avg have no args, then we want them to return ().  We can handle this as part of the special semantics of function calls with arguments that are aggregated variables https://github.com/ballerina-platform/ballerina-spec/issues/1134#issuecomment-1174577892.

**Comment by jclark** [comment]
Question: what should decimal:avg do on overflow?

**Comment by KavinduZoysa** [comment]
> When min/max/first/last/avg have no args, then we want them to return (). We can handle this as part of the special semantics of function calls with arguments that are aggregated variables [#1134 (comment)](https://github.com/ballerina-platform/ballerina-spec/issues/1134#issuecomment-1174577892).

@jclark, do we need to return `()` from aggregated function or from the collect-clause? For example,
```ballerina
    var input = [{name: "Saman", price: 1}, {name: "Amal", price: 2}, {name: "Saman", price: 3}];
    var x = from var {name, price} in input
                where name == "No name"
                collect min(price);
```
is the value of x `()`?

If yes, the output of the following query expression should be `()`.

```ballerina
    var x = from var {name, price} in input
                where name == "No name"
                collect avg(price1) + avg(price2);
```

**Comment by jclark** [comment]
The answer to both questions is yes.

But this doesn't change the definition of the langlib functions. Rather it's part of the process by which `min(price)` gets handled when price is an aggregated variable: if `price` refers to an empty list, then the result is nil, otherwise int:min is called.

For the second case, the static type of `avg(price1)` and of `avg(price2)` is `int?`, so because of nil lifting https://ballerina.io/spec/lang/2022R4/#nil_lifting the type of `avg(price1) + avg(price2)` is also `int?`.

**Comment by KavinduZoysa** [comment]
@jclark, based on the above comment, please help me to understand the following points.

1. If query-expr ends with `collect expression` and if the static type of `expression` is `T` can we say that the static type of query-expr is `T?` ?
2. Please consider the following example.
```ballerina
    var x = from var {name, price} in input
                where name == "No name"
                collect {average: avg(price)};
```
Is the output of `x` `()` or `{average: ()}`?
Also, for an example as shown below, we are getting an empty array as the result.
```ballerina
type Price record {|
    decimal p?;
|};

    Price[] x = from var {name, price} in [{name: "", price: 2}]
                       where name == "No name"
                       group by var _ = true
                       select {average: avg(price)};
```

**Comment by jclark** [comment]
> 1. If query-expr ends with `collect expression` and if the static type of `expression` is `T` can we say that the static type of query-expr is `T?` ?

No. The static type is T. The expression following `collect` is evaluated even if there are no input frames.

```ballerina
    var x = from var {name, price} in input
                where name == "No name"
                collect {average: avg(price)};
```

The output is `{average: ()}`. Some of the aggregation functions work just fine with 0 args (e.g. sum).

Note that you can also do something like `min(0, price)` to get 0 if there are no args.

```ballerina
type Price record {|
    decimal p?;
|};

    Price[] x = from var {name, price} in [{name: "", price: 2}]
                       where name == "No name"
                       group by var _ = true
                       select {average: avg(price)};
```
> we are getting an empty array as the result.

That's correct.  With `group by`, you don't create empty groups. The possibility that an aggregated variable may be an empty list can happen only with collect.

**Comment by jclark** [comment]
My fix in https://github.com/ballerina-platform/ballerina-spec/commit/5e764141a5bbad3e8162b67434fd8228e9b1c314  doesn't handle `count` right.  It needs to fall back to lang.value as with method calls.
