### ISSUE TITLE
Support parameterize sub section of resource path segment

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-spec#1138]
**Description:**
This is related to the following issue https://github.com/ballerina-platform/ballerina-lang/issues/36900 raised in ballerina-lang.

For some use cases in resource function in the OpenAPI tool, we receive an endpoint with parameterized sub-section in the path when using the Shopify API contract for service and client generation.
Reference: https://shopify.dev/api/admin-rest/2022-07/resources/customer#top 

ex: URL endpoint ` /admin/api/2022-07/customers/{cunstomer_id}.json`   

Will it be possible to map these scenarios into the ballerina resource function since it allows to have path parameters as part of the sub-section and not parameterized sub-section?

```ballerina
resource function get admin/api/'2022\-7/customer/[string customerId]\.json() returns string {
        return "test";
    }
```
The above mapping gives some syntax issues. 

@jclark Could you please provide input for the handle this in the resource functions since currently, we are going to use resources in both service and client generation in the OpenAPI tool?

**Comment by jclark** [comment]
You would have to do something like this:

```
resource function get admin/api/'2022\-7/customer/[string customerIdDotJson]() returns string|error {
     if !customerIdDotJson.endsWith(".json") { return error("bad URL"); }
    string customerId = customerIdDotJson.substring(0, customerIdDotJson.length() - 4);
        return "test";
    }
```
