### ISSUE TITLE
Version management of standard library

### ISSUE THREAD

**Issue by sanjiva** [ballerina-platform/ballerina-spec#115]
We need to have a way to evolve the standard library just like other modules. The standard library should be evolvable independent of language spec releases as well.

A key issue is how to not surprise the user by a new release of the platform / implementation.

**Comment by jclark** [comment]
High-level concept discussed today is as follows:

- Every library module has a version
- The version of lang.* modules is tied to the language version
- Every other module has its own independent version
- Every implementation has an identifier registered with Ballerina Central (e.g. `jBallerina`)
- For each version of each implementation there is an implementation descriptor, which is an immutable JSON file stored on Ballerina Central that says
    - what language version it implements
    - what version of each module it ships with
- The TOML file in the source directory for a module specifies a implementation name and version
- An unversioned import has the semantics of importing the version specified in the implementation descriptor for the implementation specified in the TOML file
