### ISSUE TITLE
Can byte-array-literal create readonly value?

### ISSUE THREAD

**Issue by prakanth97** [ballerina-platform/ballerina-spec#1150]
**Description:**
https://ballerina.io/spec/lang/master/#type-cast-expr
```
Note that a type-cast-expr of <readonly> can be used both to cause constructors within the expression to construct values with the read-only bit on and to verify that the value resulting from the evaluation of expression has its read-only bit on.
```

and https://ballerina.io/spec/lang/master/#byte-array-literal
```
The inherent type of the array value created is also byte[N].
```

From the specs, clarified that a byte-array-literal is not a constructor expression, and always has the type byte[N], which would lead to using a cast with readonly panicking rather than creating an immutable array.

The concern is that `byte-array` is a subset of `int-array`. Should the `byte-array-literal` also behaves as the `list-constructor-expr`?
  
**Code sample that shows issue:**
```
int[] b = <readonly>[1, 3]             // allowed
byte[] a = <readonly> base16 `aa bb`.  // run-time error
```

**Comment by jclark** [comment]
If the contextually expected type is readonly, then it should create a readonly value.

**Comment by MaryamZi** [comment]
```
any[] a = <any[]> base16 `aa bb`
```
