### ISSUE TITLE
On fail support for statements other than regular-compound-stmt

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-spec#1157]
**Description:**
Relates to https://ballerina.io/spec/lang/master/#stmt-with-on-fail

With the current implementation, we have mistakenly added support for having `on-fail` for `transaction` and `retry` based on https://github.com/ballerina-platform/ballerina-spec/issues/337#issuecomment-660922407.

We anyway can wrap `transaction` within a `do-onfail` to achieve the same behavior. 
I was wondering whether it makes sense to have this sugaring for error handling of transaction blocks specifically. 

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**
Raised a lang issue as the current implementation has a spec deviation
https://github.com/ballerina-platform/ballerina-lang/issues/37315.

**Comment by jclark** [comment]
At first sight, what the implementation is doing seems reasonable. Let me look at this in more detail.

**Comment by jclark** [comment]
Concretely issue is whether the grammar should have

```
retry-stmt
| transaction-stmt
| retry-transaction-stmt
```

in [regular-](https://ballerina.io/spec/lang/master/#regular-compound-stmt) rather than `statement`.

**Comment by jclark** [comment]
This also needs some wording changes. We need to consider `retry X on fail Y` as lexically enclosing `retry X`.
