### ISSUE TITLE
Clarification on ambiguity error for union configuarable variables

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-spec#1158]
**Description:**
Currently, the union type `configurable` variables throws an error if the provided values matches to more than one member type of the union. This depends on the TOML to Ballerina value mapping we do for the configurable variables.

https://ballerina.io/learn/configure-ballerina-programs/provide-values-to-configurable-variables/#provide-via-toml-syntax

Eg. : 
```ballerina
type Person record {|
    string name;
    string city;
|};

configurable map<string>|Person m = ?;
```
In `Config.toml`
```toml
m = {name = "Jack", city = "Colombo"}
```
This throws the following error. 
```
error: [Config.toml:(1:1,1:37)] ambiguous target types found for configurable variable 'm' with type '((map<string> & readonly)|(foo:Person & readonly))'
```

As per the current improvements in the `fromJsonWithType` & `cloneWithType` implementations to support first-match policy ([comment](https://github.com/ballerina-platform/ballerina-spec/issues/1088#issuecomment-1220194734)), should we comply to this for the configurable variable behavior as well?

Instead of throwing an error, should we create the value with the first-matching type?

**Related Issues:**
https://github.com/ballerina-platform/ballerina-spec/issues/1088

**Comment by jclark** [comment]
It is not in the scope of the language spec to describe how TOML file supplies configurable variables.

However, I would expect it to use `fromJsonWithType`, which would mean it should pick up the improvements from #1088.
