### ISSUE TITLE
Support for creating GraalVM native image with the CLI

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-spec#1159]
The user should be able to generate and test the GraalVM native image for a Ballerina program. This can be done by introducing a new flag to `bal build` and `bal test` commands. With the C2C option enabled, the user should be able to generate a native docker image.

**Approach:**

Pre-requisites to generate the GraalVM executable:
* User needs to install Graalvm in the local machine
* To generate the native docker image, the user needs to install Docker 

The behavior of the CLI commands:

The build option `--native-image` will be introduced to the `bal build` and `bal test` commands.
* `bal build --native-image` 
   * This will generate the GraalVM native executable
* `bal test --native-image`
   * This will generate the GraalVM native testable image for each module and execute tests against each image
* `bal build --native-image --cloud=docker [--skip-executable]` will generate the native docker image
   * C2C plugin will build a docker image with the multi-stage build and produce a docker file with the native executable compatible with the docker image 
    *  The purpose of introducing the `--skip-executable` is to skip the native image build for the local OS to save time. Using this flag will eliminate the prerequisite of installing GraalVM in the local machine as well.

**Comment by sanjiva** [comment]
IMO "native image" and "Docker image" are going to be confusing.

Shall we call this `--native` only?

**Comment by hevayo** [comment]
We use `--native-image` since the GraalVM command is the same name. But in this context `--native` make more sense. Also we didn't worry about forward compatibility with nBallerina given nBallerina will be a major version and we can rethink how the tools work at that time.

**Comment by shafreenAnfar** [comment]
Yeah, `--native` is better. That is what quarkus has done as well.
```
quarkus build --native
```

**Comment by shafreenAnfar** [comment]
I wonder instead of doing a multi-stage build in the case of docker, should we do something as the following.

|No|Command|Input|Output|
-|-|-|-
1|`bal build`|src-files|foo.jar|
2|`bal build --native`|foo.jar|foo-runner|
3|`bal build --native --in-container`|foo.jar|foo-runner|
4|`bal build --native --cloud=docker`|foo-runner|foo-docker-image|

In the case of No.3, command use the container to build the runner. Therefore users does not need to install GraalVM locally.

I feel this makes things more consistence. This is similar to quarkus functionality.

**Comment by xlight05** [comment]
> I wonder instead of doing a multi-stage build in the case of docker, should we do something as the following.
> 
> No	Command	Input	Output	Description
> 1	`bal build`	src-files	foo.jar	
> 2	`bal build --native`	foo.jar	foo-runner	Native to host OS
> 3	`bal build --native --in-container`	foo.jar	foo-runner	Native to container OS
> 4	`bal build --native --cloud=docker`	foo-runner	foo-docker-image	Build the image with foo-runner native to host OS
> 5	`bal build --native --in-container --cloud=docker`	foo-runner	foo-docker-image	Build the image with foo-runner native to container OS
> * In the case of No.3, command use the container to build the runner. Therefore users does not need to install GraalVM locally.
> * In all the cases output is written to `target` directory similar to what we do now.
> 
> I feel this makes things more consistence. This is similar to quarkus functionality [1].
> 
> [1] https://quarkus.io/guides/building-native-image

Just to make sure if I understand this right, 

What would be purpose of the 4th case?  
As I understood, what we are doing is copying the executable generated for the host's machine, and building the image?
If so what would be the use of this? Isn't it safer to build the native in container itself as host executable might not be compatible? 


5th case, Isn't this the same outcome as multistage build? If so isn't it better to do the multistage build?

**Comment by shafreenAnfar** [comment]
> What would be purpose of the 4th case?
As I understood, what we are doing is copying the executable generated for the host's machine, and building the image?
If so what would be the use of this? Isn't it safer to build the native in container itself as host executable might not be compatible?

Yeah, you are right but I feel we don't have to close the door for the user. It's their choice.

> 5th case, Isn't this the same outcome as multistage build? If so isn't it better to do the multistage build?

It is the same outcome if you ignore the `target` directory. But for the sake of the argument let's say they are. With the originally proposed solution you have to do the below.

`bal build --native --cloud=docker`

This command is not useful due to following reasons,

- It triggers two builds and generates two native images
- Generated native images are not identical

Therefore, users are left with the following command. Basically, we are adding ` --skip-executable` as a workaround for the above problem. It is less structured and less coherent compared to what is newly proposed. 

`bal build --native --cloud=docker --skip-executable`

Also originally proposed solution has no mapping command for the below. Where the (linux) users, can build the native executable without installing GraalVM.

`bal build --native --in-container`

Therefore, when you look at it *overall*, the original solution is not only less coherent but also closes doors for the users, IMO.

**Comment by xlight05** [comment]
> Yeah, you are right but I feel we don't have to close the door for the user. It's their choice.

But the concern is the compatibility, I feel like for a user `bal build --native --cloud=docker` seems like the simplest command to specify, to build a native container image. That command being possibility incompatible is an issue ;(

How about those set of commands we discussed in the last call we had? 

| No 	| Command                           	| Description                                                                                                                                                           	|
|----	|-----------------------------------	|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| 1  	| bal build                         	|                                                                                                                                                                       	|
| 2  	| bal build --native                	| Generates native executable from HOST OS if GraalVM exists locally, else creates a linux executable(if compatible) from docker put the built executable to target dir 	|
| 3  	| bal build --native --cloud=docker 	| Only generates Docker image using Multistage build                                                                                                                         	|

**Comment by azinneera** [comment]
> How about those set of commands we discussed in the last call we had? I feel like this simplifies the user experience in most common use cases.
> 
> No	Command	Description
> 1	`bal build`	
> 2	`bal build --native`	Generates native executable from HOST OS if GraalVM exists locally, else creates a linux 
                                        executable(if compatible) from docker put the built executable to target dir
> 3	`bal build --native --cloud=docker`	Only generates Docker image using Multistage build. Local build is skipped.

Commenting on option 2 above, I think the CLI should not decide to create a Linux executable if the GraalVM installation is not found locally. If the user's OS is not Linux, then generating this image/failing the command will not be useful for the user. IMO, the user would prefer creating a docker image in this case. So if a GraalVM installation is not found locally, we should rather give a suggestion in the error message telling the user to additionally pass `--in-container` instead. Having options 2 and 3 @shafreenAnfar suggested in https://github.com/ballerina-platform/ballerina-spec/issues/1159#issuecomment-1250932104 suits better.

Nonetheless, I too agree on removing option 4 due to the same concerns @xlight05 mentioned in https://github.com/ballerina-platform/ballerina-spec/issues/1159#issuecomment-1254573422

So the suggestion is:
|No|Command|Input|Output|Description|
-|-|-|-|-
1|`bal build`|src-files|foo.jar|
2|`bal build --native`|foo.jar|foo-runner|Native to host OS|
3|`bal build --native --in-container`|foo.jar|foo-runner|Native to container OS|
4|`bal build --native --in-container --cloud=docker`|foo-runner|foo-docker-image|Build the image with foo-runner native to container OS|

**Comment by xlight05** [comment]
> > How about those set of commands we discussed in the last call we had? I feel like this simplifies the user experience in most common use cases.
> > No	Command	Description
> > 1	`bal build`
> > 2	`bal build --native`	Generates native executable from HOST OS if GraalVM exists locally, else creates a linux
> > executable(if compatible) from docker put the built executable to target dir
> > 3	`bal build --native --cloud=docker`	Only generates Docker image using Multistage build. Local build is skipped.
> 
> Commenting on option 2 above, I think the CLI should not decide to create a Linux executable if the GraalVM installation is not found locally. If the user's OS is not Linux, then generating this image/failing the command will not be useful for the user. IMO, the user would prefer creating a docker image in this case. So if a GraalVM installation is not found locally, we should rather give a suggestion in the error message telling the user to additionally pass `--in-container` instead. Having options 2 and 3 @shafreenAnfar suggested in [#1159 (comment)](https://github.com/ballerina-platform/ballerina-spec/issues/1159#issuecomment-1250932104) suits better.
> 
> Nonetheless, I too agree on removing option 4 due to the same concerns @xlight05 mentioned in [#1159 (comment)](https://github.com/ballerina-platform/ballerina-spec/issues/1159#issuecomment-1254573422)
> 
> So the suggestion is:
> 
> No	Command	Input	Output	Description
> 1	`bal build`	src-files	foo.jar	
> 2	`bal build --native`	foo.jar	foo-runner	Native to host OS
> 3	`bal build --native --in-container`	foo.jar	foo-runner	Native to container OS
> 4	`bal build --native --in-container --cloud=docker`	foo-runner	foo-docker-image	Build the image with foo-runner native to container OS

So, what if the user invokes `bal build --native --cloud=docker` ? Are we taking the --in-container as implicitly?

**Comment by azinneera** [comment]
> So, what if the user invokes `bal build --native --cloud=docker` ? Are we taking the --in-container implicitly?

Yes, even if there is a local installation.

**Comment by xlight05** [comment]
Also, one downside of the `bal build --native --cloud=docker`  command that i've suggested is that, the cli should know if the --cloud flag is there, it needs to skip the executable generation. In the case of c2c, its fine as c2c is packed with ballerina lang itself. If we look at Azure functions or AWS Lambda, we can't do this. 

From the way I see it, we have two solutions. 
User based Approach -  `--skip-executable` flag discussed in the original post.
Compiler Plugin author - Compiler plugin Author should be able to specify that if the user is consuming this plugin, the cli should not generate the executable.

**Comment by sameerajayasoma** [comment]
How can we specify build options such as -gc=G1 during the image build time?

**Comment by xlight05** [comment]
To provide more context on azure functions scenario requirements. 

Azure functions local setup requires a executable which runs and compatible in the host machine.  (native build is done by the local pc)

Azure functions remote deployment requires a executable which runs and compatible with os - linux  arch - amd64

To facilitate the remote deployment, we are thinking of creating the executable on the docker and copying it to host machine.

**Comment by sameerajayasoma** [comment]
We had a meeting on this topic to finalize commands. Participants were Asma, Anjana, Anuruddha, Aquib, Joe, Sameera, Shafreen, and Tharmigan. 

The two most common use cases are:
1) Build a native image in the developer machine. This step requires a GraalVM installation in the developer machine.
2) Build a docker image with the native image compatible with the docker base image. This step does not require a GraalVM installation in the developer machine. 

Therefore we decided to introduce the `--native` command line option to the `bal build` command in Update 3. Here are the semantics of the commands. 

`bal build --native`
- Generates the native executable of the Ballerina program that works on the host OS. 
- Requires a GraalVM installation in the host machine.

`bal build --cloud=docker --native`
- Generates a docker image with a native executable that works on the base docker image. We can pick the default base image. 
- Does not require a GraalVM installation in the host machine.
- This is a multi-stage docker build.

**Comment by hevayo** [comment]
@xlight05 For Azure functions IMO we would need to use both commands `bal build --native` for local testing. `bal build --cloud=docker --native` for remote deployment. In this case how can we pass the Azure specific image for the build. Is the default docker build compatible with Azure ?

**Comment by xlight05** [comment]
> @xlight05 For Azure functions IMO we would need to use both commands `bal build --native` for local testing. 

Yes

> `bal build --cloud=docker --native` for remote deployment. In this case how can we pass the Azure specific image for the build. Is the default docker build compatible with Azure ?

I don't think we should use --cloud=docker in this case. In the case of `bal build --cloud=docker --native` ultimately we generate a docker image, not just a executable right? In Azure function's case, we don't need a docker image, we want to build the executable inside docker(as it needs linux amd64) and copy it back to host machine.

The reason why we use docker is because GraalVM doesn't support cross compilation as golang. Therefore its an implementation detail(or hack) we use. Therefore we need to take care from the compiler plugin, without letting the user decide.
