### ISSUE TITLE
Clarification on constant type checking rules

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-spec#1160]
**Description:**
Need to clarify whether the following constant expressions should be allowed or not.

> 1). When should we do the type checking of constant expressions against the contextually expected type?, before evaluating the expression or after evaluating the expression?
```ballerina
const byte A = 300 - 200; 
// Suggested behaviour: Compile error since additive operator is not defined with `byte`. 
// But the evaluated result belongs to byte.
```
> 2).
```ballerina
const A = true;
const int B = A? 1 : 0.1;
// Suggested behaviour: this scenario is not a compile error since condition is singleton `true`(In a ternary-conditional-expr C ? T : F; if the static type of C is singleton true, then the static type of the result is the static type of T). 
// But if we change the value of `A` to false, then this will be an compile error. Should we disallow these scenarios in constants (condition will be always a singleton value) considering practical usage?
```

**Comment by hasithaa** [comment]
If we apply normal type checking rules, both case 1 and case 2 are compile-time errors.  I think it should be the same for consts as well. 

But, if we extend Case 2 like this, I think it should be ok IMO. 
```ballerina
const A = true;
const B = A? 1 : 0.1;
```

@jclark thoughts?

**Comment by jclark** [comment]
> When should we do the type checking of constant expressions against the contextually expected type?, before evaluating the expression or after evaluating the expression?

This question makes no sense to me. The contextually expected type is not used for type checking.

**Comment by SandaruJayawardana** [comment]
> If we apply normal type checking rules, both case 1 and case 2 are compile-time errors. I think it should be the same for consts as well.

When we consider case 2;
According to the [spec](https://ballerina.io/spec/lang/master/#section_6.32), static type of the result in conditional expression is defined as follows,
```
 In a ternary-conditional-expr C ? T : F, the static type of C must be a subtype of boolean, and the static type of the result is determined from ther static types of C, T and F as follows:

    if the static type of C is singleton true, then the static type of the result is the static type of T;
    if the static type of C is singleton false, then the static type of the result is the static type of F;
    otherwise, the static type of the result is the union of the static types of T and F.
```
When we apply these rules to above example; since type of the `A` is singleton true, result of conditional expression will be the static type of `1`, isn't it?

**Comment by SandaruJayawardana** [comment]
> This question makes no sense to me. The contextually expected type is not used for type checking.

[Spec](https://ballerina.io/spec/lang/master/#section_8.8) says that ```If type-descriptor is present, then it provides the contextually expected type for the interpretation of const-expr. It is a compile-time error if the static type of const-expr is not a subtype of that type. ```
Don't we need to use the type descriptor to type check the constant expression when the type descriptor is available?

**Comment by jclark** [comment]
> Don't we need to use the type descriptor to type check the constant expression when the type descriptor is available?

The static type of the RHS expression is checked against the declared type of the constant.  The declared type of the constant also provides the contextually expected type used to interpret the RHS expression.

In case 2, the static type of the conditional expression is int `1` (per the section of the spec you quoted). This is a subtype of the declared type of the constant (`int`). So it's OK, as you suggest.

In case 1, the contextually expected type for `300 - 200` is byte, which means contextually expected type for `300` and `200` is int. Static type of `300` is thus int `300` and of `200` is int `200` (both singletons). So static type of `300 - 200` is int `100` (also a singleton). This is a subtype of `byte`, so example 1 is OK.
