### ISSUE TITLE
lang.* library spec licensing

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#117]
Our current approach to licensing is that

- source code is Apache
- spec is CC-BY-ND

Switching from built-in methods defined in prose in the spec to function in lang.* modules defined in .bal files raises the question of what license to use for these .bal files.

I am not sure if GitHub allows more than one license per repository, so this might affect which repository they go in.

Maybe we could say these files are dual-licensed?

**Comment by hasithaa** [comment]
@jclark @sanjiva Please look at this, https://github.com/digitallinguistics/DFT/blob/master/LICENSE.md

They have 3 sperate Licence for spec, example, and code. I think we can do the same.

**Comment by jclark** [comment]
That seems like a good approach.

**Comment by jclark** [comment]
We decided to go with same code licensing as elsewhere Apache 2.0.
