### ISSUE TITLE
How should the `lock` statement work when the strand yields inside it?

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-spec#1170]
**Description:**

There is a possibility of deadlock, in this case. The spec says execution of the lock statement-block should not be interleaved with the execution of a lock-stmt on any other strand. So I think we should not release the acquired lock when the strand is yielded, and if we do the behaviour will be different from what is said in the spec. But consider the below code.
```bal
import ballerina/io;

int a = 10;
int b = 20;

public function main() {
    worker w1 {
        lock {
            a += 1;
            io:println(a);
            3 ->> w2;
            b += 1;
            io:println(b);
        }
    }

    worker w2 {
        lock {
            b += 1;
            io:println(b);
            int x = <- w1;
            a += 1;
            io:println(a);
        }
    }
}
```
Then this hangs at runtime and would be an example of a deadlock in Ballerina. Is there anything to be done about this?

Does the spec need to say anything specifically about what should be done when the strand is yielded inside a lock statement?

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by hasithaa** [comment]
We have restricted a few cases related to strands, But I think we missed this case. Yes I agree that we should restrict such cases from the compiler side.

**Comment by jclark** [comment]
We need to do something here.

**Comment by jclark** [comment]
We currently have this:

> It is not allowed to start a new strand within a lock. More precisely, when a strand has started but not yet completed the execution of a lock-stmt, the execution of a named-worker-decl or a start-action on that strand will result in a panic. It is a compile-time error for a named-worker-decl or start-action to occur lexically within a lock-stmt.

So an inter-worker message send/receive can be within lock only if it is lexically within a lock, so the compiler can detect this as part of deadlock analysis of inter-worker message send/receive (which is not currently covered by the spec).

But I wonder if other cases of yielding within a lock (unrelated to inter-worker message send/receive) are also problematic.  The idea of `lock` is that it only contains minimal chunks of code that access mutable state.  Putting things that can yield inside lock is not a good idea. I am wondering whether attempting to yield within a lock should be a runtime error.

**Comment by hasithaa** [comment]
We yield strands when they waiting for IO. i.e., remote method calls. So making yield within a lock means we can't do an http call inside a lock.

There are some patterns like Single producer, which we can implement using the lock. But those are not the actual intended usage of the lock feature. We need a semaphore to implement those.  

Considering the general case, restricting yielding within a lock seems to be a good idea since it encourages the intended usage of the lock.

**Comment by jclark** [comment]
Simple fix is to say that blocking send or receive inside a lock is a compile-time error.
