### ISSUE TITLE
Putting optional fields conditionally inside an expression function body

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-spec#1186]
**Description:**

Let's take below example which is one of the use cases from a Data Mapper user. 

```ballerina
type FooRecord record {
    string foo;
    string title?;
};

type BarRecord record {
    string bar;
    string title?;
};

function foo2bar(FooRecord foo) returns BarRecord => {
    bar: foo.foo,
    title: foo.title ?: "default val" // Note: Issue is here
};
```

Instead of a default value, we need to avoid putting **title** field if **foo.title** is not present. 
Is there a way to achieve this right now in Ballerina?

When the target field is in a nested level, this is achievable by writing a conditional expression or a helper function to create the whole nested value. 

```ballerina
type FooRecord record {
    string foo;
    record {
        string text;
        string title?;
    }[] notes;
};

type BarRecord record {
    string bar;
    record {
        string text;
        string 'type;
        string title?;
    }[] notes;
};

function foo2bar(FooRecord foo) returns BarRecord => {
    bar: foo.foo,
    notes: from var notesItem in foo.notes
        let var notesSegment = 
            {
                'type: "ISSUE",
                text: notesItem.text
            },
            var title = notesItem.title
        select (title is string)
            ? 
                {
                    ...notesSegment,
                    title
                }
            : notesSegment
                
};
```

Originated from the discussion at :
https://discord.com/channels/957996897782616114/1040676583985401866/1040676583985401866

Related data mapper issue
https://github.com/wso2/ballerina-plugin-vscode/issues/274

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
This is fixed by #1079.  You should be able to do simply:

```
function foo2bar(FooRecord foo) returns BarRecord => {
    bar: foo.foo,
    title: foo.title
};
```
