### ISSUE TITLE
Can't we have a filler value for regexp type

### ISSUE THREAD

**Issue by prakanth97** [ballerina-platform/ballerina-spec#1188]
**Description:**
According to the spec, there is no filler value for regexp type. This restricts few use cases of regexp like below,
```
string:RegExp[4] regArr = [re `A`, re `B`, re `C`];
regArr[3] = re `D`;
```
but it is better to allow these cases.
https://ballerina.io/spec/lang/master/#FillMember

**Comment by jclark** [comment]
I agree with your suggestion.

**Comment by jclark** [comment]
Part of #130.

Need to think about how we generalize this to data-tags.

**Comment by jclark** [comment]
Generalize by saying if

```
d``
```

is valid for the data-tag d, then that's the filler value.
