### ISSUE TITLE
No way to write type of function.call built-in method as a function

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#119]
We would need something like

```
@typeParam
private TupleType any|error[];
@typeParam
private Type any|error;
public function call(function<TupleType,Type> f, *TupleType) returns Type;
```
where `*T` splices in the type (like in a record type) i.e. `T...` is the same as `*T[]`.

Alternatively, we could consider coming up with syntax for this, which might also address issue #98.

**Comment by jclark** [comment]
This also related to #7

**Comment by sameerajayasoma** [comment]
How about this? 

Assumption: The type descriptor of any function is `function returns any|error`

```
@typeParam
private Type any|error;
@typeParam
private Type1 any|error;
public function call(function returns Type f, Type1... args) returns Type;
```

**Comment by jclark** [comment]
We decided not to provide this as a lang.function function and not to provide syntax for this yet.

The use case for this is where you have a field of function type and you want to call it. Workaround is to assign to a variable and then call through the variable.
