### ISSUE TITLE
Creating the `Dependencies.toml` file by default

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#1190]
The `Dependencies.toml` file captures the state of a package (dependency graph) at the time of the last successful build. Bal tool uses the `Dependencies.toml` file to produce deterministic builds if required by the developer. In all other cases, bal tool uses the `Dependencies.toml` file to upgrade dependencies to their latest patch versions automatically. Bal tool does not upgrade to the latest minor dependency version. 

Bal tool with the `Dependencies.toml` file can produce successful builds if the following assumptions hold:
- Newer patch versions of a given dependency version are compatible
- No source code changes
- Ballerina platform update version used to produce the `Dependencies.toml` file is used for the subsequent build.
- New patch versions of a given Ballerina platform update are compatible.

**Comment by sameerajayasoma** [comment]
However, we've recently encountered build issues when switching to a newer or older platform update version, and the standard solution is to delete the `Dependencies.toml` file. 

Due to some corner cases in the spec or the compiler implementation, we had to add a few backward incompatible essential changes to the recent platform updates. Because of such modifications, some standard library versions released with new updates are incompatible with older platform versions. Some standard library versions released with older platform updates are incompatible with more recent versions. 

We discussed a solution to record the minimum platform version required to build a package in https://github.com/ballerina-platform/ballerina-spec/issues/903. With that, we can figure out a way to solve the above issue.

**Comment by azinneera** [comment]
Deleting the `Dependencies.toml` might not be the ideal solution for a user who has imported libraries belonging to non-ballerina organizations such as `ballerinax` packages. These packages can be published with new major versions which will have incompatible changes and if the `Dependencies.toml` is not present, the latest version which contains incompatible changes will be pulled and the build would fail.

**Comment by azinneera** [comment]
We discussed the following solution:

* Record the distribution version in the Dependencies.toml
* If the distribution of the current build is higher than the one recorded in the Dependencies.toml, then 
     * Set the version resolution to `SOFT` lock mode (automatic updates are set to pick the latest compatible minor version). 
       Once the build is successful, the distribution version in the Dependencies.toml will be updated to the version of the current distribution. The next builds will resolve patch versions as usual.
     * Issue a warning to notify the user that a higher version of the distribution is detected and so dependencies will be upgraded to the latest minor versions.
* The next builds will have the automatic update at patch level which is the default behavior

**Comment by azinneera** [comment]
There is another case that satisfies the condition to set the locking mode to `SOFT`:

* The `Dependencies.toml` does not exist but a dependency (applies to both direct and transitive) is built using an older Update distribution which. 
   E.g. A user working with U4 imports `foo` that has the latest version built with U3. `foo` has dependencies that contain code incompatible with U4. Currently, `foo` must do a dependency update and release it with U4.
