### ISSUE TITLE
Allow action invocations inside `join-clause`

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#1210]
As part of the https://github.com/ballerina-platform/ballerina-spec/issues/1059, We allowed `from-action-clause`, `let-action-clause`, and `select-action-clause`.  But we can allow action invocation in other clauses such as join, where, etc.

**Comment by jclark** [comment]
@sameerajayasoma's issue was `join`. Each kinds of clause raises its own issues, so let's keep this one to `join`.

**Comment by jclark** [comment]
This would involve changing the reference to join-clause in (intermediate-action-clause)[https://ballerina.io/spec/lang/2022R4/#intermediate-action-clause] to reference:

```
join-action-clause := ["outer"] "join" typed-binding-pattern "in" action-or-expr on join-on-condition
```

**Comment by jclark** [comment]
@hasithaa The language allows actions only in contexts that are "top-level" in some sense, not in arbitrary nested expressions. For example, the boolean condition in an if-else-stmt cannot be an action. This is to facilitate the drawing of the diagram.
