### ISSUE TITLE
Cannot add ` in regex expression 

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-spec#1215]
**Description:**
Ballerina specification did not allow to use \` inside regular expression.
\\` is not working according to the current specification.

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/39446

**Comment by SasinduDilshara** [comment]
![Screenshot 2023-02-06 at 11 31 46](https://user-images.githubusercontent.com/47134066/216895564-206eb24d-dfb7-44ea-816f-063ffef22aec.png)

Spec is currently allowing only above `ReSyntaxChars` after the `\\`.

**Comment by jclark** [comment]
You need to use `\u{60}`.

**Comment by SasinduDilshara** [comment]
> You need to use `\u{60}`.

The specification did not mention about this. Don't we need to add it?

**Comment by SasinduDilshara** [comment]
> > You need to use `\u{60}`.
> 
> The specification did not mention about this. Don't we need to add it?

This is mentioned in the `String template expression` section as follow

```
A literal ` can be included in string template by using an interpolation ${"`"}.

```
