### ISSUE TITLE
How to deal with map as function name?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#122]
Our revised approach to built-in functions (#111) requires that map be a function name in the lang.* modules for list and map.

We can consider built-in type names to be identifiers that are reserved in certain contexts, but not others, in particular not in the name of a method-call (which is a different symbol space). Then we can use a delimited identifier to define these in the lang.* modules.

**Comment by sameerajayasoma** [comment]
In the section `in particular not in the name of a method-call `, Did you mean to say method-decl or method-defn here?

**Comment by jclark** [comment]
No I meant method-call, e.g. I can says x.map(y) even though map is reserved as the name of a type.

**Comment by jclark** [comment]
We decided to deal with this by using a delimited identifier in the lang.* modules.
