### ISSUE TITLE
`cloneWithType` leftmost rule results in surprising outcomes

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-spec#1229]
```ballerina
import ballerina/io;

type D readonly & record {|
    decimal n;
|};

type F readonly & record {|
    float n;
|};

public function main() returns error? {
    F r1 = { n: 1.0f };
    D|F r2 = check r1.cloneWithType();
    io:println(r2 is D); // prints `true`
}
```
I expected `cloneWithType` to preserve the type.

**Comment by manuranga** [comment]
I think leftmost tie breaking has to happen as a last resort, but in the above case there has to be a stronger rule that selects the existing type.

Perhaps the leftmost rule is only important for `fromJsonWithType`.

**Comment by jclark** [comment]
Let's move this into #1194

**Comment by manuranga** [comment]
Moved
