### ISSUE TITLE
Add lang.future module

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#123]
Need at least a method to kill a worker (see #40).

**Comment by hasithaa** [comment]
In the implementation, we support the following. 

https://github.com/ballerina-platform/ballerina-lang/blob/0bd8e8dc223f325e292f2688e979df64e9a440d5/stdlib/builtin/src/main/ballerina/builtin/futurelib.bal#L21-L31

**Comment by jclark** [comment]
@hasithaa What are the semantics of isCancelled and isDone?

**Comment by hasithaa** [comment]
`isDone` returns `true`, if the future is completed, `false` otherwise. 
`isCancelled` returns `true` if the future is canceled. (stand is status is terminated). `false`, otherwise.

**Comment by jclark** [comment]
@hasithaa At what point is future completed (after a wait has been done, or when a wait can be done without blocking)? At what point is it cancelled (immediately after cancel has been called, or after the worker has acted on the cancel)? Are isDone and isCancelled independent of each other? We should draw ourselves a little state diagram for a future to show possible states and transitions between states.

**Comment by jclark** [comment]
I added cancel with a nil return (so you don't have to check it).

For the others, I added a separate issue #139.
