### ISSUE TITLE
Clarification regarding when a union type is definite

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#1237]
**Description:**
The spec says 

[union-type-descriptor](https://ballerina.io/spec/lang/master/#union-type-descriptor)

> A union type T1|T2 is definite if and only if both T1 and T2 are definite and the set of type-ids induced by T1 and T2 are the same. If it is definite, then it induces the same set of type-ids as T1 and T2, and a type-id is primary if it is primary in either T1 or T2.

[error-constructor-expr](https://ballerina.io/spec/lang/master/#error-constructor-expr)

> The applicable contextually expected type E must be definite.

Just to confirm, 

1. in the following example, `E3` is not definite, and therefore, using it with the error constructor should result in a compilation error, right? (jBallerina allows this at the moment).

```ballerina
type E1 distinct error;
type E2 distinct error;

type E3 E1|E2;

public function main() {
    E3 e = error("Oops"); // compilation error?
}
```

2. since for a union `T1|T2` to be definite, `T1` and `T2` have to be definite and the type-ids induced by T1 and T2 have to be the same, doesn't that effectively mean a union of distinct errors is definite only if each member is the same type?

```ballerina
type E1 distinct error;
type E2 E1;

type E3 E1|E2; // now definite?

public function main() {
    E3 e = error("Oops"); // OK
}
```

Just trying to figure out when exactly an error union can be definite.

For objects, I guess there can be unions of different object types that are definite.

```ballerina
distinct class A {
    int i = 1;
}

class B {
    *A;

    function init() {
        self.i = 2;
    }
}

class C {
    *A;

    function init(int i) {
        self.i = i;
    }
}

type D B|C; // definite?
```

3. The last sentence (on unions) says 

> If it is definite, then it induces the same set of type-ids as T1 and T2, and a type-id is primary if it is primary **in either T1 or T2**.

I did see https://github.com/ballerina-platform/ballerina-spec/issues/524#issuecomment-631269583, but if it is definite, won't the primary (and therefore, secondary) type-ids always be the same in both T1 and T2? Just to confirm because "either-or" is used.

**Related Issues:**
https://github.com/ballerina-platform/ballerina-spec/issues/527
https://github.com/ballerina-platform/ballerina-spec/issues/1177

**Comment by jclark** [comment]
When you are constructing an error, you have to know the type-ids that the error you're constructing should have, and there shouldn't be any ambiguity about it.

The complexity comes from dealing with things like `(E & error<T>)|E`, where E is a distinct error.

**Comment by jclark** [comment]
> if it is definite, won't the primary (and therefore, secondary) type-ids always be the same in both T1 and T2?

Why?

**Comment by MaryamZi** [comment]
> > if it is definite, won't the primary (and therefore, secondary) type-ids always be the same in both T1 and T2?
> 
> Why?

Is it possible to have two types with the same type ids but not the same primary type ids (and secondary type ids)?

Maybe I misunderstood, but I couldn't think of such a scenario. Doesn't a primary type-id become a secondary type-id only when used in a distinct type-descriptor or a distinct class? And since that would always result in a new primary type-id the type-id sets won't be equal?

**Comment by jclark** [comment]
> Is it possible to have two types with the same type ids but not the same primary type ids (and secondary type ids)?

Can we not get that from intersections https://ballerina.io/spec/lang/2022R4/#section_5.6.8 ?

**Comment by MaryamZi** [comment]
> > Is it possible to have two types with the same type ids but not the same primary type ids (and secondary type ids)?
> 
> Can we not get that from intersections https://ballerina.io/spec/lang/2022R4/#section_5.6.8 ?

Even with an intersection type (`T1 & T2`), won't a primary type-id continue to be a primary type-id (since the spec doesn't require it to be primary in both `T1` and `T2`)?

> An intersection type T1&T2 is definite if and only if both T1 and T2 are definite. If it is definite, then it induces the union of the set of type-ids induced by T1 and T2, and **a type-id is primary if it is primary in either T1 or T2**.

**Comment by jclark** [comment]
I was wondering about something like `(T&S)|T`, where  S is a subtype of T, and the type-ids that are primary in S are secondary in T. In that case, won't `T&S` have the same type-ids as `T`, but `T&S` will have more primary type-ids?

**Comment by MaryamZi** [comment]
> I was wondering about something like `(T&S)|T`, where S is a subtype of T, and the type-ids that are primary in S are secondary in T. 

Where `T` is a subtype of `S`, right? Got it, thank you.

**Comment by jclark** [comment]
> Where T is a subtype of S, right?

Right.
