### ISSUE TITLE
Should object method param names be equal in declaration and definition?

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-spec#124]
If we consider an object, should the parameter names of a method declaration be equal to their corresponding counterparts in the method definitions? 
```ballerina
type Foo object {
    function print(string value);
};

function Foo.print(string v) {
    
}
```
The spec doesn't specify whether the param names are significant in this case. 

Somewhat related to #125 as well

**Comment by jclark** [comment]
There is no logical need for them to be the same, but it would probably reduce confusion to require this. @sanjiva what do you think?

**Comment by sanjiva** [comment]
We should require them to be the same - otherwise its lots of unnecessary confusion.

**Comment by pubudu91** [comment]
Ack. Will keep the same name for both.

**Comment by jclark** [comment]
@sanjiva Also need to decide whether annotations are required to be the same for both.

**Comment by sanjiva** [comment]
No I think annotations have to be different I think .. and we union the annotations. 

(That raises an interesting question whether annotation order matters .. new issue?)

**Comment by jclark** [comment]
I don't think they should be union-ed. A user who wants to make use of the object type should only have to read the object type declaration, and should not need to look at the outside method implementations. If you don't want to repeat, then I think the annotations relating to the function type should be on the declaration only. Annotations on extern could of course on the definition.

**Comment by sanjiva** [comment]
Hmm that means there's a semantic difference between

```
object A {
  @x:y { }
  function foo () { .. }
}
```
and
```
object A {
  function foo ();
}

@x:y { }
function A.foo () { .. }
```

I'm not sure that's good.

Also, didn't understand `Annotations on extern could of course on the definition.` If you meant "could be on the definition" then I don't know what that means ... extern means not implemented in B7a. So where would B7a annotations go?

**Comment by sameerajayasoma** [comment]
AFAIU, What @jclark  meant to say is the following.
```ballerina
object A {
  @x:y { }
  function foo ();
}

@java {class:"", method:"" }
function A.foo () = external
```
This can confuse a mort. Figuring out what annotations go on the declaration and what annotations go on the definition is not straightforward IMO.

**Comment by sameerajayasoma** [comment]
Should we also talk define which documentation takes the precedence? It is logical to say that documentation should be specified on the method declaration.

**Comment by jclark** [comment]
The @java annotation should be on the external

**Comment by jclark** [comment]
This also relates to parameter names being optional, which was issue #148.

**Comment by sanjiva** [comment]
All of this my poor Mort-mind-blowing aspects can be avoided if we lose outside methods and just say methods have to defined, not just declared, in the object itself.

I guess that ship has sailed already :).

In that case I think we should just require everything that is being repeated (function name (duh), param names, modifiers) to be the same and for other metadata (docs, annotations) to be in declaration in the object. If anything is specific to the implementation (e.g. annotation related to '= external') then that can be on the definition, not decl.

**Comment by jclark** [comment]
Conclusion after discussion today was that we should consider removing the outside method definition feature. See issue  #179.

**Comment by jclark** [comment]
Since we decided to remove the outside method definition feature, this issue no longer arises.
