### ISSUE TITLE
Using computed-name-fields when constructing immutable mapping values

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#1245]
**Description:**
The [spec](https://ballerina.io/spec/lang/master/#computed-name-field) says 
> A mapping-constructor-expr first constructs a mapping value without considering any computed-name-field. The effect of a computed-name-field is to modify the member of the mapping with the specified name after the mapping has been constructed.

But this disallows using computed keys when constructing immutable values, right?

```ballerina
function constructMap(string k, int v) returns readonly & map<int> => {[k]: v};
```

The jBallerina implementation allows this atm (creates an immutable mapping with the specified key-value pair).

Related to https://github.com/ballerina-platform/ballerina-spec/issues/532#issuecomment-635298201

**Related issues:**
https://github.com/ballerina-platform/ballerina-spec/issues/532

**Comment by jclark** [comment]
I think one could rephrase it a bit to make this work for immutable mappings: i.e. mutate the members and then set the read-only bit.  With immutable structures there's always an initial stage where one is constructing the value during which the memory associated with the structure is immutable.
