### ISSUE TITLE
Significance of param names is inconsistent in grammar vs. the text

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-spec#125]
In the grammar, the function signature is defined as follows:
```
function-signature := ( param-list ) return-type-descriptor
return-type-descriptor := [ returns annots type-descriptor ]
param-list :=
   required-params [, defaultable-params] [, rest-param]
   | defaultable-params [, rest-param]
   | [rest-param]
required-params := required-param (, required-param)*
required-param := annots type-descriptor param-name
defaultable-params := defaultable-param (, defaultable-param)*
defaultable-param := annots type-descriptor param-name default-value
rest-param := annots type-descriptor ... [param-name]
```
According to the above definition, param names are a part of the function signature as well, except in the case of rest params. But later on the spec says the following:
```
The parameter names do not affect the shape of the function and thus do not affect typing.
```
Normally when we use the term function signature we are only concerned about the types, not the names right? If so, the grammar doesn't really reflect that.

**Comment by jclark** [comment]
Parameter names are allowed in the signature but do not affect the type. In this respect, Ballerina is no different from Java, C and C++.

Where Ballerina is different is that parameter names are part of the _type descriptor_ (note that type and type descriptor are not the same thing: a type descriptor denotes a type but that's not all it does) and are used in a function-call-expr to transform named arguments into positional ones (in a similar way to Scala).

Please feel free to reopen if you are unclear about the behaviour the spec intends.

**Comment by hasithaa** [comment]
@jclark According to current spec grammar, the following syntax is not allowed. 

```ballerina
function test() {
  (function (string,int) returns boolean) foo= somefunction;
}
```

Instead, it supports,

```ballerina
function test() {
  (function (string name, int age) returns boolean)  foo= somefunction;
}
```

1) It seems like a bug. isn't it?
2) However if we support both, we can allow named argument in function pointer call `foo(name = "aaa", age = 10);`

**Comment by jclark** [comment]
This is a separate point: should parameter names be optional in function type declaration? Please create a separate issue.

**Comment by hasithaa** [comment]
Ack.
