### ISSUE TITLE
Clarification on computing intersections for records having annotations on fields

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-spec#1258]
**Description:**
Consider the following program where the field `a` of record `Foo` and `Bar` having annotations attached

```bal
annotation map<anydata> x on field;

type Foo record {|
    @x {
        maxValue: 10
    }
    int a;
|};

type Bar record {|
    @x {
        maxValue: 20
    }
    int a;
|};

type FooBar Foo & Bar;
```

Spec does not define how to deal with annotations in such scenarios

**Comment by jclark** [comment]
Please supply a *complete* program whose behaviour is undefined.

**Comment by jclark** [comment]
I don't think we allow general intersections as inherent types, so you can't get this from a `typeof`.  The case we do need to deal with is much simpler e.g. `readonly & record {| @x { maxValue: 20 } int a; |}`

**Comment by rdulmina** [comment]
This means we disallow (ie: disallow cases where the intersection type used as CET for the constructors)
```bal
FooBar a = {a: 3};
```
but allow
```bal
Foo & readonly a = {a: 3}; // Allow only readonly intersections as CET for the constructors
FooBar b = a;
```

**Comment by jclark** [comment]
Yes.

**Comment by jclark** [comment]
We should define this for intersections generally as part of #1143.

**Comment by jclark** [comment]
Feel free to reopen if you think #1143 doesn't cover this.
