### ISSUE TITLE
Clarify the type handling method in Ballerina Binary Expressions

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-spec#1262]
Please consider the following case,
```
xml a = "a" + "b" + xml ``; // No compile error
```
In here, Ballerina will first calculate the ("a" + "b"), for that additive operation and the contextual expected type is xml.

In the Ballerina spec, under the `Additive Expressions` section, It says
```
the static type of both operand expressions is a subtype of the same basic type, in which case the static type of the result will be this basic type
```
So according to that the addition between two strings under the xml as a contextual expected type is should be a compile time error.

In user point of view 
```
xml a = "a" + "b" + xml ``;
```
 This is a addition between xml and string which is allowed by the Ballerina.
 
 What should be the correct behaviour?
 
 Note that this will also applicable to the `float f = 1 * 1 * 1.2;` as well

**Comment by jclark** [comment]
The difference is that `"x"` always has type string, whereas `1` can have type int, decimal or float depending on the contextually expected type.
