### ISSUE TITLE
Invalid equality check between two xml

### ISSUE THREAD

**Issue by prakanth97** [ballerina-platform/ballerina-spec#1268]
**Description:**
```
public function main()returns error? {
    xml xml1 = xml `<Data xmlns:ns1="NS1" ns1:a="1">value</Data>`;
    xml xml2 = xml `<Data xmlns:ns2="NS1" ns2:a="1">value</Data>`;

    io:println(xml1 == xml2);
}
```
In the above case `ns1` and `ns2` have same `URI` hence `xml1` and `xml2` should be equal but we get `false`. It seems we check the string equality instead of checking the namespace. 

Is the above behaviour correct?

**Comment by jclark** [comment]
The two attributes `ns1:a` and `ns2:a` are the same but the attributes `xmlns:ns1` and `xmlns:ns2` aren't. If you declare the namespaces using Ballerina xmlns declarations and omit the xmlns attributes, then the two XML documents should compare ==.

**Comment by hasithaa** [comment]
In JBallerina, the following program returns `false`. According to your explanation, this is a spec deviation in the implementation. 

```ballerina
import ballerina/io;

public function main() {

    xmlns "NS1" as ns1;
    xmlns "NS2" as ns2;
    xml xml1 = xml `<Data ns1:a="1">value</Data>`;
    xml xml2 = xml `<Data ns2:a="1">value</Data>`;
    io:println(xml1 == xml2); // should be `true`
}
```

But semantically, the above is equal to the following program. However, the actual XML value sequences are different in two cases. I guess that is your point. 

```ballerina
import ballerina/io;

public function main() {

    xml xml1 = xml `<Data xmlns:ns1="NS1" ns1:a="1">value</Data>`;
    xml xml2 = xml `<Data xmlns:ns2="NS1" ns2:a="1">value</Data>`;
    io:println(xml1 == xml2); // `false`
}
```

So depending on the way we write the program, XML's deep equal semantics are affected. Not sure whether we should document this in the spec.

**Comment by jclark** [comment]
I think the spec addresses this in its description of the XML namespaces: https://ballerina.io/spec/lang/2022R1/#section_5.3.2.1  Ballerina's model of XML includes XML namespace attributes.

It's important to remember that the xml type represents not just complete XML documents but fragments of XML documents.  When an xml value represents an element occurring not at the root of as document, it's possible and reasonable for the element to use namespaces without there being corresponding namespace attributes.
