### ISSUE TITLE
Allow named worker to have on-fail clause

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#1274]
For #1271, it would be convenient to allow a named-worker-decl to have an on-fail-clause.

This is just a syntactic convenience to avoid an extra level of nesting.

**Comment by lochana-chathura** [comment]
@jclark we have implemented this as well.

**Comment by jclark** [comment]
@lochana-chathura Please tag any others you've implemented with implementation/done

**Comment by sanjiva** [comment]
Can we do this for the default worker too please? The semantics are ok ;-).

```ballerina
function f() {
  // code1
  // named workers
  // code2
} on fail .. {
}
```

Any `check` in code1 or code2 will get directed to the `on fail` for the function worker.
