### ISSUE TITLE
Spec doesn't mention about the immutability of the RegExp type

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-spec#1282]
**Description:**
The ballerina specification does not provide information on about the  immutability of the RegExp type. Is it inherently immutable or selectively immutable? I think this information should be included the spec.
[https://ballerina.io/spec/lang/master/#section_5.6.5](https://ballerina.io/spec/lang/master/#section_5.6.5)

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by hasithaa** [comment]
Regexp is a tagged data. In the spec, under [Tagged Data](https://ballerina.io/spec/lang/master/#section_5.2.5) this is mentioned. 

> Every tagged data value is plain data, immutable and has no storage identity.
