### ISSUE TITLE
What is the reason for not allowing default values for record fields with previous record fields.

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-spec#1287]
Please consider following code.

```
type Rec record {|
    int a;
    int b;
    int add = a + b;
|};
```

This is not allowed in our Ballerina spec.

But if we consider the function definitions, following is allowed.

```
function test(int a, int b, int add = a + b) {
    
}
```

In the spec, under the `functions` section, it says,

```
An expression can be used to specify the default value; this expression may refer to previous parameters
```

Is there any specific reason to not allowing default values for record fields with previous record fields?

**Comment by hasithaa** [comment]
Record fields are not ordered and syntactic order doesn't imply the order. but function parameters are ordered. That is why, we can't refer to other fields from another field.

**Comment by SasinduDilshara** [comment]
> Record fields are not ordered and syntactic order doesn't imply the order. but function parameters are ordered. That is why, we can't refer to other fields from another field.

Thank you.
