### ISSUE TITLE
Scope of the XML namespace declaration statement 

### ISSUE THREAD

**Issue by poorna2152** [ballerina-platform/ballerina-spec#1289]
**Description:**

For [xmlns-decl-statement](https://ballerina.io/spec/lang/master/#xmlns-decl-stmt),
1. Is it possible to forward-reference a xml namespace defined within a function/block. If possible does a default xml namespace affect the xml variables defined prior to namespace definition (eg: does the default namespace in the `main` function affect `x` in the code.)
```ballerina
public function main() {
    xml x = xml `<a>ab</a>`;
    xmlns "http://example.com/" ; 
}
```
 
2. Is it possible to define multiple default xml namespaces within the same block. If it is possible to define multiple default xml namespaces what is the scope that is relevant to a particular definition.

```ballerina
public function main() {
    xmlns "http://example.com/"; 
    xml x1 = xml `<a>ab</a>`;

    xmlns "http://example2.com/"; 
    xml x2 = xml `<b>cd</b>`;
}
```
**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
The usual rules for declarations should apply.  So you can't have forward references within a block, and you cannot redeclare the default namespace within a block.
