### ISSUE TITLE
Finalize name for lang.any module

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#132]
We need to finalize a name for the module that we have been calling any.

**Comment by sameerajayasoma** [comment]
If the functions defined in this module accepts errors, then it is not correct to say `any` IMO.  Relates to #127

**Comment by jclark** [comment]
Agreed any is right. Semantic is function that applies to more than one basic type (not all basic types). Note that also used as fallback for single basic type.

Best solution proposed so far is `value`.
