### ISSUE TITLE
Name and semantics of value:convertTo/setType

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#136]
Should we rename to to value:convertToType?

- make it pair better with setType
- make it clear that it is not a general value conversion facility (as it has been misused up to now), but relates to the changing the inherent type of values

**Comment by sanjiva** [comment]
+1.

**Comment by sanjiva** [comment]
Sorry meant to add:

To me `convertToType` has a hint of in-place conversion.  Should we maybe use `copyAsType`?

**Comment by jclark** [comment]
At the moment the value module has `clone` and `unfrozenClone`. I don't think the word `copy` goes well with those. How about `typedClone`? `cloneAsType` would imply that it handles frozen values like clone does (i.e. leaves them frozen), which I think is probably not what we want (since it would prevent adding defaults), but I think we probably want cloning more like `unfrozenClone` does.

**Comment by sanjiva** [comment]
The most accurate name would be `unfrozenCloneAsType` .. rather ugly but accurate. 

Are we expecting this to be widely used? If not, I prefer using ugly but semantically accurate names.

**Comment by jclark** [comment]
This raises wider issues of whether we need both this function and setType, and what its semantics should be.

**Comment by jclark** [comment]
I think we want to name this function so it groups with setType rather than with clone, since the former can return errors and the latter cannot.

**Comment by jclark** [comment]
@hasithaa @sameerajayasoma Can you comment on the implementation implications of setType and convertTo? Is setType long-term going to handicap implementation performance?

**Comment by hasithaa** [comment]
I don't have a clear idea, how this is going to work on native implementation. But in current JBallerina implementation, we can support this with minimal cost, because JBallerina tracks inherent type as a field of the value. (@sameerajayasoma correct me if I am wrong). 

But the current approach is not optimal.  Ideally, we should generate direct Java classes for each Ballerina types (i.e., record, objects, etc.). In such cases, the Java class itself represents the inherent type. So we have to do some magic to support these two operations.

**Comment by jclark** [comment]
I suspect `freeze` will share some of the same implications for implementation as `setType`, since `freeze` effectively narrows the inherent type.

**Comment by jclark** [comment]
Conclusion:

- get rid of value:setType
- replace value:convertTo by typedesc:constructFrom(anydata)

Semantics of constructFrom  is similar to recursively calling constructors passing parts of anydata as input, so will do a mutable clone.
