### ISSUE TITLE
Add lang.xml module

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#138]
Need at least

- length
- iterator
- attributes (replaces `@` operator)
- fromString
- setContent
- something to get element name

Probably lots more.

**Comment by hasithaa** [comment]
Following are the functions we support in the current implementation. 

https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/builtin/src/main/ballerina/builtin/xmllib.bal

It seems like some functions are no longer needed, (like `copy` as we have clone). 

@jclark I think this should be part of the R2; At least a minimal set of functions.

**Comment by jclark** [comment]
@hasithaa Why is the parameter type of setAttributes map<any> rather than map<string>?

**Comment by hasithaa** [comment]
It seems like a mistake, it should be a `map<string>`

**Comment by jclark** [comment]
Also note that in R1, XML is not a preview type.

**Comment by jclark** [comment]
See #160 and #142 and #115.

**Comment by jclark** [comment]
We decided to make XML preview in R2. See issue #184. So this is done unless implementation side needs changes,
