### ISSUE TITLE
Function in lang.map to remove all entries

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#141]
Possible names:

- clear
- removeAll

We don't need this for array, because we can just do `arr.setLength(0)`.

**Comment by sameerajayasoma** [comment]
We already have `remove` and I think `removeAll` is consistent with that. 

The current implementation has `clear`.

**Comment by jclark** [comment]
Although removeAll is tempting because of the relationship to remove, I prefer clear. If you were talking to somebody, would you say "now clear the map" or "now remove all entries from the map"?

JavaScript has Map.clear. Java has Map.clear. C# has Dictionary.clear. Python has dict.clear.

If we have remove on array and remove on map and removeAll on map, then I think we would need removeAll on array, which is unnecessary given setLength.

Another difference is that remove for us, is remove the value _and return it_.

**Comment by hasithaa** [comment]
@jclark, IMO, `clear` has a different semantics when it is used on a closed record. We can fill the required keys with a filler value (like lists) otherwise panic. If so, `clear` will not set the length to zero.

**Comment by jclark** [comment]
It won't work well to use that semantics for clear. Problem is that records are a subtype of map. Suppose you have a function foo that takes a map, and calls clear on it. The expectation would be that all entries are removed. If a record is passed to that function foo, then it's not OK if clear succeeds without removing all entries.

Note that the problem here is not closed records, but records with non-optional fields. Also filler values are a concept that is array-specific: records have defaults.

However, I do accept the point that the meaning of clear is more open to misinterpretation than removeAll, when applied to a record. We have to balance that against the conciseness and almost universal choice of clear as the name of the method that removes all entries from a map.

I am OK with either name. But the semantics needs to be remove all entries, and panic if that is inconsistent with the inherent type.

**Comment by jclark** [comment]
Decision is for `removeAll` on both array and map.

**Comment by hasithaa** [comment]
@jclark map lib still has the clean function.

https://github.com/ballerina-platform/ballerina-spec/blob/2799bd7d6730427f8b9eedbec0523bbb3022886d/lang/lib/map.bal#L48
