### ISSUE TITLE
Versioning of lang.* modules

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#142]
The following are inconsistent

1. lang.* modules are versioned according to the spec
2. spec versions are 20xxRy
3. module versions must follow semver syntax

**Comment by sanjiva** [comment]
I think the idea is that a spec version will indicate the set of version #s of the lang.* modules that go with that spec version right? (That's what we documented in #115 I think.)

In that case I'm not sure what the problem?

**Comment by jclark** [comment]
The grammar for import-decl requires a X.Y.Z version number, which stops you importing e.g. version 2019R3 of a lang module.

**Comment by jclark** [comment]
Solution is that langlib has a mapping from spec version e.g. 2019R3 to semver 1.0.0

**Comment by jclark** [comment]
There is a lang spec part of this (lang spec defines version number for each lang module) and a platform part (how does the compilation environment pick up these version numbers).
