### ISSUE TITLE
Pure/isolated function concept

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#145]
I think there is a concept of what might be called a _pure_ function that needs to be worked out. The basic idea is that pure functions have limited access to global state. They can access mutable state via parameters but their access to module-level variables is restricted. A Listener would be able to safely use multiple threads on resource methods that are pure. 

This relates to a number of different things that we have discussed:

- service concurrency #116 
- when is right to treat a function value as immutable, and thus able to be a member of a frozen container? relates to issue #70 
- compile-time functions
- functions used within queries
- lock statement #357 
- transactions #267 
- sessions

There is a close relationship to immutability: I suspect that just as our solution to immutability is not purely static (because that is excessively burdensome on the programmer), so our approach to functions will also need to be at least partly dynamic.

**Comment by jclark** [comment]
D has something like this

https://dlang.org/spec/function.html#pure-functions

**Comment by jclark** [comment]
Need to think about how this relates to function as a service: the key thing is to be able to separate out the state from the logic so that the runtime can manage the state.

**Comment by jclark** [comment]
There's now a [proposal](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/isolated/isolated.md).

**Comment by rdhananjaya** [comment]
I think we need to extend the `isolated` analysis into type definitions since object/record construction could execute user-defined behavior as default values. Maybe mandate those functions to be isolated.

```ballerina
int x = 10;

type Foo record {
    int i = foo(); 
}

function foo() returns int {
     x= 20;
     return 33;
}

isolate function bar () {
    Foo f = {}; // this might cause a side effect. // A problem case.
}

isolate function baz (Foo f) {
    f.i = 10; // OK
}
```
Putting down a few thoughts I had while reading the proposal, these are influenced by experiences I had working with the taint analyzer.

Say when the Ballerina program is first developed `foo()` was not side-effecting (inferred to be isolated), but after some time someone changes something and now the `foo()` is inferred to be a side-effecting function and the compiler now surprise the developer with an error saying something like `invalid record literal, a default value may cause the state to change in an isolated context`.

I think it's really difficult to analyze the side effects caused by functions passed in as values:

Q1. When a function pointer is passed in as an argument to the function and execution of that function pinter could mutate something somewhere, are those mutable bits part of the mutable local storage graph of the isolated function?

And since the arguments are runtimes values, except for simple cases it's difficult to detect which function is being passed in as an argument. (I think same is true when the function value is passed via a closure or module variable)

Another thing to note is that majority of the improvements/bug fixes to this isolated function analyzer will break user code,

**Comment by jclark** [comment]
The design of isolated feature is different in fundamental ways from the taint feature.

On your first point, my inclination to mandate that expressions specifying defaults for record fields be isolated.

On your second point, the key difference is that isolated is part of the type of the function. If an isolated function f gets passed a function g as a parameter, f cannot call g unless g is isolated.

If the user declares a function as isolated, then it's an error unless the compiler can verify that it is indeed isolated. Improvements to the compiler will thus cause things that were errors to cease to be errors.

**Comment by rdhananjaya** [comment]
I was under the impression that inferred isolatedness of callee functions is used when analyzing a function that is explicitly marked `isolated`.

Thank you for the clarification.

**Comment by jclark** [comment]
The proposal is explicit that this is not the case:

> if a function is explicitly declared as isolated, then all functions it calls must also be explicitly declared as isolated

**Comment by jclark** [comment]
@MaryamZi When you implement this, can you please have a look whether it will cause problems in the current code base to require closures specifying default values to be isolated?

**Comment by jclark** [comment]
Need to think about how isolated works for arrow functions, since there is no syntax for explicitly declaring them as isolated.

**Comment by jclark** [comment]
I think we also need [isolated objects](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/isolated/isolated.md#isolated-objects) for the reasons explained in #[574](https://github.com/ballerina-platform/ballerina-spec/issues/574#issuecomment-663971916).

**Comment by MaryamZi** [comment]
> @MaryamZi When you implement this, can you please have a look whether it will cause problems in the current code base to require closures specifying default values to be isolated?

Ack, will do.

**Comment by sameerajayasoma** [comment]
The function `foo` in the following snippet is not an isolated function IMO. In general, the compiler has no way of knowing the internals of the record type `Person`.  Should we think of a way to mark the record isolated? This is another complexity that we get with default values in records/objects. 

```
// module abc
int value = 10;
function getA() returns int {
    value += 1;
    return value;
}

type Person record {
    int a = getA();
};

// module xyz
function foo() {
    abc:Person p = {};
}
```

**Comment by jclark** [comment]
@sameerajayasoma That was the first point of @rdhananjaya in https://github.com/ballerina-platform/ballerina-spec/issues/145#issuecomment-663459919. One solution is to require defaults to be isolated.

**Comment by jclark** [comment]
There’s a problem with functions like `array:map`, in that, according to the proposed definition, they are isolated only if their functional argument is isolated, but there’s no way to express that. I suspect we should probably extend `@typeParam` to express this.

There is another complication with closures. Consider this:

```
isolated function arrayInc(int[] v, int k) returns int[] {
  return v.map(n => n + k);
}
```

This ought to work, but the closure passed to map is not isolated, because it accesses state outside its (the closure’s) parameters, namely k. From a type-checking point of the concept needs to be isolated wrt a specific stack frame. Declaring a function isolated means that is isolated wrt its own stack frame. The closure passed to map is isolated with respect to arrayInc’s stack frame. So the call to map is isolated with respect to arrayInc’s stack frame, so it’s OK for arrayInc to call it.

This means we ought to infer the isolatedness of anoymous functions values within a function.

**Comment by jclark** [comment]
This rule relating to `lock` doesn't work:

> a module-level variable can be read or written, provided that all uses of that module-level variable are within a lock statement

The problem is that the variable may refer to a mutable value that has a reference to it from elsewhere. So requiring the use of the module-level variable to be within a lock statement isn't sufficient.

A related point is that you can think of a module as being an object, with the module-level functions being methods. So ideally the rules on isolated objects ought to be applicable (with minimal modification) to modules also.

**Comment by jclark** [comment]
I did a new revision of the [proposal](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/isolated/isolated.md):

- added isolated objects
- revised approach to module-level state that repairs holes in previous approach

I haven't yet incorporated:
- handling of record default values
- inferring the function invocation with respect to which anonymous functions are isolated
- dealing with langlib functional method

@MaryamZi Please review.

**Comment by sameerajayasoma** [comment]
I raised this concern previously as well. With this proposal, we can mark the following method `increment` as an `isolated` method. 

The proposal says:

> A caller of an isolated function can ensure that a call is concurrency-safe by ensuring that it is safe to access the parameters for the duration of the call. 

But the calls to the following method is not concurrency-safe. 

```
class Foo {
  int count = 0;

  isolated function increment(int amount) {
    self.count += amount;
  }
}
```

**Comment by jclark** [comment]
The proposal also says:

> In a method call, self is treated as a parameter

This isn't safe unless the caller ensures that it is safe to access the self parameter for the duration of the call.

This is the problem that [isolated objects](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/isolated/isolated.md#isolated-objects) are designed to deal with:

```
isolated class Foo {
  private int count = 0;

  isolated function increment(int amount) {
    lock {
      self.count += amount;
    }
  }
}
```

**Comment by sameerajayasoma** [comment]
So the bottom line is that the caller of an isolated function should be the sole owner of values passed to the function as parameters.

**Comment by jclark** [comment]
Yes, with some provisos

- if caller is not using multiple threads itself, it doesn't have to worry about this
- it only needs ownership for the duration of the call
- it doesn't need ownership of read-only values
- it doesn't need ownership of isolated objects

**Comment by MaryamZi** [comment]
Few questions;

1. Is `isolated`-ness a part of an object's type? If it is, since an object without fields is considered to be inherently isolated, will all objects no longer belong to `object {}`? 

2. Can `isolated` be used in any order with other class type qualifiers or function/method qualifiers?

3. The proposal says "function call expression that calls an isolated function is unique if the expressions for all its arguments are unique.". I guess this also means a function call can be unique only if the function is an `isolated` function and all the arguments passed are unique?

**Comment by sameerajayasoma** [comment]
IMO, calls to non-isolated functions, can be unique: consider a call to a function with type `function (int, int) returns int`. The arguments are always unique and the return value is always unique.

**Comment by jclark** [comment]
To answer @MaryamZi’s questions:

1. isolated-ness is part of the shape of an object (like the read-only bit).`isolated object {}` is a subtype of `object {}`, so all objects still belong to `object {}`.

2. class-type-quals remains unordered

3. A call to a function whose return type is a subtype of readonly is also obviously unique (this covers @sameerajayasoma‘s example). I cannot think of any other cases where the compiler can tell from the types that that the result is unique.

**Comment by sameerajayasoma** [comment]
Can we consider an expression whose static type is a subtype of `isolated object{} | isolated function ...` is unique? 

If that is the case, a call to a function of type `function () returns isolated object{}` is unique?

**Comment by jclark** [comment]
The proposal handles that case by saying that an field whose type is an isolated object is not restricted to be initialized by a unique expression.

Another approach is to come up with a term that means isolated object or readonly or mutable+unique. It’s too much of a stretch, I think, to use _unique_ for this; it’s already a stretch to include read-only in unique. I couldn’t think of a good word for this yet.

**Comment by sameerajayasoma** [comment]
A follow-up question related to my previous comment: https://github.com/ballerina-platform/ballerina-spec/issues/145#issuecomment-664721250

Here `Person` is a record type. My point is that the compiler has no way of verifying that function `foo` is an `isolated` one. The `Person` record may have a non-isolated closure that specifies a default value. 

```
isolated function foo() {
  abc:Person p = {}
}
```

**Comment by jclark** [comment]
Is there a problem with the solution I already proposed to that: https://github.com/ballerina-platform/ballerina-spec/issues/145#issuecomment-663466512 https://github.com/ballerina-platform/ballerina-spec/issues/145#issuecomment-664723050 ?

**Comment by sameerajayasoma** [comment]
Oh. I think I've missed the point where you've suggested to mandate all such record closures to be isolated. My apologies. I guess we should do the same for object field defaults as well.

**Comment by MaryamZi** [comment]
Thank you, @jclark, @sameerajayasoma. 

> To answer @MaryamZi’s questions:
> 
> 1. isolated-ness is part of the shape of an object (like the read-only bit).`isolated object {}` is a subtype of `object {}`, so all objects still belong to `object {}`.

Since the proposal says "An object without fields or an object all of whose fields are readonly is inherently isolated.", I assumed `object {}` meant `isolated object {}`, which would then disallow considering a non-isolated object as a subtype of `object {}`? I see the same issue even if we consider an object with no fields to be subtype of `isolated object {}`.

> 2. class-type-quals remains unordered

Ack. I assume this is the case for functions too. (Related to https://github.com/ballerina-platform/ballerina-spec/issues/584)

> 3. A call to a function whose return type is a subtype of readonly is also obviously unique (this covers @sameerajayasoma‘s example). I cannot think of any other cases where the compiler can tell from the types that that the result is unique.

Yes, was thinking of uniqueness independent of being read-only. This is clear.

**Comment by jclark** [comment]
We need to keep clear about whether we are talking about types or values.  An object constructor expression `object { }` will create an object value with a shape that is isolated. This does not imply that an object _type descriptor_ `object {}` is equivalent to `isolated object {}`: an object value belongs to the latter type only if its shape is isolated.

**Comment by MaryamZi** [comment]
> We need to keep clear about whether we are talking about types or values. An object constructor expression `object { }` will create an object value with a shape that is isolated. This does not imply that an object _type descriptor_ `object {}` is equivalent to `isolated object {}`: an object value belongs to the latter type only if its shape is isolated.

Got it, thank you.

**Comment by MaryamZi** [comment]
Follow up question related to inferring isolated-ness.

Taking functions as an example, the proposal says

> When compiling a module, the compiler can infer that some or all of the functions in the module are isolated even though they were not explicitly declared as such, if the functions would meet the requirements for isolated if they had all been declared as such. 

Does this mean a developer would be able to use a function that is not explicitly marked as `isolated` in a context where an isolated function is expected (if the compiler infers it to be an `isolated` function)? Or is this inferring just to inform the developer that they can mark the particular function as `isolated`?

```ballerina
function access(int[] x) {
    int i = x[0];
}

isolated function (int[]) func = access; // is this valid?
```

Since the proposal requires

> Furthermore, if a function is explicitly declared as isolated, then all functions it calls must also be explicitly declared as isolated.

should this also be disallowed unless `access` is explicitly marked as `isolated`?

**Comment by jclark** [comment]
The main point of being able to infer isolated is so that services written by the user can be inferred to be isolated, without the user having to even be aware the isolated feature; a Listener can then safely dispatch incoming requests concurrently to an isolated service method of an isolated object.

But we shouldn't extend the inference feature beyond what is necessary. I don't think your example should be allowed: in general, the program should be comply with the rules on isolated, without any inference being done.

An exception to this is arrow functions, where there is no syntax to explicitly declare the function as isolated. So I think we need to allow this:

```
type F isolated function (int) returns int;
F f = x => x + 1;
```

**Comment by MaryamZi** [comment]
> The main point of being able to infer isolated is so that services written by the user can be inferred to be isolated, without the user having to even be aware the isolated feature; a Listener can then safely dispatch incoming requests concurrently to an isolated service method of an isolated object.
>
> But we shouldn't extend the inference feature beyond what is necessary. I don't think your example should be allowed: in general, the program should be comply with the rules on isolated, without any inference being done.
> 

Yes, agreed.

> An exception to this is arrow functions, where there is no syntax to explicitly declare the function as isolated. So I think we need to allow this:
> 
> ```
> type F isolated function (int) returns int;
> F f = x => x + 1;
> ```

Ack, thank you.

**Comment by jclark** [comment]
@MaryamZi Isolated objects will be affected a bit by #580.

**Comment by MaryamZi** [comment]
> @MaryamZi Isolated objects will be affected a bit by #580.

Noted, thank you.

**Comment by MaryamZi** [comment]
For objects, in addition to `module-class-defn`s, will the `isolated` qualifier also be allowed with `object-constructor-expr` and `object-type-descriptor`?

**Comment by jclark** [comment]
@MaryamZi We definitely need it on the `object-type-descriptor`, since isolated is part of the type. For `object-constructor-expr`, I think it's probably better if the isolatedness of the constructed object comes from the contextually expected type or explicitly referenced type (like distinct and readonly), so that it works when a service declaration is desugared into an object-constructor-expr.

**Comment by MaryamZi** [comment]
> @MaryamZi We definitely need it on the `object-type-descriptor`, since isolated is part of the type. For `object-constructor-expr`, I think it's probably better if the isolatedness of the constructed object comes from the contextually expected type or explicitly referenced type (like distinct and readonly), so that it works when a service declaration is desugared into an object-constructor-expr.

Ack, we'll allow it with `object-type-descriptor` too. Thank you.

**Comment by jclark** [comment]
We will need to say something about defaults for function arguments.

**Comment by jclark** [comment]
@MaryamZi  I did an updated proposal

* I moved the isolated module level variables section from Future Work into the body of the doc, since we clearly need it. Did you implement this?
* I added a [section on strand creation](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/isolated/isolated.md#strand-creation). Please review.

**Comment by MaryamZi** [comment]
> @MaryamZi I did an updated proposal
> 
> * I moved the isolated module level variables section from Future Work into the body of the doc, since we clearly need it. Did you implement this?

Noted, we've not implemented this yet.

> * I added a [section on strand creation](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/isolated/isolated.md#strand-creation). Please review.

Ack.

**Comment by MaryamZi** [comment]
Shouldn't object defaults also have restrictions similar to record defaults (the field initializer should also meet the requirements for `isolated`)?

e.g.,
```ballerina
int x = 1;

class Foo {
    int i = x; // not isolated
}

isolated function bar() {
    Foo f = new;
}
```

**Comment by jclark** [comment]
If the object defines an init method and the init method isn't declared as isolated, then there's no need to require the object initializers to meet the requirements for isolated. Otherwise (no init method, or init method declared as isolated) I agree that the initializers should be required to be isolated.

**Comment by jclark** [comment]
@MaryamZi Have you done isolated objects or just isolated functions? I might split this issue up.

**Comment by MaryamZi** [comment]
> If the object defines an init method and the init method isn't declared as isolated, then there's no need to require the object initializers to meet the requirements for isolated. Otherwise (no init method, or init method declared as isolated) I agree that the initializers should be required to be isolated.

Noted.

So basically if there is an `init` function and it is not marked as `isolated` you cannot create the object within an `isolated` function. But if there is an `isolated` `init` function or if there is no `init` function (where we require the initializers to be `isolated`) it will be allowed?  


> @MaryamZi Have you implemented isolated objects or just isolated functions? I might split this issue up.

We've completed isolated functions only.

**Comment by jclark** [comment]
Right, `new C` is implicitly calling C's init function. If there isn't an explicit init function defined, then the compiler synthesizes one that's isolated, has no arguments and returns ().

**Comment by MaryamZi** [comment]
> @MaryamZi When you implement this, can you please have a look whether it will cause problems in the current code base to require closures specifying default values to be isolated?

When mandating default value closures to be `isolated` we came across an issue in the standard library, where configuration values read via functions from the `ballerina/config` module are used as default values for certain fields. These functions are not `isolated`, and thus with the new restriction they cannot be used as default values, and will require some changes to maintain the same behaviour.

```ballerina
public type ConnectionPool record {|
    // `15` is the default if not specified as a config
    int maxOpenConnections = config:getAsInt("b7a.sql.pool.maxOpenConnections", 15);
    int minIdleConnections = config:getAsInt("b7a.sql.pool.minIdleConnections", 15);
|};
```

Instead of requiring record default value closures to be isolated, can we disallow in an `isolated` function the construction of values which call non-isolated closures in the process?

For example, where `foo` is not isolated

```ballerina
type Bar record {
   int i = foo();
};

function foo() returns int {}
```

can we allow the above definition and make it an error

1. if a `Bar` value is constructed in an `isolated` function

```ballerina
isolated function baz() {
   Bar b1 = {}; // error, since a non-isolated closure will be called

   Bar b2 = {i: 1}; // error, since a default value closure is non-isolated 
}
```

or

2. if a `Bar` value is constructed in an `isolated` function resulting in the non-isolated closure being called

```ballerina
isolated function baz() {
   Bar b1 = {}; // error, since a non-isolated closure will be called

   Bar b2 = {i: 1}; // OK, since the non-isolated closure will not be called
}
```

I guess we will have similar concerns with objects too.

**Comment by jclark** [comment]
The config:getXyz functions definitely have to be isolated. I don't know what the implementation looks like, but it might need the ability for isolated functions to access isolated module level variables within a lock. A simple isolated implementation would be for the start-up code to load the config into a readonly final variable, then the config:getXyz function would just access this. So conceptually I see no need for them not to be isolated.

I don't think your suggestion isn't a good approach, because modules need to have an explicit interface, and there's no way for records to declare which fields defaults have an isolated closure.

The specific case of config would also be dealt with by #41.

**Comment by MaryamZi** [comment]
> The config:getXyz functions definitely have to be isolated. I don't know what the implementation looks like, but it might need the ability for isolated functions to access [isolated module level variables](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/isolated/isolated.md#isolated-module-level-variables) within a lock. A simple isolated implementation would be for the start-up code to load the config into a readonly final variable, then the config:getXyz function would just access this. So conceptually I see no need for them not to be isolated.
> 
Yes, we had a discussion regarding this and decided that the config functions can be marked as `isolated`, where the config registry can be considered as an `isolated` module level variable.  

> I don't think your suggestion is a good approach, because modules need to have an explicit interface, and there's no way for records to declare which fields' defaults have an isolated closure.
> 
Yeah, agreed.

> The specific case of config would also be dealt with by #41.

**Comment by jclark** [comment]
I have moved isolated module-level variables and objects to a separate issue, so we can keep this just for the basic isolated functions concept, which has been implemented already.

**Comment by jclark** [comment]
Spec changes needed:

* [ ] Fix grammar to allow isolated
* [ ] Explain what isolated means for a function type (in Types section along with readonly)
* [ ] Explain requirements for function bodies when type is isolated (probably in Function Definition section)
* [ ] Explain requirements for external functions
* [ ] Restriction on records default closures to be isolated
* [ ] How new, init and object initialization work with isolated
* [ ] How isolated is inferred within a module
* [x] Declare langlib functions as isolated (issue #596)

**Comment by jclark** [comment]
We can deal with function argument defaults straightforwardly: when a function is declared as isolated, the requirements for the function body apply also to the expressions for the defaults.

**Comment by jclark** [comment]
I pushed the isolatedness wrt a stack frame problem (mentioned in https://github.com/ballerina-platform/ballerina-spec/issues/145#issuecomment-668404584) to #602.
