### ISSUE TITLE
Future panic scenario in an Alternate wait action is not clear

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-spec#147]
**Description:**
In the spec v2019R1, when one of the futures in an `alternate-wait-action` panics, the result of the wait action is not mentioned.
Is it the same as error returns?

Panic related scenarios in `multiple-wait-action` and `single-wait-action` also not specified. But it is obvious that we have to propagate the panic in those two scenarios.

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
This is supposed to be covered by the following passage in "Statement execution":

> Except where explicitly stated to the contrary, statements handle abrupt completion of the evaluation of expressions and actions as follows. If in the course of executing a statement, the evaluation of some expression or action completes abruptly with associated value e, then the current worker is terminated with termination value e; if the abrupt termination is a check-fail, then the termination is normal, otherwise the termination is abnormal. If the execution of a substatement causes termination of the current worker, then the execution of the statement terminates at that point.

A panic indicates a bug in the program, and so in my view it is better by default to fail fast with a panic. It can be trapped explicitly if necessary.

Please let me know if this addresses your question.

**Comment by vinok88** [comment]
Thank you James. That answers my question.

**Comment by jclark** [comment]
I think the spec could be improved here.
