### ISSUE TITLE
Should parameter names be optional in function type declaration?

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#148]
@jclark According to current spec grammar, the following syntax is not allowed. 

```ballerina
function test() {
  (function (string,int) returns boolean) foo= somefunction;
}
```

Instead, it supports,

```ballerina
function test() {
  (function (string name, int age) returns boolean)  foo= somefunction;
}
```

1) Option 1 seems more convenient to use.
2) However if we support both, we can allow named argument in function pointer call `foo(name = "aaa", age = 10);`

_Originally posted by @hasithaa in https://github.com/ballerina-platform/ballerina-spec/issues/125#issuecomment-495595610_

**Comment by jclark** [comment]
We have to at least allow named parameters, both for documentation purposes and for named arguments. I am OK with making them optional. @sanjiva What do you think?

**Comment by sanjiva** [comment]
+1.
