### ISSUE TITLE
Spec is not clear how the lhs of a compound assignment statement is evaluated

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#149]
The expression `f(i)` will be evaluated twice in the following assignment statement.
```ballerina
a[f(i)] = a[f(i)] * 10;
```

But `f(i)` will be evaluated once in the following compound assignment statement.
```
a[f(i)] *= 100;
```

Spec is not clear. The current implementation evaluates `f(i)` twice in the latter case. I will create a separate issue against the implementation.

**Comment by jclark** [comment]
In

```
a[f(i)] *= 100;
```

`f(i)` should only be evaluated once.

**Comment by sameerajayasoma** [comment]
That is correct. Spec doesn't say that clearly. Created this issue to track it.
