### ISSUE TITLE
Should match patterns cause type narrowing?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#152]
Consider

```
function jsonIt(json|error myJson) returns json{
    match myJson {
        error() => return {};            
        var x => return x;
    }
}
```

Should the type of x be json? If I wrote

```
function jsonIt(json|error myJson) returns json{
    match myJson {
        var e if e is error => return {};            
        var x => return x;
    }
}
```

then the type would be narrowed.

See
https://stackoverflow.com/questions/56348280/how-to-de-structure-match-json-type-in-ballerina/56351472

**Comment by jclark** [comment]
Particularly for error constructors referring to a named error type, it seems weird not to narrow.

**Comment by jclark** [comment]
We can also leverage readonly here.

**Comment by jclark** [comment]
This is also affected by read-only types. If a value is read-only and it matches something, then we can say something about its type.

**Comment by jclark** [comment]
A key principle of the match-statement is this: whether a value matches a pattern is determined by the values's shape rather than the value's inherent type. This makes a difference for mutable values whether mutation changes the shape but not the inherent type. It is thus complementary to conditional statements and `is`, which looks at the inherent type of a mutable value rather than its current shape.

This affects type narrowing. For any match-pattern there is a set of shapes that will match the pattern. In other words, every match-pattern corresponds to a type. But if a match-statement is used with a variable and a match of the value of the variable against a match pattern succeeds, we cannot in general narrow the type of the variable to the type corresponding to the match pattern, because a successful match does not imply that the variable *belongs to* the type only that it currently *looks like* the type. This is different from conditional statements and `is`, where we know the variable belongs to a type, and so can narrow the type of the variable.

But there are cases where a successful match does imply that the variable belongs to a type. This is particularly the case for error. For example, this does not compile currently, although we can safely narrow the type of err to MyError:

```
function foo(error err) returns MyErrror?
{
   match err {
      MyError() => { return err; }
   }
}
```

The key thing that makes it possible to narrow is immutability.  For an immutable value, _looking like_ a type and _belonging to_ a type are the same thing.

I therefore suggest the following rule for match-statements. In statement `match v` where v is a variable with static type T, a match-pattern corresponding to type P should narrow v to type `T & P` if  `T & P` is a subtype of readonly. This would imply narrowing for subsequent match clauses also.

We could also allow a type name instead of `var` when the type name refers to a readonly type. (For a non-readonly type allowing this would be unclear: does it mean "looks like" or does it mean "belongs to"? It should mean "looks like" for consistency, but then we cannot narrow to the type.)

**Comment by sameerajayasoma** [comment]
Based on the above description, the following should work.
```
type Person record {string name; ...};

function foo(Person|error v) returns string {
    match v {
        error e => { return e.message(); }
        _ => { return v.name;}
    }
}
```

**Comment by jclark** [comment]
@sameerajayasoma That isn't actually covered by the rule I gave, but it would be nice to make that work too.

**Comment by ecoupal** [comment]
This is not working for me, I get invalid operation: type XXX does not support field access.

Ballerina Swan Lake Beta 3
Language specification 2021R1
Update Tool 1.3.5

```
import ballerina/sql;

type Person record {string name; };

function foo(Person|error v) returns string {
    match v {
        error sql:NoRowsError() => { return "OK"; }
        _ => { return v.name;}
    }
}
```

The narrow doesn't seems to work, am I missing something ?

**Comment by jclark** [comment]
@ecoupal `v.name` should work, but you should get an error for not returning a string at the end of the function, because a `_` pattern does not match errors, and v allows arbitrary errors, but the error match pattern only matches a specific type of error. Looks like a bug in jBallerina to me.
