### ISSUE TITLE
Add back table<R>

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#153]
Table is supposed to be iterable in its rows. This means the lang.table module needs an iterator function. 

We previously allowed `table<R>` as a shorthand. With this we can write iterator like this:

```
@typeParam
private type Type = anydata|error;

public function iterator(table<Type> tbl) returns abstract object {
    public next() returns record {|
        Type value;
    |}?;
} = external;
```
Without this we would need to invent something else.

I am 90% sure we will want this anyway and it is still in the implementation. We can leave the semantics a bit vague until we fix issue #47.

**Comment by sanjiva** [comment]
So `table<R>` == `table { *R; }` right? So its a lightweight table without keys.

+1 for this.

**Comment by jclark** [comment]
Right, at least when R is closed.

**Comment by jclark** [comment]
We previous removed this for two reasons:

> - mutation: mutating the values you get from an iterator does not affect the table, as it would do for map<T> and T[]
> - the record type has to be sealed, but it would be annoying to always require users to write the !...
> 

But both of these can be dealt with:

- I believe tables should contain only frozen values, which means the record returned from an iterator can also be frozen
- open table types actually make sense and are useful, provided they are not used as inherent type
