### ISSUE TITLE
A lang.* module to keep Listener built-in abstract object. 

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#154]
**Description:**
In the current implementation, we define Listener abstract object in the builtin module and Developers who write server connectors can refer to this abstract object. This is purely for developer convenient.  

With current lang.* module approach, I can think followings.
1. We can put this to `lang.value` module. So they refer it using `value:AbstractListener*`.  Which gives a similar developer experinace.
1. Instead of adding this to `lang.value` we can bring a new module to deal with services, endpoints, and listeners.
1. Do not define an `AbstractListener`. 

Another advantage of having AbstractListener is, we can make the compiler aware of these objects (like other lang.* functions) and use those to do the semantic analysis. And it simplifies compiler logic significantly.  (It is a matter of checking `X is value:AbstractListener`  )
Right now knowledge about the Listener shape is hardcoded into the compiler.

**Comment by jclark** [comment]
The value module is supposed to be for functions that are not specific to any basic type.

This is specific to to the basic type object. AbstractListener is a bit Java-ish; the spec calls it Listener, so we should be consistent with that.

So I would propose adding

```
public type Listener abstract object {
   function __attach (service s, string? name = ()) returns error?;
   function __start () returns error?;
   function __stop () returns error?;
};
```

to a new lang.object module.

**Comment by hasithaa** [comment]
lang.object module looks best fit for me.
