### ISSUE TITLE
Do annotation declarations require a semicolon?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#156]
**Description:**
The [current grammar](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/spec.html#L5019) for `annotation-decl` doesn't have a semicolon at the end.

```
annotation-decl :=
   metadata
   [public] [const] annotation [type-descriptor] annot-tag 
   [on annot-attach-points]
annot-tag := identifier
```

Is this intended or should there be a semicolon at the end similar to other module-level declarations?

**Comment by jclark** [comment]
It should have a semicolon at the end.
