### ISSUE TITLE
Better name for "lang.value" module

### ISSUE THREAD

**Issue by sanjiva** [ballerina-platform/ballerina-spec#158]
The name `value` does not seem self evident to users. I don't have a better suggestion yet .. recording issue for now.

**Comment by jclark** [comment]
I am certainly not in love with the `value` name, but I don't think it is bad.

The `value` name only gets exposed to users for functions that are not being called by the method call syntax. Almost all the functions in lang.value work well as method calls. The one exception is conversion from some generic string format e.g. JSON now and BVN (#159) latter to a Ballerina value: for this I think `value` works quite well as a module name, i.e. `value:fromJsonString`. This is reminiscent of the Java pattern of having static methods like `java.lang.Integer.valueOf`.

Other choices considered and rejected include:

- any
- anydata
- universal
- generic

**Comment by sanjiva** [comment]
Yeah I can't think of a better alternative than everything we've already rejected. So lets keep it.
