### ISSUE TITLE
2019R2 tracking

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#162]
This issue is to keep track of discussions related to 2019R2 milestone.

**Comment by jclark** [comment]
This is the list of issues that I have tagged as needing discussion:

https://github.com/ballerina-platform/ballerina-spec/issues?q=is%3Aopen+is%3Aissue+milestone%3A2019R2+label%3Astatus%2Fdiscuss

**Comment by jclark** [comment]
I suggest we start with a group of issues related to core language semantics:

- #120 named parameters
- #100 object init
- #85 E[E] E.x operators
- #133 nil lifting for methods
- #124 outside method definitions

**Comment by hasithaa** [comment]
Shall we add the following issue as well?
- #17 built-in annotations

**Comment by jclark** [comment]
There's a group of issues related to versioning:

- #17 built-in annotations (#96 also relates to this)
- #160 lang.* preview modules
- #142 lang.* versioning
- #115 standard library versioning
- #18 deprecation design

There's an important related meta-issue here, of where stuff that doesn't belong in the language spec gets written down and who is going to write it.

**Comment by jclark** [comment]
There's a group of issues related to XML:

- #138 lang.xml built-in functions (see my first cut here https://github.com/ballerina-platform/ballerina-spec/blob/master/langlib/xml.bal)
- #176 fixing up the type system as regards XML (which #177 will build on)
- #166 Fleshing out how XML namespace support works
- #161 XML text chunking

There's a meta issue here of how we deal with XML for jBallerina 1.0; in the current spec XML is not preview.

**Comment by jclark** [comment]
There are also a couple of issues related to langlib we could usefully discuss now:

- #136 convertTo/setType
- #141 removeAll/clear

**Comment by jclark** [comment]
I suggest two groups of issue today:

1. Let's deal with #85 and figure out which parts we need to do for R2. At least #201, #196, #202, #203. But also maybe #199, #209, #210.

2. Cloning and freezing. #208, #136, #186.

**Comment by jclark** [comment]
Things to discuss tomorrow:

1. Program startup semantics #44 
2. It's not going to work well for the spec to use the word read-only instead of immutable. Do we still want to stick with ReadOnly as the word we expose to the user?
3. string indexing #209, #211 
4. Which issues from member access to we want to do for R2? Current list is #201, #196, #203, #202, #209, #210, #199, #212
