### ISSUE TITLE
Runtime attached type descriptor for listener annotations

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#163]
**Description:**

The spec says that for annotations with the `listener` attachment point, annotations are attached to the "type of object" at runtime.

Is this different from the static type of the listener?

For example,
```ballerina
@v0
listener http:Listener l1 = new(8080);

@v1
@v2 {
    foo: "bar"
}
listener http:Listener l2 = new(8181);
```

Currently, both `l1` and `l2` are of a single `http:Listener` type and `http:Listener` would have the annotations specified for the `http:Listener` type. Where would the annotations for the listener declarations be added?

**Comment by jclark** [comment]
The annotations in those examples are annotating the variable.

Type annotations would be on the definition of the Listener object type in the http module.

**Comment by MaryamZi** [comment]
> The annotations in those examples are annotating the variable.

Does this mean the attachment point applicable for these examples would be the `var` attachment point?

The syntactic attachment point for the `listener` attachment point is defined as `listener-decl`. Should this be `module-type-defn` where the type is a subtype of the Listener type instead?


| Attachment point name | Syntactic attachment point(s) | Attached to which type descriptor at runtime |
| -- | -- | -- |
| listener | listener-decl | type of object |
| var | module-var-decl, local-var-decl-stmt | none |



If not, not quite sure how annotations with the `listener` attachment point work if the syntactic attachment point is `listener-decl`, but at runtime is available on the object type. 

For example,

```ballerina
type TRUE true;

annotation v0 on object type;
annotation v1 on listener;

// Listener impl.
@v0
public type Listener object {
    ....
}

@v1
listener Listener l = new;

public function main() {
    typedesc t = typeof l; // would return typedesc for `Listener`
    boolean annotated = t.@v0 is TRUE; // `true` since `Listener` is annotated with `v0`
    annotated = t.@v1 is TRUE; // `false` since `Listener` is not annotated with `v1`
}
```
How could one access the annotations with attach point `listener` at runtime (`v1` here)?

**Comment by jclark** [comment]
You are right. There is a confusion in the spec as regards the listener attachment point.

@hasitha What are you using the listener attachment point for?

**Comment by hasithaa** [comment]
Docker and K8S annotations use `listener` attachment point. Those are not runtime annotations. So semantic vise `listener` attachment point is equivalent to `var` attachment point. This is somewhat similar to `function` and `resource function` model.

**Comment by jclark** [comment]
@hasithaa Can we just change `listener` attachment point to be source only then?

**Comment by hasithaa** [comment]
I am +1 for the change.
