### ISSUE TITLE
Annotations on anonymous types

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#165]
**Description:**

Are annotations allowed on anonymous types? 

There could be scenarios such as the following, where whether the annotation is on the type or the var is not clear.

```ballerina
@v0
object {
   string name = "John";

   @v1
   function foo() {
       
   }
} value = new;
```

Is `v0` attached to the anonymous object ("type" attachment point) 
```ballerina
// as if it was defined as follows
@v0
type AnonObj object {
   string name = "John";

   @v1
   function foo() {
       
   }
}

AnonObj value = new;
```

OR to the variable declaration for the variable `value` ("var" attachment point)? 
```ballerina
type AnonObj object {
   string name = "John";

   @v1
   function foo() {
       
   }
}

@v0
AnonObj value = new;
```

Related to https://github.com/ballerina-platform/ballerina-spec/issues/105#issuecomment-491160273

**Comment by jclark** [comment]
The spec grammar does not allow annotations on a type descriptor; only on a type definition. The `type` attachment point is consistent with this.
