### ISSUE TITLE
Describe how XML namespace support works

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#166]
The spec describes the syntax for describing an XML namespace, but we don't completely describe the effect that this is supposed to have. If we have a xmlns decl for a prefix `p` as namespace `uri`, then in certain situations  a qualified identifier `p:ident` is supposed to turn into an expanded name `{uri}ident`.

This is an important point, because it was part of the motivation for using `prefix:name` as the qualified identifier syntax.

Relates to #85.

**Comment by jclark** [comment]
Need to think about where we have imported a module as `foo`, but still want to be able to use `foo` as an XML namespace prefix. A special case of this is `xml` where it is natural to want to import the lang.xml module as `xml` but we also need to use the `xml` as a namespace prefix.

**Comment by jclark** [comment]
Things that need to be said:

- xml import prefix predeclared and overrideable
- xmlns:space etc included in lang.xml
- xmlns namespace prefix predeclared and not overrideable
- which namespace attributes are added by xml``
- namespace attribute handling on serialization
- foo:bar works as string, if foo is a namespace prefix (do we need this if we have `x.foo:bar = "baz"`?)

**Comment by rdhananjaya** [comment]
Could you please elaborate on second point `xmlns:space etc included in lang.xml` a bit.

**Comment by jclark** [comment]
I meant `xml:space`. The idea is that lang.xml does:

```
const space = "{http://www.w3.org/XML/1998/namespace}space";
```

This is so you can say:

```
xml:Element e;
map<string> atts = e.getAttributes();
string? s = atts[xml:space];
```

Thus xml prefix (which is a module prefix) will work like prefixes that are defined as namespace prefixes.

It should also work for `.` and `?.` e.g.
```
xml:Element e;
string? s = e?.xml:space;
```
but the spec doesn't cover this yet.
