### ISSUE TITLE
Mathematically equal decimals should have same shape

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#167]
Two numbers with a different scale e.g. 1.0 and 1.00 are distinct values in the IEEE spec, but they should have the same shape (in Ballerina). This means that `1.0 == 1.00` would be true, but `1.0 === 1.00` would be false.

Need to investigate IEEE 754 and ANSI X3.274 standards.

Relates to #137.

**Comment by jclark** [comment]
This is explicit in section 3.5.1 of IEEE 754-2008:

> Unlike in a binary floating-point format, in a decimal floating-point format a number might have multiple representations. The set of representations a floating-point number maps to is called the floating-point number's cohort; the members of a cohort are distinct representations of the same floating-point number.

**Comment by jclark** [comment]
@hasithaa Note that this means that `==` should use `BigDecimal.compareTo` and `===` should use `BigDecimal.equals`

**Comment by hasithaa** [comment]
@jclark Ack.
