### ISSUE TITLE
Convenient XML navigation

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#169]
The semantics of our xml type was designed to support something similar to the XPath `/` operator.

**Comment by jclark** [comment]
Apparently implementation supports x.e where X is of type xml, equiv to x/e in XML.

**Comment by jclark** [comment]
So E.x concatenation of, for each element item e in E, the children of e that are element items with name x. Question then is what E[x] should do when x is a string.

- E[n] works on self axis
- E[x] works on child axis

Not clear why we have to use "." for this.

**Comment by jclark** [comment]
I want to distinguish navigation, by which I mean access to existing XML structures, from querying, which may involve the construction of new XML structures.

**Comment by jclark** [comment]
Considering:

- parallel between xmlelement and error (explained in #224)
- use of E.x to access error detail record (proposed in #221)
- precise XML typing for elements (as suggested in #177)
- lax/strict typing for XML attribute access (issue #197)
- the use of E.x in JavaScript DOM to access attributes
- removal of E@ syntax for XML attribute map access

I think it is clear to me that E.x on an xmlelement should access the attributes of the element.

**Comment by jclark** [comment]
We then need a syntax to access children. The syntax that springs to mind is:

- `x.<foo>` returns element children of x named foo
- ` x.<foo|bar>` returns element children of x named foo or bar

**Comment by sanjiva** [comment]
And x.<*> for all element children of x I assume?

We only use `<..>` for type parameterization or related things but since this is the natural xml syntax its good. 

What about navigation? Same way then? `x.<foo>.<*>`?

**Comment by jclark** [comment]
`*` would be natural as a wildcard, even though it's slightly different from our use of `*` in a type context to mean inferred. We could also support `ns:*`.
 
I'm not to worried about this overloading `<X>`, since

- there is a strong foundation in XML syntax (as you mention)
- this is in an expression rather than a type descriptor
- it is  `X.<Y>` rather than simply `X<Y>`

The ability to support `|` naturally is a big win.

**Comment by jclark** [comment]
If we use E.x for XML attribute access, need also to think about how to iterate over all attributes and how to remove an attribute.

**Comment by jclark** [comment]
See [Improved navigation](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md#improved-navigation) section  of XML proposal
