### ISSUE TITLE
Built-in annotations

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#17]
Current implementation has a concept of built-in annotations, which can be used without a module qualifier and without importing a module.

The spec currently requires that an annotation tag must reference an annotation.

**Comment by sanjiva** [comment]
One approach to address this is to make it illegal to use annotations in the same module they're declared in.

Declaring annotations are not an everyday thing. The odds of someone defining an annotation only to be used within their module is like zero. That means we need to make annotations public always (right now we do allow module visible annotations).

A next step could be to say annotations must always be in their own module but IMO that's not needed (even though that's what is likely to be the case!).

With this approach we can consider any unqualified annotation application to be a built-in annotation.

Where do we define the built-in annotations? Currently we use the special module `builtins` to define all built-in methods and methods.

**Comment by jclark** [comment]
I think it's good to say that unqualified annotation names refer to annotations that are built-in rather than annotations in the same module.

The bigger question to me is what specifies the semantics of these built-in annotations. How do programs indicate what semantics they intend these built-in annotations to have? How can we allow the annotations to evolve? How can source code be portable to another implementation that perhaps provides different annotations?

**Comment by jclark** [comment]
See also #96.

**Comment by sanjiva** [comment]
I don't understand this part of your comment James: "How do programs indicate what semantics they intend these built-in annotations to have?".

Semantics of an annotation are defined by the person defining the annotation. I'm sure I'm not getting what you were trying to state.

On evolution - since annotations are Ballerina symbols like any other kind, they can be versioned.

On portability - I think the question is what is the compiler supposed to do with annotations it doesn't understand. Should it error or ignore? If its ignore then one can apply impl specific annotations and have things work.

**Comment by jclark** [comment]
Let me try to explain my conceptual model of this.

Annotations can change the semantics of a module, i.e. what happens when the module is compiled and run. Thus the semantics of the module come from both the language specification and the annotations used. In both these cases, I see three questions

1. What is the context-independent identifier for the semantics?
2. Where does the human readable description of that semantics live?
3. How does source code specify the semantics that it expects?

For language-defined semantics, I would say the answers to these questions are:

1. The language version e.g. 2019R1 (nobody else gets to define their own alternative version of the language)
2. In the language spec on ballerina.io
3. By using a TOML file to specify the version (probably only if the compiler's default version isn't right) 

For normal annotations that are imported from a module, I would say the answers are:

1. The organization/module name/version triple (there's a subtlety here, in that this triple is identifying not just the language-defined effect of the declarations, but the intended semantics of the annotation also)
2. In the documentation string of the module source.
3. By using an import statement with a version clause (as with libraries, I think there is work to be done here to ensure that its convenient for the source code to say what versions it is expecting)

It is not obvious to me what the right answers are for built-in annotations. I can think of several ways to do it.  I don't think it will be sufficient to say that all built-in annotations share the same version number: that will work OK when there's a single implementation, but will cause problems when there are multiple implementations.

One approach might be for Ballerina Central to provide metadata about each version of each distribution of Ballerina. So, for jBallerina 1.0 distribution there would be a URL that has something in TOML/XML/JSON giving the versions of various things implemented in that distro:

- language version
- version of each library module
- version (and other identifier?) of each built-in annotation

When compiling a module, you could then tell the compiler (e.g via TOML) that the module was written expecting a particular version of a particular distro, and this would enable the compiler to compile it with the expected semantics or report that it was unable to do so.

**Comment by jclark** [comment]
The solution to this needs to fit with the overall version management approach described in #115.

**Comment by jclark** [comment]
We have a direction built we need to sort out the details/

**Comment by jclark** [comment]
The lang spec needs to say that the compilation environment maps some annotation tags onto a versioned module; these tags are what is referenced by an unqualified annotation tag rather than tags in the same module.

**Comment by hasithaa** [comment]
Since this is like a normal module, someone can import this module explicitly. will imported annotations affect the compilation process? For example, will Type1 is a param type?

ballerina```
import ballerina/xxx.annotation as a;

@a:typeParam
private type Type1 anydata;  

@typeParam
private type Type2 anydata;
```

I guess it is safe to say No and they will be treated as just annotation attachment. Thoughts?

**Comment by jclark** [comment]
@hasithaa I would say "yes". Conceptually, the compilation environment determines a module identifier (org/module/version) for each unprefixed annotation tag; the compiler should associate the semantics with the module identifier + annotation tag.
