### ISSUE TITLE
Add lang.stream module

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#170]
Implementation version is here:

https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/builtin/src/main/ballerina/builtin/streamlib.bal

I don't think the `startForever` belongs there.

**Comment by jclark** [comment]
@hasithaa Please see if this is enough. Do we need to support unsubscribing?

**Comment by jclark** [comment]
We need to support error as an argument to support the stderr stream concept.

**Comment by hasithaa** [comment]
@jclark For completeness having `unsubscribe` is good. But we can live with `publish` and `subscribe` for now.

`startForever` is something related to siddhi ballerina implementation, which is going to be removed with JB 1.0.
