### ISSUE TITLE
XML item types should be proper types

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#176]
At the moment, XML item types are not types at the Ballerina level, but the functions that make sense depend on the item type. For example, setChildren only makes sense if the xml sequence consists of a single element. Currently people have to say something similar to:

```
if xml.getItemType() ==  "element" {
  xml.setChildren(children);
}
```

which prevents proper type-checking.  It would be much better to say:

```
if xml is xmlelement {
  xml.setChildren(children);
}
```
where `lang.xml` has

```
public function setChildren(xmlelement elem, xml children) = extern;
```

To make this work:

- xml continues to be a basic type
- xmlelement is a subtype of xml; an xml sequence belongs to xmlelement if it is a singleton consisting of an element item
- xmlpi, xmlcomment are also subtypes for singleton processing-instruction, comment items
- xml<T> is a subtype of xml that will be iterable as a sequence of values of type T
- xml is equivalent to `xml<xmlelement|xmlpi|xmlcomment|string>`
- xmltext is equivalent to `xml<string>`

This allows us to type the xml.lang functions properly:

```
public function iterator(xml<ContentType> x) returns abstract object {
    public next() returns record {| ContentType value; |}?;
} = external;
public function elements(xml x) returns xml<xmlelement> = external;
public function getElementName(xmlelement x) returns string = external;
public function getAttributes(xmlelement x) returns map<string> = external;
public function slice(xml<ContentType> x, int startIndex, int endIndex = x.length())
  returns xml<ContentType> = external;
// strip comments, PIs and whitespace only text nodes
public function strip(xml x) returns xml<xmlelement|string> = external;
```

Then our XML processing becomes quite smooth (significantly better than any other programming language!)
```
foreach x in xml.strip() {
  if x is xmlelement {
     
  }
  else {
    // x is string here
  }
}
```

**Comment by sanjiva** [comment]
It would be useful to have an xmldocument subtype as well as we currently don't have a clean way to represent document level info.

**Comment by jclark** [comment]
Think about how typeof works.

Also think about mutation and identity. Only xml elements are mutable and need identity.

**Comment by jclark** [comment]
@sanjiva I made the point about XML document into a separate issue #226.

**Comment by jclark** [comment]
Should an xml sequence that consists of only character items belong to type string? It is a fundamental question and the right answer is not obvious to me.

**Comment by sanjiva** [comment]
Very fundamental .. effectively you're wondering whether xml should become a union type. 

We could take it further .. we could treat the xml type as fully type aware and even consider 1234 as an int and not a sequence of character items, except if someone asks for the character item of the information set as XML. Attributes are already a map (with special handling of namespace declarations), an element could be a record with a qualified name and its children become a list of a subset of anydata.

If we do it that way we'd open up the possibility to use a subset of the Ballerina type system as a schema language for XML as well, like we have for JSON.

**Comment by jclark** [comment]
At this stage, my question is just about our universe of values. Should we consider e.g. `"abc"` and ``xml`abc` `` to be the same value, given that they both represent a sequence of 3 characters? If so, then we would need to look at how we could adjust our type system to accommodate this.

After thinking about it some more, I believe the answer is no. Consider `"<"` and ``xml`&lt;` ``. These both are sequences consisting of the single character `<`, but `value:toString` needs to treat them differently, returning `"<"` for the former and `"&lt;"` for the latter.

I made a separate issue #249 for your second paragraph.

**Comment by sanjiva** [comment]
+1 on not considering "s" and xml`s` as the same.

**Comment by jclark** [comment]
This is covered by [XML proposal](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md). This consists off

- add built-in subtypes:
    - xml:Element
    - xml:ProcessingInstruction
    - xml:Comment
    - xml:Text
- allow xml type to have allowed subtypes as optional parameter
- change langlib to use these
