### ISSUE TITLE
Deprecation design

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#18]
Design how deprecation should work.

We want to be able to smoothly introduce new library modules.

This might use an annotation, and so maybe affected by issue #17

**Comment by jclark** [comment]
Compare with Java deprecation

https://docs.oracle.com/en/java/javase/11/core/enhanced-deprecation1.html

**Comment by jclark** [comment]
In addition to the annotation, there is probably a documentation part to this, which could explain, for example, how to replace the use of the deprecated construct.

**Comment by jclark** [comment]
From a spec perspective this is solved modulo built-in annotations #17.

**Comment by jclark** [comment]
Do we need a Markdown convention for providing human-readable information about the deprecation?

**Comment by jclark** [comment]
BFM in the spec needs to mention convention about section whose title is `Deprecated`.

**Comment by sameerajayasoma** [comment]
The deprecation design spec is now available in the following location.
https://github.com/ballerina-platform/ballerina-spec/tree/master/langext/deprecation
