### ISSUE TITLE
Variable scoping rules for anonymous functions

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-spec#190]
Consider the following example:
```ballerina
function testScoping() returns string {
    int x = 0;

    var fn = function () returns int {
        int x = 10;
        return x;
    };

    return fn.call();
}
```
Should the above case be allowed? Or is this considered as the scope of x inside the anonymous function overlapping with the scope of x in `testScoping()` (and thus, considered a compile error)?

**Comment by pubudu91** [comment]
Also, wouldn't it be better if a section on scoping is included? Currently there's a section on variable scoping. But the details talked about in #97 are spread across the spec and aren't defined anywhere like in https://github.com/ballerina-platform/ballerina-spec/issues/97#issuecomment-490697084 (e.g., XML namespaces section talks about the symbol space of XML namespaces, annotation section talks about the symbol space for annotation tags). Shouldn't the main symbol space also be defined somewhere in the spec (i.e., which categories of symbols belong in the main symbol space)?

**Comment by jclark** [comment]
No, we don't want to allow that. There is a section called "Variable scoping" which says:

> A variable with block scope can have the same name as a variable with module
> scope; the former variable will hide the latter variable while the former
> variable is in scope. However, it is a compile error if a variable with block
> scope has the same name as another variable with block scope and the two scopes
> overlap.

**Comment by jclark** [comment]
By the way, suggestions for improvements to the spec explains things are welcome. But please make them separate issues because they will get fixed on a different timescale.

**Comment by pubudu91** [comment]
Ack. Created #192 for the suggestion made above.
