### ISSUE TITLE
More nil lifting

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#191]
C# talks about "lifted operators" with regards to their nullable types. But, in Ballerina, we talk about both error and nil lifting. I think we should define what are the lifted operators in Ballerina. #85 

Nil Type
At the moment we consider both "." and "[]" are lifted, operators.  As an example, define the "." operator as follows. Let T1 and T2 be types in Ballerina.

`"."(T1, identifier) evaluates T2 `, then we make the "." operator a lifted operator by allowing 
`"."(T1?, identifier) evaluates to T2?`

Likewise, what are the other operators that we can consider as lifted operators? How about `.@` and the type-cast operator `<T>e`?

**Comment by jclark** [comment]
Relevant part of C# spec is here:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#lifted-operators

**Comment by jclark** [comment]
Let's make this one about nil lifting and have a separate issue for error lifting.

**Comment by jclark** [comment]
Error lifting is #195.

**Comment by jclark** [comment]
Example in #893

**Comment by jclark** [comment]
Conclusion of discussion today is to do nil lifting for operators with numeric operands and a numeric result.

**Comment by hasithaa** [comment]
Here is the expression set we decided to support today. 
```
Unary => + x, - x, ~ x, 
Multiplicative  => x * y, x / y, x % y
Additive => x + y, x - y
Shift  => x << y, x >> y, x >>> y
Binary bitwise => x & y, x ^ y, x | y
```

**Comment by jclark** [comment]
Need to think about what happens with compound assignment. Do we do nil lifting there? Not clear if that is the right behavior.  For example, given

```
m["x"] += 1;
```

and `m["x"]` does not exist, then not really the right thing to make `m["x"]` be nil. Better for it to be an error or not to do the assignment at all.

@hasithaa What  have you implemented?

**Comment by hasithaa** [comment]
We didn't consider the compound assignment. The comment https://github.com/ballerina-platform/ballerina-spec/issues/191#issuecomment-878747786 has all the expressions we allowed. Btw, JBallerina has a bug, so this case is not working at the moment.

**Comment by jclark** [comment]
OK, I made a separate issue #1009 for what to do about compound assignment.

**Comment by jclark** [comment]
Points to note:

- Doesn't apply to compound assignment (that's #1009)
- I haven't allowed cases where an operand has type nil: it has to be actually lifting a valid case, i.e. if you take away nil from the types, you get something that would be valid
- You never get a singleton type from the lifted case (because the type of at least one of the operands has to be nil plus something else, and so is not a singleton)
