### ISSUE TITLE
error-match-pattern have too many 'var's

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#194]
**Description:**

```ballerina
match err1 {
    var error(var reason, message = m) => return return expr...
    var error(var reason, message = m, x = x) => return return expr...
    var error(var reason, message = m, blah = x) => return return expr...
    var error(var reason, ...var rest) => return expr...
}
```

It feels like there are too many `var`s in this block of code code.

**Comment by jclark** [comment]
That is not what the grammar specifies.  A match-pattern can be `var binding-pattern`. Within the binding-pattern, you cannot have a `var`. In other words var switches from a mode where identifiers are constants into a mode where identifiers are variables

**Comment by rdhananjaya** [comment]
Then following is correct I assume.
```ballerina
match err1 {
    var error(reason, message = m) => return return expr...
    var error(reason, message = m, x = x) => return return expr...
    var error(reason, message = m, blah = x) => return return expr...
    var error(reason, ...rest) => return expr...
}
```

**Comment by jclark** [comment]
The LHSs looks good. The principle is that every place that creates one or more variables specifies a type descriptor or `var`.
