### ISSUE TITLE
Update specification of experimental features to better match implementation

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#20]
Main features are:

1. Lock
2. Querying 
   1. Table queries
   2. Streaming queries
3. Transactions

**Comment by jclark** [comment]
I would suggest moving the transaction stuff into a separate doc in the ballerina-spec repository.

**Comment by sanjiva** [comment]
Transactions adds a statement .. not impossible to separate but its hard to do it. I would prefer to keep it and clearly mark it (as already done).

**Comment by sanjiva** [comment]
Per discussion today with @jclark, we will do the following:
- experimental means there is a design and an implementation in the distribution
- remove experimental parts from the specification
- for each experimental topic have a guide on ballerina.io (similar to streaming guide)
- add new section to spec called future work
- list experimental features under that
- also list other features that we want to do but haven't yet done designs for (like parametric typing, service typing, long running execution

**Comment by jclark** [comment]
The experimental features are now in a separate document `experimental.html`, which the spec links to.

**Comment by jclark** [comment]
I suggest adding something on channels (at least the grammar).

**Comment by sanjiva** [comment]
Apparently we've removed channels from the  jballerina 1.0 implementation.

**Comment by jclark** [comment]
This is mostly irrelevant not, so closing.
