### ISSUE TITLE
Make E[n] work in expressions for strings

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#209]
Should align with semantics of iteration and array access, and return a string of length 1 or panic.

Do we also want to provide this as a lang.string function?

This is just as an expression not on an LHS since strings are immutable.

**Comment by jclark** [comment]
Relates to #85.

**Comment by jclark** [comment]
Note that JavaScript supports E[n] for strings.

**Comment by sameerajayasoma** [comment]
+1 for supporting E[n] for strings.

**Comment by jclark** [comment]
Agreed to do this.
