### ISSUE TITLE
Add get function to lang.map

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#210]
This would work like E[n] for lists in that it would panic if the member does not exist.

```
function get(map<Type> m, string k) returns Type;
```

When using this to access a map the result of accessing a member of map<T> is T, whereas with E[x] the result is T?.

**Comment by sameerajayasoma** [comment]
Do we need to provide two ways to achieve the same thing?  I know that`E[n]` is different from `map:get` because `map:get` panic if the key does not exist. 

We can add it later if there is a requirement.

**Comment by jclark** [comment]
You are correct that this is the run-time semantics. However, the compile-time semantics are different, because the typing is affected by the type of the key when it is more precise than just string.

**Comment by jclark** [comment]
I like m.get because

- it is useful because it returns T rather than T?
- it feels like a fundamental primitive
- it provides the same runtime semantics for map that E[x] provides for arrays
- the name matches with __get for objects
