### ISSUE TITLE
Provide string:charAt?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#211]
Do we want to provide this as well as #209?

Result would be a string of length 1.

**Comment by jclark** [comment]
string:charAt does not feel harmonious with map:get #210, nor __get method #204, but we have string:codePointAt already.

**Comment by jclark** [comment]
Maybe don't add string:charAt and change string:codePointAt to string:getCodePoint?

**Comment by jclark** [comment]
@sanjiva @sameerajayasoma @hasithaa Thoughts?

**Comment by sameerajayasoma** [comment]
If we decided to support E[n] for strings, then we don't need string:charAt IMO.

**Comment by jclark** [comment]
Consensus was to do only #209 and not this.
