### ISSUE TITLE
Starting a service in imported module

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#215]
@jclark @sanjiva @sameerajayasoma @hevayo 
Recording the $Subject, which we discussed during the packerina meeting. 

Consider a Ballerina program which imports a module with a module level service attached to a listener.  With current semantics, when we run the program, The listener in the imported module will also start. 

This is what spec says, 

https://github.com/ballerina-platform/ballerina-spec/blob/ff94220d5e66d495dd76b7652fcaff1c743c9615/lang/spec.html#L4731-L4735

Implicitly starting listeners in imported modules has the following problems.
- The developer isn't aware of those services or listeners.
- This allows someone to write a library module, with a backdoor easily.

There can be a scenario, where libraries want to start services in the background, But that can be done by calling the listener life cycle methods programmatically.

**Comment by jclark** [comment]
I am trying to collect problems with the current design in issue #44.

Is the backdoor point really an issue? If you import a malicious module, surely it is game over (since functions called in initializers of module-level variables can do anything).
