### ISSUE TITLE
Compile-time requirement on filler values for variable length arrays

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#216]
At the moment, it is a requirement that variable-length arrays have a filler value. This is proving inconvenient in practice.

This has to be enforced at the time the array is constructed. It cannot be enforced at the time the array is used in an lvalue, because whether a member has a filler value depends on the type _descriptor_ that is part of the inherent type (e.g. whether there is a default).

We do not attempt this compile-time enforcement for mapping values.

Simple solution is

- do not do this check at compile-time
- if you write to an array in a way that requires a filler value, and the inherent type of the array is not one that provides filler values, then you get a panic

**Comment by jclark** [comment]
Practical problem is that it is common that

1. you want to have a value of type T[]
2. the length of T[] is not known at compile-time
3. T does not have a natural filler value (e.g. T is a record with a required field)
4. you intend to write to the array in sequential order, without skipping members in a way that would require the use of filler values

At the moment, Ballerina forbids this, in order to ensure that you do not get a panic at runtime, in the case where you inadvertently do not follow your intention per point 4.

But this warps the code, forcing you to either
- use T? instead of T
- make T fillable by adding defaults that you do not ever intend to use

So better to give a panic if you do not do what you intend in case 4. Surely no worse than panicking when you access a non-existent member of the array.

**Comment by jclark** [comment]
Note that tuples with rest member types give rise to the same issues as with array types. (The spec doesn't deal with this at the moment.)

**Comment by sameerajayasoma** [comment]
Here are some record types that are defined in Ballerina compiler. These record types are used to model Ballerina intermediate representation(BIR) in the compiler. All the array definitions have the form T?[] in here. When going through this code, we realized the practical problems of the current semantics of variable-length arrays in Ballerina. People have even written utility methods to covert T?[] arrays to T[].  

As discussed during the call, case 4 is the best solution to solve this problem. 

```ballerina
public type Package record {|
    ImportModule[] importModules = [];
    TypeDef?[] typeDefs = [];
    GlobalVariableDcl?[] globalVars;
    Function?[] functions = [];
    Name name = {};
    Name org = {};
    BType?[] types = [];
    Name versionValue = {};
|};

public type ImportModule record {
    Name modOrg;
    Name modName;
    Name modVersion;
};

public type TypeDef record {
    Name name = {};
    DiagnosticPos pos;
    Visibility visibility = "PACKAGE_PRIVATE";
    BType typeValue = "()";
    Function?[]? attachedFuncs = ();
};

public type TypeRef record {|
    Name name = {};
    ModuleID externalPkg;
|};

public type Function record {|
    DiagnosticPos pos;
    int argsCount = 0;
    BasicBlock?[] basicBlocks = [];
    FunctionParam?[] params = [];
    BasicBlock?[][] paramDefaultBBs = [];
    ErrorEntry?[] errorEntries = [];
    boolean isDeclaration = false;
    boolean isInterface = false;
    VariableDcl?[] localVars = [];
    Name name = {};
    BInvokableType typeValue = {};
    Visibility visibility = "PACKAGE_PRIVATE";
    ChannelDetail[] workerChannels;
    BType? receiverType;
|};

public type BasicBlock record {|
    Name id = {};
    Instruction?[] instructions = [];
    Terminator terminator = {pos:{}, kind:"RETURN"};
|};
```

**Comment by sanjiva** [comment]
While I agree with the problem, effectively this makes sparse array usage the one that trips up Mort as that will cause panics and there's no way for the compiler to help.

What I like about our current approach is that l-value use of arrays can never panic. We could even make that work for r-value usage .. if you access a member beyond the current length we auto-fill to that length and return the filler value. That would mean using an array never panics.

Seems to me this can be solved by having a variant of our solution for fixed length arrays- either you indicate the length or use '*' to say that its computed from the initial value. Could we not use a syntax to say I want non-sparse arrays .. which the compiler will allow variable length arrays of types that are not defaultable and will result in panics if misused.

**Comment by jclark** [comment]
Non-sparse arrays will only panic if you use a member type without a filler value.

**Comment by jclark** [comment]
Also worth mentioning that there are several cases where lvalue use of E[n] can panic for arrays (inherent type of member, and fixed length arrays).
