### ISSUE TITLE
Distinguish unit of compilation and unit of code sharing

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#230]
Ballerina module is a namespace that isolates function definition, type definitions, constants from other namespaces. It supports encapsulation, modularity, and reuse. It is also the compilation unit.

At the time of writing this issue, Ballerina module is also used as the unit of sharing or distributing code as libraries in module repositories such as Ballerina central. This imposes certain limitations to library developers, IMO. I will not explain such constraints here, but I will try to provide references later. 

When you look at other languages, they have addressed this issue by introducing a higher level aggregation above the namespace or the compilation unit (Ballerina module). This aggregation has been described as the unit of sharing. Some languages have addressed this from the beginning while others have addressed this later. 

| Language  | Rust | Java | Go | Python | Ballerina |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Unit of compilation  | Module  | Package  | Package  | Module | Module |
| Unit of sharing  | [Crate](https://doc.rust-lang.org/1.1.0/book/crates-and-modules.html)  | [Module](https://www.oracle.com/corporate/features/understanding-java-9-modules.html)  |  [Module](https://github.com/golang/go/wiki/Modules#new-concepts) | [Package](https://www.learnpython.org/en/Modules_and_Packages)  | - |

We've discussed this briefly during the "packerina" discussions, but decided to postpone further discussions because this higher level aggregation affects the language spec. If you look at all the above languages, these two concepts have been defined in their language specs. 

I created this issue to track this suggestion and also would like to see whether we can introduce another layer(if we decided to do so) of abstraction without any breaking changes in the future. 

@sanjiva @hasithaa @hevayo @jclark 

Relates to #44

**Comment by jclark** [comment]
This split influences how you identify what to import at the language level.

In these other languages
- is the unit of versioning the same as the unit of compilation or unit of sharing?
- does the language import statement refer to the unit of sharing as well as the unit of compilation?

**Comment by sameerajayasoma** [comment]
* is the unit of versioning the same as the unit of compilation or unit of sharing?
Rust - Unit of sharing
Java - Unit of sharing. 
Go - Unit of sharing
Python - Unit of sharing

* does the language import statement refer to the unit of sharing as well as the unit of compilation?
Except for Java in all the other languages, the unit of sharing is part of the import path of a unit of compilation. 

Say `foo` is the name of the unit of sharing and the `bar` and `bazz` are unit of compilations packaged within foo.

1) Some languages have a root unit of compilation concept
```
import foo;  // importing the root unit of compilation in the unit of sharing foo.
import foo/bar // importing the unit of compilation bar in foo.
```

2) Some languages don't have the root concept. 
```
import foo/bazz;  // importing the unit of compilation bazz in foo.
import foo/bar // importing the unit of compilation bar in foo.
```

In Rust, Go and Java,  the versions of the unit of sharing are managed in a descriptor.

**Comment by sameerajayasoma** [comment]
From the language spec perspective, Ballerina module is a unit of compilation that provides namespace isolation, but from a general usage perspective, it helps to break large programs or libraries into more manageable units. This is called modularising the code. But when your libraries evolve, you tend to break it into more modules. When the number of modules grows, it is hard to manage them for the library author as well as the consumer. All these modules should have the same version: They have to be released together since there are related individual modules, the consumer to have to declare their versions in the TOML file, etc.  

The easiest workaround with the current module concept is to put everything into a single module so to make things simple. If you see the [ballerina/http](https://github.com/ballerina-platform/ballerina-lang/tree/master/stdlib/http/src/main/ballerina/http) module, you would see this pattern in the code. The code inside the module is organized into multiple directories. They don't have any semantics in the language perspective because all the symbols will be part of the http module, but these directories indicate the attempt to organize related symbols.
```
http/
-- Ballerina.toml
-- auth/
-- caching/
-- http2/
-- redirect/
-- resiliency/
-- websocket/
-- other .bal files 
```

At the moment, all the symbols defined in these modules are in the http namespace. But it would be nicer to say that they are in modules such as http, http.auth, http.caching, http.resiliency, http.websocket etc and also to release, version and share them as a single unit.

**Comment by jclark** [comment]
I think it is important to keep in mind that `ballerina/http` is much more complex than the typical module, so I don't think we should optimize for that use case.

**Comment by jclark** [comment]
I would summarize the problem like this: there is no way to modularize the unit that you share.

**Comment by sameerajayasoma** [comment]
There is a proposal to address this issue: [Ballerina packages](https://github.com/ballerina-platform/ballerina-spec/blob/master/project/proposals/packages/packages.md)

**Comment by jclark** [comment]
Does this require any language spec changes?

**Comment by sameerajayasoma** [comment]
There are no language spec changes required for this proposal. 

I thought about [`type-ids`](https://ballerina.io/spec/lang/draft/v2020-06-18/#section_5.1.3) to verify whether packages have an impact on the type-ids. Since the `module id` in a `type-ids` is globally unique (within Ballerina central) even with packages, there shouldn't be a problem.   

I am still working on the runtime view of modules and packages. I.e., We need to offer APIs to access the current module and the current package. There are some use cases AFAIR.

**Comment by jclark** [comment]
I would expect langlib to eventually provide some runtime access to modules, probably via the introspection facilities of the typedesc module.

**Comment by jclark** [comment]
Also related is #96.

**Comment by jclark** [comment]
The language spec has some introductory material about projects, which I think is no longer true. https://ballerina.io/spec/lang/draft/v2020-09-22/#program_structure
