### ISSUE TITLE
Dealing with method overloading when annotating function body that is external

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#237]
With the first iteration of Java interop design, we are planning to declare interop related annotations on the external.  Consider the following example. 

Java static functions:
```java
public static void foo(String s) {} // A
public static void foo(UUID u) {} // B

```
Corresponding external function in Ballerina:
```ballerina
public function foo(handle h) = @java:staticMethod{class:"a/b/c/D"} external;
```
Let's say that I want to invoke A with the above ballerina function. I think the best way to handle that scenario is by annotating the parameter `h`. e.g.    But this doesn't look right. 
```ballerina
public function foo(@java:ParamType{name:"java.lang.String"} handle h ) = @java:staticMethod{class:"a/b/c/D"} external;
``` 
Another way to solve this problem is to specify param types within the `@java:staticMethod` annotation itself. But that approach also doesn't look right.

**Comment by jclark** [comment]
Conceptually param types belong as part of the staticMethod annotation, since you are identifying a specific Java method by giving its class, method name, and sufficient of its parameter types to distinguish it from other methods of the same name. So I would suggest something like:

```
public function foo(handle h ) = @java:staticMethod {
   class: "a/b/c/D",
   paramTypes: {
      handle: "java.lang.String"
   }
} external;
```

**Comment by sanjiva** [comment]
+1.

Shouldn't `handle: "java.lang.String"` be `h: "java.lang.String"`?

**Comment by jclark** [comment]
@sanjiva Right. I fixed the example.

**Comment by sameerajayasoma** [comment]
+1
