### ISSUE TITLE
Variant of import that initializes another module without importing symbols

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#241]
Sometimes you want to "import" a module  just so that its services get started or so that its __init function gets runs. If you use regular import for this, it becomes problematic for the compiler to complain about an unused import.

We could, like Go, do `import ... as _` to mean that it is not used directly.

https://medium.com/golangspec/import-declarations-in-go-8de0fd3ae8ff

_Originally posted by @jclark in https://github.com/ballerina-platform/ballerina-spec/issues/44#issuecomment-476614355_

**Comment by sameerajayasoma** [comment]
+1. This is a useful feature to import module just for side effects.

**Comment by jclark** [comment]
At this point, the spec can say it's an error to import a module and not use the symbols.

**Comment by sameerajayasoma** [comment]
+1 for this. But if we add this after 1.0, already written code will break.

**Comment by jclark** [comment]
If you can implement it in time for 1.0, I am happy to add it to the spec now.

**Comment by SupunS** [comment]
This is added with PR: https://github.com/ballerina-platform/ballerina-lang/pull/18060
