### ISSUE TITLE
Clarification on lax type chained access

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#256]
**Description:**
Considering the following sample

```ballerina
json j = { a: { b: 2, c: "string value" } };
json|error j2 = j.a.b;
```

just to clarify we allow the `j.a.b` access.

The field-access-expr mentions that the static type T of expr needs to be lax or a subtype of mapping. 

But in this case, T (static type of `j.a`) is `json|error`, which is neither lax (because of `error`) nor a mapping? So do we allow accessing `b` on `j.a`? (Optional field access too.)

Is this what is covered by the second point of the evaluation? 
"if v has basic type error, the result is v (this can only happen in the lax case)"

**Comment by jclark** [comment]
We definitely want to allow this, but the spec does not handle this properly. Under field-access-expr, where it now says

> The static type of field-access-expr is M|E, where E is empty if K is a required key type and T' is a subtype of T, and error otherwise (E can only be error in the lax case.)

I think we need to add that the static type of the field-access-expr is lax if M is lax. Would that address your point?

**Comment by MaryamZi** [comment]
> We definitely want to allow this, but the spec does not handle this properly. Under field-access-expr, where it now says
> 
> > The static type of field-access-expr is M|E, where E is empty if K is a required key type and T' is a subtype of T, and error otherwise (E can only be error in the lax case.)
> 
> I think we need to add that the static type of the field-access-expr is lax if M is lax. Would that address your point?

@jclark Yes, +1.
