### ISSUE TITLE
Syntax to allow directly calling a field of function type

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#257]
If you have a record with a field of function type and you want to access the field and then call it, you cannot do `r.f()` because that will be interpreted as a method call. Previously we had a built-in method function.call to deal with this, but we could not make that work as a lang library function, because there is no way to write the type.

It would be nice to have a syntax for this.

**Comment by sameerajayasoma** [comment]
This works in the compiler due to a bug. 

And it allows me to write a custom `toString` for a record :)

```
type Person record {
    int i = 10;
    function () returns string  toString = () => "sss";
};

Person p = {};
var str = p.toString();
```

**Comment by jclark** [comment]
With #547, if you have a method-call, `x.foo(args)` and x has a field `foo`, then `foo` must be of function type, and the effect would be to call the value of the foo field.

So the current behaviour would no longer be a bug.

**Comment by jclark** [comment]
If you really want to write a real toString, it's quite tricky, because you don't have `self`:

```
type Person record {
    int i = 10;
    function () returns string  toString = () => "";
};

function makePerson(int i) returns Person {
  Person p = { i: i };
  p.toString = () => "Person: " + p.i.toString();
  return p;
}
Person p = makePerson(17);
var str = p.toString();
```
