### ISSUE TITLE
Rename checkpanic to must?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#260]
There was a proposal for a Go built-in function with similar semantics to our `checkpanic`, and the word they used was `must` (https://github.com/golang/go/issues/32219), which seems quite a bit nicer to me.

Is it worth violating our self-imposed design-freeze for this?

**Comment by hasithaa** [comment]
Another variant to `must` is `assert`,  But it is used in a slightly different way in other programming languages. 
```
string name = assert filepath:filename("/A/B/C");
```

**Comment by jclark** [comment]
An appropriate use of `checkpanic` would be a case where the programmer is parsing a string into something where the programmer knows that the parse will succeed (perhaps because they constructed the string themselves or perhaps because a function's contract requires it) e.g.

```
int n = checkpanic int:fromHexString(s);
int n = must int:fromHexString(s);
```

Not clear to me that this is a win.

**Comment by jclark** [comment]
Decided not to do this.
