### ISSUE TITLE
A Langlib method to produce a list from a mapping value

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#263]
I see this is useful in two cases, 
1) Get values only list from a map.
1)  Use as a built-in reduce function to be used with  `map` method. 

The current solution is to write a reduce function to get the values.

**Comment by jclark** [comment]
I agree. Something like this?

```
public function toArray(map<Type> m) returns Type[] = external;
```

I'm suggesting toArray rather than toList because we have lang module `array` rather than `list`, and the returned value has array type.

We could have this for other types to (could potentially make sense for anything iterable).

**Comment by hasithaa** [comment]
Yes, +1 `toArray` name as well.

**Comment by jclark** [comment]
We need an analogous toStream method.

**Comment by hasithaa** [comment]
@jclark Adding `toStream` is not captured as a spec issue.
