### ISSUE TITLE
Stabilize transactions support

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#267]
Could potentially be split into two parts:

- local
- distributed

**Comment by lafernando** [comment]
Hi,

As brought up in #266, the transactions feature will be critical to Ballerina to be a production ready programming language. This is based on the soon to be released jBallerina 1.0. The 1.0 version generally gives the idea that the prominent features available and stable. Specially, Ballerina positioned as a network distributed programming language, database transactions can be considered something fundamental that should be there. 

So is it possible to give this aspect more priority to improve the design (at least local transactions), validate its usage, and come to a point that, we can take it out of experimental status for jBallerina 1.0?.  Or else, maybe we have to possibly think of a lower version label for the jBallerina release?.

Cheers,
Anjana.

**Comment by jclark** [comment]
There is now a [proposal](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/transaction/transaction.md) for this.

**Comment by jclark** [comment]
Need to deal with #597.

**Comment by jclark** [comment]
Some clarifications/notes as I add the proposal to the spec:

* lang.transaction:Info uses a `timestamp` type, but we haven't defined timestamp yet
* the proposal does not say which langlib module RetryManager and RetriableError go into 
* lang.transaction functions need to be isolated
* subtyping of transactional (see #597)

Will update this comment as I discover more.

**Comment by mohanvive** [comment]
Please find some details on this. 

- At the moment, we are using int type for the `startTime` attribute
- We are maintaining it at lang.transaction. Yes, we should move that. We'll accommodate other suggestions as well.
- Sure, we'll make them isolated.
- There is an error called `TransactionError` used for this. It is located at lang.transaction.

@gimantha FYA

**Comment by jclark** [comment]
For timestamp, I suggest something like this:

```
public type Timestamp readonly & object {
    # Returns milliseconds since 1970-01-01T00:00:00Z, not including leap seconds
    public toMillisecondsInt() returns int;
    # Returns string in ISO 8601 format
    public toString() returns string;
};
```

Then in the future we can just do:

```
type Timestamp timestamp;
````

**Comment by jclark** [comment]
Still to do:

- [ ] explain transactional on workers and with `start` (starting new branch)
- [ ] improve explanation of transaction managers and distributed transactions at beginning of Transactions section
- [ ] explain static failure type of a block
- [ ] doc in transaction.bal
- [ ] timestamp as https://github.com/ballerina-platform/ballerina-spec/issues/267#issuecomment-737944898
- [ ] explain possibility that transaction statement gets to do something when there's a panic
- [ ] say something about how transactions work with services and clients
- [ ] explain transactional scope in transaction statement
- [ ] say something about how transactions nest

**Comment by jclark** [comment]
@mohanvive @gimantha My thinking on outstanding nits is as follows:

1. The CommitHandler and RollbackHandler types need to be isolated (it's not safe otherwise)
2. There should be  a distinct error type `transaction:Error` for errors from commit (`transaction:TransactionError` is unnecessarily repetitive)
3. For a `rollback` statement without an expression within a retry-transaction-stmt, we have two choices
   * it's a compile-time error, or
   * it's allowed and no retry will happen (I think this would be slightly more useful, but I don't feel strongly)
4. whether an anonymous function is transactional should be inferred based on whether the function does anything which is allowed only for a transactional function (`transactional` is doing a different kind of thing from `isolated`, so inference should work differently)
5. RetryManager and RetriableError should go in lang.error (but with `error:Retriable` rather than `error:RetriableError`)

We can discuss further if you disagree with any of these.

**Comment by pcnfernando** [comment]
Ack on 1, 2 and 4.
Need some verification on point 3 and 5.

(3) The behavior as per the current implementation for `rollback` statement  within a `retry-transaction-stmt` is to rollback without retrying. It should be an error return(fail e or return e) from the transaction for it to retry. 
As per https://github.com/ballerina-platform/ballerina-spec/issues/267#issuecomment-737635124 I inferred that it should retry.  
Therefore, we'll rollback and pass nil to `shouldRetry()` so that retrying is ignored for the `rollback` statement without an expression within a `retry-transaction-stmt` and retry for the other case.

(5) We moved `RetryManager` to `lang.object` and `RetriableError` as `error:Retriable` to `lang.error` as per the suggestion in https://github.com/ballerina-platform/ballerina-spec/issues/267#issuecomment-737635124. We will have to move back `RetryManager` to `lang.error` now.

**Comment by jclark** [comment]
@pcnfernando I was confused on (3): what you are doing sounds good.

But `return e` isn’t a failure, so it shouldn’t retry.

**Comment by jclark** [comment]
Please have a look at 7.22 and 7.23 in the spec to make sure we are in alignment.

**Comment by pcnfernando** [comment]
Ack. (3) should be corrected as: 
> It should be an failure outcome from the transaction for it to retry.

Furthermore, we'll be keeping the existing behavior for the rollback within a `retry-transaction-stmt`.

**Comment by pcnfernando** [comment]
Clarification on making CommitHandler and RollbackHandler types isolated (1).
When we make the handlers isolated, the functions passed for onCommit and onRollback needs to be isolated and the variables within the functions should abide according to isolated function type. 

eg:
```ballerina
string ss = "";

@test:Config {
}
function testTrxHandlers() {
    ss = ss + "started";
    transactions:Info transInfo;
    var onRollbackFunc = isolated function(transactions:Info? info, error? cause, boolean willTry) {
        //ss = ss + " trxAborted";     # invalid access of mutable storage in an 'isolated' function
        io:println("trxAborted");
    };

    var onCommitFunc = isolated function(transactions:Info? info) {
        //ss = ss + " trxCommited";   # invalid access of mutable storage in an 'isolated' function
        io:println("trxCommited");
    };

    transaction {
        transInfo = transactions:info();
        transactions:onRollback(onRollbackFunc);
        transactions:onCommit(onCommitFunc);
        trxfunction();
        var commitRes = commit;
    }
    ss += " endTrx";
}

```

**Comment by jclark** [comment]
> When we make the handlers isolated, the functions passed for onCommit and onRollback needs to be isolated and the variables within the functions should abide according to isolated function type.

Yes, that is the effect of making these types isolated.
