### ISSUE TITLE
Usability problem with open types, optional/default fields and mapping constructors

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#268]
Consider:

```
type Person record {
  string name;
  string country?;
}

Person p = { name: "James Clark", county: "Thailand" };
```

This will compile despite `country` being misspelled, because the record is open and the `country` field is not required.   There would be the same problem if `country` was required, but had a default value. This seems very much not OK to me.

**Comment by jclark** [comment]
I think there is a potential solution which is to do something similar to what we do with the dot operator and assignment.  We do not allow `p.county = "Thailand";`, and I think we can use a similar rule here.  The rule would be something like this: when the contextually expected type is a record type, you can only use identifiers for field names that are mentioned in the type. For other fields, you would have to use a string, e.g. if you wanted a `county` field you would have to do

```
Person p = { name: "James Clark", "county": "Bangkok" };
```

just as you have to use `p["county"] = "Bangkok";` to do the assignment.

**Comment by sanjiva** [comment]
I agree this is a serious usability problem and +1 for the proposed approach for solving it.

**Comment by hasithaa** [comment]
We have implemented this for JBallerina 1.0.0-Alpha

**Comment by jclark** [comment]
Is it working OK?

**Comment by hasithaa** [comment]
Yes, This change is a good one.  It really helps to detect typos quickly.
