### ISSUE TITLE
Provide more built-in subtypes of int

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#270]
At the moment, Ballerina provides one built-in subtype int, namely byte (corresponding to the range 0-255 i.e. 8-bit unsigned). There are a number of important use cases related to interop where more built-in subtypes would be useful:

- Java interop
- protocol buffers/gRPC

Potentially useful subtypes are signed/unsigned subtypes in 8/16/32-bit widths.

These should act as proper types (conceptually equivalent to a union of singletons).

Bitwise operation typing rules should be similar to byte for the unsigned types.

**Comment by jclark** [comment]
Suggested names, when using the approach proposed in #272, would be e.g. `Unsigned32`; this is intended to work well when prefixed with the imported module prefix e.g. `int:Unsigned32`.

**Comment by jclark** [comment]
So specifically we would add to the `int` module:

- Signed8
- Unsigned8
- Signed16
- Unsigned16
- Signed32
- Unsigned32

The existing byte type is the same as `int:Unsigned8`.

**Comment by jclark** [comment]
This may also be useful for interop with SQL, which has multiple integer types.

**Comment by jclark** [comment]
Need to define how operations deal with signed subtypes and mixed subtypes.

**Comment by jclark** [comment]
Currently the operators that treat byte specially are `>>`, `>>>`, `&`, `|`, `^`.

The simplest approach would be to say that these same operators are the only ones that do anything special with integer subtypes, and they do so only when both operands are unsigned subtypes. If the operands are of different sizes, the results are the same as when both operands have the larger size.

Although we could do much more than this, I suspect it would not be very useful.

Maybe we should also do something with `%` (i.e. UnsignedX % UnsignedY has type UnsignedY).

**Comment by jclark** [comment]
Still need to generalize rules for bitwise ops.

**Comment by hasithaa** [comment]
@jclark builtinSubtypes need to be public here https://github.com/ballerina-platform/ballerina-spec/commit/0574a8a35b64125d06d6f915f2fc2794d1b23f54.

**Comment by jclark** [comment]
@hasithaa Thanks. I fixed this.
