### ISSUE TITLE
Improved enumeration support

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#276]
The typical way of doing an enumeration in Ballerina at the moment would be either:

```
const FOO = “foo”;
const BAR = “bar”
type E = FOO|BAR;
```

or

```
const FOO = 1;
const BAR = 2;
type E = FOO|BAR;
```

When compared to the enumeration type provided by Protocol Buffers (or by Go), there are a number of ways that this might be improved:

1. Too much repetition (each enum case is mentioned three times)
2. No obvious single right way to do things (although, when you look at things structurally, the first is cleary better)
3. No concept of open enumeration
4. No scoping of const name to type (related to 3)

For example, you might have 

```
enum E {| FOO, BAR |};
```

defines type E as union of “FOO” and “BAR” and makes E.FOO be the constant “FOO”. You could override the string using e.g. `FOO = “foo”`. Also

```
enum E { FOO, BAR }
```

would be an open enumeration that allows any string for E. It is not yet clear to me how to make “open” enumerations work in a protocol buffer context, when you get an integer for values not included in the enumeration.

**Comment by jclark** [comment]
In protocol buffers, field number for record fields is analogous to enumeration value for enumerations.

**Comment by jclark** [comment]
TypeScript has both string and numeric enums. String enums look like this:

```
enum Direction {
    Up = "UP",
    Down = "DOWN",
    Left = "LEFT",
    Right = "RIGHT",
}
```

Numeric enums look like this:

```
enum Direction {
    Up = 1,
    Down,
    Left,
    Right,
}
```

The first enum is 0 if not specified.

The names of the constants are scoped to the enumeration type e.g. `Direction.Up`.

**Comment by sanjiva** [comment]
Looks good.

**Comment by jclark** [comment]
Initial design is as follows.

An enumeration declaration is sugar for some const declarations and a union type. For example

```
    public enum Direction {
      NORTH,
      EAST,
      SOUTH,
      WEST
    }
```

would be *completely* equivalent to

```
    public const NORTH = "NORTH";
    public const EAST = "EAST";
    public const SOUTH = "SOUTH";
    public const WEST = "WEST";
    public type Direction NORTH|EAST|SOUTH|WEST;
```

(although hopefully the enum declaration would make it easy for an IDE to suggest identifiers rather than strings in a context where an enum type is expected)

An enumeration type is thus a subtype of json.

The value of the const can be overridden in the enum declaration:

```
    public enum Direction {
      NORTH = "N",
      EAST = "E",
      SOUTH = "S",
      WEST = "W"
    }
```

The expression following `=` must be const-expr, with a static type that is a subtype of string.

The syntax would allow metadata (documentation and annotations) before each enumeration constant.
