### ISSUE TITLE
Typing of response of service resource

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#278]
The type of a service resource method does not make explicit the type of the response that the resource method will send to a client when it is invoked.

This is not a good fit for gRPC and will likely cause problems for session typing across Ballerina programs.

@sanjiva points out that “using return has the problem that the code doesn't know whether return succeeded - that's why it was done that way from the start”

**Comment by sanjiva** [comment]
With our current approach we don't also have a way to record say media type + content schema of responses. 

That's what Swagger calls "produces": https://swagger.io/docs/specification/2-0/basic-structure/.

**Comment by jclark** [comment]
I haven’t thought this through, but the Swagger “produces” concept triggered the following idea:

1. allow a resource method to say `produces T` in addition to `returns T`.
2. have a `produce` action, analogous to a `return` statement
3. since it’s an action, it can return an error (but what can you do if it does return an error?)

**Comment by sanjiva** [comment]
Yes I was thinking along the lines of your point 1 too.

Ref the action, there are protocol specific actions currently to actually send the response and given the different kinds of replies based on protocol and the terminology used: http - respond, grpc - send but maybe that's fixable. The signatures would not match of course.

Ref point 3, if the action returns an error then the resource function returns an error. In that case the protocol driver (which is the one that invokes the resource function in the first place) is responsible for responding / negotiating the protocol properly. For HTTP that might be simply to return 500 server error.

**Comment by jclark** [comment]
If you are writing a client and service in Ballerina, it would be nice if the service declaration could be used as a client declaration.

**Comment by jclark** [comment]
This is handled by #606. We drop the requirement that resource methods (which become service remote methods) return a subtype of `error?`. This allows them to use the return value to describe the response. This works only when for a request/response message exchange pattern. For more complex patterns, the resource method should be passed a strongly typed client.
