### ISSUE TITLE
Ensure gRPC support makes appropriate use of current language

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#281]
In particular

- handle enumeration by union of const strings
- handle oneof using optional fields
- map Duration onto decimal (number of seconds)
- handle Value/Struct (and related types) using json, map<json> (and subtypes)
- for client-side use, should generate a stub which is a `client` object with `remote` methods

**Comment by daneshk** [comment]
@jclark for enumeration, we are using the union of const strings. for example

Let's say we have protobuf config,
```proto
enum Sentiment {
    HAPPY = 0;
    SLEEPY = 1;
    ANGRY = 2;
}

message HelloRequest {
    string message = 1;
    Sentiment sentiment = 5;
}
```

Generated Ballerina code looks like,

```ballerina
type HelloRequest record {|
    string message;
    Sentiment sentiment;
    
|};

public type Sentiment "HAPPY"|"SLEEPY"|"ANGRY";
const Sentiment SENTIMENT_HAPPY = "HAPPY";
const Sentiment SENTIMENT_SLEEPY = "SLEEPY";
const Sentiment SENTIMENT_ANGRY = "ANGRY";
```

But in proto definition, it also supports defining enum within the protobuf message like below,

```proto
message HelloRequest {
    string message = 1;
    Sentiment sentiment = 5;

    enum Sentiment {
       HAPPY = 0;
       SLEEPY = 1;
       ANGRY = 2;
   }
}
```
This enum definition only visible within the message. In Ballerina, we couldn't support it. Current implementation, We always generate public union type irrespective of where it definition in proto config.

Is there any better way to achieve this in Ballerina.

**Comment by jclark** [comment]
I don't see any better way to do it today, but it would nice to improve on this. See issue #276.

**Comment by daneshk** [comment]
To me, Oneof field is not only an optional field. According to the protobuf definition, we can group set of fields as Oneof field. If we group set of fields, we can set only one of those fields at a given time. For example,

Let's say we have protobuf config,
```proto
message Person {
	oneof identity {
		string passportId = 2;
		string nic = 3;
	}
}
```
User can only set either passportId or nic as identity of the person. 
In Ballerina code, we support above Oneof field like below

```ballerina
type Person record {|
    Identity identity;
|};

public type Identity Person_Passportid|Person_Nic;

type Person_Passportid record {|
    string passportId;
|};

type Person_Nic record {|
    string nic;
|};
```
Here we define record type for each Oneof field and define a union type of those record types. So we can make sure user can set only one field. 
This is similar to how golang support protobuf oneof fields.

Is there any better way to achieve this in Ballerina.

**Comment by jclark** [comment]
We can separate this into two issues:

1. what is the right way to represent the values when oneof is being used?
2. how to we write a type for those values?

For 1, the right way to represent the value of a message with a oneof field is simply as a message with one of the fields. This is how it is on the wire, and is consistent with the field names and numbers for oneof fields being in the same symbol space as regular fields. It is definitely not right to introduce another level of records as you have done. You can see this in the [JSON serialization](https://stackoverflow.com/questions/44069789/what-is-the-expected-json-serialization-of-oneof-protobuf-field). The discriminator field (`identity`) in your example is not part of the message and is just something needed for access by most programming languages, which are not structurally typed. In the example of oneof in the proto3 docs, the name of the discriminator field is _not_ a name for the union of the oneof fields, but is a name to test which of the oneof fields is present (i.e. an appropriate name in your example would be `test_identity` not `identity`). 

For 2, the best that is possible in Ballerina today is:

```
type Person {
  string passportId?;
  string nic?;
};
```

This is not precise, because it does not capture that exactly one of the fields must be present. In other word's, it's a supertype of the type that you want. But this is the case with other features of implementation today (e.g. `int32`).

There is an issue to do better with oneof: #274.

**Comment by daneshk** [comment]
Agreed. The serialized message only contains the specific field (either `passportId` or `nic`). It is a part of the library(or implementation) to restrict the user to set only one of those fields.

Problem with having optional fields for those fields, we are not restricting the user to set only one of those fields. If the user sets more than one of those fields. we either can 

- Give the priority to the field order of the record type to pick which field value to serialize. For example. If both `passportId` and `nic` are set, we pick `passportId` when serializing the message.

- Give an error to the user saying you can only set one of those fields.

What is the better way to tackle this problem?

**Comment by jclark** [comment]
Using field order of the record type is not OK.

Giving an error is OK. You could also generate a function for setting each oneof field, which first removes the other fields on the oneof group.

Another approach would be for the mapping value to remember the order in which fields were added to the mapping and then give priority to the last one added.
