### ISSUE TITLE
Ballerina implementation uses '*' to get children of xml element

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#283]
**Description:**
Ballerina implementation uses `*` operator to get all children of a xml element, this is similar to langlib.getChildren()

Sample: [BBE xml functions](https://github.com/ballerina-platform/ballerina-lang/blob/ae01ae7b54dd599708dd62fe7f47218fc4c09e63/examples/xml-functions/xml_functions.bal#L43)

**Comment by jclark** [comment]
Thanks for the link. The XML support is still at the preview stage, and support for convenient navigation will be added in due course (see issue #169). I suspect we will use `.` to access attributes rather than child elements.
