### ISSUE TITLE
Service detach lifecycle function for listeners

### ISSUE THREAD

**Issue by wggihan** [ballerina-platform/ballerina-spec#284]
Currently `__attach` function is available for attaching services to the listener. But if we want to dynamically remove and re-attach an updated service, then there is no way. Mainly this function requires to support mutable gateway to update APIs dynamically.

**Comment by jclark** [comment]
So you're looking for an additional Listener method

```
public function __detach(service s) returns error?;
```
?

**Comment by wggihan** [comment]
Yes.

**Comment by sanjiva** [comment]
This is fine but @wggihan what are the thoughts on any active connections? Are the desired semantics that of a graceful detachment or sudden detachment? 

Also note that if its graceful then returning doesn't mean its actually detached - just that no new connections will be accepted. For something like websockets that could mean the connection lives on for as long as the application layer is using it.

**Comment by wggihan** [comment]
We are looking a graceful detachment. Each listener will have its own behavior. So in websocket situation, we can decide either do nothing or send a close frame upon the detach function call.

So basically, it up to the connector developer to decide what to do with active connections.

**Comment by jclark** [comment]
Do we want to add this for R3?

**Comment by wggihan** [comment]
Yes. That would be better. But currently we can achieve the same behavior simply by providing a function in the listener in an unofficial manner. But it would be better if we can have this as a proper lifecycle function.

**Comment by hasithaa** [comment]
Since this is a breaking change, Better we can add this to R3.
