### ISSUE TITLE
__init method for services

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#289]
**Description:**

Doing some initialization before service start is useful in most cases. 
 Eg. Initialize database connection before service. Initialize service variables, etc.

This is similar to object __init. But service __init signature has to no argument and return type must both be a subtype of error? and contain (). 

This is something working (unintended) in the current implementation, where we use objects values to model services.

**Comment by jclark** [comment]
Services (as they are in the spec) have no fields and thus do not have state, so I don't see how initialization makes sense.

**Comment by hasithaa** [comment]
Yes, it is doesn't make sense. I think we missed this change (service having no fields). Right now it is allowed.

**Comment by jclark** [comment]
I created a new issue to deal with this #290.
