### ISSUE TITLE
Consts for max/min values in integer types

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#291]
**Description:**
Spec defines max and min value each basic numeric types (int, float, decimal). But there is no way to get these values programmatically.  Most languages define these as constant values.

**Comment by jclark** [comment]
I agree that this would be a good thing to have. It's straightforward for int. but a bit more complicated for floating point types.

**Comment by hasithaa** [comment]
Yes, agree. Java provides more consts  double type. https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#MAX_VALUE

Once we support subtype of int https://github.com/ballerina-platform/ballerina-spec/issues/270, we can provide more constants value.

**Comment by jclark** [comment]
For the `int` module, I think we can easily do MIN and MAX, plus variants for the builtin subtypes eg. SIGNED32_MAX.

For decimal, we could have:

1. maximum value
2. maximum integer
3. smallest positive value
4. maximum precision

**Comment by jclark** [comment]
We will separate into int and floating point and do int now and floating point later.

**Comment by jclark** [comment]
Since we have min() and max() functions, I think it's better if we add _VALUE to the name of the constants like e.g. MAX_VALUE. Java also does this e.g. java.lang.Long.MAX_VALUE.

**Comment by jclark** [comment]
We will make this issue just for int and its built-in subtypes; limits for floating point types will be dealt with later in #430.
