### ISSUE TITLE
Should we allow `var []` as a match pattern?

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-spec#292]
Spec defines match-pattern as follows;

```
match-pattern :=
  var binding-pattern
   | ...

binding-pattern :=
   capture-binding-pattern
   | wildcard-binding-pattern
   | list-binding-pattern
   | ...

list-binding-pattern := [ list-member-binding-patterns ]

list-member-binding-patterns :=
   binding-pattern (, binding-pattern)* [, rest-binding-pattern]
   | [ rest-binding-pattern ]
```

According to this, should we allow `var []` as a match pattern without any identifier?

```ballerina
function matchValue(anydata a) returns string {
    match a {
        var [] => {
            return "found a list";
        }
    }
    return "Default";
}
```

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/17204

**Comment by jclark** [comment]
It is allowed because `list-member-binding-patterns` allows `[ rest-binding-pattern ]`, which means `rest-binding-pattern` or nothing.

**Comment by grainier** [comment]
Ok. However, the spec says following; and it's a bit unclear when `list-member-binding-patterns` contains nothing, which semantic to go by.

> a list-binding-pattern with m binding patterns matches a list with n members if m is less than or equal to n, and the i-th binding pattern matches the i-th member of the list for each i in 1 to m, and either m is equal to n or the list-binding-pattern includes a rest-binding-pattern; if there is a rest-binding-pattern ...v, then a successful match causes a new list value consisting of all members of the matched list except for the the first m values to be assigned to v;

If we take the same example;

```ballerina
function matchValue(anydata a) returns string {
    match a {
        var [] => { // list-member-binding-patterns
            return "found a list through list-member-binding-patterns";
        }
        [] => { // list-match-pattern
            return "found a list through list-match-pattern";
        }
    }
    return "Default";
}
```

What should it match for `var []`? Should it match empty list (i.e `i` where, `int[] i = [];`) or any list? If it matches an empty list, isn't it same as `list-match-pattern`?

**Comment by grainier** [comment]
@jclark, any update on this?

**Comment by jclark** [comment]
The part you quoted says "and either m is equal to n or the list-binding-pattern includes a rest-binding-pattern", so the semantics are the same i.e. only matches list with length 0.  Note that both list binding patterns and list match patterns are not open unless there's a `...`.

**Comment by jclark** [comment]
If this is not clear, please reopen.
