### ISSUE TITLE
Inconsistencies on `.mergeJson()` failure

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#293]
**Description:**
```ballerina
public function mergeJson(json j1, json j2) returns json|error = external;
```

The spec says, where both `j1` and `j2` are mappings, `.mergeJson()` should merge each entry in `j2` to `j1` (updating `j1` and its members itself).

We currently do this by iterating through the fields in `j2` and merging them into `j1`. However, if the merge fails halfway through, an error is returned, but the changes already done to `j1` still remain.

Sample Code:
```ballerina
import ballerina/io;

public function main() {
    json j1 = { x: { a: 1 }, y: 2 };
    json j2 = { x: { b: 2 }, y: "string" };

    var result = j1.mergeJson(j2); // `mergeJson` should fail for key `y`
    io:println("result: ", result);
    io:println("j1: ", j1);
}
```

Output:
```cmd
$ ballerina run merge_json.bal 
result: error {ballerina}MergeJsonError message=JSON Merge failed for key 'y' cause=error {ballerina}MergeJsonError message=Cannot merge JSON values of types 'int' and 'string'
j1: {"x":{"a":1, "b":2}, "y":2}
```

Note the changes to the `x` field in `j1`.

Should `.mergeJson()` operate on a clone instead? Or is this behaviour OK?

**Comment by jclark** [comment]
You should first check that the merge can succeed; if it cannot, return an error, otherwise perform the merge.

This is inconvenient to implement, but is the cleanest behavior for the user.

**Comment by MaryamZi** [comment]
> You should first check that the merge can succeed; if it cannot, return an error, otherwise perform the merge.
> 
> This is inconvenient to implement, but is the cleanest behavior for the user.

Agreed, we will update the implementation.

**Comment by jclark** [comment]
Docs for mergeJson should clarify that arguments should be unchanged on error.
