### ISSUE TITLE
Clarification on "Module and program execution"

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#295]
**Description:**
Creating this issue to clarify a few points regarding the "Module and program execution" section of the spec.

**1. Behaviour when module initialization panics**

The spec says 
```
A module's initialization function performs expression evaluation so as to 
initialize the identifiers declared in the module's declarations; if evaluation 
of an expression completes abruptly, then the module initialization function 
immediately returns the error value associated with the abrupt completion. 
If a module defines a function named __init, then a module's initialization 
function will end by calling this function; if it terminates abruptly or returns 
an error, then the module's initialization function will return an error value.
```

Does this mean even abrupt completion (panics) should eventually result in the synthesized init function returning the error, instead of panicking?

**2. Signature of the user defined module init function** 

Should we place a restriction on the signature of this `__init()` function? 
e.g., no parameters, return type should be a subtype of `error?`.

**3. Status code on error returns from the function acting as the entry point**

When we had the `main()` function, which could optionally return an error, as the entry point we discussed setting the status code based on an integer value in the error (Related discussion - https://groups.google.com/d/msg/ballerina-dev/Yxy-qB-4e-I/Rv5be-lLGwAJ). Would this be part of the language spec or should it come from the platform spec?

**Comment by jclark** [comment]
1.  I don’t see how it makes any observable difference. Whether module initialization panics or fails, the effect on program execution is the same.
2. The spec answers this in the affirmative in the section on “Function definitions”.
3. As far as the lang spec is confirmed, if the program terminates unsuccessfully you get an error value. It would be up to the platform spec to turn that into something appropriate to the underlying operating system.

**Comment by MaryamZi** [comment]
> 1. I don’t see how it makes any observable difference. Whether module initialization panics or fails, the effect on program execution is the same.

The difference was regarding printing the stack trace on panicking. But given that the stack trace can be accessed from the error value, and both returning and panicking have the same effect when it comes to module initialization, agreed that it is pretty much the same. 

> 2. The spec answers this in the affirmative in the section on “Function definitions”.

Ack, sorry, missed this.

> 3. As far as the lang spec is confirmed, if the program terminates unsuccessfully you get an error value. It would be up to the platform spec to turn that into something appropriate to the underlying operating system.

Ack.

**Comment by jclark** [comment]
For stack trace purposes, better to propagate a panic as a panic rather than as an error.

**Comment by MaryamZi** [comment]
So IIUC, if initialization panics (either the synthesized init function or the user defined one), the panic is propagated. If an error is returned from the user defined init function, the synthesized init function would return the same error.

On a related note, would the behaviour for `check` with module level expressions be the following?

```ballerina
int i = check foo();

public function main() {
    
}

function foo() returns int|error {
    error e = error("err");
    return e;
}
``` 

If `foo()` evaluates to `error`, the synthesized init function would return the error? (i.e., the synthesized init function may also return error).

**Comment by jclark** [comment]
For that case, the synthesized init should return an error.

The principles are:

- error return values should not get implicitly turned into panics (can be done explicitly with checkpanic).
- panics should not get implicitly turned into errors (can be done explicitly with trap)
- the compiler should be able to determine a specific error type for the error return value

**Comment by jclark** [comment]
Please reopen if not clear.
