### ISSUE TITLE
Allow metadata on object and record fields

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#299]
Metadata (annotations and doc comments) are currently allowed on object methods but not object or record fields.  There does not seem any good reason for this. It is inconvenient not to be able to document fields like object methods.

**Comment by pubudu91** [comment]
Metadata is not allowed currently on object fields as well right? Currently object fields are defined as follows:
```
object-field-descriptor :=
   object-visibility-qual type-descriptor field-name [default-value];
```

**Comment by jclark** [comment]
Good point. We should allow metadata for both object fields and record fields.

**Comment by sameerajayasoma** [comment]
Even though metadata is allowed on object and record fields,  I don't see annotation attachment points in the spec.

**Comment by jclark** [comment]
Thanks. I created a separate issue #446 for that, so it doesn't get forgotten.
