### ISSUE TITLE
Cooperative multitasking

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#30]
At the moment it is too easy for an a programmer to unintentionally write programs that have data races.

A concept for fixing this is have multitasking be cooperative by default. This would mean that a new strand will run on the same thread as its starting strand unless the programmer explicitly uses a keyword on the worker declaration to indicate that it should run on a new thread.

**Comment by jclark** [comment]
We distinguish between

- function-level concurrency: semantics of concurrency constructs used within functions to create new strands, specifically named workers and `start`
- service concurrency: see issue #116

This issue deal with the former only. The agreed approach is that the new strand will be on the same thread, unless the compiler can prove that running it on a different thread would be safe (i.e. not lead to data races).

**Comment by jclark** [comment]
We also need to specify at what points a strand-switch is possible. (By strand-switch, I mean current strand execution being suspended, and execution switching to a new strand.) When modifying global state, it must be possible to have critical sections in which the user can be sure that only one strand will be in the critical section at the time. In the absence of explicit locking (which we are trying to avoid for simple cases), then the user can only achieve this by knowing which operations might cause a strand-switch, and avoiding those functions in a critical section. The problem is with functions in different modules. How does the user know whether such a function can suspend? We can guarantee all lang library functions won't.

For others, I think we are going to need to have an annotation or perhaps something in the language saying that a function won't do anything that would result in the strand being suspended. The compiler can leverage this to avoid the Kotlin-style coroutine transformation in those cases.

Potential strand-switch points need to include at least operations where the semantics involves waiting for something:

- synchronous worker send
- flush
- worker receive
- wait

**Comment by sameerajayasoma** [comment]
In the current jBallerina impl, we made this assumption that all function invocations can cause a strand-switch. Therefore, in generated function body, you would see a continuation as well as a switch case to handle strand switches.

**Comment by jclark** [comment]
The potential strand-switch points are related to cancellation. When worker A cancels worker B that just conceptually sets a flag, and then at particular points in execution B will automatically check the cancellation flag and panic if it is set; we can call those points _cancellation points_.  Cancellation has a similar potential to cause global invariants to be violated, so it would make sense to me to say that potential cancellation points are the same as potential strand-switch points.

**Comment by jclark** [comment]
Following a suggestion by @hasithaa, I plan to use the term _yield point_ instead of _strand-switch point_.

**Comment by jclark** [comment]
@hasithaa Note that we need to allow annotations on things that create new strands so that they can indicate that the newly created strand runs on a new thread.
