### ISSUE TITLE
Clarification regarding the Module stop execution order

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-spec#305]
**Description:**
According to the spec, module initialization happens bottom-up, as in, first, it initializes all the dependent packages, and then it initializes current package, 

So what should be the module stop order? is it same as the initialization order or should it be top-down?(that is, should it stop the current package before calling stop on the dependant packages? which is reverse of the initialization order)

the current implementation does this in the same order as initialization

**Comment by jclark** [comment]
The specification does not currently require any particular order.

I would have thought it would be better to stop services in the reverse of the order in which they were started.

**Comment by lankavitharana** [comment]
Thanks, @jclark will proceed in that way, will close the issue as it is resolved now
