### ISSUE TITLE
Can XML namespace prefixes be shadowed?

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-spec#308]
The "Variable and identifier scoping" section of the spec talks about shadowing only with regard to variable names. Are we allowed to shadow XML namespace prefixes as well? In the current implementation, we allow it. For example,
```ballerina
xmlns "http://sample.com/wso2/a1" as ns;

function testNamespaces() {
    xmlns "http://sample.com/wso2/a2" as ns; // Allowed, and shadows the module level prefix

    if (true) {
        xmlns "http://sample.com/wso2/a3" as ns; // Allowed, and shadows the above prefixes
    }

    xmlns "http://sample.com/wso2/a3" as ns; // Compile error since the prefix is already defined in the same scope.
}
```

**Comment by jclark** [comment]
The rule should be consistent for the prefix symbol space: declarations at the block level can shadow declarations at the module level but must not shadow other declarations at the block level.

**Comment by pubudu91** [comment]
Also, on a slightly related note, the scoping section only mentions variable names when talking about shadowing. But do those scoping rules apply to all identifiers in the main symbol space? Currently we don't allow shadowing for type names. But for functions we do. For example, the following is valid in the current implementation.
```ballerina
function test() {
    int test = 10;
    int x = test + 10;
}
```

**Comment by jclark** [comment]
Shadowing should be consistent for all identifiers in the main symbol space. (Otherwise adding a module-level name would require looking at all local identifiers in every function in the module to check that none of them not shadow the new name.)
