### ISSUE TITLE
setLength/removeAll behavior on tuple

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#309]
**Description:**
Is it legal to change the length of tuple value using setLength/removeAll methods given that tuple was create using tuple type descriptor with rest type

```
[int...] i = [2, 3];
i.removeAll(); // this is valid?
```

This relates to discussion here https://github.com/ballerina-platform/ballerina-lang/pull/18015
**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
Yes. The type `[int...]` contains exactly the same set of shapes as `int[]`, so when a list value has an inherent type of `[int...]` it can be modified in exactly the same was as a list value that has an inherent type of `int[]`.
