### ISSUE TITLE
$$ not allowed by string template grammar

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#31]
The string template grammar does not allow '$$' in a string unless it is immediately before an interpolation.

 ```
int value = 10;
string s = string `Price - $${value}`; // supported. `s` contains Price - $10
string s = string `Hello $$ world`; // unsupported
```

However, we can add multiple $ symbols using an interpolation.

```
string s = string `Hello ${"$$"} world`;
```

**Comment by jclark** [comment]
That looks like a bug in the grammar to me.

We want to allow `$$` but still recognize `$${`.

The easiest way to solve this might be to extend the lexical formalism to include lookahead, ie recognize `$`  as a delimiter only when it is followed by a left brace. If so, we should do this in a way that fits well with ANTLR.

**Comment by jclark** [comment]
@hasithaa Will it work if we change BacktickTwoChars and BacktickFinalOneChar to use $+ instead of $?

**Comment by hasithaa** [comment]
@jclark I think, this should work. 
```
BacktickTwoChars :=  $+ ^ ( { | ` )
BacktickFinalOneChar := $+
```

**Comment by jclark** [comment]
I don’t think that can be right. BacktickTwoChars cannot allow $ as its final character.

```
BacktickTwoChars :=  $+ ^ ( { | `|$ )
```

Could you test this with the ANTLR grammar?

**Comment by hasithaa** [comment]
@jclark yes you are correct, I misread the grammar. Following solves the issue. 

```
BacktickTwoChars :=  $+ ^ ( { | ` |$ )
BacktickFinalOneChar := $+
```
