### ISSUE TITLE
Behaviour on updating an iterable collection/members while iterating it via foreach

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#313]
**Description:**

**Updating Members**

The spec says "The scope of any variables created in typed-binding-pattern is block-stmt. These variables are implicitly final".

Does this mean the following should fail at compile time, similar to ordinary final variables?

```ballerina
import ballerina/io;

type Foo record {
    string bar;
};

public function main() {
    Foo[] arr = [{ bar: "test" }, { bar: "string" }];

    foreach Foo f in arr {
        io:println(f);
        f.bar = "new value"; // attempt updating f - should fail at compile time?
    }

    io:println(arr);
}
```

**Updating the collection itself**

Also, if someone tries to update a collection (add/remove members) while iterating it, should this result in something like a concurrent modification error?

**Comment by jclark** [comment]
On your first point, declaring a variable `final` just stops assigning a new value to the variable; it does not prevent mutating the value that the variable refers to. So

```
final Foo f = { bar: test };
f.bar = "new value";
```
is fine. Your example also is fine.

**Comment by jclark** [comment]
For the your second point, there needs to be well-defined, interoperable behaviour.

I suspect simply giving an error is going to be inconvenient; for example, you might want to remove things from a collection as you iterator over them. This needs some more thought.

**Comment by MaryamZi** [comment]
> On your first point, declaring a variable `final` just stops assigning a new value to the variable; it does not prevent mutating the value that the variable refers to. So
> 
> ```
> final Foo f = { bar: test };
> f.bar = "new value";
> ```
> 
> is fine. Your example also is fine.

Sorry, my bad. Wanted to clarify the same - whether assigning a new value to `f` needs to be restricted. 

The behaviour for normal `final` variables is as you explained, but we have not restricted assigning a new value to variables created in the typed-binding-pattern of foreach. We will update the implementation. Thank you.

**Comment by jclark** [comment]
`java.util.Iterator` has the remove method, which we don't. To get that functionality, I propose

- if an iterator has already returned the member for some key/index, then it is OK to remove that member, and it has no effect on the iterator (i.e. so `filter` for example can be written using an iterator)
- apart from that, a call to `next` on an iterator will get a panic if the set of valid keys/indices is different from when the iterator was created

If that turns out to be too restrictive, we can loosen it later.
