### ISSUE TITLE
Static type of the result of bitwise-xor-expr when both operands are bytes

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#315]
**Description:**
The spec says the following for bitwise-xor-expr:

"The static type of both operands must be a subtype of int. The static type of the result is as follows:
- for AND, if the type of one operand is a subtype of byte, then the result has type byte; otherwise, the result has type int;
- for OR, if the type of both operands have a type that is a subtype of byte, then the result has type byte; otherwise, the result has type int;
- **for XOR, the result has type int.**"

Should the result type for XOR be `int` when both operands are subtypes of `byte` too, given that the possible value ranges from 0-255?

**Comment by jclark** [comment]
Yes, you are right: it should be like AND and OR. I was getting confused.

**Comment by jclark** [comment]
Specifically the rule for XOR should be the same as the rule for OR: if the high-order bits of both operands are zero, then the high-order bits of the result will be zero.
