### ISSUE TITLE
Downgrade lang.stream module version number

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#317]
Currently, we have `1.0.0`
https://github.com/ballerina-platform/ballerina-spec/blob/f43b64d75c5de85a7eeea92c221bdd70c186bff2/lang/lib/versions.json#L10

Since the streaming is an experimental feature, I feel it is better to downgrade it to `0.1.0`.

**Comment by jclark** [comment]
Agreed. That's a mistake.
