### ISSUE TITLE
Clarification regarding module-qualified reason strings

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#318]
**Description:**

The spec says

"A module-qualified reason string is a string that has the form
```
   {org-name/module-name}identifier
```
where org-name, module-name and identifier are as defined by the grammar in this specification, but with no whitespace allowed between tokens. Any reason string that starts with a { should be a module-qualified reason string. "

- does the whitespace restriction mean a module-qualified reason string cannot have any whitespace at all or just that whitespace is not allowed between `{` and `org-name`, `org-name` and `/`, etc.

- regarding restricting reason strings starting with `{` to be module qualified strings, does this restriction apply only to error type descriptors, or does it apply to error constructors too?

The validation we are planning on introducing is to check if the org-name and module-name of such a reason string matches the module the error is defined in. For example, the following is only valid in the `ballerina/io` module.

```ballerina
public const FileNotFoundReason = "{ballerina/io}FileNotFound";

public type FileNotFoundError error<FileNotFoundReason>;
```

Similarly should the following also be validated to check if it matches the current module?
```ballerina
public const FileNotFoundReason = "{ballerina/io}FileNotFound";

public function main() {
    error e = error(FileNotFoundReason);
}
```

If this validation is done, it would not be possible to create a value of such an error type from a different module, even if the type is public.

**Comment by jclark** [comment]
I don't understand the whitespace part of your question. The grammar defines `org-name := identifier`.

All the spec says is:

> Any reason string that starts with a { **should** be a module-qualified reason string.

So it's just a recommendation not a requirement.

I suggest that the only thing you do is to give a warning for a type `error<S>` when S is finite, if it contains a string starting with `{`  that is not syntactically a module-reason string.

The idea to "check if the org-name and module-name of such a reason string matches the module the error is defined in" goes beyond what the spec requires.

**Comment by jclark** [comment]
Please reopen if this is not clear.
