### ISSUE TITLE
Resource method signatures and external resource methods

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#32]
**Description:**

Current grammar allows us to have resource methods with external function body. This brought up the following question.

Normally, the result of a function or a (remote) method is represented by the return value. In the external case, the function signature is good enough to understand the function/method semantics without knowing the implementation. 

But resource methods are special. The result of a resource method will be handled using an action invocation. (in WebSocket that can be multiple action invocations). The return value is used to represent the end of the resource or error situation.

Technically we should be able to achieve the same with an external implementation. Conceptually resource signatures are not initiative enough to understand the resource semantics in an external case.

We have the following options.
1) Not allowing external resource methods. - which is inconsistent with other methods.
2) Fix resource signature.
3) Allow external resource methods - considering this is a rare case.

@jclark @sanjiva Thoughts?

**Related Issues:**
N/A

**Comment by jclark** [comment]
I don't understand. What have resource methods to do with action invocations? Do you mean remote methods?

**Comment by hasithaa** [comment]
Yes, Consider the following program.

```ballerina
service hello on new http:Listener(9090) {
    resource function sayHello(http:Caller caller, http:Request req) {
       
       var result = caller->respond("Hello, World!");

        if (result is error) {
            log:printError("Error sending response", err = result);
        }
    }
} 
```

sayHello resource has two results 1) string value "Hello World" using a remote call, and 2) nil value using return. If I write the same sayHello resource using an externally implementation, this is how it looks like. 

```ballerina
service hello on new http:Listener(9090) {
    resource function sayHello(http:Caller caller, http:Request req) = external;
} 
```

**Comment by sanjiva** [comment]
IMO this is ok .. I agree there are two results but strictly speaking the network result or results, if any, are an implementation detail of the resource function. 

It is true that the network result is part of the service typing part of the problem however. We haven't sorted out service typing yet but I don't think we will be able to do that fully without some annotation support as it won't be something we can validate without an extension that understands every action and participates in the type checking process.

Overall I'm no longer thrilled with any implementation being outside of its container - object methods or service resources :). But I agree with James that if we're going to keep one its best to be consistent.

**Comment by jclark** [comment]
Deal with this in #278.
