### ISSUE TITLE
Ballerina object methods static or virtual?

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#320]
**Description:**
In the current jBallerina implementation method invocations on object values are virtual similar to Java.

```ballerina
import ballerina/io;

type Obj1 object {
    int i;

    function __init(int i) {
        self.i = i;
    }

    function foo() {
        io:println("Obj1.foo");
        _ = self.bas();
    }

    private function bas() returns int {
        io:println("pvt bas");
        return 0;
    }
};

type Obj2 object {
    int i;

    function __init(int i) {
        self.i = i;
    }

    function foo() {
        io:println("Obj2.foo");
    }

    // private function bas() returns int {
    //     return 0;
    // }
};

public function main(string... args) {
    Obj1 o = new(0);
    Obj2 o2 = o;
    o2.foo(); // calls Obj1.foo();
}
```
This prints 
```
Obj1.foo
pvt bas
```

Looking at the spec about effects of visibility regions of methods on object subtyping rules, it feels like Ballerina object methods are meant not to be virtual. This is because of statement
`if an object type descriptor T has private fields or methods, then it is not possible to define another object type descriptor that is a subtype of T,`. Please clarify whether method dispatch is static or dynamic.

**Comment by jclark** [comment]
The methods are part of the object's value, so it's dynamic.

**Comment by rdhananjaya** [comment]
Reopening to clarify a related issue.

Given methods are part of the object value, why is it that type T can't have a subtype T' when T have private methods? 

T's private methods only come to the context when we consider values which are created using T, and since private methods are limited to scope of T I can't see the reason why we need to consider T's private members when it come to subtyping.

**Comment by jclark** [comment]
A made a separate issue for you #321
