### ISSUE TITLE
Function in lang.decimal to control precision

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#322]
IEEE has quantize, which is not a very intuitive name.

**Comment by jclark** [comment]
Do we also need something to get the precision?

**Comment by jclark** [comment]
java.lang.BigDecimal has `scale` and `setScale` (`setScale` is an anomalous name, since it doesn't mutate.)

decNumber (this is the C package that nBallerina uses, which is done by Mike Cowlishaw how is main person behind IEEE decimal floating point) has quantize and rescale functions (but rescale isn't available for decQuad, which is the type nBallerina uses).

However, Java `setScal`e and decNumber `rescale` interpret the integer scale differently:

- in decNumber, it's the decimal exponent, so rescale(123.4567, -2) would be 123.46
- in Java, it's the negative of the exponent,  so setScale(123.4567, 2) would be 123.46

The Java way round is consistent with the round function, i.e. positive N means N digits are the decimal point.

**Comment by jclark** [comment]
So my view is we should use `quantize` with IEEE semantics.

**Comment by SandaruJayawardana** [comment]
Current langlib `decimal:quantize` function is as follows,
```
# IEEE quantize operation.
# + x - decimal value to operate on
# + y - decimal value from which to get the quantum
# + return - `x` with the quantum of `y`
public isolated function quantize(decimal x, decimal y) returns decimal = external;
```
BTW, there can be some scenarios where the user may need (in monetary applications etc.) to change the rounding direction (ceiling or floor). 
Python also supports both up and down rounding directions. Refer to [quantize(exp, rounding=None, context=None)](https://docs.python.org/3/library/decimal.html#decimal.Decimal.quantize).
I think, we can make it more flexible to the user by adding an optional parameter for rounding direction.

**Comment by jclark** [comment]
@SandaruJayawardana In IEEE 754 rounding direction is an attribute that is an implicit parameter to most floating point operations (including quantize). I agree some applications need control over this. But it's not a requirement that is specific to quantize (or even to decimal). I created a new issue #1103 for this.
