### ISSUE TITLE
Invoking a service method via service object

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-spec#325]
**Description:**
In the current spec under **service constructor** it states

`If a service-method-defn contains a resource qualifier, then it defines a resource, otherwise it defines a method. The self variable can be used in a method-body of a service-method-defn in the same way as for objects.`

`service-method-defn-quals :=
   [explicit-visibility-qual | resource]`

Under **method call expression** it states

`
If the static type of expression is a subtype of object or a subtype of service, and the object type or service type includes a method named method-name, then the method-call-expr is executed by calling that method on v. 
`

Does this mean invoking a service method via a service value as shown bellow is allowed?

```ballerina
import ballerina/io;

service s = service {
    function bar() {
        io:println("bar");        
    }
};

public function main() {
    s.bar();
}
```

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
Yes.

**Comment by hasithaa** [comment]
@jclark @sanjiva Right now, services are stateless. I don't see any value, function inside a service or a normal function in this case. Additionally, it is like another grouping mechanism for functions. 
If we allow service state in the future, this allows someone to manipulate service state from outside, which requires more thinking. 

Considering above, I would suggest, remove access modifier from service methods (similar to resources methods), So those are always available via self inside a service.

**Comment by jclark** [comment]
There is more basic problem: there is no way to statically type the call to `s.bar()`, so we cannot allow this until we have service typing.

**Comment by jclark** [comment]
I have fixed as @hasithaa suggests: no access modified on service methods, and method-call-expr allowed on services only with self. We can fix this when we do service typing.
