### ISSUE TITLE
Invoking a service method via service reference

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#327]
2019R3 Spec allows $Title. 

```ballerina
service x = service {
  function foo1() {}

  resource function bar() { }
};

function baz() {}

... 
x.foo(); // Allowed (1)
baz() // (2)
```

Concerns : 
- Right now, services are stateless. I don't see any value, function inside a service or a normal function in this case. (1) and (2) Behave the same. Additionally, it is like another grouping mechanism for functions. 
- If we allow service state in the future, this allows someone to manipulate service state from outside, which requires more thinking. 
- service typing is required in order to use this across modules. (Even across functions, if service value created inside a function.)

Considering above, I would suggest, remove access modifier from service methods (similar to resources methods), So those are always available via self inside a service.

_Originally posted by @hasithaa in https://github.com/ballerina-platform/ballerina-spec/issues/325#issuecomment-527273978_

**Comment by jclark** [comment]
Sorry, I was wrong about #325. The spec is not coherent here, because there is no way to statically type the method call. Let's close this one and deal with it in #325.
