### ISSUE TITLE
Proper service type descriptor

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-spec#329]
**Description:**
Currently all the services are of the generic type `service` and hence the `__attach` life cycle function of all the listeners take the same service. This has caused complications in differentiating services when the same listener supports two different service types (Eg. `http:Listener` supports both WebSocket and http services.) In this case it is difficult to have proper compiler validations. Although we have certain hacks in the compiler plugin that uses the resource parameters to validate the service, these are not proper solutions as we get odd compiler messages at certain times. 
Also compile time validations are complicated when defining the service as a separate variable. In this case also resource parameters are used for compiler validation which is not particularly useful in all instances. One example is [here](https://github.com/ballerina-platform/ballerina-lang/issues/14148).
This also causes issues in tooling code generation because, the tooling also need to depend on the listener or other means to generate code snippets.
Related mail thread though a little outdated:  https://groups.google.com/d/msg/ballerina-dev/AicMMCXL8kA/w9l1vNz1CAAJ
   
**Code sample that shows issue:**
Attaching two services to same listener:
```
service serviceName on new http:Listener(9090) {
    resource function onOpen(http:WebSocketCaller caller) {
        
    }
}
```
```
service serviceName on new http:Listener(9090) {
     resource function newResource(http:Caller caller, http:Request request) {
        
    }
}
```
Defining service as a different variable:
https://gist.github.com/riyafa/3f0b31ce53a75911d7ef1bc00ff43b83

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/14148

**Comment by jclark** [comment]
This is definitely on our radar.

Until gets this added to the language, the idea is that you can annotate the service type.

```
@service { type: "http" }
type HttpService service;
```
You then treat the abstract type `Listener` as being parameterized in the service type i.e. as `Listener<S>` where `S` is the annotated service type.

Relates to #278 and #290.

**Comment by jclark** [comment]
This will be dealt with by #559, #608, #609.
