### ISSUE TITLE
JSON defined as a union including "decimal" type

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-spec#332]
The current "json" type is defined as the following union:

()|boolean|int|float|decimal|string|json[]|map<json>

In [1], it recommends the usage of IEEE 754 double precision numbers, which is what our "float" is. This is due to keeping interoperability with other implementations. Due to this reason, shall we remove "decimal" type from the definition?. 

[1] https://tools.ietf.org/html/rfc7159#section-6

**Comment by jclark** [comment]
See issue #8.
