### ISSUE TITLE
Differentiate between variable and var in Ballerina Flavored Markdown

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-spec#335]
**Description:**
In the Ballerina Specification, it is specified that we can refer to Ballerina-Defined identifiers if the identifier within backticks are preceded by a set of keywords. 

Within the set of keywords, "variable" and "var" are both specified. What is the difference expected between these 2 keywords?

Should we add const to the set of keywords?
**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
No difference between them, just two different ways of referring to it: one is the English word, one is the Ballerina keyword.

**Comment by jclark** [comment]
We should also allow const/constant as you suggest.

**Comment by jclark** [comment]
I made a separate issue for the const point.
