### ISSUE TITLE
Add boolean:fromString

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-spec#339]
**Description:**
Does lang lib provide a way to convert string to boolean ?
some thing like :
`boolean myboolean = boolean.fromString("true");`

if not lets create something like that and add an example to learn by example document also.

**Affected Versions:**
v 1.0.0
**OS, DB, other environment details and versions:**
Mac OS, JDK 1.8

**Suggested Assignees (optional):**
@hasithaa @MaryamZi @dulvinw

**Comment by hasithaa** [comment]
Move this issue to spec repo, this is related to langlib.

**Comment by hasithaa** [comment]
@ramith , This can be done with existing language constructs. i.e.
```ballerina
boolean b = x == "true"; // Here x is a string variable. 
```

@jclark IIRC, we didn't add this for some reason.  But `value:toString()` defines a string representation for boolean, So we can add this. If we provide boolean lang lib method called `fromString` the return type will be `boolean|error` , assuming we are matching string value `true`, `false` and error for other strings.

**Comment by jclark** [comment]
I agree this should be in langlib.

Not sure if we want to allow a bit more flexibility than just "true" or "false":

1. trailing or leading white space
2. allow upper case (we allow this for hex numbers for example)
3. allow 1 and 0 as well as true or false (representation of other value types does not require English)

**Comment by jclark** [comment]
We don't have a boolean module currently, so we will need to add that.

The other fromString methods don't strip whitespace, so this shouldn't also.
