### ISSUE TITLE
RecordSet instead of Table

### ISSUE THREAD

**Issue by hrennau** [ballerina-platform/ballerina-spec#348]
**Description:**
The [Preview] Tables type perhaps introduces unnecessary heterogeneity? Proposal: consider replacing type Tables with a new type RecordSet. A recordset-type-descriptor identifies a record type, plus a possibly empty list of field names used as primary keys. Benefits: reuse of syntactical constructs, reuse of the existing concept "field" (getting rid of columns), gratuitous introduction of default values (not yet included in the Table model).

Also to be considered: shifting the concept of "primary key" into Record, at the same time evolving it into the more abstract notion of "identity defining fields". So it would be conceivable to extend the definition of Record to include optional flags marking fields as contributing to semantic identity, something which might be valuable beyond the use of databases. Primary keys would then simply be an application of semantic identity.

**Suggested Labels:**
Tables, Records, RecordSets, Semantic Identity

**Comment by jclark** [comment]
Thank you for your comment. There is a proposal for tables, which is fills out what is in the spec.

https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/table/table.md

I am trying to gather discussion on that in issue #354. Could you make your comment there? Or I can copy it.  We have not made any decision about whether to adopt the proposal, and are open to alternative suggestions.

**Comment by jclark** [comment]
I have mentioned this in https://github.com/ballerina-platform/ballerina-spec/issues/354#issuecomment-538708067

**Comment by jclark** [comment]
There is a new [proposal](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/tablenoclone/tablenoclone.md) for tables, which is more like a RecordSet.
