### ISSUE TITLE
Open records vs json

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#353]
At the moment, if you create declare an open record using `record { }`, it will not be a subtype of json, because the  implicitly allowed fields are of type anydata, which is not a subtype of json. This means the user can not use such a value as json, but has to create a new value which is json.

Three obvious possibilities to fix this:

1. Say any `record { }` is open to `json` not `anydata`.
2. Provide an alternative easy syntax to declare records that are open to `json` rather than `anydata`
3. Provide a new lang library function to jsonify anydata.

**Comment by jclark** [comment]
Another possible solution is to define a standard way to map from anydata to JSON, and then allow the HTTP response payload to be anydata, with the semantic that this standard mapping is applied.

Apart from tables, the only non-JSON thing is XML, and there’s an obvious JSONificiation, which is to represent the XML value as a string.

**Comment by jclark** [comment]
Apart from XML, there are error values, which would naturally map to some sort of object.

We would then allow value:toJsonString to work on anydata, and we could provide a `typedesc:constructFromJson`, which would work with whatever `value:toJsonString` produces.

**Comment by jclark** [comment]
Two parts to this:
1. change `value:toJsonString` to accept `anydata` rather than just `json`, with tables being represented as an array of mappings, and xml being represented as a string
2. add `typedesc:constructFromJson` which can construct a table value from an array of mappings, and an xml value from a string

Alternative to (2) would be to incorporate the functionality in `typedesc:constructFrom`.

**Comment by jclark** [comment]
`typedesc:constructFrom` does not (for the most part) change the shape, so this this functionality should not be included there.

We cannot really design this without having dealt with #471.

**Comment by jclark** [comment]
#471 proposes that typedesc:constuctFrom changes to value:cloneTyped with the argument order swapped, so `T.constructFrom(v)` changes to `v.cloneTyped(T)` with v being defaultable from the contextually expected type.

In addition to this, we need four functions, which should also both be in lang.value:

1. a function to down-convert from anydata to json by turning
   - a table into a list of records
   - an xml value into the string representation of the XML, and
    - (when we have it) a timestamp into a string representation of the timestamp
2. a function that does 1 combined with converting from json to a string in JSON format
3. a function to up-convert from json to a user-defined subtype of anydata; this does a combination of the reverse of 1 and of cloneTyped; this combination cannot be separated because the type is used to recover the information lost by the down-conversion
4. a function that does 3 combined with converting from a string in JSON format to a string

To be consistent with our current langlib naming conventions, the names for the four functions should be:

```
public function toXyzJson(anydata d) returns json = external;
public function toXyzJsonString(anydata d) returns string = external;
public function fromXyzJson(json j, typedesc<anydata> t = <>)
    returns t|error = external;
public function fromXyzJsonString(json j, typedesc<anydata> t = <>)
    returns t|error = external;
```

where `Xyz` is a word that describes the kind of anydata to json conversion that is being done. The best idea I have thought of so far for `Xyz` is `Simple` on the basis that this conversion from anydata to json is the one that produces the simplest json structure. Note that if we leave out `Xyz`, then we would get the problem that applying `toJson` to an xml value would give a value that the user would probably not expect.

**Comment by jclark** [comment]
An arguable weakness in this naming scheme is that the names of the `from*` functions do not capture that they include the strong typing done by `cloneTyped`.

**Comment by jclark** [comment]
Conclusion from meeting today is that `Xyz` should be empty: all the choices for `Xyz` are worse than the unexpected behaviour when applied to xml.

**Comment by jclark** [comment]
value:string already has:

```
public function fromJsonString(string str) returns json|error = external;
```

Maybe better to use `WithType` on the from ones, to match `cloneWithType`.

```
public function fromJsonWithType(json j, typedesc<anydata> t = <>)
    returns t|error = external;
public function fromJsonStringWithType(string s, typedesc<anydata> t = <>)
    returns t|error = external;
```

**Comment by jclark** [comment]
We decided we were OK with the `WithType` suffix.

**Comment by dulajdilshan** [comment]
Hi @jclark ,

Let's say we want to convert `A` json to `B` record type which has a field with a union type
```ballerina
type B record {
    xml|string p;
};

public function main() {
    json A = {p: "<b>xml or string</b>"}
}
```
In here to which type we have to convert (to a `string` or a `xml`) ?

This question occurs when we have a `JSON` with numeric value and `record` with union of numeric types
