### ISSUE TITLE
Ballerina Flavored Markdown: Ballerina-defined name reference with arbitory depth

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#359]
**Description:**
```
    x()
    m:x()
    t.y()
    m:t.y()
```

`m:t1.t2.y()` is a valid reference in Ballerina Flavored Markdown right?

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
t is an object type name. What would t1.t2 mean?

**Comment by rdhananjaya** [comment]
My apologies, I assumed it's a `const`

**Comment by jclark** [comment]
I think it will be less confusing if I use T rather than t.
