### ISSUE TITLE
Provide a way to dynamically register a module listener

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#361]
Similar to what the listener declaration does.

User description of scenario is:

> Hi all, I am doing some work with multi-module projects and I have run into an odd scenario whereby I want to abstract the functionality of a service for the main module (module1) to a supporting module (module2). In this case, module2 is intended to connect to an external WebSocket server and on receiving a binary stream back from the server it will run the function defined by module1. The issue is that the module2 service doesn’t continue running due to module1 having only a very basic main() function (entry point). See code examples below: I am wondering if there is a way to get the service defined in module2 to act as an entry point for module1?

**Comment by jclark** [comment]
Looks like we need this for Swan Lake. See #635.

**Comment by jclark** [comment]
This is complicated by #615. If this is done by a langlib function, how do we write the parameter type? Maybe just this in lang.object:

```
# Register a listener with the module from which this function is invoked.
public isolated function registerListener(object {
   public function gracefulStop() returns error?;
   public function immedateStop() returns error?;
} listener) = external;
```

The module doesn't need to do attach/detach, so the object type doesn't need to declare these methods.

@hasithaa Does this work?

**Comment by hasithaa** [comment]
Similar to register, we need a unregister function as well. Once all registered listeners are unregistered, the runtime can terminate. 

Also, I feel this has to be a runtime related function like `runtime:sleep()`, not a lang lib related functionality.

**Comment by jclark** [comment]
Decision is to put register and unregister in a new lang.runtime module.

**Comment by jclark** [comment]
The object needs a `start` method too, since the module may be registered by the module `init` function and `start` gets called after module initialization.

**Comment by jclark** [comment]
`deregister` is better English: it is removing the object from the module's list of listeners.

**Comment by riyafa** [comment]
should `gracefulStop` be called when deregistering a listener as well as when the program exits? Or only when the program exits?

**Comment by jclark** [comment]
That seems like a reasonable thing to do, but I am not sure about the scenarios for which `deregisterListener` is intended. @hasithaa What do you think?

**Comment by hasithaa** [comment]
This is what I am thinking. There are two ways users can use listeners. 

1) Using a listener declaration. Here Compiler/Runtime handles listener life-cycles.
2) Programeticly. Here the user is responsible for handling the listener life-cycle. 

In the latter case, users should be able to use listeners without registering with runtime. They need to register only if they want to run in daemon mode. This means life-cycles methods independent from register/deregister runtime methods. 

In the former case, life-cycles methods and register/deregister should be handled automatically by runtime/compiler. 
So when the program starts, 
- for each listener declarations, init listener varaibls.
- for each listener declaration, call `runtime:registerListener()` method
- for each listener declaration, call `listener.start()` method.

Once the program is started, uses can registers listeners. So we need to handle them when the program stops;

Case 1: Immediate stop. i.e:  ctrl + c 
- For each listener registered with the runtime using `runtime:registerListener()`, the runtime has to call the listener.immediateStop()
- Runtime doesn't wait for the result of the immediate stop.
- Stop the runtime.

Case 2: Graceful stop i.e: by calling runtime:exit() method
- For each listener registered with the runtime using `runtime:registerListener()`, the runtime has to call the listener.gracefullStop()
- Runtime wait for each return of the gracefullStop before stopping.

**Comment by jclark** [comment]
@riyafa We discussed today and the answer to your question is no.

**Comment by jclark** [comment]
Clarification of immediateStop/gracefulStop per https://github.com/ballerina-platform/ballerina-spec/issues/361#issuecomment-730503896 is #652.
