### ISSUE TITLE
Unary expression syntaxes are confusing

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-spec#365]
**Description:**
Current unary expression syntaxes are bit confusing as some users can think it as a post decrement or increment operation. Because with the grammar rule below
```antlr
expression
    |    (ADD | SUB | BIT_COMPLEMENT | NOT | UNTAINT) expression
```

It is allowed for user to write unary operations as below.
```ballerina
function func1() {
    int a = 1;
    a = --a;
    a = ++a;
    a = -+a;
    a = ------+------a;
}
```
 can we make this a bit less confusing?

**Comment by rdhananjaya** [comment]
Transferred from `ballerina-lang` repo to `ballerina-spec` repo as the question is about the spec.

**Comment by jclark** [comment]
The spec does not have `++` and `--`:

https://v1-0.ballerina.io/spec/lang/2019R3/#unary-expr

**Comment by jclark** [comment]
They were removed a long time ago: not even in R1.

**Comment by rdhananjaya** [comment]
Just to verify: Current behavior of `--` is double negation hence no negation at all, and `---` result in plain negation, is this the expected behavior?

**Comment by jclark** [comment]
Yes. `--x` is same as `-(-x)`; `---x` is same as `-(-(-x))`. BTW, `--x` is not a no-op (e.g. the most negative int).
