### ISSUE TITLE
Unclear if parenthesis can be used with function reference in Ballerina Flavoured Markdown

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-spec#367]
It is unclear if we can use, function `f()` in BFM. Is this a valid scenario or should we warn for invalid reference?

**Comment by hasithaa** [comment]
Spec says, 

> BFM also recognizes `f()` as an alternative to function `f`. In both cases, f can have any of the following forms (where `m` is a module import, `x` is a function name, `T` is an object type name, and `y` is a method name):

> -    x()
> -    m:x()
> -    T.y()
> -    m:T.y()

According to that followings are valid. 
1. ``function `math:add` ``
2. ``function `math:add()` ``
3. `` math:add() ``
