### ISSUE TITLE
Support for classic (c = readchar()) > 0 style syntax

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-spec#370]
**Description:**
This might sound crazy but consider the following suggestion:
```ballerina
    if (var s = getStringOrSomethingElse()) is string && someOtherExpression() {
     // do something with variable `s` 
    }
```
this might help me to write less number of lines of code.   
**Steps to reproduce:**
N/A
**Affected Versions:**
1.0.1
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
suggestion, improvement
**Suggested Assignees (optional):**

**Comment by jclark** [comment]
Design philosophy of Ballerina is to prefer clarity and maintainability over conciseness. So C-style assignment expressions aren't going to happen.  Also this would not fit well with Ballerina type syntax, because some type declarations look like expressions (e.g. singleton types).
