### ISSUE TITLE
Iterable object is missing in lang.object module

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-spec#374]
By reading the spec, I assume that the iterable object has the following structure

```ballerina
@typeParam
type Type any|error;

# An iterable object is represented by a subtype of `Iterable`.
public type Iterable abstract object {
    public function __iterator() returns
        abstract object {
            public function next() returns
                record {|
                    Type value;
                |}?;
        };
};
```
Currently object module only contains the `Listener` abstract object. 
I would like to get below two clarified.
1. Is the Iterable abstract object defined above correct in representing the Iterable objects?
2. Where does the Iterable abstract object should go in the lib (should it go to lang.object)?

**Comment by jclark** [comment]
From https://ballerina.io/spec/lang/2019R3/#built-in_abstract_object_types

> There are several abstract object types that are built-in in the sense that the language treats objects with these types specially. Note that it is only the types that are built-in; the names of these types are not built-in.

`@typeParam` is only defined for functions. Simply extending it to object types is not sufficient because `Iterable<T>` is not valid syntax.

So the answer to your questions are "no" and "nowhere".
