### ISSUE TITLE
Having param-names for only a subset of parameters in function-type-descripter

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-spec#378]
**Description:**
Under `function-type-descriptor` (v2019R3) it says:

`A param-name can be omitted from a required-param, defaultable-param or rest-param only when occuring in the function-signature of a function-type-descriptor.`

With the current implementation, following two scenarios are supported.

With param-name for all parameters
```ballerina
function (string a, int[] b) returns string bar = foo; 
```

Without param-name for any parameters
```ballerina
function (string, int[]) returns string bar = foo; 
```

Do we need to support scenarios where only a subset of parameters have param-names?
Ex:
```ballerina
function (string a, int[]) returns string bar = foo; 
```

**Comment by jclark** [comment]
The wording in the spec allows your example:

```
function (string a, int[]) returns string bar = foo; 
```
