### ISSUE TITLE
XML attribute mapping: Multiple NS prefixes to same Namespace URI

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#379]
**Description:**
This is regarding the XML proposal https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md

Do we allow multiple prefixes pointing to the same NS URI in the same attribute map?

**Comment by jclark** [comment]
You can have multiple distinct prefixes pointing to the same NS URI e.g.

```
<foo xmlns:x=“http://xyz” xmlns:y=“http://xyz”/>
```
