### ISSUE TITLE
How to handle fields in abstract object?

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-spec#380]
**Description:**
According to the spec,

`An abstract object type must not declare an __init object.`

According to the current implementation for a non-abstract object, all fields are added to __init function. For an abstract object, it is unclear how to handle fields.

**Comment by jclark** [comment]
When you do `new T`, `T `must be a non-abstract object type, and that determines how the fields are initialized. So the issue of how to initialize the fields of a non-abstract type never arises.
