### ISSUE TITLE
Clarification: fillMember for lists

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#383]
**Description:**
For a list of lists should the fillMember fill empty list when inserting a member to an uninitialized member list?

```ballerina
int[][] lst= [];
lst[0][2] = 3; // should the fillMember fill l[0] with the emtpy array first?
```

Note: In current Ballerina implementation `lst[0][2]` is implemented as 2 steps. First, perform the get and then perform the add, and the compound operation fails as there is no element `0` in `lst`.

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
You perform a _filling-read_ on `lst[0]`, which creates an array. See https://ballerina.io/spec/lang/2019R3/#section_7.14.1 
 and in particular https://ballerina.io/spec/lang/2019R3/#member-access-lvexpr
