### ISSUE TITLE
Further clarification on fillMember on list

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#384]
**Description:**
For a list without a fixed length, if we try to read out of range member, do we attempt fillMember operation first or is it straight away index out of range error?

This relates to https://github.com/ballerina-platform/ballerina-spec/issues/383

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
If it’s an expression, then an out of range index is a panic:

https://ballerina.io/spec/lang/2019R3/#section_6.17

(There’s a difference between lvexpr and expression.)
