### ISSUE TITLE
XML proposal: lang-lib xml.getChildren

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#394]
**Description:**

Does this comment [also want getChildren lifted over sequences](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.bal#L14) means that getChildren should return all children of all elements if invoked on a xml sequence?

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
What I meant by that comment was that we also need to provide functionality equivalent to `getChildren` applied to an xml sequence. This will come from `/<*>`. The low-level `getChildren` function should be parallel to `setChildren` and work only on type Element.
