### ISSUE TITLE
Unclear what is meant by "All lock statements acquire the same mutex."

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-spec#397]
Does $title mean that there is one single lock to be acquired by all over the program?

For an example, if two functions have used the lock statement, cannot they run in parallel?

**Comment by jclark** [comment]
The results of the execution must be _as if_ there was single mutex over the whole program. A high quality implementation would not implement it that way. See the papers referenced in the issue.

**Comment by jclark** [comment]
I rewrote the spec. Hopefully it is clearer now.
