### ISSUE TITLE
Allow spread operator in mapping constructors

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#399]
This is the analog of #52 for mapping constructors.

We should be able to say `{ ...x }` where x is a mapping. 

This is needed to make query expressions #398 work smoothly.

**Comment by jclark** [comment]
For consistency, we should also make `...` work with a mapping value in a function call. I guess that's doable with a closed record type.

**Comment by sanjiva** [comment]
So its basically a set of named args that you get from `...x` in a function call if x is a closed record type right? Yes that'll be very helpful.

**Comment by MaryamZi** [comment]
#52 says "At the moment it when applied to a list, it has the effect of specifying each member as a positional argument; I wonder if it could also be made to apply to a record with the effect of specifying each member as a named argument."

Does this mean the following (and similar scenarios) is also valid?

```ballerina
type Foo record {
    string s;
};

type Bar record {
    int i;
    string s;
};

public function main() {
    Foo f = {s: "hello"};
    Bar b = {i: 1, ...f}; // valid since `f` has a required field named `s` of type `string`
}
```

**Comment by jclark** [comment]
Your example should work. This issue is about allowing that and similar scenarios i.e. applying to mapping value in mapping constructor.

The comment in #52 was about `...` applied to a mapping value in function calls.

**Comment by MaryamZi** [comment]
> Your example should work. This issue is about allowing that and similar scenarios i.e. applying to mapping value in mapping constructor.
> 
Ack.

> The comment in #52 was about `...` applied to a mapping value in function calls.

Yeah, sorry, meant to relate it to being equivalent to each member being specified as a separate field.

**Comment by jclark** [comment]
There's a nasty problem lurking here because of openness. Consider:

```
Foo f = {s: "hello", "i": "not an int" };
```

**Comment by MaryamZi** [comment]
Isn't the following scenario with computed keys somewhat similar?

```ballerina
type Bar record {
    int i;
    string s;
};

public function main() {
    string str = "i";
    Bar b = {i: 1, s: "hello", [str]: "not an int"};
}
```
The invalid field results in a panic.

```cmd
$ ballerina run test.bal 
Compiling source
        test.bal

Generating executables
Running executables

error: {ballerina/lang.map}InherentTypeViolation message=invalid value for record fiel
d 'i': expected value of type 'int', found 'string'
        at test:main(test.bal:8)
```

**Comment by jclark** [comment]
I agree there are similarities and we need to consider these two cases together, but I think there is an important difference: with computed keys, the user is explicitly requesting dynamic behaviour, but with the `...` case, I think some level of static checking would be expected. For example, in your first example if Foo had an `int i` field, I would expect a compile-time error.

**Comment by MaryamZi** [comment]
Agreed, I was thinking the validation could still be done for the fields that are present in the type-descriptor (missing field, duplicates, etc.), but for the rest fields, we can only validate at runtime.

But yes, there would still be some dynamic behaviour, if open records/maps are allowed with the spread operator for a mapping constructor creating a record.

**Comment by MaryamZi** [comment]
Few more questions, 
- can more than one spread operator be used in a single mapping constructor? (`{a: 1, ...x, ...y}`)
- can a spread operator be used anywhere in the mapping constructor or should it come after all the key-value/var-name fields? (Is `{a: 1, ...x, b: 2, c}` valid or should it be `{a: 1, b: 2, c, ...x}`?)

**Comment by jclark** [comment]
Answers:

- yes (this is useful)
- should be allowed anywhere (order not significant for fields in mapping constructors)

**Comment by jclark** [comment]
Another interesting case is something like this:

```
type Foo record {
   string s;
};

Foo[] input;
Foo[] output;

output = from var {s, ...rest} in input select {s, ...rest };
```
The obvious type for `rest`  is `record {}`, but that type does not guarantee no field duplication between `s` and `rest` in `select {s, ...rest}`.

But actually we can do better for `rest`. We can infer the type of `rest` as:

````
record { never s?; }
```

and that does guarantee no duplication.

@MaryamZi @hasithaa @sameeerajayasoma What do you think?
