### ISSUE TITLE
Killing a worker

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#40]
It would be useful to be able to kill a worker if it's known that its results will not be used. However, given that workers can modify global state, killing a worker off at an arbitrary points might lead to global data being left in an inconsistent state.

Java threads have a non-preemptive killing mechanism (which it calls interrupt), which looks promising. The idea is that a strand would have a cancelled flag. Futures would have a builtin method cancel: f.cancel() would set the cancelled flag to true. Worker would check its cancelled flag at specific points (e.g. message send/receive and blocking IO), and would panic if the flag was set.

**Comment by jclark** [comment]
@hasithaa Does the implementation have something like this already?

**Comment by hasithaa** [comment]
Yes, @jclark Implementation has "future.cancel" [1] built-in method for said functionality. The `cancel` method flags the stand as `aborted` and BVM checks for this flag before executing a new BVM instruction. If the flag is true, the stand is taken out from the execution. 

[1] - https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/builtin/src/main/ballerina/builtin/futurelib.bal#L31

**Comment by jclark** [comment]
@hasithaa Are you planning to use java.lang.thread.Interrupt in jBallerina?

**Comment by jclark** [comment]
I think we should check at the same points that a task switch could occur with cooperative multitasking #30.

**Comment by hasithaa** [comment]
I am looping @manuranga @vinok88 , who are working on stand implementation in JBalerina. Still, we haven't fully figured it out how to implement this.

**Comment by vinok88** [comment]
@jclark  and @hasithaa , Current plan is to use  java.lang.thread.Interrupt in jBallerina for cancelling a future. We do not have a concrete play yet. The idea is to share the strand instance as the future within JVM. Then there will be a cancel method in the Strand that will call  java.lang.thread.Interrupt.

**Comment by jclark** [comment]
Great. So we definitely should have a future.cancel() built-in method with semantics similar to Thread.interrupt. We can finalize precise semantics in due course.
