### ISSUE TITLE
Type inference for mapping constructor in select clause

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#401]
We need to fix the rules for inferring the type of a mapping constructor when there is no contextually expected type, so that the type inferred for a mapping constructor in a select clause is a record type rather than a map type.

Ideally, we should do this in a general way rather than special-casing select.

This is part of #340.

**Comment by jclark** [comment]
The current design came from #143.

**Comment by jclark** [comment]
Need to consider computed field names e.g. `{ x: 1, y: 2, [fieldName]: 4 }`.

**Comment by jclark** [comment]
It seems strange that we cannot currently do `m == {}` or `a == []` to test for emptiness.

**Comment by jclark** [comment]
One approach is to have different rules for a mapping constructor in certain contexts.  Another approach is to change the rules for mapping constructors and also list constructors so that they are OK in this case also. If it can be made to work, the latter approach is simpler and easier to understand.

After discussion with @hasithaa, it looks like the latter approach is feasible.

- with no contextually expected type, infer exclusive tuple/record type that allows only the keys/indices occurring in the initializer
- type for each field is widened type of initializer (as for var)
- if a mapping has a computed field name, then it is open to the union of types of the initializers of the computed field names
- no special rule for empty list constructor, mapping constructor

So:

- `[1, 2]` gives `[int, int]`
- `{x: 1, y: 1}` gives `record {| int x; int y; |}`
- `{x: 1, y: 2, [fieldName1]: "str", [fieldName2]: true } gives `record {| int x; int y; (string|boolean)... ;|}`
- `{ }` gives `record {| |}`

Note that:

```
var x = [];
x[0] = 1;
```

will still get a compile-time error, because x will have an inferred type of tuple of length 0 and any indexing into that will be an error.

**Comment by sanjiva** [comment]
Won't
```ballerina
var x = [1];
```
be ambiguous? Or how do I get an array of length 1 with a value in it?

Also, is there now any constructor syntax for an open record? I guess I must have a contextually expected open type for that to work now? Maybe that's ok.

**Comment by sameerajayasoma** [comment]
As per these rules,  the type of `x` in `var x = [1]` will be `[int]`. No ambiguity here AFAIK

Btw, in `var x = []`, the type of `x` is the supertype of all tuples I think.
