### ISSUE TITLE
Generalize iterability to allow errors

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#402]
Recall that a value that is iterable as a sequence of values of type T can create an iterator object with a next method that returns a value of type

```
record {| T value; |}|()
```

where () indicates the end of the iteration.  We extend this to allow the end of an iteration to be indicated by an error value as well as by (). So the spec-internal abstract object type `Iterator<T>` becomes `Iterator<T,E>`. The concept of_ iterable as a sequence of values of type T_ becomes _iterable as a sequence of values of type T with error type E_.

A value that is iterable with error type never, where `never` is the type that contains no shapes (see #74), is said to be _infallibly iterable_. All value types defined as iterable in the current spec are infallibly iterable. The foreach statement works only when an iterable value is infallibly iterable. `Iterator<T>` is short for `Iterator<T,never>`.

The source type for a query-expr can be a value type iterable with any error type. If a query-expr's iteration terminates with an error value e, the result of the query-expr is e.

If an object's __iterator method returns an `Iterator<T,E>`, then it is iterable with error type E.

This is part of #340.

**Comment by jclark** [comment]
We need to find a way not to use the word "sequence" here, given the introduction of sequence types.

**Comment by grainier** [comment]
> So the spec-internal abstract object type Iterator<T> becomes Iterator<T,E>. The concept of_ iterable as a sequence of values of type T_ becomes iterable as a sequence of values of type T with error type E.

Just to clarify, do you mean, the return type of next method changes to below?; 

```ballerina
record {| T value; |}|()|E
// or
record {| T|E value; |}|()
```

**Comment by jclark** [comment]
I mean:

```ballerina
record {| T value; |}|()|E
```

**Comment by jclark** [comment]
I have chosen to explain this slightly differently in the spec: the type is `Iterable<T,R>` where R is the result of the iteration, which is a subtype of `error|()`. So the type of next() is

```
record {| T value; |}|R
```

**Comment by grainier** [comment]
Hi @jclark, can you clarify on following? Take this example; where, personStream is a stream of `stream<Person, Error>`

```ballerina
type Person record {|
   string firstName;
   string lastName;
|};

type Error record {|
    string message?;
    error cause?;
|};

type PersonItr object {
    public function next() returns Person|Error? {
        // ...
    }
};

PersonItr personItr = new();

stream<Person, Error> personStream = new(personItr);

// Foreach A
foreach Person p in personStream {
    // panic / terminate on error?
}

// Foreach B
foreach Person|Error p in personStream {
    // let user handle error
}

// Foreach C
foreach var { firstName, lastName, deptAccess} in personStream {
    // if the error should come inside the foreach, do we allow above binding?
}
```

So the question is, since personStream can result in an `Error`, or `Person` value, how are we suppose to handle that? Are we only going to pass `Person p` to the foreach block (i.e Foreach A) and panic or terminate on the event of an Error, or are we going to pass `Person|Error p` to the foreach block (i.e Foreach B)and let the user handle the Error by themselves?

If we are going to panic or terminate on an Error, what difference does it make compared to the event of a `()` and terminating the loop. And how the user suppose to capture that Error?

Or else, if we are going to pass both `Person|Error p` to the foreach block, how are we going to handle binding patterns? (i.e Foreach C).

**Comment by jclark** [comment]
First, there is a confusion in your example: the 2nd type param to stream has to be a subtype of error? (not a record as in your case).

Apart from that, these are compile-time errors. From https://ballerina.io/ballerina-spec/spec.html#section_7.20

> The static type of action-or-expr must be an iterable type with an iteration completion type of nil.

The idea is to use a query-action from/do in this case.

**Comment by jclark** [comment]
@grainier The spec now has full details on streams. Please review the relevant sections:

- https://ballerina.io/ballerina-spec/spec.html#section_5.4.7
- https://ballerina.io/ballerina-spec/spec.html#section_6.12
- https://ballerina.io/ballerina-spec/spec.html#section_6.39
- https://ballerina.io/ballerina-spec/spec.html#section_7.10

**Comment by grainier** [comment]
> First, there is a confusion in your example: the 2nd type param to stream has to be a subtype of `error?` (not a record as in your case).
> 
> Apart from that, these are compile-time errors. From https://ballerina.io/ballerina-spec/spec.html#section_7.20
> 
> > The static type of action-or-expr must be an iterable type with an iteration completion type of nil.
> 
> The idea is to use a query-action from/do in this case.

Sorry, My bad. It should've been following; So that `Error` is a subtype of `error?`

```ballerina
type ErrorData record {|
    string message?;
    error cause?;
|};
type Error error<string, ErrorData>;
```
