### ISSUE TITLE
Use variable in XML navigation syntax

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#404]
**Description:**
Is it possible to use the value of a variable in XML navigation syntax?
In `x.<ns:foo>` where ns is an xmlns decl and foo to be a variable reference? If I understand correctly, `foo` is `const foo = "foo"` in the proposal.

And also should we support `x.<"{ns.url.com}foo">` syntax where expanded element name is provided as a string literal (or maybe a variable ref as in the first question). Maybe we are deligating that to lang-lib xml functions.

**Comment by jclark** [comment]
No. We don't need this in the navigation syntax: we will use lang lib functions for this.
