### ISSUE TITLE
Handle variable and identifier shadowing

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-spec#405]
**Description:**

Under the title **Variable and identifier scoping**, it says that 

> It is not an error if an identifier is declared with block-scope and there is already a declaration of the same identifier in the same symbol space with module-scope. In this case, the block-scope declaration will hide the module-scope declaration for the region where the block-scope declaration is in scope.

```
type Person object {
    string name = "Smith";
};

public function main() {
    string Person = "Cal";
    Person p = new;
}
```
According to the above statement, inside the main function, `string Person` hide the `object type Person`. Then what should happen if we initialize an object `Person p = new;` inside the main function? IMO, the compiler should throw an error because `object type Person` cannot find.

**Comment by jclark** [comment]
I agree.

Variable names and type names are in the same symbol space. So the variable name `Person` shadows the type name `Person`. So the declaration `Person p` is an error, because `Person` refers to a variable not a type.

@hasithaa Do you have any  thoughts on this?

**Comment by hasithaa** [comment]
I think the same.  `Person p` should be an error. 

Once a symbol is shadowed, there is no way to refer it back. A mechanism to refer to the module-level like java `self` would be nice to have. Maybe we can have a predefined module alias xxx. 

type Person object {
    string name = "Smith";
};

public function main() {
    string Person = "Cal";
    xxx:Person p = new;
}

We can use `self` but we use it in objects. But usage wise, it is deferent `self:` and `self.`

**Comment by jclark** [comment]
@hasithaa That's issue #96.
