### ISSUE TITLE
Declare same identifier in module-scope 

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-spec#407]
**Description:**
Under the **Variable and identifier scoping**, it says that

> However, it is a compile error if an identifier is declared with block-scope and its scope overlaps with the scope of another declaration of the same identifier in the same symbol space also with block-scope.

According to that inside the block scope, we cannot declare two identifiers which are in same symbol space.

In the module-scope if we declare two identifiers which are in the same symbol space, what can be the expected behaviour?

For example,

```
type Person record {
    string name = "Smith";
};
const Person = "P";
```
IMO, this should be an compiler error.

**Comment by jclark** [comment]
That's a compiler error.

**Comment by KavinduZoysa** [comment]
Since this is not explicitly mentioned in the spec, it would be better if it can be mentioned in the spec.
