### ISSUE TITLE
Define the length of CodePoint

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-spec#408]
**Description:**
Under the subtitle **string** in **Values, types and variables**, it says 

> In a StringNumericEscape, CodePoint must valid Unicode code point; more precisely, it must be a hexadecimal numeral denoting an integer n where 0 <= n < 0xD800 or 0xDFFF < n <= 0x10FFFF

Also, the CodePoint is defined as follows.

> CodePoint := HexDigit+

According to that, the length of the Unicode can be less than 4. (ex: \u{0}, \u{0A}). But normally, the length of that Unicode is greater than or equal 4.

So it is possible to write the Unicodes which have the length less than 4?

**Comment by jclark** [comment]
Yes: `\u{0A}` is fine.

Same as JavaScript. See https://www.ecma-international.org/ecma-262/10.0/index.html#prod-CodePoint
