### ISSUE TITLE
Can a string-literal be used to specify a required/optional record field in a mapping-constructor-expr?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#412]
**Description:**
The spec says
"If the inherent type descriptor is a record type descriptor and a field is specified using a field-name rather than a string-literal or expression, then the record type descriptor must include that field-name as an individual-type-descriptor."

So a field-name can only be used to provide a required/optional field.

But, can a string-literal also be used to provide a required/optional field? Or, can such a field only be specified as a field-name?

```ballerina
type Foo record {
    string s;
    int i;
};

public function main() {
    Foo f = {s: "hello", "i": 1}; // is `"i"` valid?
}
```

(The implementation allows this atm)

**Comment by jclark** [comment]
The spec allows this. I think that is the consistent behavior, since we allow `f["i"]`.
