### ISSUE TITLE
Nominal typing

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#413]
Ballerina is fundamentally a structurally-typed language, but there are cases where nominal typing would be useful, both for improved error checking and for interop with other systems that use nominal typing. Examples of the latter include SQL (with distinct types) and GraphQL (the __typename feature).

At the moment we can simulate nominal typing like this:

```ballerina
const PointTypeName = "{some module}Point";

type Point record {
   PointTypeName _typeName = PointTypeName;
   float x;
   float y;
};
```

You can then say:

```ballerina
Point p = { x: 1.0, y: 2.0 };
```

and the `_typeName` field gets defaulted.

The planned functional constructor syntax combines nicely with this:

```ballerina
var p = Point(x = 1.0, y = 2.0);
```
Private fields in objects also provide a way to create the effect of nominal typing. See https://github.com/ballerina-platform/ballerina-spec/issues/43#issuecomment-487533909

This relates to a number of other things in the language:

- the error type has a reason field, which is also conventionally a module-qualified string; XML elements have a element name, which is a namespace-qualified string; we are trying to find a nice syntax for this #225, which could also be used for this
- we want better support for enumerations (see #276)
- we want support for immutable types (see #338)
- the `_typeName` field is interesting in that it has a single possible value, and that value is immutable, which means the field is effectively immutable; there are a couple of other language features that also potentially have immutable fields (for table primary keys and event stream timestamps)

**Comment by jclark** [comment]
A [message](https://groups.google.com/d/msg/ballerina-dev/nY7v506lc4o/TIW5g3sFDgAJ) to ballerina-dev specifically highlights the case of wrapping an existing simple type. One design issue is to what extent to prioritize that compared to records. My sense is that approaching the problem as a something that is layered on records is going to be a better fit for the language as a whole and for JSON/GraphQL.

**Comment by jclark** [comment]
The fundamental idea is integrating nominal types into a structural language by having some sort of named marker attached to values. I believe this is usually called brands or branded types. Modula-3 has a `BRANDED` keyword for this.

**Comment by jclark** [comment]
GraphQL __typename is here:

https://graphql.org/learn/queries/#meta-fields

**Comment by tj800x** [comment]
It would be nice to be able to have a keyword that returned the org, module, and scope at compile-time, so that the "brand" wouldn't need to be maintained.  In the C world this would be akin to the __FILE__ and __LINE__ macros, a bit like __ORG__, __MODULE__, and __SCOPE__.  __FULLSCOPE__ might combine these three.
 
That would give us this, which feels like an improvement since the record is self-contained.

type Point record {
   PointTypeName _typeName = __FULLSCOPE__;
   float x;
   float y;
};

**Comment by tj800x** [comment]
My original suggestion was for using tuples to create simple distinct types.  Essentially this allows the creation of a new "bottom" to a type hierarchy that is above the basic type.  My hope was for a the basic type to be fully encapsulated and not easily accessible.  I had envisioned the need to use casting to convert to/from the basic type (except for literals).  I still think this is the cleanest approach and worthy of some thought for simple distinct types (a two element tuple --  one value and one constant.)

```
type Name distinct string;
type City distinct string;

public function main() {

 Name name = "Thomas";
 Name nickname = "Tom";
 City city = "Washington"];
 
 name = nickname;
 
 // compile-time error : incompatible types: expected distinct City, found distinct Name'
 // name = city;
}
```
One option would be to allow the use of underscore on the RHS when destructuring a tuple, with the RHS underscore meaning "don't replace."  For a tuple with constant elements this makes sense.  Actually, for constants it wouldn't even be needed (see nickname assignment below). 
 Combining this with the __ FULLSCOPE __ macro would give us this:

```
type Name [string,_typeName=__FULLSCOPE__];
type City [string,_typeName=__FULLSCOPE__];

public function main() {

 Name name = ["Thomas", _ ];  // Slightly wonky syntax  
 Name nickname = ["Tom"];  // Better syntax
 City city = ["Washington"];
```
Having said all that, I'll be happy with whatever approach makes sense for the community as a whole.

**Comment by tj800x** [comment]
Here is a paper outlining how the authors added nominal typing capability to a structurally typed language:  https://michael.homer.nz/Publications/ECOOP2015/paper.pdf .

**Comment by sanjiva** [comment]
If we had branded types we could use the brand of an error type as the default error reason value too.

**Comment by jclark** [comment]
Flow has an interesting concept of [opaque](https://flow.org/en/docs/types/opaque-types/) types.

**Comment by sameerajayasoma** [comment]
We've been using tags/brands to overcome similar issues in our Ballerina compiler codebase.
https://github.com/ballerina-platform/ballerina-lang/blob/v1.1.0/stdlib/bir/src/main/ballerina/src/bir/bir_model.bal#L365

**Comment by jclark** [comment]
@sameerajayasoma That's an important use case. Nominal typing design ought to provide a solution that is usable for this.

**Comment by jclark** [comment]
There's now a [proposal](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/distinct/distinct.md).

**Comment by sanjiva** [comment]
James why do you say this:
```
An error error type error<R> means that the detail record must belong to the type
    readonly & record {| *R; (anydata|readonly)...; |}
In a match-statement, a error-match-pattern with a user-defined error type should match only if the shape of the value belongs to type.
```

Why can't I say error<readonly & record {| int x; |}> to create an error with a detail record that is not open? Why do we require error detail records to be open?

**Comment by jclark** [comment]
It would get very confusing with `&`.

**Comment by sameerajayasoma** [comment]
Regarding the intersection of object types. 
- If object `A` has field `f` of object type `X`  and object `B` has a field `f` of object type `Y`, what would be the type of the field `f` in `A & B` given that `X & Y` is valid?

**Comment by jclark** [comment]
Conclusions from meeting:

1. only apply intersection to abstract object types
2. only provide access to type id via typedesc and typeof
3. type id contains local id and module id consisting of organization name, module name, version
4. need to create issue on langlib versioning and how that really works, in particular as regards including nominal types defined in langlib

**Comment by jclark** [comment]
@sameerajayasoma I added an issue on function intersection types #506.

**Comment by jclark** [comment]
The error-specific parts of this will be covered in #509. This just covers the distinct type feature.

**Comment by jclark** [comment]
Changes to the spec:

- [ ] In "Behavioural types" section, say that object and error values contain type-ids
- [ ] In "Distinct types" section, explain what it means for a value to belong to a distinct type
- [ ] Explain how an error or object value gets type-ids when it is constructed (probably in Distinct types section)
- [ ] Add function to lang.typedesc to get type-ids; also needs record type for type-id
- [ ] Replace double underscore convention on built-in abstract object types by distinct types
- [ ] Change `__init` to `init` for objects and modules

**Comment by jclark** [comment]
Semantics explained in commit 2baf5ae2599037b28577995db9177813f474bf3c

**Comment by jclark** [comment]
Decided today _not_ to require value:toString's use of toString on objects to require distinct type.
