### ISSUE TITLE
XML navigation: select all descendants syntax

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#414]
**Description:**
In XML proposal https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md#proposed-syntaxsemantics do we support following syntax?
`x/**/<ns:foo|ns:bar>`

If we do, is it like a depth-first search until we find `ns:foo` or `ns:bar` and if we do find such sub-tree then we select it and go on search other sub-trees.

**Comment by jclark** [comment]
We should support this. Semantics are the same as `x//(ns:foo|ns:bar)` in XPath. It returns all descendant elements with the specified name in document order. So if you find ns:foo or ns:bar, you include it and also search within it. Typical example would be something like `doc/**/section/title`: in a document with nested sections if would give you all the section titles in the right order.
