### ISSUE TITLE
How to define filler value for record type and tuple type ?

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-spec#420]
**Description:**
How to define the filler value for record type and tuple type?

**Comment by jclark** [comment]
This is covered by the entries in the table at https://ballerina.io/spec/lang/2019R3/#FillMember for mapping type descriptor (which is either a map type descriptor or a record type descriptor) and list type descriptor (which is either an array type descriptor or a tuple type descriptor).
