### ISSUE TITLE
Use E.att for attribute access in XML

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#422]
See

https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md#attribute-access

**Comment by jclark** [comment]
E.att is allowed when E is a subtype of xml. The type of the result is string|error. The semantics are similar to JSON lax static typing.

1. Evaluate E resulting in value v.
2. If v is not an xml element, then the result is an error
3. If v does not have an attribute att, then the result is an error.
4. Otherwise, the result is a string.

**Comment by jclark** [comment]
Also need to make `e.xml:space` work.

**Comment by rdhananjaya** [comment]
This syntax is supported. (`e.'xml:space`)

Should there be a special semantic for `xml:space` like it should by default defined to be "default" or something? 

When we use it with an xml literal (which was declared without explicitly declaring xml:space attribute) it returns an error saying attribute is not found, is this semantic correct?

**Comment by jclark** [comment]
There's seems to be some confusion here.

`'xml:space` is not any different from `xml:space`. See

https://ballerina.io/spec/lang/2019R3/#QuotedIdentifier

QuotedIdentifier does not allow `:` unless preceded by `\`.

If you say

```
xml`<doc xml:space="preserve"/>`
```

the attributes map in the xml value in Ballerina will have a member whose key is the string

```
"{http://www.w3.org/XML/1998/namespace}space"
```

The way `e.foo:bar` works is:

- if foo is a namespace prefix bound to U, then this looks up an attribute named `{U}bar`
- if foo is a module prefix, then module `foo` must define a const string `bar`, and it looks up an attribute A, where A is the value of `foo:bar`

In the case of `xml:space`, the xml module defines

```
public const string space = "{http://www.w3.org/XML/1998/namespace}space";
```

So `e.xml:space` will look up an atribute `{http://www.w3.org/XML/1998/namespace}space`, which will match what you get when you use an attribute of `xml:space` in a doc.

**Comment by rdhananjaya** [comment]
`'xml` is because of a technical limitation in the parser. (xml and `:` both are tokens)

```ballerina
xml x = xml`<doc xml:space="preserve"/>`;
xml|error val = x.xml:space; // val will containt "preserve"
```

In the spec
```
xml-attribute-access-expr := xml-required-attribute-access-expr | xml-optional-attribute-access-expr
xml-required-attribute-access-expr := expression . xml-qualified-name
xml-optional-attribute-access-expr := expression ?. xml-qualified-name
xml-qualified-name := xml-namespace-prefix : identifier 

The xml-namespace-prefix must be declared using an xmlns-decl-stmt. 
```

Taking the above paragraph what we did was to pre-define an xml namespace declaration for `xml` prefix using namespace URI `http://www.w3.org/XML/1998/namespace`.

**Comment by jclark** [comment]
It doesn't work to pre-define an xml namespace declaration for the xml prefix, because xml namespace prefixes and module prefixes are in the same symbol space, and xml is defined as a module prefix.

As I said in https://github.com/ballerina-platform/ballerina-spec/issues/166#issuecomment-596925462, the spec doesn't yet cover how e.xml:space works. (I am writing it now.)
