### ISSUE TITLE
Should documentation of record fields also be copied when a record is referenced?

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-spec#423]
There's an issue raised regarding the documentation of referenced types: https://github.com/ballerina-platform/ballerina-lang/issues/21082

There are 3 approaches we can consider in documenting fields coming from a referenced record:
1) Let the user writing the referencing type document the fields of the referenced type(s) as well (currently, this is not allowed).

2) List the referenced types in the generated documentation of the referencing type and link them to the relevant doc pages of the referenced types.

3) Copy the documentation of the fields as well when copying the fields from the referenced types (currently we only copy the fields themselves).

With the first approach, the generated doc will show the referenced fields just like it would show a regular field. But IMO, this will defeat the purpose of referencing a type, since we refer a type because we don't want to manually define each of those fields again. I think the same holds true for documentation.

With the second approach, we don't have to change anything in the compiler side. The doc generation tool will have to be modified to include links to the referenced types. The downside to this (if this can be considered one) is that we make a clear distinction between the regular fields and the referenced fields. 

If we take the third approach, we can avoid the shortcomings in both (1) and (2). However, the spec doesn't say anything about copying documentation of the referenced types. 

Which of the above approaches (or another alternative) would be appropriate to resolve the above mentioned issue (21082)?

**Comment by jclark** [comment]
The documentation for fields should be on the fields not on the record, as with object fields. See #299.

If you do this, then the documentation of the field is part of the field metadata and will thus copied along with the field. (It would also be good for the documentation to include an indication that the field was copied from a particular type.)

In the meantime, I would just list the copied fields in the referencing type and say "copied from T" with a link to T.
