### ISSUE TITLE
Allow initializing module-var-decls inside the __init function

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#424]
As per the spec, the initializer is mandatory for module-var-decls. Can we relax this and allow the initialization inside the `__init` function.
```
module-var-decl :=
   metadata
   [final]
   typed-binding-pattern = expression ;
```

I think we can statically check whether a given module-var-decl is initialized or not. We perform similar analyses in the following situations. 
- local-var-decls with no initializers. The compiler checks whether the variable is initialized before the first read.
- object fields with no initializers. The compiler checks whether the field is initialized inside the object's __init() function.

**Comment by jclark** [comment]
I think this is a good change.

However, we do need to be careful that we do not inadvertently make it possible to access uninitialized variables.  Since we do not allow cycles in the module dependency graph, a module imported by module X cannot call a public function of module X, so we only need to worry about access from functions called from within the module. In any case, we already have a similar problem when initializers call module-level functions.

**Comment by KavinduZoysa** [comment]
With the above change, is below program valid? In this program, the parameter 'a' is initialized inside 'foo()'. But function 'foo()' is called by the module init.

```
import ballerina/io;

int a;
int b;

function __init() {
    b = 2 + foo();
}

public function foo() returns int {
    a = 48; // 'a' is initialized here and 'foo()' is called by '__init()'
    return a;
}

public function main() {
    io:println(b);
}
```

**Comment by hasithaa** [comment]
@KavinduZoysa , Dataflow analyzer can detect this. Technically we can support this. 

But I think to make the code look simple and improve the readability, better to restrict this to `__init` method.

**Comment by jclark** [comment]
There's a similar situation with __init on objects:

https://ballerina.io/spec/lang/2020R1/#section_5.4.2.5

Module __init should be similarly restricted: i.e. __init of module m should not call a function of module m while there are still potentially uninitialized variables.

**Comment by sameerajayasoma** [comment]
I think this is an unnecessary restriction. We can detect cycle in the static analysis phase.  See how go lang handles this. https://golang.org/ref/spec#Package_initialization

**Comment by jclark** [comment]
@sameerajayasoma What is an unnecessary restriction?

**Comment by sameerajayasoma** [comment]
As per the following restriction, this code example will not compile.
```
Module __init should be similarly restricted: i.e., __init of module m should not call a function of module m while there are still potentially uninitialized variables.
```
```
int a;
int b;

function __init() {
    a = initializeA(); // compilation error as per the restriction
    b = initializeB(a);
}
```

The static analyzer can detect uninitialized variable access. Therefore such a restriction is unnecessary IMO.

**Comment by jclark** [comment]
Can we relax the object restriction in a similar way?

**Comment by sameerajayasoma** [comment]
We need to come up with rules to verify the definite assignment for the following cases:
- Module-level variables with no initializer
- Object fields with no initializer
- Local variables for no initializers

At the moment spec says the following about local variables:
`A local variable declared local-no-init-var-decl-stmt must be definitely assigned at each point that the variable is referenced. This means that the compiler must be able to verify that the local variable will have been assigned before that point. If final is specified, then the variable must not be assigned more than once.`

To relax the restrictions discussed in earlier threads, we need these definite assignment rules. I will try to define those rules for the module-level variables first.

**Comment by sameerajayasoma** [comment]
Btw, there are situations where we cannot figure out the order of module-level variable initialization. Consider the following case. 

```
Person p = <Employee> {};
int a = getId(p);
int b = a;

function getId(Person p) returns int {
    return p.id;
} 

type Person record {
    int id;
    string name;
};

type Employee record {
    int id = b;
    string name = "Default";
};

public function main() {
    io:println(b); // Current compiler output is 0
}
```

**Comment by jclark** [comment]
It seems to me you have a dependency cycle there. Using `=>` for depends on, we have

p => Employee default closure => b => a => p

So shouldn't that be a compile-time error?

**Comment by sameerajayasoma** [comment]
Can we determine the relationship `p=> Employee default closure` every time? 

```
Person p = createPerson();
```

**Comment by jclark** [comment]
The dependency then would be

p => createPerson => Employee default closure => b => a => p
