### ISSUE TITLE
How to deal with case insensitivity e.g. in SQL?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#425]
SQL regular identifiers are case insensitive, whereas SQL delimited identifiers (in double quotes) are case sensitive. SQL implementations appear not to be case preserving and fold case insensitive identifiers. Most implementations fold to upper case, but some (e.g. PostgreSQL) fold to lower case. JDBC provides a `ResultSetMetaData.isCaseSensitive(int column)` to test this.

This complicates our solution to data binding. The original idea would be that the type of the Ballerina record representing the row would be inferred from the SQL type, and then cast to the Ballerina type. But if we represent the SQL type by a normal SQL record with the fields of names folded to upper or lower case, we cannot then _cast_ it to a type where the field names have another case, because the target type will not be a subtype of the source type.

For example, if we have a database with FirstName, LastName columns that get folded to FIRSTNAME, LASTNAME. Then the record type inferred from the schema will be

```ballerina
record {|
  string FIRSTNAME;
  string LASTNAME;
|};
```

We cannot then cast that to

```ballerina
record {|
  string firstName;
  string lastName;
|};
```

because, as far as Ballerina is concerned, this is a completely different type. Furthermore, there is no way to convert a value:

```ballerina
{ FIRSTNAME: "James", LASTNAME: "Clark" }
```
to

```ballerina
{ firstName: "James", lastName: "Clark" }
```

**Comment by jclark** [comment]
The only solution I see to this is to give the desired Ballerina type to the query method as as parameter of type typedesc; the query method can then use this typedesc in conjunction with the ResultSetMetaData to do the right conversion. Specifically, a case-insensitive column-name can be mapped onto any record field whose name is case-insensitively equal.

**Comment by sameerajayasoma** [comment]
One possible approach would be to define an annotation in the ballerina/sql module to specify the corresponding column name. 
```ballerina
record {|
  @sql:column("FIRSTNAME")
  string firstName;
  @sql:column("FIRSTNAME")
  string lastName;
|};
```
But then users will have to use this annotation most of the time.  So I also think that the query method performing an implicit conversion is a good idea, as James suggested in the above comment.

**Comment by jclark** [comment]
Passing the typedesc to the query can be made to work well. See #426. That can make use of annotations if we want.
