### ISSUE TITLE
Add query clause for sorting

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#438]
Sketch of design

```
order-by-clause := "order" "by" order-key ("," order-key)*
order-key = expression [order-direction]
order-direction := "ascending" | "descending"
```

An order-by-clause is executed as follows:

*   create an empty list s
*   for each input frame f
    *   evaluate each order-key expression with f in scope to produce a sequence of ordering keys 
    *   add an entry to s with the ordering keys and f
*   sort the list s using the ordering keys and the order direction
*   for each entry of the list
    *   emit the entry's frame

The static type of the expressions in the order by clause must be ordered, where the following rules determine whether a type is ordered:

*   a subtype of a simple basic type is ordered
    *   strings are ordered as with codePointCompare
    *   numbers are ordered by <
        *   -0.0f is before +0.0f
        *   need to say how NaN is handled (IEEE has a totalOrder function)
    *   false comes before true
*   if T is ordered, T? is ordered; nil comes first
*   if T is ordered, T[] is ordered; ordering is lexicographic

Open points:

*   need to be able conveniently to do proper i18n-aware string ordering (see [Unicode TR10](http://www.unicode.org/reports/tr10/)), without building this into the language; should not force dependency on huge Unicode tables
*   Probably should extend language relational operators (<, >, <=, >=) to be consistent with this (but what about NaN?)
*   How does ordering interact with grouping?

**Comment by lasinicl** [comment]
@jclark 
How does `order by` clause going to work for streams? Are we going to consume the input stream, create a list, sort it, and then create an output stream?

```
stream<Person> personStream = from var person in personList.toStream()
                             order by person.id
                             select {
                                 id: person.id,
                                 name: person.name
                           };
```

**Comment by jclark** [comment]
For unbounded streams (which we are probably not doing for Swan Lake), we will need either to have a window within which the sorting happens or disallow sorting.

For bounded streams (which is what we have at the moment), it will, as you suggest, need to consume the whole input stream, sort it, and then emit a sorted stream.

This is the same situation as with the join clause.

**Comment by lasinicl** [comment]
Can there be `order keys` which do not belong to a basic type(i.e.nil, boolean, int, float, decimal)? For an example can a user provide a `record` type field as the order key?
Consider the following.
```
type Person record {|
   string firstName;
   string lastName;
   Address address;
|};

type Address record {|
   int unitNo;
   string street;
|};

Person[] outputList =  from var person in personList
                  order by address descending
                  select person;
```
Should we allow a user to order a list of `Person` using `address`? If so, what/how fields in `Address` be considered when sorting?
Can a user order using a field which is of `union` type?

**Comment by jclark** [comment]
We need to provide a way for the user to control sorting. The old-fashioned way to do this is with a comparison function, but a better approach is a key function, as in Python 3: https://docs.python.org/3/howto/sorting.html#key-functions

e.g. assuming #107 you could write

```
Person[] outputList =  from var person in personList
                  order by address descending
                  key {unitNo, street} => [unitNo, street]
                  select person;
```
Then there should be a library function to generate a sort key using the Unicode Collation Algorithm: https://unicode.org/reports/tr10/#Default_Unicode_Collation_Element_Table

**Comment by jclark** [comment]
Thinking about it some more, I don't think we need a separate key function: we can use the expression in the order-key to express the function:

```
Person[] outputList =  from var person in personList
                  order by address.unitNo, address.street.toLowerAscii()
                  select person;
```

The above would be sort the street case-insenstively for ASCII.

For a Unicode-aware sort you would do something like `myLocale.sortKey(address.street)` where `myLocale` would be an object representing the locale. You would use a Unicode standard library module to create the locale using a locale identifier e.g. `unicode:getLocale("en_US")` The application would choose the locale identifier from IP-based geolocation or Accept-Language HTTP header or user account.

The type ordering rules for lists should be improved a bit too:

- if T, T1, T2,...Tn, are ordered, then [T1, T2, ..., Tn, T`...`] is ordered; either T or the Ti can be missing

So for example: `[int, string]` is ordered (since `int` and `string` are both ordered.

**Comment by jclark** [comment]
We need to say how NaN sorts when the type is float. The IEEE754 totalOrder function doesn't help, because it relies on NaNs having signs, whereas we (following most other programming languages) do not distinguish different kinds of NaN. 

Our treatment of NaN should also be consistent with nil. In a type `string?`, `()` is playing a similar role to `NaN` in a type of `float`.

I also think it would make for a more consistent experience if the relational operators (`< <= > >=`) behaved consistently with `order by`.

Let's make this concrete. Suppose we have four values: `( ), NaN, 1, 2`. What should be the sort order with `ascending` and with `descending`?

With `ascending`, I think the order should be:

- 1
- 2
- NaN
- ( )

In other words:

- in type `T?`, T sorts before nil (this is different from what I proposed above)
- in type float, any floating-point number (i.e. any value other than NaN) sorts before NaN

This is what the ECMAScript sort function does, and I think it's the most useful behaviour. Consider in particular using the `order by` clause in conjunction with the `limit` clause, for example, get the top ten most expensive products. In this kind of case, it's more useful to have undefined/missing values come last rather than first.

Now consider `descending`. At first, it might seem that you want `descending` to be the opposite of `ascending`. But this has two problems:

- it's not consistent with how the relational operators handle `NaN`; the relational operators treat NaN as not ordered with respect to floating point numbers so both `NaN <= 1.0` and `NaN >= 1.0` are false (consistent with IEEE 754 and most/all programming languages)
- I might use the `order by` clause with the `limit` clause to get, for example, the top ten cheapest products; in this case, I want the undefined/missing values to come last not first even though I am using `descending`

I believe then that in descending order the example should sort as

- 2
- 1
- NaN
- ( )

This means the model for `order by` should be that
- we distinguish values that are not ordered
- `order by` will put the values that it cannot order last
- ascending/descending applies to values that can be ordered

**Comment by lasinicl** [comment]
@jclark 
```
Person[] outputList =  from var person in personList
                       order by address 
                       select person;
```
As given in the above example if a user provides a complex type `order key`, which in this case is `address`, should a compilation error be given?

**Comment by jclark** [comment]
Yes: the static type of the expression in "order by" must be an ordered type.

**Comment by jclark** [comment]
Should also have `array:sort` function with arguments with key function and direction ascending/descending.

**Comment by jclark** [comment]
I’ve realized that handling NaN/() is complicated by the fact that they can occur inside tuples. But some some tuples containing NaN are ordered with respect to other tuples, e.g.

```
[1.0, NaN] < [2.0, 0.0]
```
So you cannot approach the problem simply as having some values in an ordered type being not part of the order.

**Comment by jclark** [comment]
I've moved the addition of the `array:sort` function into a separate issue #572.
