### ISSUE TITLE
Is variable shadowing allowed for let variable declarations?

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-spec#439]
**Description:**
Should the following code snippets produce a compilation error for redeclaring variable `x` ?

```ballerina 
function test1() {
        int x = 5;
        int b = let int x = 4 in 2*x;
}
```

```ballerina
//global scope

int k = let int x = 1, int y = 4 in x + y;

function test 2() {
        int x = 5;
}
```

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
First is an error, since local declaration cannot shadow local declarations.

Second is fine, since the x declared with let is not in scope in the function, so there is no shadowing.
