### ISSUE TITLE
Allow `mapping-constructor-expr` to be optional in annotations

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#447]
As per the spec, the type of the annotation tag must be a subtype of one of the following three types: `true`, `map<anydata>`, `map<anydata>[]`. If the type-descriptor is omitted, then the type is `true`.

If the type`T` of the annotation tag is a subtype of `map<anydata>`  and if `{}` is a valid constructor for `T`, then make the `mapping-constructor-expr` optional for that annotation. 

In the following case, the constructor `{}` is a valid constructor for the deprecated annotation. Can we make this `{}` optional in this case?
```
@deprecated {}
function add(int x, int y) returns int { return x +y;}
```

```
@deprecated
function add(int x, int y) returns int { return x +y;}
```

**Comment by jclark** [comment]
I agree it's inconvenient to require the `{}`, but I don't think it's consistent with the rest of the language to automatically interpret missing constructor as equivalent to `{}`.

I can see two approaches to help here:
- allow the type to be a union of true and `map<anydata>`; bare annotation consistently means `true`
- allow default to be specified in `annotation-decl`

**Comment by jclark** [comment]
I find it a bit strange that we didn't decide to make missing annotation argument equivalent to `()`. Maybe because `()` seems falsish?

**Comment by jclark** [comment]
We might need this for #457.

**Comment by jclark** [comment]
Given our approach to included record parameters #578, treating a missing constructor as equivalent to '{ }' seems OK to me.

I still wonder whether we shouldn't treat annotation with no argument as having value of `()`.

**Comment by jclark** [comment]
Conclusion from discussion today is that annotation:

- annotation with no argument should be equivalent to `()` rather than `true` and
- type of annotation value should be able to be mapping or nil (or list of them)

**Comment by sanjiva** [comment]
Thinking out loud - why would we not just say type is anydata instead of map<anydata>|anydata[]|()?

**Comment by jclark** [comment]
The type corresponds what you can write with the annotation syntax (arrays come from multiple annotations with the same tag). See https://ballerina.io/spec/lang/master/#section_9.1 

The current restriction is:

> The type must be a subtype of one of the following three types: `true`, `map<value:Cloneable>`, `map<value:Cloneable>[]`.

With this issue, the types would change to: `()`, `map<value:Cloneable>?`, `map<value:Cloneable>?[]`.

**Comment by MaryamZi** [comment]
With this change, would the value returned by annotation access change to indicate the absence of the annotation (similar to iterator `next` maybe)?

Currently, annotation access returning `()` indicates the absence of the annotation.

```ballerina
import ballerina/io;

const TRUE = true;

annotation test on function;

function func() {
}

@test
function testFunc() {
}

public function main() {
    TRUE? v1 = (typeof func).@test;
    io:println(v1 is TRUE); // currently `false`

    TRUE? v2 = (typeof testFunc).@test;
    io:println(v2 is TRUE); // currently `true`
}
```

But with this change the value itself can be `()`, so with the current definition of how annotation access works, we would not be able to distinguish between the value being `()` and the absence of the annotation?

**Comment by jclark** [comment]
@MaryamZi Good catch. I had forgotten about that. I think that's a good reason to stick with `true` for this.

This would mean the types change to:  `true`, `map<value:Cloneable>|true`, `(map<value:Cloneable>|true)[]`.

**Comment by jclark** [comment]
Conclusion is to treat no curly braces following an annotation as equivalent to `{}`, if the annotation type requires a map.
