### ISSUE TITLE
Allow spread operator with mapping value in function call

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#455]
For consistency, we should also make `...` work with a mapping value in a function call. I guess that's doable with a closed record type.

_Originally posted by @jclark in https://github.com/ballerina-platform/ballerina-spec/issues/399#issuecomment-577515940_

**Comment by jclark** [comment]
This goes with #577, #578.

**Comment by jclark** [comment]
The semantics are that `...m` where m is a mapping is the same as supplying each member of the mapping as a named argument. It is a compile-time error if any such named argument might be invalid.

**Comment by chiranSachintha** [comment]
```ballerina
type Foo record {|
    int c = 10;
    int d?;
|};
function value(int a, int b, int c, int d = 1) {
}

public function main() {
    Foo f = {
    };
    value(10, 10, ...f);
}
```
Is this a valid program? Can we define optional fields within a closed record type relate to this scenario?

**Comment by jclark** [comment]
@chiranSachintha Is there some reason that should not be valid? It is OK with the semantics in https://github.com/ballerina-platform/ballerina-spec/issues/455#issuecomment-674334299 as far as I can see.

**Comment by chiranSachintha** [comment]
> @chiranSachintha Is there some reason that should not be valid? It is OK with the semantics in [#455 (comment)](https://github.com/ballerina-platform/ballerina-spec/issues/455#issuecomment-674334299) as far as I can see.

According to the semantics in  #455 (comment) it's fine but if there are optional fields within a closed record, We want to check on the expression whether the optional fields of the closed record are initialized or not. 
When considering the below example I feel that we can't depend on the expression.

```ballerina
function func(Foo f) {
     value(10, 10, ...f);
}
```

**Comment by jclark** [comment]
@chiranSachintha In that example, the compiler would have to generate code that

1. tested whether f had a d field,
2. if it does, then the d parameter comes from that field
3. if it doesn't, then the d parameter would be defaulted

**Comment by chiranSachintha** [comment]
@jclark  For further clarification, With the mentioned example in https://github.com/ballerina-platform/ballerina-spec/issues/455#issuecomment-735047553 `f` has an `optional` field as `d`. But in this instance not surely know whether `d` is initialized or not(without a value for `f`). We can call `func` function as the below examples. 
Example 1.
```ballerina
public function main() {
    Foo f = {
    };
    func(f);
}
```
In here `d` parameter comes from default values. (It is similar to the third point in https://github.com/ballerina-platform/ballerina-spec/issues/455#issuecomment-735106934)

Example 2.
```ballerina
public function main() {
    Foo f = {
        d: 10
    };
    func(f);
}
```
In here `d` parameter comes from a field in `f` values. (It is similar to the second point in https://github.com/ballerina-platform/ballerina-spec/issues/455#issuecomment-735106934)

According to the above instances, we don't know whether the `d` comes from default value or field of `f` value before call the `func` function. Isn't it a problem?

**Comment by jclark** [comment]
@chiranSachintha I'm not seeing the problem. The compiler just generates code that handles both cases as described in https://github.com/ballerina-platform/ballerina-spec/issues/455#issuecomment-735106934.

**Comment by jclark** [comment]
The case that would be an error is:

```
type Foo record {|
    int c = 10;
    int d?;
|};
function value(int a, int b, int c, int d) {
}

public function main() {
    Foo f = {
    };
    value(10, 10, ...f);
}
```

In this case, since the `d` parameter has no default, there is the possibility that the conversion into named arguments (which conceptually happens at runtime) would result in an call that does not match the function's type.

**Comment by jclark** [comment]
I clarified the semantics in https://github.com/ballerina-platform/ballerina-spec/issues/455#issuecomment-674334299 to make things clearer.
