### ISSUE TITLE
Clarification on signed right shift

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#458]
**Description:**
The spec says ">> performs a signed right shift; the bits shifted in on the left are the same as the most significant bit".

So, irrespective of whether the relevant type is signed or unsigned, we would use the most significant bit to shift on the left? 

Going by this,

**Case 1**

```ballerina
'int:Signed8 a = -1;
int x = a >> 2;
```
Is `-1` the correct result for `x`? (`1111 1111` shifted by 2, resulting in `1111 1111` again).

**Case 2**

Similarly for
```ballerina
'int:Unsigned8 a = 255;
int x = a >> 2;
```
is `255` the correct result for `x`? (`1111 1111` shifted by 2, resulting in `1111 1111` again).

Just for clarification, since some languages such as C, C++ seem to be handling right shift differently for signed vs unsigned types (Case 2 would result in 63 (`0011 1111`) instead).

Reference: https://docs.microsoft.com/en-us/cpp/cpp/left-shift-and-right-shift-operators-input-and-output?view=vs-2019#right-shifts.

**Comment by jclark** [comment]
int:(Un)signed8 is a subtype of int, not a distinct basic type. It's not at all the same as int and unsigned in C where these are distinct types (or short/int in Java).

The value that you get from an arithmetic operation depends only on the basic type of the operand: the arithmetic operations (including left shift) are operations on 64-bit ints.  The value always (conceptually) has 64 bits, and the most significant bit means the most significant of those bits. The most significant bit of 255 is 0 not 1.

So the answer to your question is no and no. The correct answer for x in case 1 and case 2 is 255 >> 2, which is 63.

**Comment by jclark** [comment]
It might help to think like this. If x == y, then (x OP z) == (y OP z).

**Comment by MaryamZi** [comment]
Got it, thank you. 

I assume the behaviour would be similar for bitwise (and/or/xor) operations too - based on 64 bits?

For example,
```ballerina
    'int:Signed8 a = 1;
    'int:Signed16 b = -128;

    int x = a | b;
```

`x` would be the result of bitwise-or for

`0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0001`

and

`0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 1000 0000 0000 0000`

**Comment by jclark** [comment]
Your 2nd bit pattern is the bit pattern of 1 << 15, which is 32768.

The bit pattern of -128 is the bit pattern of -128 in 64-bit two's complement form, which is

```
1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1000 0000
```

**Comment by MaryamZi** [comment]
But then, for "Case 1" in my original issue, the bit pattern for `a` where `a` is 

`'int:Signed8 a = -1;` would be 

`1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111` right?

So `a >> 2` would still be -1?

**Comment by jclark** [comment]
Sorry, I didn't read your "Case 1" carefully enough. Yes, you're right. You take:

```
1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111
```

do a signed right shift by 2 on it, which gives you:

```
1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111 1111
```

again.

**Comment by MaryamZi** [comment]
Thank you, all clear now.
