### ISSUE TITLE
Distinguish graceful and immediate shutdown in Listener interface

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#46]
Should listener interface be changed to support both graceful shutdown and immediate shutdown, and, if so, how?

**Comment by sanjiva** [comment]
Yes we need to do this - we had a discussion about this a while ago (stop() vs. shutdown()) but I can't find the thread to put a link.

**Comment by jclark** [comment]
Two possibilities

- halt and shutdown
- immediateStop and gracefulStop

**Comment by jclark** [comment]
I wonder how immediate stop works: if it calls worker.cancel(), then that's asynchronous; if it does something in Java which is more drastic, then global state will be potentially corrupted.

**Comment by jclark** [comment]
@sanjiva Can we settle on gracefulStop/immediateStop on the basis that those names are the least susceptible to misunderstanding?

@hasithaa Can you comment on whether synchronous semantics is workable for immediateStop given worker.cancel semantics?

**Comment by jclark** [comment]
We will go with gracefulStop/immediateStop and be silent on synchronous/asynchronous for now.
