### ISSUE TITLE
Method-call-expr is not allowed in a field-access-lvexpr

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-spec#466]
**Description:**

Regarding the section https://ballerina.io/ballerina-spec/spec.html#field-access-lvexpr

```
field-access-lvexpr := lvexpr . field-name

lvexpr :=
   variable-reference-lvexpr
   | field-access-lvexpr
   | member-access-lvexpr
```
Seems the spec doesn't allow to have a `method-call-expr` in a `field-access-lvexpr`. But it is allowed in `member-access-lvexpr`. See the below example:

   
**Code sample that shows issue:**
```ballerina
function foo() {
    Person p = new();
    map<string> m = {};

    p.getAddress().city = "Colombo";    // not allowed

    m[p.getAddress().city] = "SL";  // allowed
}

type Person object {
    string name = "";
    Address adrs = {};
   
    function getAddress() returns Address {
        return self.adrs;
    }

};

type Address record {
    string city = "";
    string country = "";
};
```

Wonder why the spec enforces such a restriction?

**Comment by jclark** [comment]
Short answer is because lvalues aren't values.  If you work through https://ballerina.io/spec/lang/2020R1/#section_7.15.1 in detail, it should become apparent why this doesn't work. This isn't allowed in Java either IIRC.

**Comment by SupunS** [comment]
I think I still haven't got hold of it.

I was thinking, in the same above example, wouldn't
```ballerina
p.getAddress().city = "Colombo";
```
be same as below one?
```ballerina
var tmp = p.getAddress();
tmp.city = "Colombo";   // this is allowed
```
Both are referring to the same storage location which is the member `city` of `p.adrs`. Wouldn't this be falling under the 3rd-bullet-point of the section https://ballerina.io/spec/lang/2020R1/#section_7.15.1?

In java, this is actually allowed.

**Comment by jclark** [comment]
Look at step 2 of the evaluation semantics for field-access-lvexpr: "perform a filling-read operation on lv".
