### ISSUE TITLE
Clarification for defining filler value for union

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-spec#468]
**Description:**
Section 5.7.1 FillMember defines one scenario for **union** to have a filler value as below.
> if all members of the union belong to a single simple basic type B, and the filler value for B also belongs to the union

Need clarification on **single basic type** here.
Lets consider below examples.
#### Case 1:
```Ballerina
const FOO = 0;
type Bar FOO|1;
public function main() {
    Bar[2] x = [];
}
```

Here `Bar` is a union of singletons. Can we argue that Bar is also a basic type of `int` and filler value `zero` also belong to `Bar`? Therefore `Bar` has the filler value `0`.

#### Case 2:
```Ballerina
const FOO = "foo";
const BAR = "bar";
type FooBar FOO|BAR;
public function main() {
    (map<FooBar>|map<string>)[2] x = [];
}
```

Here `x` is a union of single structured basic type `map`. Filler value for mapping type descriptor is `{}`. Can we also argue that `x` does not have a filler value? Because even though the map is the basic type to properly define the map, the type of value should also be considered. Here we have two types of values `union of singleton` and `string`.

**Suggested Labels:**
spec/cosmetic
spec/unclear

**Comment by jclark** [comment]
I don't understand which bit is unclear.

Basic type is defined here: https://ballerina.io/spec/lang/2020R1/#values_types

Single means that there must be single basic type to which all members of the union belong.

In your case 1, there is a single basic type, namely `int`, to which all members of the union belong (i.e. the singleton types FOO and 1 are both subtypes of `int`).

The filler value for `int` is 0 and 0 belongs to FooBar.  What is the issue?

For case 2, there's an issue with what the inherent type of the empty mapping filler values should be. I would be inclined to say there is no filler value on the basis that:

```
map<FooBar>|map<String> u = {};
```

isn't allowed.

**Comment by KRVPerera** [comment]
The problem with case 1 is how it relates to case 2. We can try to apply the case 1 explanation to case 2. In case 2 basic type of `FooBar` is `string`. Therefore what prevents us from thinking that both `map<FooBar>` and `map<string>` can have a single type `map<string>`.

**Comment by jclark** [comment]
The basic type of both `map<FooBar>` and `map<string>` is mapping.

**Comment by KRVPerera** [comment]
It is clear now. Thank you.
