### ISSUE TITLE
Langlib behavior on unions

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#472]
**Description:**
Should we allow langlib method invocation on unions of the same basic type, such as `int[]|float[]`?
Allowing this for modifying operations may lead to inherent type violation errors and will panic. 

Original discussion: https://ballerina-platform.slack.com/archives/CAXS256RX/p1585731990078300
**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
The spec clearly does not allow this:

https://ballerina.io/spec/lang/2020R1/#section_6.20

If you want to allow this, please make a clear issue proposing a change.

Please include the relevant code in the issue, rather than linking to slack.

**Comment by rdhananjaya** [comment]
My original understanding was that it's not allowed. But as that particular slack discussion indicates, we (the dev team) have different opinions about allowing it and disallowing it. Now after reading section 6.20 I feel that this should be allowed. So my understanding of subtyping is wrong. Please help clear it.

```ballerina
    int[] a = [];
    int[]|string[] b = a;
    b.push("string"); // error
```
Under section 6.20 it says `If the static type of expression is a subtype of some basic type with identifier B, and the module lang.B contains a function method-name then M is B. The identifier for a basic type is the reserved identifier used in type descriptors for subtypes of that basic type, as listed in the Lang library section.`

Here is how I reasoned about it.
Let's consider `b`.
- The static type of `b` is `int[]|string[]`.
- According to https://github.com/ballerina-platform/ballerina-spec/issues/468#issuecomment-605431607, the basic type of `b` is array/list.
- `int[]|string[]` is a subtype of list basic type.
- `lang.array` does contain a method named `push`.
Hence `push` should be allowed on `b`.

**Comment by jclark** [comment]
Sorry, I didn't read your question carefully enough.

Yes, you are right. If it's one basic type, then it is fine.

Static types in Ballerina only guarantee that reads will be type safe; mutations of structural values can always cause a panic at wrong time.

For example:

```
int[] a = []; 
(int|string)[] b = a; // ok: subtype
b[0] = "string"; // runtime panic because it violates inherent type
```

Does that answer your question?

**Comment by rdhananjaya** [comment]
Just to make sure the example given is correct right?
```ballerina
    int[] a = [];
    int[]|string[] b = a;
    b.push("string"); // compiles fine, panic at runtime.
```

**Comment by jclark** [comment]
Right: `int[]|string[]` is a subtype of `(int|string)[]`, so it will call `array:push` with `Type` bound to `int|string` i.e.

```
function push((int|string)[], (int|string)...) returns ()
```

**Comment by rdhananjaya** [comment]
All cleared, thank you.
