### ISSUE TITLE
Clarification regarding `.shift()` on a tuple with a rest-descriptor

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#474]
**Description:**
The spec says the following for `.shift()`.

```
// Queue-like methods (JavaScript, Perl, shell)
// panic on fixed-length array
// compile-time error if known to be fixed-length

# Removes and returns first member of an array.
# The array must not be empty.
#
# + arr - the array
# + return - the value that was the first member of the array
public function shift(Type[] arr) returns Type = external;
```

It is clear that the following should be disallowed, since the tuple is of a fixed length.
```ballerina
    [int, int] a = [1, 2];
    int x = a.shift();
```

My question is regarding allowing `.shift()` on a tuple with a rest-descriptor.

**Case I**

At compile-time, should we disallow the following also, even though the list itself does not have a fixed length?
```ballerina
    [int, string...] a = [1, "hello", "world"];
    int x = a.shift(); // if the first member is removed it violates the inherent type of `a`
```

**Case II**

Similarly what about when the rest-descriptor is of a type that is compatible with the fixed members of the tuple (this could happen at runtime too)?
```ballerina
    [int, int...] a = [1, 2, 3];
    int x = a.shift();
```

Do we allow this at compile-time and at runtime if values are available for the rest descriptor use them as replacements for the removed member?

Meaning in this case the tuple will become `[2, 3]`?

**Case III**

But for 
```ballerina
    [int, int...] a = [1];
    int x = a.shift();
```
`.shift()` would result in a panic?

Or do we disallow this also at compile-time?

**Comment by jclark** [comment]
Let's discuss the runtime part first. The question to ask is whether this mutates the value in a way that is not allowed by the inherent type. If so, then it must panic at runtime. So case I, as you observe, must panic at runtime.  The mutation in case II is allowed by the inherent type and so must not panic. The mutation in case III is _not_ allowed by the inherent type, and so must not panic.

As regards compile-time errors, the spec does not require a compile-time error. But if you can tell that a lang lib function is used in a way that would always cause a panic, then I think it's helpful to give a compile-time error.

**Comment by MaryamZi** [comment]
> Let's discuss the runtime part first. The question to ask is whether this mutates the value in a way that is not allowed by the inherent type. If so, then it must panic at runtime. So case I, as you observe, must panic at runtime. The mutation in case II is allowed by the inherent type and so must not panic. The mutation in case III is _not_ allowed by the inherent type, and so must not panic.
> 
I assume this (case III) was supposed to be **must panic**.

Got it, thank you.

**Comment by jclark** [comment]
Correct: Case III should have been must panic. (I just edited it.)
