### ISSUE TITLE
How should table type handle duplicate keys?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#477]
This was not specified by [revised table design](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/tablenoclone/tablenoclone.md).

Contexts where this can happen:

1. langlib methods that add a row to a table
2. table constructor
3. table constructor with spread operator (if we allow it)
4. query expression that creates a table

Possible strategies:

1. Compile-time error
2. Run-time panic
3. Run-time error value
4. Replace any value with same key

Relates to #47.

**Comment by jclark** [comment]
With mappings:

- mapping constructor usually reports error at compile-time
- use of computed key syntax `{[expr]: value}` in mapping constructor will replace any entry with same key
- with spread operator uses compile-time checking: only uses of spread operator that are compile-time safe are allowed

**Comment by jclark** [comment]
I think the overall strategy should be:

- there is a syntax for the table constructor that always performs compile-time checking of duplicate keys; this has to constrain the value of key fields to be const
- a query-expr should have a clause that allows for control over how duplicates are handled; at a minimum it should allow both a strict policy in which a duplicate results in the query-expr returning an error value, and a looser policy in which one of the duplicates is discarded (probably the first)

**Comment by jclark** [comment]
For the table constructor syntax, we can leverage the fact the the keys are ordered and that every entry must have a value for each key field. For example:

```
type Order record {
  readonly int id;
  int quantity = 1;
  decimal price;
};

table<Order> key(id) orders;
// Option A
orders = table [
  1 => { quantity: 10, price: 0.50 },
  2 => { price: 5.00 }
];

// Option B
orders = table [
 { 1 => quantity: 10, price: 0.50 },
 { 2 => price: 5.00 }
];

// Option C
orders = table [
  [1]: { quantity: 10, price: 0.50 },
  [2]: { price: 5.00 }
];

// Option D
// This doesn't really work because { x } already has a meaning
orders = table [
 { 1, quantity: 10, price: 0.50 },
 { 2, price: 5.00 }
];

// Option E
orders = table [
  { key(1), quantity: 10, price: 0.50 },
  { key(2), price: 5.00 }
];
```

**Comment by jclark** [comment]
Another possibility for the constructor is simply to require the expressions for the rows of the table to be mapping constructors, with key fields being non-computed and const.

**Comment by jclark** [comment]
The query clause might look like this (only makes sense when creating a table):

```
table key(id) from r in stm
  select r
  duplicate var prev io:println(`duplicate for ${r.id}: ${r.name} vs ${prev.name}`)
```
or

```
table key(id) from r in stm
  select r
  duplicate var prev DuplicateError("duplicate detected", this=r, prev=prev)
```

i.e. syntax is

```
duplicate-clause := "duplicate" typed-binding-pattern expression
```

Semantics is:

- `duplicate` clause gets executed when select emits a row that has the same key as a row that it emitted earlier
- bind typed-binding-pattern to the previous row that has the same key
- evaluate expression resulting in v, which must be a subtype of `error?`; evaluation of expression is allowed to have side-effects such as logging
- if v is an error, then the result of the query-expr is an error
- otherwise, replace old value with new value and continue without giving an error
 
Issues:
* Not sure about the right keyword. Maybe should be something with `key` in it.
* Is providing the previous value sufficiently useful to justify the complexity?

**Comment by hasithaa** [comment]
> Another possibility for the constructor is simply to require the expressions for the rows of the table to be mapping constructors, with key fields being non-computed and const.

I have added this as option G.

```
// Option G
order = table key(id) [
 { id : 1, quantity: 10, price: 0.50 },
 { id : 2, price: 0.50 },
];
```

I think Option G works well. I prefer it over others.

**Comment by jclark** [comment]
Consensus is option G for table constructor.

**Comment by jclark** [comment]
Need a better word than `duplicate`. Please add suggestions. In the absence of duplicate clause, would use the last row with a particular key.

**Comment by jclark** [comment]
In the absence of the new query-expr clause, a row with the same key as a previous row replaces the previous row.
