### ISSUE TITLE
Clarification regarding `readonly` type

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#478]
**Description:**
The spec says
```
A value belonging to an inherently immutable basic type will always have its 
read-only bit on. These basic types are:

- all simple types
  - nil
  - boolean
  - int
  - float  
  - decimal
- string
- error
- function
- service
- typedesc
- handle

A value belonging to a selectively immutable basic type may have its read-only bit 
on. These basic types are:

- xml
- list
- mapping
- table
```

Wanted to validate the following behaviour-related assumptions.

A value belonging to an inherently immutable basic type can be assigned to a variable of type `readonly` but the same cannot be done for a value of a selectively immutable basic type.

```ballerina
public function main() {
    readonly a = 1; // allowed

    int[] b = [1, 2]; 
    readonly c = b; // invalid - disallowed at compile-time - may or may not have 
                    // read-only bit on
}
```

But, a type test for `readonly` can be done with a variable of a selectively immutable basic type?

```ballerina
public function main() {
    int[] d = [1, 2];

    boolean res = d is readonly; // same results as `d.isReadOnly()`
}
```

And the narrowed type would be based on the particular selectively immutable basic type?
```ballerina
public function main() {
    int[] c = [1, 2];
    int[] d = c.cloneReadOnly();

    if d is readonly {
        int[] e = d; // d is `int[]`
    }
}
```

**Comment by jclark** [comment]
In doing this, I suggest you lookahead to #464 and #476: `readonly` by itself is just a first step.

> A value belonging to an inherently immutable basic type can be assigned to a variable of type `readonly` but the same cannot be done for a value of a selectively immutable basic type.

The first part is true, but the second part is not true in general.

An assignment

```
T v;
v = E;
```

is allowed if you know at compile-time that the value of E belongs to T.  So

```
readonly v;
v = E;
```

is allowed only if you know at compile time that that result of evaluating v will have its read-only bit set, or in type terms if E is a subtype of `readonly`.

If static type of E is a subtype of a selectively immutable basic type, then it is still possible for it to be a subtype of `readonly`.

For example, given

```
const PAIR = [1, 2];
```
the static type of PAIR is a subtype of `readonly`.

Another case is:

```
readonly v;
v = <readonly>[1, 2];
```
In this case, the contextually expected type for the expression `[1, 2]` is a subtype of `readonly`, so it will construct a list value with its read-only bit set.

> a type test for `readonly` can be done with a variable of a selectively immutable basic type?

That is true. You can do a type test for readonly just like any other type test.

> And the narrowed type would be based on the particular selectively immutable basic type?

The narrowed type is the intersection of the type you already have and the type you test for. So the narrowed type of d would be `int[] & readonly` (where `&` means intersection).

When we have #476, the type of cloneReadOnly will change to:

```
public function cloneReadOnly(CloneableType v) returns CloneableType & readonly = external;
```

**Comment by jclark** [comment]
Please feel free to reopen if this is not clear.

**Comment by MaryamZi** [comment]
Thank you @jclark, this is all clear.
