### ISSUE TITLE
Clarification regarding mapping constructor spread-field

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#479]
**Description:**
The section in the spec regarding spread-field says

```
It is a compile-time error if the static type of the expression in a spread-field 
allows a field that duplicates a specific-field or that could also occur in 
another spread-field. Note that a spread-field with an inclusive record type 
of record { never x?; } cannot duplicate a specific field for x.
```

**Case I**
Going by the above I guess the following should be **disallowed** since even though field `i` is optional in `Foo` it could still occur?

```ballerina
type Foo record {|
    int i?;
|};

public function main() {
    Foo f = {i: 1};

    map<int> m = {i: 0, ...f};
}
```

**Case II**
IIUC, this also means as spread-fields we cannot use values of inclusive-record types such as `Bar` in the following example, since `b` could have a field with the key `i`.

```ballerina
type Bar record {
    int j;
};

public function main() {
    Bar b = {j: 1, "i": 2};

    map<anydata> m = {i: 0, ...b};
}
```

**Case III**
But a value of an inclusive-record type can be used if there are `never x?;` fields for each `x` that has already occurred/could have occurred in the mapping constructor expression.
```ballerina
type Bar record {
    int j;
    never i?;
};

public function main() {
    Bar b = {j: 2, "k": 3};

    map<anydata> m = {i: 0, ...b}; // allowed now
}
```

**Case IV**
I guess this would also mean that in general you cannot have more than one spread-field of a type that has an inclusive-type-descriptor.

```ballerina
type Foo record {
    int i;
    never j?;
};

type Bar record {
    never i?;
    int j;
};

public function main() {
    Foo f = {i: 1, "k": 4};
    Bar b = {j: 2, "k": 4};

    map<anydata> m = {...f, ...b}; // `k` duplicated
}
```

**Comment by jclark** [comment]
That all looks right to me.

An important point is that the type that you infer for a variable bound by rest-binding-pattern include `never x?;` for each field name `x` that occurred in a field binding pattern.

Before you spend too much effort on this, it might be sensible to wait for a conclusion on #477, since it is possible that the solution to that issue could cause us to revisit this.

**Comment by jclark** [comment]
Conclusion to #477 does not require a change here.
