### ISSUE TITLE
Select XML elements using dynamic name

### ISSUE THREAD

**Issue by chipsmaster** [ballerina-platform/ballerina-spec#480]
**Description:**

WIth new xml syntax and xml library, it seems there is no way to access dynamically to a subelement with a dynamic name (there was still a way with bracket syntax but now deprecated in 1.2.1)
Could it be possible to have a way to access xml elements dynamically? Ideally with a xpath query string or something similar

**Comment by jclark** [comment]
Yes, we should add something to make this easy. Probably a langlib function.

I would like to understand your scenario better. Where does the dynamic name come from? Is it a name dynamically chosen from a set of names known at compile-time?  Are the possible namespace URIs or the element name known at compile time (and declared in the Ballerina program with xmlns declarations) or are they dynamic also?  Default namespaces can be problematic here.

**Comment by chipsmaster** [comment]
In my case, element names and namespaces are known at compile time (string literals), it's just they go through functions/methods parameters so that i can add code before/after fetching the element

But we could imagine i'd like to build the names dynamically

**Comment by jclark** [comment]
There are several features in the [XML design](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md) for this, which are not yet in the spec:

1. elements method can have an optional string argument
2. there's an elementChildren method with an optional string argument
3. there's also a [feature](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md#better-integration-with-types) for making patterns first-class

We should do at least the first two of these.
