### ISSUE TITLE
Prevent remote methods from using object types as params or return types

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-spec#484]
If remote methods are only accepting record types and primitive types, creating a form to capture the arguments is straight forward.  On top of that, there's another question - does it make sense to pass an object to a remote method? Since objects cannot be sent over wire.

**Comment by jclark** [comment]
That doc is not publicly readable.

That's not a restriction that makes sense to me in general for remote methods.

There's a kind of client object type where a restriction does make sense: a client object type that represent an strongly-typed, application-level, protocol-independent interface. For this kind of client object, you use the parameter and return types of the remote method to map from the protocol-level interface to the application-level interface.  The right restriction would be to restrict the parameter and return types to anydata.

For client objects describing a protocol-level interface, it makes no sense to have such a restriction on remote methods.

There's a parallel situation with services and resource methods.

I think the solution is to recognize a distinction between protocol-level interfaces and application-level interfaces for both client objects and services. I do not yet have a good sense of how this should manifest itself in the language.

**Comment by jclark** [comment]
It's up to the service object type to constrain the type of resource/remote methods.

This will be dealt with by #609.
