### ISSUE TITLE
Revise iterator invalidation to work with tables

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#485]
Currently the spec says:

> At any point during the execution of a program, a container has a set of valid keys; these are keys for which the container has a member; a key has type int for lists and type string for maps. A call to next() must panic if the set of valid keys is not the same as the set of valid keys when the iterator was created, with the following exception: it is allowed to remove a key if the member for that key has already been returned by next().

This would be inconvenient to implement for tables, and is probably inconvenient for mappings in the case where you remove a key and then add the same key back.

**Comment by jclark** [comment]
Relates to #47

**Comment by jclark** [comment]
Can we say instead that any mutation invalidates an iterator except for:

- changing what is associated with an existing key, or
- removing an member that has already been returned by the iterator

?

**Comment by hasithaa** [comment]
@jclark Current JBallerina implementation doesn't handle mutations as per specified in the spec. https://github.com/ballerina-platform/ballerina-lang/issues/21329 created to capture this. 

> Can we say instead that any mutation invalidates an iterator except for:
> 
> * changing what is associated with an existing key, or
> * removing an member that has already been returned by the iterator
> 
> ?

+1.
