### ISSUE TITLE
Clarification on filler value for xml subtypes

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-spec#490]
**Description:**

> There are built-in subtypes xml:Element, xml:ProcessingInstruction, xml:Comment and xml:Text corresponding to the above singletons; xml:Text also allows the empty xml value.

Can we assume all subtypes of XML also has the same filler value defined for basic type ```xml```?  ```xml:Text``` is immutable therefore having a filler value feels illegal. Looking at constructors and the uses, having the empty filler value may not make sense for all the subtypes.

**Comment by jclark** [comment]
The filler value for the xml type is an empty xml value. An empty xml value belongs to xml:Text, so the filler value for that should also be an empty xml value.  The other built-in subtypes would not have a filler value.
