### ISSUE TITLE
Clarification on `readonly` fields in a mapping constructor

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#493]
**Description:**
A specific-field in a mapping-constructor-expr now allows using `readonly`.

```
specific-field :=
   [readonly] (field-name | string-literal) : value-expr
   | [readonly] [variable-name]
```

The spec says "If the applicable contextually expected type is a subtype of readonly, then the mapping will be constructed with its read-only bit on. If the inherent type makes a specific field readonly, then that field will be constructed with its read-only bit on. A specific-field that starts with readonly will also be constructed with its read-only bit on.".

**Case I - No contextually expected type**

So when there is no contextually expected type, would this result in an inferred type 

a) where the particular field is a `readonly` field

e.g.,
For
```ballerina
type Details record {|
    string name;
    int id;
|};

public function main() {
    Details & readonly details = {
        name: "Amy",
        id: 1234
    };

    var x = {
        readonly details,
        department: "finance"
    };
}
```

the type inferred for `x` would be
```ballerina
type $inferred$ record {|
    readonly Details details;
    string department;
|};
```

This would mean that for any `readonly x` or `readonly w: x`, x would have to be a value with its read-only bit set or would be constructed with its read-only bit set?

b) or just that the value's read-only bit would be/have to be set?

Which would mean the inferred type would be

```ballerina
type $inferred$ record {|
    Details & readonly details;
    string department;
|};
```

**Case II - There is a contextually expected type but without `readonly` fields in the type-desc**

```ballerina
type Employee record {|
    Details details;
    string department;
|};

type Details record {|
    string name;
    int id;
|};

public function main() {

    Employee x = {
        readonly details: {
            name: "Amy",
            id: 1234
        },
        department: "finance"
    };
}
```

Going by "A specific-field that starts with readonly will also be constructed with its read-only bit on.", would this just result in `{ name: "Amy", id: 1234 }` being created as an immutable value? 

So while the following will fail (at runtime, because we don't know `x.details` is immutable at compile-time),
```ballerina
x.details.id = 3456;
```

the following is allowed (since the field itself is not read-only)?
```ballerina
x.details = {
    name: "Jo",
    id: 2345
};
```

**Follow-up question**

If the behaviour for Case II is as mentioned, and for Case I the behaviour is b), can we not achieve the same via a cast to `readonly` (instead of allowing `readonly` for mapping-constructor fields)?

```ballerina
public function main() {

    var x = {
        details: <readonly> {
            name: "Amy",
            id: 1234
        },
        department: "finance"
    };
}
```

**Comment by jclark** [comment]
`readonly` in a mapping constructor means the field is `readonly`, which means

- the value of the field must be readonly, and
- the field cannot be assigned to or removed

It would be useless if it meant just that the value was `readonly`, since you could achieve that with a cast to `<readonly>`.

The read-only bit of a field is distinct from the read-only bit of the value of the field. If the former is on, the latter must be on. But the latter can be on without the former being on.

**Case I**

The answer is (a).

**Case II**

Assigning to `x.details` is a runtime panic.

Does that answer your question?

**Comment by MaryamZi** [comment]
So IIUC, even though there is a contextually expected type, we are inferring some information from the expression itself? 

So for 

```ballerina
type Employee record {|
    Details details;
    string department?;
|};

type Details record {|
    string name;
    int id;
|};

public function main() {
    
    Details & readonly details = {
        name: "Amy",
        id: 1234
    };

    Employee e = {
        readonly details
    };
}
```

would the inherent type for `{ readonly details }` be a type similar to `Employee` with additional constraints for `readonly` fields?

```ballerina
    record {|
        readonly Details details;
        string department?;
    |}
```

So saying 

```ballerina
Employee e = {
    readonly details
};
```

is like saying

```ballerina
    record {|
        readonly Details details;
        string department?;
    |} rec = {
        readonly details
    };
    
    Employee e = rec;
```

**Comment by jclark** [comment]
> So IIUC, even though there is a contextually expected type, we are inferring some information from the expression itself?

Yes. The contextually expected type concept needs reworking to deal with this. See #392. The idea is that you are unifying information from the context and from the expression to arrive at the complete type.

The answer to both your other questions is yes.

**Comment by MaryamZi** [comment]
Got it, thank you!
