### ISSUE TITLE
Revisit toString

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#499]
Given we are doing 2.0, I think we should revisit the design of `toString` to see if we can come up with something that works better than our current approach.

**Comment by jclark** [comment]
Need to consider how this relates to #159.

**Comment by jclark** [comment]
Also may want to specify in more detail how toString works on error.

**Comment by jclark** [comment]
Also related to #135.

**Comment by jclark** [comment]
New design is as follows.

The spec would define an abstract operation ToString(v, style), where three styles are supported:

*   expression style: produces a string that uses a subset of Ballerina expression syntax; guarantees that
    *   for a value v that is anydata, the string can be parsed and will produce a value that is == to v
        *   if value is acyclic, result will be Ballerina expression
    *   for a value v that non anydata, string is distinguishable from value produced for v that is anydata
*   informal style: similar to expression style, but
    *   avoids some more esoteric Ballerina syntax
    *   does not preserve all the distinctions that expression style does
*   direct style: converts a value to string in a more direct way, for basic types where this makes sense
    *   more direct means _converting_ the value to a string rather than _describing_ the value using a string
        *   most importantly, direct style applied to a string leaves string as is
        *   xml is represented in XML format
    *   falls back to informal style, for basic types where this doesn’t make sense, e.g. for collections
    *   for object, uses toString method of object if there is one
        *   should probably be required to be isolated

This design is similar to Python:

*   Python’s str(x) function corresponds to direct style
*   Python’s repr(x) functions corresponds to expression style

Python doesn’t have the third style; this leads to weirdness when applying str(x) to collections, in that the members are output in a way that has an inappropriate level of detail.

The `value:toString` function would be defined to use direct style.

A new `value:toBalString` will use expression style. Informal style would probably be available by using arguments to value:toBalString; other options can be added over time (e.g. for pretty printing).

`j.toBalString()` when j is json is guaranteed not to have newlines; `d.toBalString()` may have newlines if d contains tables or XML.

These functions should be robust in the presence of cycles. The implementation of toString would have a stack of the structures/objects that are being converted; toString when applied to some object, would first check whether the object is on the stack; if so, then there’s a cycle; otherwise, when it calls toString on members, it does so with itself added to the top of the stack. For now, we have the limitation that there is no mechanism for user-defined toString on objects to deal with cycles.

The following table summarizes the behaviour of the abstract operation ToString(v, style)

<table>
  <tr>
   <td rowspan="2" >Type of v
   </td>
   <td colspan="3" >style
   </td>
  </tr>
  <tr>
   <td>expression
   </td>
   <td>informal
   </td>
   <td>direct
   </td>
  </tr>
  <tr>
   <td>nil
   </td>
   <td><code>()</code>
   </td>
   <td><code>null</code>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>true
   </td>
   <td colspan="3" ><code>true</code>
   </td>
  </tr>
  <tr>
   <td>int
   </td>
   <td colspan="3" ><code>2</code>
   </td>
  </tr>
  <tr>
   <td rowspan="3" >float
   </td>
   <td colspan="3" ><code>1.0</code>
   </td>
  </tr>
  <tr>
   <td><code>float:NaN</code>
   </td>
   <td colspan="2" ><code>NaN</code>
   </td>
  </tr>
  <tr>
   <td><code>float:Infinity</code>
   </td>
   <td colspan="2" ><code>Infinity</code>
   </td>
  </tr>
  <tr>
   <td rowspan="2" >decimal
   </td>
   <td><code>1d</code>
   </td>
   <td colspan="2" ><code>1</code>
   </td>
  </tr>
  <tr>
   <td><code>1.20d</code>
   </td>
   <td colspan="2" ><code>1.20</code>
   </td>
  </tr>
  <tr>
   <td>string
   </td>
   <td colspan="2" ><code>"xyz"</code>
   </td>
   <td><code>xyz</code>
   </td>
  </tr>
  <tr>
   <td>xml
   </td>
   <td><code>xml`&lt;d>t&lt;/d>`</code>
   </td>
   <td><code>`&lt;d>t&lt;/d>`</code>
   </td>
   <td><code>&lt;d>t&lt;/d></code>
   </td>
  </tr>
  <tr>
   <td rowspan="2" >array
   </td>
   <td colspan="3" ><code>[<em>X</em>,<em>Y</em>]</code>
   </td>
  </tr>
  <tr>
   <td><em>X</em>, <em>Y</em> expression style
   </td>
   <td colspan="2" ><em>X</em>,<em>Y</em> informal style
   </td>
  </tr>
  <tr>
   <td rowspan="2" >map
   </td>
   <td colspan="3" ><code>{ "x": <em>X</em>, "y": <em>Y</em> }</code>
   </td>
  </tr>
  <tr>
   <td><em>X</em>, <em>Y</em> expression style
   </td>
   <td colspan="2" ><em>X</em>,<em>Y</em> informal style
   </td>
  </tr>
  <tr>
   <td rowspan="2" >table
   </td>
   <td><code>table key(k) [<em>R<sub>1</sub></em>,<em>R<sub>2</sub></em>]</code>
   </td>
   <td colspan="2" ><code>[<em>R<sub>1</sub></em>,<em>R<sub>2</sub></em>]</code>
   </td>
  </tr>
  <tr>
   <td><em>R<sub>1</sub></em>, <em>R<sub>2</sub></em> expression style
   </td>
   <td colspan="2" ><em>R<sub>1</sub></em>, <em>R<sub>2</sub></em> informal style
   </td>
  </tr>
  <tr>
   <td rowspan="2" >error
   </td>
   <td colspan="3" ><code>error D<sub>1</sub>&D<sub>2</sub> (F<sub>1</sub>=V<sub>1</sub>,F<sub>2</sub>=V<sub>2</sub>)</code>
   </td>
  </tr>
  <tr>
   <td>V<sub>1</sub>, V<sub>2</sub> expression style
   </td>
   <td colspan="2" >V<sub>1</sub>, V<sub>2</sub> informal style, D is {module}local-name
   </td>
  </tr>
  <tr>
   <td>object w/o toString
   </td>
   <td colspan="3" ><code>object D1&D2 U </code>U is an identifier that uniquely identifies the object (based on ===)
   </td>
  </tr>
  <tr>
   <td>object with toString
   </td>
   <td><code>object S</code>
   </td>
   <td colspan="2" ><code>S</code>
   </td>
  </tr>
  <tr>
   <td rowspan="2" >cycle
   </td>
   <td><code>...[N]</code>
   </td>
   <td colspan="2" ><code>...</code>
   </td>
  </tr>
  <tr>
   <td>N is 0-based index down path from root object to object where cycle is detected
   </td>
   <td colspan="2" >
   </td>
  </tr>
</table>

**Comment by lasinicl** [comment]
@jclark 
Consider applying toString() on an `error` type value
```
public type FirstError distinct error;
error cause = error("Account not found", accountID = 123);
FirstError err = FirstError("Reason1", cause, detail = "Failed to get account balance");
string str = err.toString();
```
Is the expected value of `str`, the following?
```
error FirstError (message=Reason1, cause=error error (message=Account not found, detail={"accountID":123}), detail={"detail":"Failed to get account balance"})
```
For the example given below,
```
error cause = error("Some issue");
http:FailoverAllEndpointsFailedError err = http:FailoverAllEndpointsFailedError("failoverMessage", failoverErrors = cause);
string str = err.toString();
```
can this be the expected outcome?
```
error {ballerina/http}FailoverAllEndpointsFailedError (message=failoverMessage, detail={"failoverErrors":error error (message=Some issue)})
```

**Comment by jclark** [comment]
The entry for error in the table isn't quite right: I just edited it.

Note that your syntax is no longer right in Swan Lake. It's

```
error cause = error("Account not found", accountID = 123);
FirstError err = error FirstError("Reason1", cause, detail = "Failed to get account balance"); // error keyword needed here too
```

The toString output should look like the constructor:
```
error FirstError ("Reason1", error("Account not found", accountID=123), detail="Failed to get account balance");
```

Specifically:

- omit the distinct name if there isn't one
- omit the cause if it's nil

The expression style includes the module name in the distinct type-id.

**Comment by mohanvive** [comment]
@jclark a quick clarification on map. 

Does map contains a space after after the ":" and before the value ,

For example,
```ballerina
{"name": "Jane", "age": 25, "spouse": "John", "gender": "female"}
```

**Comment by jclark** [comment]
I definitely wouldn't put a space before `:`. I don't have a strong opinion about after `:`, but `,` and `:` should be treated consistently as regards spacing (for both mappings and lists) So either:

```
{"name": "Jane", "age": 25, "spouse": "John", "gender": "female"}
[1, 2, 3]
```

as you wrote, or

```
{"name":"Jane","age": 25,"spouse": "John","gender":"female"}
[1,2,3]
```

I slightly prefer with spaces for readability. Which do you prefer?

**Comment by mohanvive** [comment]
Actually I prefer the second option which you suggested (without spaces), just intuitive. 

But shall we make a quick decision on this because there are some dependent changes pending on this.

**Comment by jclark** [comment]
I don’t have a strong opinion and I don’t think it matters very much. Do whichever the implementation team prefers and let me know which you decide.

**Comment by mohanvive** [comment]
Sure James. We are moving forward with the option #2 (without spaces).

**Comment by jclark** [comment]
OK, I updated the table above accordingly: toString for error also should not add space after string.
