### ISSUE TITLE
Float/Decimal literal descriminator (f/d) conflics with hex literals

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#50]
**Description:**
```ballerina
decimal d = 0x22.Fd;
```

Interpreting final letter 'd' seems ambiguous as is could be number 'D' or decimal discriminator 'd'.

**Comment by jclark** [comment]
Hex floating point literals can’t have a d/f suffix: they are always float. I believe this is clear in the current spec. They would not make any sense for decimal, since their purpose is to provide an exact representation of a radix 2 floating point number.
