### ISSUE TITLE
Extract annotation fields from a variable

### ISSUE THREAD

**Issue by whizsid** [ballerina-platform/ballerina-spec#503]
**Description:**
I am writing an ORM module to Ballerina Lang. I have defined an annotation with some fields to attach to the types. Now I want to extract annotation fields from a variable.

**Code sample that shows issue:**

```ballerina
// Defining my annotation
public type EntityType record {|
    string primary;
|};

public annotation EntityType Entity on type;

// Creating my entity
@Entity {
 tableName: "Actor",
 primary: "id"
}
type Actor record {
   int id;
   string name;
}

// Creating a variable
Actor a1 = {
  id: 1,
  name: "Irrfan Khan"
}

// I want to access the tableName from here
// Suggested:-
string tableName = a1.getType().getAnnotation(Entity).get('tableName');
```

This feature is already implemented in Java Lang.

**Comment by jclark** [comment]
The spec allows you to do this:

```
string tableName = typeof(a1).@Entity.tableName;
```

See:
* https://ballerina.io/spec/lang/2020R1/#annot-access-expr
* https://ballerina.io/spec/lang/2020R1/#typeof-expr

If this doesn't address your problem, please reopen.

Not sure what the implementation status is.

**Comment by MaryamZi** [comment]
The following is supported in the current implementation (any version since 1.0.0).

Since the implementation does not **yet** support retrieving the typedesc and using annotation access in-line, I've done the typedesc retrieval separately.

```ballerina
import ballerina/io;

public type EntityType record {|
    string tableName;
    string primary;
|};

public annotation EntityType Entity on type;

@Entity {
    tableName: "Actor",
    primary: "id"
}
type Actor record {
    int id;
    string name;
};

Actor a1 = {
    id: 1,
    name: "Irrfan Khan"
};

public function main() {
    typedesc<Actor> td = typeof a1;

    string? tableName = td.@Entity?.tableName;

    // Or
    // EntityType? entityType = td.@Entity;
    // if entityType is EntityType {
    //     string tableName = entityType.tableName;
    // }

    io:println(tableName);
}
```

```cmd
$ ballerina run xyz.bal 
Compiling source
        xyz.bal
Running executables

Actor
```

I've also added a `string tableName;` field to the `EntityType` record.

**Comment by jclark** [comment]
@MaryamZi Why `?.` not `.`?

**Comment by MaryamZi** [comment]
The static type of annotation access is `T?` right, where `T` is the annotation tag type?

So in this scenario the static type of `td.@Entity` is `EntityType?`, on which we can't use field access. Thus requires optional field access?

**Comment by jclark** [comment]
@MaryamZi I had forgotten that. You are quite right.

**Comment by whizsid** [comment]
@MaryamZi @jclark Thank You! It is working. But seems like not working on test cases. `td.@Entity` is a nil value on my test case.

## Annotation Definition:-
```ballerina
// annotaions.bal
public type EntityType record {|
    string primary;
    string tableName;
|};

public annotation EntityType Entity on type;
```

## Test Case:-
```ballerina
// tests/testannotations.bal
import ballerina/io;
import ballerina/test;

@Entity{ 
    primary:"id" ,
    tableName: "Actor"
}
type Actor record {
    string name;
    int id;
};

// Test function.
@test:Config {}
function testFunction1() {
    Actor a1 = {
        name: "Irrfan Khan",
        id: 1
    };

    typedesc<Actor> td = typeof a1;

    io:println(td);// typedesc foo:Actor
    io:println(td.@Entity);// Nothing

    string? tableName = td.@Entity?.tableName;

    test:assertEquals(tableName, "Actor");
}
```

**Comment by jclark** [comment]
That looks to me like it should work. @MaryamZi If it's an implementation issue, could you please move the issue into the ballerina-lang repo?

**Comment by MaryamZi** [comment]
@jclark, @whizsid, yes this seems to be an issue in the implementation. 

I've extracted this out to https://github.com/ballerina-platform/ballerina-lang/issues/23043.
