### ISSUE TITLE
Precise type for final var variables in let-expr, for-each

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-spec#512]
**Description:**
According to the spec:

_Local variable declaration statements_
`If the typed-binding-pattern uses var, then the type of the variable is inferred from the static type of the action-or-expr; if the local-init-var-decl-stmt includes final, the precise type is used, and otherwise the broad type is used.`

_Module variable declaration_
`If the typed-binding-pattern uses var, then the type of the variable is inferred from the static type of expression; if the module-var-decl includes final, the precise type is used, and otherwise the broad type is used.`

Hence the type of `v1` in the following code snippet is `1` (not int);
```ballerina
const ONE = 1;

public function main() {
    final var v1 = ONE;
}
```

**My question is, does this rule (precise type) applies to variables that are implicitly final?** (let-expr, foreach)

 let-expression the spec says:
`Since expressions cannot modify variables, the variables bound in a let-var-decl are implicitly final.`

Under foreach:
`The scope of any variables created in typed-binding-pattern is block-stmt. These variables are implicitly final.`

**Comment by jclark** [comment]
Yes, variables that are implicitly final should use the precise type (the only reason not to use the precise type is if mutation is possible).

**Comment by jclark** [comment]
For let-expr it says so explicitly:

> If the typed-binding-pattern uses var, then the type of the variable is inferred from the precise static type of the expression following =

Does it arise in the case of `foreach`, since the type comes from the return type of the iterator?
