### ISSUE TITLE
Precedence for type descriptors is unspecified

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-spec#513]
**Description:**

Consider the below type-desc:
```ballerina
function () returns int | string;
```

This matches to both:
```ballerina
function () returns (int | string)
```
and 
```ballerina
(function () returns int) | string
```

**Suggested Labels:**

   
**Code sample that shows issue:**
Added above

**Related Issues:**
N/A

**Comment by jclark** [comment]
We need a precedence table for type descriptors. 

I think that one should be parsed as `function () returns (int | string)`.

We have a similar problem with `&` and `|` (which should get parsed the same as with expressions).

**Comment by SupunS** [comment]
A similar problem exist for arrays. eg: `T1 | T2 []`

**Comment by jclark** [comment]
Right. We should follow expression precedence. So the precedence order (most to least) should be:

```
T[]
T1&T2
T1|T2
function(args) returns T
```
