### ISSUE TITLE
Clarification on xml<never>

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#517]
**Description:**
T x = xml ``;
Should we allow T to be `xml<never>` as the compiler knows that this is an empty XML sequence?

In the same note should we allow:
```ballerina
xml<never> x = xml ``;
xml<xml:Text> t = x;
```

**Comment by jclark** [comment]
`never` is a subtype of `xml` and of `xml:Text`, so the answers are: yes and yes.
