### ISSUE TITLE
Use of only annotations for service attachment is too restrictive

### ISSUE THREAD

**Issue by sanjiva** [ballerina-platform/ballerina-spec#519]
Currently attaching a service to a listener is done via an annotation. However, that does not support scenarios where we need to attach a service value that is created at a module level and we want to attach it to a dynamic path.
```ballerina
function bar(http:Listener hl, string path) {
  hl.__attach(
    @http:ServiceConfig { basePath: path }
    service { .. }
  );
}
```

That is supposed to work (does not currently due to an impl restriction - no issues) but what I want is to create the service value outside (once) and attach it dynamically to different paths.

**Comment by jclark** [comment]
I don't understand this. Why is it important to create the service value at module level once?

**Comment by sanjiva** [comment]
Well its not a critical requirement, but given services are stateless that should be possible.

The most important reason is that I have a few hundred lines of code to write in there and I don't want to nest that several levels down inside the function which is attaching the service value. 

Yes I can move the logic to functions and make it work too. But that's a workaround, not the elegant solution IMO.

**Comment by jclark** [comment]
This particular case is handled by handling base path in a first class way, which is part of #607.
