### ISSUE TITLE
langlib methods and intersection types

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#520]
**Description:**

The spec says

> Immutability of xml values is deep: if the read-only bit of an xml:Element is on, then the read-only bits of the mapping representing its attributes and of the xml value representing its children are also on.

Consider

```ballerina
    xml:Element & readonly x = xml `<book status="available" count="5"/>`;
```

Since `x` is immutable, I assume `x.getAttributes()` will return an immutable map of `string`.

So would the following be valid?

```ballerina
    map<string> & readonly attrMap = x.getAttributes();
```

IMO, the `.getAttributes()` langlib method's current return type (`map<string>`) does not allow/reflect this.

https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/xml.bal#L126

Or would it still return a `map<string>`, but a cast to `map<string> & readonly` will be successful?

**Comment by jclark** [comment]
The static type of `x.getAttributes() is `map<string>` as declared in lang.xml.

So this, as you say, is not valid:

```
map<string> & readonly attrMap = x.getAttributes();
```

But the value returned by `x.getAttributes()` has the read-only bit set, and so, as you suggest, can be cast to `readonly`. Thus you can do:

```
map<string> & readonly attrMap = <readonly>x.getAttributes();
```

If/when we do parameterized types, then there should be a way to make `readonly` be a parameter, so you can say that the return type of a function is readonly or not depending on whether a parameter is read-only or not.

In the meantime, we should provide this functionality for langlib with @typeParam or something similar. I made an issue #521 for that.
