### ISSUE TITLE
Need to specify parsing precedence for type descriptors

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#529]
The current distinct-type-descriptor defined as follows. 
```
distinct-type-descriptor := distinct type-descriptor
```
And Spec says, `Only object and error values can belong to a type described by a distinct-type-descriptor.`

With the above rules, The following case is valid. But it is not the intended outcome.

```ballerina 
type E1 distinct error<R1> | error<R2>;
```

So should we consider updating rules to something like this? 
```
distinct-type-descriptor := distinct distinctnable-type-descs
distinctnable-type-descs := type-reference | object-type-descriptor | error-type-descriptor
```

**Comment by jclark** [comment]
We need to specify parsing precedence for type descriptors as we do for expressions. Precedence of type descriptors and expressions should be consistent. So it should be:

```
distinct T
T[]
T1 & T2
T1 | T2
```

**Comment by jclark** [comment]
This duplicates #513, which fixed it apart from `distinct`.
