### ISSUE TITLE
Parameter type of clone and cloneReadOnly

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-spec#531]
**Description:**
There is a requirement to use an existing `array of errors` in the detail record of an error. 

Since `error[]` does not match with `anydata` (https://github.com/ballerina-platform/ballerina-spec/issues/463), this has to match with `readonly`. 

While we can create an `readonly array`:
 ```ballerina
error[] & readonly x = [e1, e2];
```
There is not a way to create a readonly copy of an existing `array of errors`.  
This `cloneReadOnly` params are of `anydata|readonly`. 

Do we need to provide a mechanism to support this?

**Comment by jclark** [comment]
The argument type of `clone` and `cloneReadOnly` are wrong. Instead of:

```
@typeParam
type CloneableType anydata|readonly;
public function clone(CloneableType v) returns CloneableType = external;
public function cloneReadOnly(CloneableType v) returns CloneableType = external;
```

we should have:

```
type Cloneable readonly|xml|Cloneable[]|map<Cloneable>|table<map<Cloneable>>;
@typeParam
type CloneableType Cloneable;
public function clone(CloneableType v) returns CloneableType = external;
public function cloneReadOnly(CloneableType v) returns CloneableType & readonly = external;
```

**Comment by jclark** [comment]
@hasithaa Note that this also needs to apply to other places where the spec used `anydata|readonly`, in particular:

- error detail record
- message send
- annotations

Since it is generally useful, I made it public in `lang.value`.

**Comment by KRVPerera** [comment]
Please help clarify. Current spec is updated as below.
```
public function cloneReadOnly(CloneableType v) returns CloneableType = external;
```

Shouldn't this be changed to
```
public function cloneReadOnly(CloneableType v) returns CloneableType & readonly = external;
```

**Comment by jclark** [comment]
Yes, it should be changed

**Comment by KRVPerera** [comment]
Thank you.
