### ISSUE TITLE
Clarification regarding readonly record/object fields

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#532]
**Description:**

**Case I - Fields with default values**

a) Records 

With a record-type-descriptor that has a `readonly` field with a default value, I assume the mapping constructor cannot specify a value for that field?

```ballerina
type Foo record {|
    readonly string name = "xyz";
    int id;
|};

public function main() {
    Foo f1 = {id: 1}; // OK

    Foo f2 = {id: 1, name: "qwe"}; // Compilation error?
}
```

b) Objects

And for a similar scenario, objects would have the same behaviour?

```ballerina
type Foo object {
    readonly string name = "xyz";
    int id;

    function __init(string name, int id) {
        self.name = name; // Compilation error?
        self.id = id;
    }
};
```

**Case II**

The spec says for object fields "If the read-only bit of a field is on, it means the field cannot be assigned to after it has been constructed.". I assume "it" here means the field itself, and not the object?

So the following should also result in an error?

```ballerina
type Bar object {
    readonly int id;

    function __init() {
        self.id = 1;
        self.id = 2; // Compilation error?
    }
};
```

**Comment by jclark** [comment]
*Case I*
No. A default value is one that used if the constructor does not supply one. Readonly doesn't change that: the value becomes readonly once it has been constructed.

*Case II*
I think it should work like final, so that case should be an error. The wording should be improved to make that explicit.

**Comment by jclark** [comment]
I should also mention that I would hope to have a feature for "const" fields: fields that are readonly and fixed in the record type e.g.

```
type Foo record {|
   const name = "xyz";
    int id;
|};
```

**Comment by MaryamZi** [comment]
> _Case I_
> No. A default value is one that used if the constructor does not supply one. Readonly doesn't change that: the value becomes readonly once it has been constructed.
> 
> _Case II_
> I think it should work like final, so that case should be an error. The wording should be improved to make that explicit.

Got it, thank you!

On a related note, what about mapping constructor expressions with computed keys? Should the following (`f2`) result in a panic?

```ballerina
type Foo record {
    readonly int i;
};

public function main() {
    string str = "i";
    Foo f1 = {i: 1}; // OK
    Foo f2 = {i: 1, [str]: 2}; // overwrites `i`, error?
}
```

**Comment by jclark** [comment]
I can see arguments both ways, what do you think?

**Comment by MaryamZi** [comment]
My concern with not making this an error is if by looking at the record type descriptor + mapping constructor it is obvious that the value may be overwritten?

```ballerina
type Foo record {
    readonly int id = 1234;
    string name;
};

Foo f = {name: "foo", [str]: 78};
```

But, since the understanding is that values specified via computed keys could overwrite values of fields already specified in the mapping constructor I'm OK with this not being an error.

I guess there's a somewhat similar scenario with objects too, unless we analyze the function calls from within the object init. 

```ballerina
type Bar object {
    readonly int x;

    public function __init(int x) {
        self.x = x;
        self.updateX();
    }

    function updateX() {
        self.x *= 2;
    }
};
```

Would it be more consistent to say a `readonly` field cannot be updated once the particular record/object is created?

**Comment by jclark** [comment]
https://github.com/ballerina-platform/ballerina-spec/commit/7abbc03996347b1336decb60e135a76d9762497d fixing #1245 clarifies the record case.

**Comment by jclark** [comment]
```
type Bar object {
    readonly int id;

    function __init() {
        self.id = 1;
        self.id = 2; // Compilation error?
    }
};
```

I don't see how this is allowed. An object-field can be declared as final but not readonly.

**Comment by jclark** [comment]
I see the spec says (about object fields)

```
If an object's read-only bit is set, then the read-only bit of the value of
every field must also be set and the value of a field cannot be changed after
the object has been constructed.
```

I can't find this any more:

> The spec says for object fields "If the read-only bit of a field is on, it means the field cannot be assigned to after it has been constructed.". I assume "it" here means the field itself, and not the object?

**Comment by jclark** [comment]
@MaryamZi Is there anything more to do here?

**Comment by MaryamZi** [comment]
I believe the example with readonly object fields is from before the object change (when we had readonly object fields instead of final fields).

**Records**

I believe the parts relevant to records are okay (jBallerina supports these too).
- a `readonly` field can have a default value, but if a value is specified for the field in the constructor, that is used instead
- computed keys can also set a value for a `readonly` field, even if a value was previously provided

**Objects**

For object final fields, since the [spec](https://ballerina.io/spec/lang/master/#section_6.8.1.1) now says

> If final is present, then the field must be assigned to exactly once, either by its initializer or in the init method. 

I believe all the object examples here (converted to final fields in classes) should result in a compilation errors.

i. if a final field has an initializer, a value cannot be assigned to it even in the `init` method (not the same as record defaults)

```ballerina
class Foo {
    final string name = "xyz";
    int id;

    function init(string name, int id) {
        self.name = name; // Compilation error
        self.id = id;
    }
}
```

ii. setting a value for the same final field more than once in the init function should also result in a compilation error.

```ballerina
class Bar {
    final int id;

    function init() {
        self.id = 1;
        self.id = 2; // Compilation error
    }
}
```

And of course, setting a value for a final field in a method that is not the `init` method will result in a compilation error anyway.

```ballerina
class Bar {
    final int x;

    public function init(int x) {
        self.x = x;
        self.updateX();
    }

    function updateX() {
        self.x *= 2; // Compilation error
    }
}
``` 

I believe all of these are now covered in the spec, and therefore, we can close this issue.

jBallerina seems to be compliant for the object cases too.
