### ISSUE TITLE
`init()` method of `T & readonly` where `T` is an object

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#533]
**Description:**
Consider the following object type definition.

```ballerina
type Details object {
    int id;
    map<anydata> info;

    public function init(int id, map<anydata> info) {
        self.id = id;
        self.info = info;
    }
};
```

Now, if I say `Details & readonly x = new (id, details);` should the new-expr only accept immutable values?

For example, should the following fail at compile-time or is it OK for it to fail at runtime?

```ballerina
public function main() {
    map<anydata> info = {name: "Jo"}; // not immutable

    Details & readonly details = new (1234, info);
}
```

I guess we can't really say all parameters have to be immutable without looking at the `init` logic.

For example,

```ballerina
type Details object {
    int id;
    map<string> info;

    public function init(int id, map<string> detInfo) {
        self.id = id;
        self.info = {...detInfo}; // OK for `detInfo` to not be immutable
                                  // since `self.info` is constructed as immutable
    }
};

public function main() {
    map<string> info = {name: "Jo"}; // not immutable

    Details & readonly details = new (1234, info);
}
```

But this would require the `init` method logic to be known wherever this type is used in a read-only intersection, even in a different module.

**Comment by jclark** [comment]
The spec says

> In an intersection type T1&T2, it is an error if either T1 or T2 refer to an object type that is not abstract

So  `Details & readonly x = new (id, details);` is not allowed, because `Details` is not abstract.

If you want a readonly object, you have to declare all the fields as readonly:

```ballerina
type Details object {
    readonly int id;
    readonly map<anydata> info;

    public function init(int id, map<anydata> info) {
        self.id = id;
        self.info = info;
    }
};
```

We do not currently provide a shorthand for this.

Please reopen if this does not answer your question.

**Comment by MaryamZi** [comment]
Sorry, missed that. This is clear, thank you!
