### ISSUE TITLE
Clarifications on query expressions

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-spec#534]
**Description:**

There are a few things we need to get clarified regarding query expressions. I know some are not finalized but it will be helpful with the implementation.

1. According to [1], are there any restrictions on the order of `intermediate-clause`s? For example, can there be a `from-clause` > `join-clause` > `from-clause`?
```
query-pipeline := from-clause intermediate-clause*
intermediate-clause :=
    from-clause
    | where-clause
    | let-clause
    | join-clause
```

2. According to [2]; should this sample throw an error?
```
// quote from [2]
from X in E1
join Y in E2 on E3 equals E4
S
The scope of bindings is as follows:
    bindings from X are in scope in E3 and S but not E4 or E2
    bindings from Y are in scope in E4 and S but not E3"
```
```
// sample:
from var person in personList
join Department dept in deptList
    on dept.id equals person.id
```

3. When it comes to query-expressions, should bindings from X be there in scope E2?
```
from X in E1
from Y in E2
S
```
```
// sample:
from Department dept in deptList
from Employee e in getEmployeesForDepartment(dept)
select {...}
```

[1] https://ballerina.io/spec/lang/2020R1/#section_6.39
[2] https://github.com/ballerina-platform/ballerina-spec/issues/435

**Comment by jclark** [comment]
#435 specifies the final design.

1. No restrictions beyond what is in grammar
2. That is compile-time error. There is a left side and a right side: `from X` is the left side; `join Y` is the right side. The on condition is `left-expr equals right-expr` where left-expr uses variables bound by the left side and right-expr uses variables bound by the right size. The semantics in #435 would not be implementable without this.
3. Yes.

If this doesn't answer your questions, please add further questions to #435.
