### ISSUE TITLE
Ambiguity is caused by xml-step-extend component in xml-step-expr

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-spec#536]
**Description:**

XML step expr is defined as:
```
xml-step-expr := expression xml-step-start xml-step-extend*
```

As a result:
```
foo/<bar>[baz]   ----(1)

foo/<bar>.baz()   ----(2)
```

(1) Matches to both:
 - `xml-step-expr` where `[baz]` is the `xml-step-extend` component
 - `member-access-expr` where container-expr is `expression xml-step-start`

Similarly (2) matches to `xml-step-expr` and `method-call expr`.

**Comment by jclark** [comment]
The match to xml-step-expr should take precedence.

**Comment by SupunS** [comment]
Noticed that (1) also matches to a third grammar rule: binary-expr with a type-cast-expr as denominator, where `[baz]` is a list constructor.

**Comment by jclark** [comment]
This ambiguity is resolved by the fact that `/<` lexes as a single token.

**Comment by SupunS** [comment]
So in that case something like `a/<b>c` becomes an invalid code. User has to put a space in between as: `a/ <b>c` or put parenthesis `a/(<b>c)`.

I was thinking, if the parser considers `a/<b>` as xml-step-expr, then the entire-expression is a syntax error. But  if it considers `<b>c`  as a type-cast, then its syntactically valid. So parser could proceed with the second option.
If it comes to ambiguity as above, precedence could be used to pick a one.

**Comment by jclark** [comment]
Yes, it would be invalid. That's normal with tokenization in C-family languages. Same as `x<<float>y`. If you want to change the tokenization design here, please file as separate bug.
