### ISSUE TITLE
Clarification on predefined module prefixes

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#538]
**Description:**
8.1 Import declaration, says:
```
A module prefix of t, where t is one of error, object or xml, is predeclared as referring to the lang.t lang library module, but this can be overridden by an import-decl. 
```

Say I have the following program.
```ballerina
import ballerina/lang.'xml as x;
public function main() {
  xml y = xml `<elem></elem>`;
  var c = 'xml:concat(y, "hello"); // predefined prefix is intact
}
```
When we import `lang.xml` module as a different prefix, is the predefined prefix still valid?

Is this part `...,  but this can be overridden by an import-decl. ` talking about a scenario where some module is imported as prefix `xml`, hence `xml` now refers to that imported module.

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
If you `import ballerina/lang.xml` as something other than `xml`, the predefined prefix `xml` is still value.

> but this can be overridden by an import-decl

This is talking about when a module is imported `as xml`.
