### ISSUE TITLE
Clarification regarding `readonly` fields of objects/records where the field's type is an object type

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#540]
**Description:**

**Case I**
The spec says for a `readonly` field `readonly T x;` in a record/object, the effective type of the field is `T & readonly`.

> If an individual-field-descriptor specifies readonly, then there is also a constraint that the field has its read-only bit set. Furthermore, the type of the field is the intersection of readonly and the type specified by the type-descriptor.

> When an object-field-descriptor includes readonly, the type of the field is the intersection of readonly and the type specified by the type-descriptor.

Does this mean when `T` is an object type, it has to be an abstract object (an object type in https://github.com/ballerina-platform/ballerina-spec/issues/535 terms) because we only allow an intersection with readonly for abstract objects?

What if `T` is a `readonly object`? 

```ballerina
type AbstractController abstract object {
    function getValue() returns int;
};

type DefaultController readonly object {
    function getValue() returns int {
        return 0;
    }
};

type Config record {|
    readonly AbstractController c1; // OK, effective type `AbstractController & readonly`

    readonly DefaultController c2; // effective type `DefaultController & readonly`
                                   // which we do not allow a user to write? 
|};
```

**Case II**
Similarly, if we see `map<T> & readonly`, we expect the values added to this map to be of type `T & readonly`. So I guess we have a similar concern there too (e.g., `map<DefaultController> & readonly`).

**Related Issues:**
https://github.com/ballerina-platform/ballerina-spec/issues/535

**Comment by jclark** [comment]
This

> the intersection of readonly and the type specified by the type-descriptor

means "the set consisting of every shape that both is a member of the set of shapes denoted by the type-descriptor and has its read-only bit set".

So in **Case I** both `c1` and `c2` are fine: `c1` is OK and its type can be written `readonly & AbstractController`; `c2` is also OK because the type denoted by DefaultController contains only shapes that have their read-only bit set.

I need an example to answer your **Case II**.

**Comment by MaryamZi** [comment]
In **Case II** I meant something like

```ballerina
public function main() {
    map<DefaultController> & readonly m = {
        k1: v1,
        v2
    };
}
```

Here as the contextually expected type for `v1` and `v2` we use something like `DefaultController & readonly`. So the concern was the same as that of Case I. Given that both `c1` and `c2` are OK in Case I, I guess this is also OK?

Basically we can use a `DefaultController` value wherever an immutable value is expected. We just can't write `DefaultController & readonly` explicitly?

**Comment by jclark** [comment]
Yes, there are two levels:

- syntactic level, which deals with type *descriptors*; at this level we have intersection type descriptors e.g. `T1 & T2`
- semantic level, which deals with types (sets of shapes); at this level we have set intersection

We specify the meaning of the syntactic level in terms of the semantic level. In the case of a field `readonly T x;` this is at the syntactic level, and we are explaining it in terms of the semantics level, not desugaring it to other syntax.

Your example is OK provided that the static type of v1 and v2 is a subtype of `readonly`: this is what is needed to guarantee that at runtime the values will have the read-only bit set.

**Comment by MaryamZi** [comment]
All clear now, thank you!

**Comment by jclark** [comment]
One point to note is that `readonly` is deep so `map<T> & readonly` is the same as `map<T & readonly> & readonly`

**Comment by MaryamZi** [comment]
Ack, this is how we have modeled it in the implementation too.
