### ISSUE TITLE
Should lang lib functions be considered a part of the shape in objects?

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-spec#543]
Consider the following scenario:
```ballerina
type Person object {
    string name = "";
    int age = 0;

    public function toString() returns string {
        return self.name + ", " + self.age.toString();
    }
};

type Employee object {
    string name = "";
    int age = 0;
    string designation = "";
};

public function main() {
    Employee e = new;
    Person p = e; // This currently fails. Incompatible types
    
    string s = e.toString() // but it looks like `Employee` has a `toString()` method
}
```
The above fails since there isn't a `toString()` method defined in the `Employee` object. But since `toString()` is provided by the `lang.value` lib, calling `e.toString()` would still work. Wouldn't this kind of be confusing since lang lib functions like `toString()` seem like implicitly defined functions available in all objects?

**Comment by jclark** [comment]
lang.value functions are not available on expressions of type object. See  https://ballerina.io/spec/lang/2020R1/#section_6.20

Se `e.toString()` is a compile-time error.

**Comment by pubudu91** [comment]
> lang.value functions are not available on expressions of type object. See https://ballerina.io/spec/lang/2020R1/#section_6.20

It looks like we totally misread and misunderstood the above and the [`toString()`](https://github.com/ballerina-platform/ballerina-spec/blob/d85f8abc54cc83c1ea183687991e95e14a54327e/lang/lib/value.bal#L114) definition. Because of that we were under the impression that we should be able to do `v.toString()` for objects as well. But I guess we can do `value:toString(v)` for objects. We'll correct this in the implementation. Thanks!
