### ISSUE TITLE
`readonly` as the contextually expected type with a constructor expression

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#554]
**Description:**
Can `readonly` be used as the contextually expected type with a constructor expression? If so, what would the inherent type of the value created be?

For example,

```ballerina
readonly x = {
    a: 1,
    b: str, // where `str` is a string-typed variable
    [computed_key]: rd // where `rd` is a readonly-typed variable
};
```

Should this be allowed with the inherent type possibly being 

`readonly & map<readonly>`

or

```ballerina
readonly & record {|
    readonly ONE a; // where ONE is the singleton `1`
    readonly string b;
    readonly...;
|}
```

And similarly for a list-constructor-expression can we use `readonly & readonly[]` or `readonly & [T1, T2]`?

**Comment by jclark** [comment]
You would infer the type in the same way as if you said `var x`, except that it would be `readonly`. This is part of #392.

**Comment by MaryamZi** [comment]
Ack, thank you.
