### ISSUE TITLE
Clarification regarding "fromJsonWithType" langlib method

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-spec#556]
Hi @jclark ,

Let's say we want to convert `A` json to `B` record type which has a field with a union type
```ballerina
type B record {
    xml|string p;
};

public function main() {
    json A = {p: "<b>xml or string</b>"}
}
```
In here to which type we have to convert (to a `string` or a `xml`) ?

This question occurs when we have a `JSON` with numeric value and `record` with union of numeric types
What are the rules that we should follow in situations like this ?

**Related Issues:**
#353

**Comment by jclark** [comment]
`fromJsonWithType` should only do something different from `cloneWithType` if `cloneWithType` would produce an error. In your case:

```
json j = {p: "<b>xml or string</b>"};
record { xml|string p; } r =check  j.cloneWithType();
```
`cloneWithType` would succeed. The value of the `p` field is already a string and no conversion is necessary.

`fromJsonWithType` does not behave differently from `cloneWithType` as regards numbers.

**Comment by dulajdilshan** [comment]
`toJson` converts the `xml` values to `string` values and `fromJsonWithType` should do the inversion of `toJson`. Isn't there a conflict with the above?

**Comment by jclark** [comment]
`toJson` is a down conversion: it loses information. The information cannot be recovered from the type in case of a union type like `xml|string`. So I think the simplest solution is for `fromJsonWithType` to behave the same as `cloneWithType`, except when `cloneWithType` would produce an error.
