### ISSUE TITLE
Is forward referencing in locally define types allowed?

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#561]
**Description:**
Local type definition statement says:
`A local-type-defn-stmt binds the identifier to a type descriptor within the scope of the current block.`
Does this mean forward referencing a locally defined type is allowed in another locally defined type?

```ballerina
function foo() {
    type A B;
    type B int;
}
```

Then the second sentence says: 
`The type-descriptor is resolved when the statement is executed.`
I felt that the second sentence means that forward referencing is not allowed, when we evaluate the statement `type A B` even though `B` is a known name, we don't know the type of `B`, as that statement is not evaluated and we can't complete evaluating the first statement.

Module-level type definitions do not say anything in this regard, but in implementation, we do allow forward referencing.

**Comment by jclark** [comment]
For module-level definitions, the spec says

> The import declarations must come before other declarations; apart from this, the order of the definitions and declarations at the top-level of a module is not constrained

so you are right to allow forward referencing for modules.

Generally, the scope of a block-level declaration starts from the point where it occurs. I think we should stick to this for types, which would mean forward referencing is not allowed.

This means that you can't have mutually recursive local types:

```
type A record {
   B? b;
};
type B record {
  A? a;
};
```

but I think we can live without that.

**Comment by rdhananjaya** [comment]
Ack, thank you.

Note: I edited the question, your answer is valid for the modified question.
