### ISSUE TITLE
Static type of a  type-cast-expr

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#564]
**Description:**
For the type cast expression, the spec says

```
type-cast-expr := < type-cast-param > expression
type-cast-param := [annots] type-descriptor | annots
```

> Let T be the static type described by type-descriptor, and let TE be the static type of expression. Then the static type of the type-cast-expr is the intersection of T and TE', where TE' is TE with its xml shapes and numeric shapes transformed to take account to the possibility of the implicit conversion and numeric conversion specified in the previous paragraph.

So, where `boolean b = true;` will the static type of `<json> b` be `boolean` since it has to be the intersection of `T` (`json`) and `TE'` (`boolean`)?

But the [section on "Precise and broad types"](https://ballerina.io/spec/lang/2020R1/#section_6.2.3) also says (extracted)

> Expressions in fact have two static types, a precise type and a broad type.

and

> For a type-cast-expr, the precise type and the broad type are the type specified in the cast.

Doesn't this imply the static type would be `json` for the same example?

**Comment by jclark** [comment]
The last sentence you quoted (last para of "Precise and broad types") is out of date. I think it can just be deleted.

**Comment by MaryamZi** [comment]
Ack. The implementation uses the type in the cast as the static type, we'll fix this to use the intersection.
