### ISSUE TITLE
add default conversion of RawTemplate to string for a subset of raw templates

### ISSUE THREAD

**Issue by sanjiva** [ballerina-platform/ballerina-spec#566]
Using string templates is useful for io:println. Is there a way to avoid having to have the raw templates acquire the contextually expected type and then enforce that for all the parts and have it work nicely?

That is, instead of
```ballerina
io:println(string`hello ${exp1} there`);
```
be able to say
```ballerina
io:println(`hello ${exp1} there`);
```

**Comment by jclark** [comment]
I would suggest `io:println` should test whether its first arg has the type `object:RawTemplate` and, if so, print it by outputting the strings as is and applying itself recursively to the insertions:  `object:RawTemplate` has a distinct type so as to allow this.

**Comment by sanjiva** [comment]
That works well, but the only issue is we won't get compile time errors for this:
```ballerina
int x = 10;
io:println(`hello ${x} there`);
```
when this will give errors:
```ballerina
io:println("hello " + x + " there");
```

Hmm maybe that's ok as the code can call .toString() on the expr after checking the type.

**Comment by jclark** [comment]
I think

```
int x = 10;
io:println(`hello ${x} there`);
```
should give the same result as:

```
int x = 10;
io:println("hello ", x, " there");
```

The latter will convert `x` to a string, right?

**Comment by sanjiva** [comment]
Yes it does.

**Comment by jclark** [comment]
We decided to let io:println take a RawTemplate arg i.e.

```
type Printable anydata|error|PrintableRawTemplate;

type PrintableRawTemplate object {
  *object:RawTemplate;
  Printable[] insertions;
};

function println(Printable...);
```

This doesn't require any language changes.
