### ISSUE TITLE
Matching against match-pattern-list

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-spec#567]
**Description:**
According to spec, match-pattern can be one of the following.

```
match-pattern :=
  var binding-pattern
   | wildcard-match-pattern
   | const-pattern
   | list-match-pattern
   | mapping-match-pattern
   | functional-match-pattern
```

Please consider this example:

```
function foo(any v) returns string {
    match v {
        var a | var b => { 
            return "A";
        } 
        _ => {
            return "B";
        }
    }
}
```

Is this a valid example? There is not a match for `var b`, therefore if can we allow to refer the variable `b` inside the clause?

**Comment by jclark** [comment]
That example is disallowed by the following sentence in the spec:

> All the match-patterns in a given match-pattern-list must bind the same set of variables.
