### ISSUE TITLE
Clarification on 7.8.2.2 Multiple receive action receiving order

### ISSUE THREAD

**Issue by sanjana** [ballerina-platform/ballerina-spec#568]
**Description:**
As [described in the spec](https://ballerina.io/spec/lang/2020R1/#section_7.8.2.2), the grammar of a multiple receive action is as following: 
`multiple-receive-action := <-  { receive-field (, receive-field)* }`

If a mapping constructor is used as the static type of `multiple-receive-action`, does the order of the `receive fields` matter?
Should the `receive fields` be inserted in to the indexes of the map as same as the order that was defined by the programmer in the source code or, should those be inserted in the order which the values are being received?

**Suggested Labels:**
lang
   
**Code sample that shows issue:**

```
import ballerina/io;

public function main() {
	worker w1 {
	   150 -> w3;
	}

	worker w2 {
	   200 -> w3;
	}

	worker w3 {
	   map<int> m = <- {w2, w1};
           io:println("m: ", m);
	}
}
```
Suppose the receiving value of **w1** will be available first, and next the value of **w2** will be available. If so, when inserting to the map, should the value of **w1** be inserted to the first index of **m** or, as defined by the programmer, should the value of **w2** be inserted in the first index of **m** by the compiler, when it becomes available?

As an example, should the out put of the above code be: 
`m: w2=200 w1=150` or `m: w1=150 w2=200`?

(A [PR I sent here](https://github.com/ballerina-platform/ballerina-lang/pull/24556) produces the output `m: w2=200 w1=150` in this case.)

**Related Issues:**
[[Spec Deviation] "Multiple receive action" is not supported ](https://github.com/ballerina-platform/ballerina-lang/issues/18163)

**Comment by jclark** [comment]
As far as the spec is concerned, maps are not ordered, so either output is fine.
