### ISSUE TITLE
[Transaction] Clarification on explicit handling error while committing

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-spec#569]
**Description:**
Please consider the samples below.

```ballerina
function foo() returns error? {
   transaction {
       foo();
       check commit;
       bar();
   }
}

transactional function bar() {
 ...
}
```

In the above scenario, we can make sure that the scope following commit-action is not transactional at compile time. Hence, this is an compilation error.

```ballerina
transaction {
    var result = commit;
    if (var is error) {
      rollback;
    }
}
```

Here, since the user handles the error manually, we cannot decide that the scope is non transactional. 

How should we consider the scope following the commit action in this case? 

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
After the commit-action completes execution, the strand is not in transaction mode (regardless of the result of the commit-action).
