### ISSUE TITLE
Add `array:sort` function

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#572]
Should also have `array:sort` function with arguments

- `key` specifying function (same role as expression in `order by` clause)
- `direction` specifying `ascending` or `descending`

_Originally posted by @jclark in https://github.com/ballerina-platform/ballerina-spec/issues/438#issuecomment-662781179_

**Comment by jclark** [comment]
The compiler needs to check a few things that cannot be expressed in the signature:

- if a key function is specified as an argument, then its return value must be an ordered type
- if there is no key function, then the member type of the array must be ordered type

**Comment by lasinicl** [comment]
@jclark 
Should the `direction` be type `string` or a `boolean` specifying the direction `isAscending` or not?

**Comment by jclark** [comment]
The former, which should be specified with an enum

```
public enum SortDirection {
   ASCENDING = "ascending",
   DESCENDING = "descending"
}

// any ordered type is a subtype of this
public type OrderedType ()|boolean|int|float|decimal|OrderedType[];

public function sort(Type[] arr, SortDirection direction = ASCENDING,
        (function(Type val) returns OrderedType)? key = ()) returns Type[] = external;
```

**Comment by sanjiva** [comment]
Shouldn't we have string in OrderedType and say its going to be ordered based on code point?

**Comment by jclark** [comment]
@sanjiva Yes, that’s an mistake in my comment (which I will edit): the spec includes string.

**Comment by lasinicl** [comment]
@jclark 
> The former, which should be specified with an enum
> 
> ```
> public enum SortDirection {
>    ASCENDING = "ascending",
>    DESCENDING = "descending"
> }
> 
> // any ordered type is a subtype of this
> public type OrderedType ()|boolean|int|float|decimal|string|OrderedType[];
> 
> public function sort(Type[] arr, SortDirection direction = ASCENDING,
>         (function(Type val) returns OrderedType)? key = ()) returns Type[] = external;
> ```

According to the spec an array can be returned from the key specifying function. If we consider the examples given below what logic should be followed to sort the given arrays?
```
int[][] arr = [[1, 2], [1, 0], [2, 1]];
int[][] sortedArr = arr.sort("descending", function(int[] x) returns int[] {
     return x;
});
```
```
int[][] arr = [[1, 2], [1, 2, 1], [1, 3]];
int[][] sortedArr = arr.sort("descending", function(int[] x) returns int[] {
     return x;
});
```
A suggested logic is given in 
https://docs.google.com/document/d/1dlYHxipvbMR3K0VoV03uID-jJJa9Ta8H05_COVkEtxo/edit?usp=sharing

**Comment by jclark** [comment]
Semantics is the same as `order by` clause (https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/array.bal#L163):

https://ballerina.io/spec/lang/master/#section_6.36.5

**Comment by jclark** [comment]
The `order by` clause and `array:sort` should be sharing code. There's a lot of complexity that you shouldn't be implementing twice:

https://ballerina.io/spec/lang/master/#ordering

**Comment by lasinicl** [comment]
@jclark Thank you!
