### ISSUE TITLE
Issue in match-pattern-list execution with match-guard

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-spec#576]
**Description:**
If there are several match-patterns in single match-clause with match-guard, how does the execution happen among the below options?

1. If the attempted match succeeds, and executed value for match-guard fails, then starts from next match-pattern in same match-clause to check
2. If the attempted match succeeds, and executed value for match-guard fails, then move to next match-clause.

**Comment by jclark** [comment]
The answer is 2.
