### ISSUE TITLE
Included record parameters

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#578]
The idea of this feature is that that a parameter list can include a record type R using `*R` (just as in a record type descriptor), and the effect is that the fields of the record behave like named parameters to the caller.

Suppose you have a function

```
// Definition
type Options record {
   boolean a = false;
   boolean b = false;
   boolean c = false;
};
function foo(string s, Options options = {}) { }
// call
foo("s", { a: true });
```

With the included record parameter feature, the function definition and call become:

```
function foo(string s, *Options options) {}
foo("s", a = true);
```

The last parameter in the definition of foo is an included record parameter. From the point of view of the function body, it behaves as if the `*` was not there: the body of foo gets access to the parameter only via the options parameter names; the field names are not in scope within the function body. The use of `*` in the declaration changes things for the caller and allows them to use named argument syntax to specify a field of an included record parameter, in addition to using it for named parameters.

To make this unambiguous, we require that
* when a record type R is included with *R, the individual field names must be distinct from the parameter names and from the field names of any other included record parameters
* a field name of an included record parameter can be supplied by the named argument syntax only if the field is specified as an individual field; it cannot use this syntax with a field name that is allowed only because the record type is open

As described in #455, a function call can use `...m` where m is a map to have the same effect as specifying arguments k = v, for each key value pair k, v in m. This should continue to work when the named arguments refer to included record fields.

We can also allow the record to be passed explicitly as an argument, either by position or name. This would be subject to the constraint that the caller must specify either individual fields or the record but not both.

This is a backwards compatible change, but to be useful the standard library would need to migrate to using included record parameters. The migration will be easier if we allow passing the record as an argument in addition to passing the individual fields.

**Rationale**

At the moment, there are two patterns that can be used when a function needs named parameters.

```
type Options record {|
   int size = 10;
  string locale = "en";
|};

// A
public function foo(string x, int size = 10, string locale = "en") { }

// B
public function foo(string s, Options options = {}) { }
```

A is more convenient for a few named parameters. B is more convenient for the function definition when there are lots of parameters or when the definition wants to get the options as a single record, but it provides a completely different user experience.  If instead foo is defined as:

```
// C
public function foo(string s, *Options options) { }
```
it supports being called both like A and like B.

**Comment by sameerajayasoma** [comment]
There can be situations where you want to provide default values for record fields, depending on the function definition. 

```
type Options record {|
   int size = 10;
  string locale;
|};

// A
public function foo(string x, int size = 10, string locale = "en") { }

// B
public function foo(string s, Options options = {locale:"en"}) { }

// C
public function foo(string s, *Options options) { }
```
In the above example, C doesn't support B. Should we allow default values for included record parameters?

**Comment by jclark** [comment]
I think that would get confusing. Consider

```
type Options record {|
   int size = 10;
   string locale = "en";
|};

public function foo(*Options options = {locale: "th"}) { }

function main() {
   foo(size = 12);
}
```
What value does `locale` get? If you want the answer to the `th`, then you have to merge records.

I think it is better to solve this use case by defining a new type descriptor with a different default.

**Comment by jclark** [comment]
We can relax this to allow a field to be specified as named argument if the record type doesn't specify any individual fields with non-never types.

```
type KVPairs record {
	never message?;
	never level?; 
};
function log(string message, LogLevel level, *KVPairs);
```

**Comment by sameerajayasoma** [comment]
Nice! This would allow us to invoke the log function in the following manner to enable structured logging. 

```
log(message = “Something happened”, level = ERROR, id = 5, value = “foo”, path = “/var/log”);
```

This came up while working on the log API design.

**Comment by jclark** [comment]
To accommodate https://github.com/ballerina-platform/ballerina-spec/issues/578#issuecomment-690851647, we refine the rules on field names as follows. First, we distinguish an individual field descriptor that allows a field (e.g. `int x;`) from an individual field descriptor that disallows a field (e.g. `never x?;`). Second, the two bulleted rules change to:

* when a record type R is included with *R, the names of fields allowed by individual field descriptors must be distinct from the parameter names and from the names of fields allowed by individual field descriptors other included record parameters
* a field name of an included record parameter can be used as a keyword if
    * it is allowed by an individual field descriptor, or
    * it is allowed by the record being open, and
         * the record type has no fields allowed by an individual field descriptor, and
         * the record type has individual field descriptors that disallow all parameter names and all fields allowed by individual field descriptors of other included record parameters, and
         * it is the only included record type that is open

@hasithaa Please check.

**Comment by jclark** [comment]
I suspect we need to change the spec in other places to deal with distinction between individual field descriptors allowing and disallowing field names.

**Comment by hasithaa** [comment]
> To accommodate [#578 (comment)](https://github.com/ballerina-platform/ballerina-spec/issues/578#issuecomment-690851647), we refine the rules on field names as follows. First, we distinguish an individual field descriptor that allows a field (e.g. `int x;`) from an individual field descriptor that disallows a field (e.g. `never x?;`). Second, the two bulleted rules change to:
> 
> * when a record type R is included with *R, the names of fields allowed by individual field descriptors must be distinct from the parameter names and from the names of fields allowed by individual field descriptors of other included record parameters
> * a field name of an included record parameter can be used as a keyword if

This should be `named parameters` instead of a `keyword`. 

>   
>   * it is allowed by an individual field descriptor, or
>   * it is allowed by the record being open, and
>     
>     * the record type has no fields allowed by an individual field descriptor, and
>     * the record type has individual field descriptors that disallow all parameter names and all fields allowed by individual field descriptors of other included record parameters, and
>     * it is the only included record type that is open
> 
> @hasithaa Please check.

This should work.
