### ISSUE TITLE
Clarification on join clause

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-spec#581]
**Description:**
According to [1], in a join clause, the`join-on-condition` is mandatory. So this will limit users from writing cross joins without on conditions. Do we need to support cross joins or should we keep it limited to inner equijoins?

```
join-clause := "join" typed-binding-pattern "in" expression join-on-condition
join-on-condition := "on" expression "equals" expression
```

**Suggested Labels:**
n/a
   
**Code sample that shows issue:**
n/a

**Related Issues:**
[1] https://github.com/ballerina-platform/ballerina-spec/issues/435

**Comment by jclark** [comment]
The point of a `join` compared to a nested `from` is that it does only one iteration over the right side of the join, and it can efficiently do the join using a hash table.

What would extending `join` to this give you that you cannot get from a nested `from`?  Please give a concrete use case.

**Comment by grainier** [comment]
I understand your point. I don't see having such use-case. Hence, closing the issue.
