### ISSUE TITLE
Support deep value equality for behavioral types

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-spec#582]
**Description:**

The use case for deep value equality for behavioral types(mainly objects) is as follows.

In the current implementation for the assertEquals function in Testerina test framework,
Deep value equality is checked only for anydata type values. For behavioral values, exact equality is checked. 

But based on the usual convention in test frameworks, the expectation for "assertEquals" is to check deep value equality. Since Testerina provides a different behavior for behavioral values, there has been confusion among users.

So, we are looking  for a way to achieve deep value equality for behavioral types. But, the current specification does not provide a way to achieve that.

Is there a possibility to support this in future? @sameerajayasoma @jclark FYA.

**Suggested Labels:**

   
**Code sample that shows issue:**

Following is the current implementation of assertEquals function.

```
public function assertEquals(any|error actual, any|error expected, public string msg = "Assertion Failed!") {
    boolean isEqual = false;
    if (actual is anydata|error && expected is anydata|error) {
        isEqual = actual == expected;
    } else {
        isEqual = actual === expected;
    }
    if (!isEqual) {
        string expectedStr = io:sprintf("%s", expected);
        string actualStr = io:sprintf("%s", actual);
        string errorMsg = string `${msg}: expected '${expectedStr}' but found '${actualStr}'`;
        panic createBallerinaError(errorMsg, assertFailureErrorCategory);
    }
}
```

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/22048

**Comment by jclark** [comment]
Deep equality on objects needs to be defined by user code. I would probably do something like this:

```
else if expected is object { public function equals(object obj) returns boolean; } && actual is object {
  isEqual = expected.equals(actual);
}
```
