### ISSUE TITLE
Remove local type definitions for now

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#589]
Consider The following example. In this example, a local type definition is used inside a closure.

```ballerina
function test1(string s) returns function (record {string name;}) returns record {string name;} {
    type Person record { string name = s;};
    var func = function (Person p) returns Person {
        Person p2 = {}; // Closure includes the `Person` local type definition. 
        return p2;
    };
    return func;
}
```

Above function can be written to support closure as, 
```ballerina
function test1(string s) returns function (record {string name;}) returns record {string name;} {
    type __temp record { string name = s;};
    final typedesc<record { string name;}> Person = __temp;
    var func = function (Person p) returns Person {  // Problem 1: Handling Parameter types.
        Person p2 = <Person>{}; //  Problem 2:  Value creation requires a new langauge feature.
        return p2;
    };
    return func;
}
```

To support this use case, we need a new language feature to create value from a typedesc value. This makes closures more complex to implement.

We have introduced local type definitions, to overcome the limitations of Local class definitions. Now we have object constructors, We don't have this use case anymore. Maybe we can reconsider the usage of local type definitions.

**Comment by jclark** [comment]
Annotations as well as default values cause a problem here.

I think it makes sense to do local types later, and at the same time add support for more cases of using a variable of type typedesc like a type definition.   In particular, `<t>expr` where t refers to a typedesc could give us a way of defining in Ballerina functions that have dependent types.

**Comment by jclark** [comment]
We agreed to do this in today's meeting.
