### ISSUE TITLE
Clarification on calling the close method of a stream

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-spec#592]
**Description:**

1. In queries, if the underlying stream is fully consumed, should the `close` method of that stream get called automatically? Or should the user call that explicitly? (i.e release DB resources after consuming a DB result stream).

2. What should be the behaviour if a user called` close()` on an already closed stream?

3. Does, the successful completion of a stream consumption and explicitly calling `close()` on a stream puts the stream in the same state, or two different states (fully consumed & closed)? (i.e to provide more meaningful panic messages).
   
**Code sample that shows the issue:**
n/a

**Related Issues:**
[1] https://github.com/ballerina-platform/ballerina-distribution/issues/730

**Comment by jclark** [comment]
My mental model is that there are three states:

1. open
2. consumed
3. closed

When the stream has been fully consumed, it should automatically release resources and transition to the consumed state.

`close` is allowed in either the open or the consumed states. In the former case, it will release resources. In both cases, it will transition the stream to the closed state.

So to answer your questions.
1. no and not necessary, but the resources should be released automatically
2. panic - that's a programming error
3. different states

**Comment by jclark** [comment]
Long-term, https://github.com/ballerina-platform/ballerina-spec/issues/427 would help ensure that close gets calls when necessary.

**Comment by grainier** [comment]
I drew the method invocation and state transition to make it clear. But still have some things to get clarified.

![Stream State Flow](https://user-images.githubusercontent.com/3824254/91681025-bdb46b80-eb6a-11ea-98a7-dcb1a9dfc432.png)

1. Is the purpose of the close method to release resources only or releasing resources just a part of it or are those two separate things?
2. Where the resource releasing logic should be written?
3. Further, from what I understood, resource releasing can happen after a next() (when the stream is fully consumed), and after a close() when end-user explicitly closes the stream. So, should the person who writes the iterator be aware and responsible to maintain the states and handle resource releasing within next() & close()?

**Comment by jclark** [comment]
Please propose what you think it should be.

**Comment by grainier** [comment]
In my opinion, resource releasing logic should be written in`Iterator.close()`. And we should enforce the Iterator implementer to make it idempotent. So that, calling it again on an already closed stream should not have any effect. Further, when it comes to auto-closing, Iterator implementer should keep track of the state of the stream (whether it's fully consumed) and call the `Iterator.close()` method accordingly.

In Java also, [1] is required to be idempotent and [2] is strongly encouraged to be idempotent. Moreover, according to [1], `Closeable.close()` closes the stream and releases any system resources associated with it. If the stream is already closed then invoking that method has no effect.

[1] https://docs.oracle.com/javase/7/docs/api/java/io/Closeable.html#close()
[2] https://docs.oracle.com/javase/7/docs/api/java/lang/AutoCloseable.html#close()

What do you think?

**Comment by jclark** [comment]
@grainier I like your approach better that what I proposed.
