### ISSUE TITLE
Problems with intersecting detail records of error types

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#594]
This is separated out from #550. 

The distinct proposal [proposed](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/distinct/distinct.md#related-changes-to-error-type) that `error<R>` means that the detail record must belong to the type

```
readonly & record {| *R; (anydata|readonly)...; |}
```

(`anydata|readonly` is not actually right: it should be `Cloneable`.)

The problem that this is trying to solve is to avoid problems when intersecting two error types. Suppose ErrorA and ErrorB are two error types. In most cases, you can combine them using the intersection operator. But there are some cases where this doesn't work.

One case is when ErrorA and ErrorB both have detail records, but they are not both open, e.g.

```
type ErrorA error<record { string a; }>;
type ErrorB error<record {| string b; |}>;
```

In this case `ErrorA & ErrorB` is equivalent to `never`, and so legal.

Another case is when one is open to anydata and the other has an error field, e.g.

```
type ErrorA error<record { error a; }>;
type ErrorB error<record { string b; }>;
```
In this case also,  `ErrorA & ErrorB` is equivalent to `never` because records are open to anydata by default, and error is in Cloneable but not anydata. (The default error detail record is `record {|...Cloneable; |}`.)

The spec at the moment doesn't say anything about this, i.e. `error<R>` means simply that the detail record belongs to R.

The issue is how the spec should address this problem.

**Comment by jclark** [comment]
My current thinking is to say that:

- in an error type descriptor `error<R>`, R must refer to an inclusive-record-type-descriptor (i.e. one that uses `{ }` rather than `{| |}`)
- when used in an error type descriptor, an inclusive-record-type-descriptor is interpreted as being open to Cloneable rather than open to anydata

**Comment by dulvinw** [comment]
Is it an error to use an exclusive record type descriptor as the detail type of an error?

**Comment by jclark** [comment]
@dulvinw The proposal in https://github.com/ballerina-platform/ballerina-spec/issues/594#issuecomment-678886940 is that it should be an error. The language design team should discuss this to confirm.

**Comment by jclark** [comment]
We are OK with https://github.com/ballerina-platform/ballerina-spec/issues/594#issuecomment-678886940

**Comment by hasithaa** [comment]
@jclark I see some usability issues with the proposal in https://github.com/ballerina-platform/ballerina-spec/issues/594#issuecomment-678886940.  Consider the following code. 

```ballerina
import ballerina/lang.'value;

// Created as a separate type to access details easily. 
type MyErrorDetails record {
  string extramsg;
};

type MyError error<MyErrorDetails>;

public function 
main () {
  MyError err = error MyError("abc", extramsg = "hello");

  MyErrorDetails d1 = err.detail(); // (1) Compile time error,
  
  record {|
     string extramsg;
     value:Clonable...;
  |} & readonly  d2 = err.detail();   // Valid
}
```
(1) is a compile-time error,  because the error details record is open to Clonable instead of anydata and that makes MyErrorDetails is no longer a subtype.

**Comment by jclark** [comment]
Hmm. I think the first bullet of https://github.com/ballerina-platform/ballerina-spec/issues/594#issuecomment-678886940 just isn't going to work.

**Comment by jclark** [comment]
For Swan Lake, I would suggest:

- don't do the change in https://github.com/ballerina-platform/ballerina-spec/issues/594#issuecomment-678886940
- standard library should use `*error:Detail;` in record type descriptors for error detail records

I don't think it's worthwhile for the language to impose requirements on the openness of the error detail records, since this would be making things harder to use only to avoid a problem in the relatively rare case of intersecting two user-defined error detail record types, which will get a compile-time error anyway (since an intersection that is equivalent to `never` is an error).

**Comment by hasithaa** [comment]
I assume `error: Detail` is something like this. 
```
// Module lang.error
type Detail record {|
  value:Clonable...;
|}
```

This means, `lang.error` is depending on `lang.value`

**Comment by jclark** [comment]
The definition of Cloneable is repeated (privately) in lang.error to avoid the dependency:

https://github.com/ballerina-platform/ballerina-spec/blob/5dca5172dccaf4e955fd162216a922e1ea7e3e04/lang/lib/error.bal#L21

**Comment by jclark** [comment]
We agreed to undo this change as suggested in https://github.com/ballerina-platform/ballerina-spec/issues/594#issuecomment-734027653.

**Comment by KavinduZoysa** [comment]
@jclark, since the compiler checks whether the Detail type is a subtype of map<Clonable> for each error type descriptor, is it still mandatory for standard library error details to have *error:Detail;?

**Comment by jclark** [comment]
Standard library should do this so that a standard library defined error type can be intersected with a user-defined error type with an error detail that includes a field of type error.

**Comment by MaryamZi** [comment]
Even if the standard library error's detail type includes `*error:Detail;`, it may still not be possible to do this intersection?

For example, 
- the standard library error detail may override the `record-rest-descriptor` with a type that does not include error

```ballerina
type Details record {|
   *error:Detail;
   string code;
   int...;
|}
```

- the standard library error detail may be a closed record

```ballerina
type Details record {|
   *error:Detail;
   string code;
|}
```

For the standard library, do we need to enforce including `*error:Detail;` (and being open to errors disallowing the above two records as detail types), or is it just a preferred approach? 

Even if it is always open to errors, I guess there's still the possibility of the intersection resulting in a compilation error due to conflicts in `individual-field-descriptor`s.

```
type StdLibError error<record { *error:Detail; string code; }>;
type UserDefinedError error<record { error code; }>;
```

**Comment by jclark** [comment]
Standard library authors shouldn't do either of those things either. (But why would they?) This is not a language requirement, just a best practice for the standard library.

**Comment by MaryamZi** [comment]
Was considering these scenarios in case we had to enforce openness to errors, but this wouldn't be an issue since it is just a best practice. Thank you.

**Comment by MaryamZi** [comment]
@jclark, would appreciate clarification regarding the following too.

If a standard library developer includes `*error:Detail;` in their record type definition, when it is part of

1. an exclusive record type descriptor

As discussed in the previous comment, this ideally shouldn't be
- a closed record
- or a record with a rest descriptor that does not allow errors

This would be OK if the rest descriptor allowed errors.

e.g.,
```ballerina
type Details record {|
   *error:Detail; // this inclusion isn't needed here though
   string code;
   value:Cloneable...; 
|};
```

2. an inclusive record type descriptor

```ballerina
type Details record {
   *error:Detail;
};
```

Doesn't the rest descriptor get overridden as `anydata` here?

So, even if standard library developers include `*error:Detail;`, they still have to explicitly define a rest descriptor that allows errors to facilitate intersections with errors? 

If so, shouldn't the best practice for standard library be to have `value:Cloneable` (or a type that includes error) as the rest descriptor instead?

**Comment by jclark** [comment]
I didn't respond to your previous message carefully enough. This

```
type Details record {|
   *error:Detail;
   string code;
|};
```

is not a closed record.  It's the same as:

```
type Details record {|
   value:Cloneable...;
   string code;
|};
```

and this is the way the standard library should do it. Using an inclusive-record-type-descriptor wouldn't work, as you say.

Doing `value:Cloneable...` is fine too, but isn't as convenient because it requires an explicit import of `ballerina/lang.value`.

**Comment by MaryamZi** [comment]
Got it. I misunderstood how inclusion worked here and was under the impression that the following would be a closed record.

```ballerina
type Details record {|
   *error:Detail;
   string code;
|};
```

Related to inclusion with open records, if I want to use record type inclusion with an open record and disallow additional fields, I guess I would have to override the record rest descriptor with `never`?

```ballerina
type Foo record {|
   int i;
   int j;
   int...;
|};

type Bar record {|
    *Foo;
    never...;
|};
```

**Comment by jclark** [comment]
I hadn't though of using `never...` to override, but that's a nice trick.
