### ISSUE TITLE
Declared langlib functions as isolated

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#596]
As part of #145, we need to change the declarations of (almost) all langlib functions to be isolated.

But we need to decide what we are going to do for now about the problem with functions like `array:map` described in https://github.com/ballerina-platform/ballerina-spec/issues/145#issuecomment-668404584. Eventually we need a way for an annotation to say that they are isolated or not according to whether their function argument is isolated, but we don't have that yet.  So our choices are:

1. declare both the function and the function argument as isolated (use with non-isolated function arguments won't compile)
2. declare neither as isolated (some functions that should be isolated won't be recognized as such)
3. declare function as isolated and function argument as not isolated (some invalid programs will get through)
4. invent the annotation syntax now (maybe related #521)

For the key argument of the new sort function, I think we should do 1. I don't see a need for that to be non-isolated.

**Comment by jclark** [comment]
My inclination is to do 2 for now (apart from `array:sort`), to avoid breaking code. @MaryamZi @hasithaa What do you think?

**Comment by jclark** [comment]
Need to think about whether `future:cancel` is isolated.

**Comment by jclark** [comment]
`isolated` is a bit different from #521 because `isolated` is a qualifier not a type, and you cannot give a user-defined name to a qualifier. So I think the annotation for this will be its own thing.

I suggest we do it like this:

```
public isolated function filter(Type[] arr, @isolatedParam function(Type val) returns boolean func) returns Type[] = external;
```

`@isolatedParam` is allowed only when:

- in langlib
- applied to a parameter
- parameter must be of function type
- must be parameter of function declared as isolated

Semantic is that when the function is in a context that requires it to be isolated, then parameter's function type must also be isolated.

Declaring the function as isolated is consistent with the general principle that an annotation should increase the static checking rather than making an invalid program valid.

**Comment by SupunS** [comment]
Can we do the same without the annot `@isolatedParam`?
Either by:

1. Using `isolated` qualifier for the function-type-descriptor of the param. e.g:
```ballerina
public isolated function filter(Type[] arr, isolated function(Type val) returns boolean func) returns Type[] = external;
```
2. Or, making parameters to infer the isolate-ness from the function's isolate-ness.

**Comment by jclark** [comment]
Neither of these work. If the parameter was declared as isolated, then you would not be able to pass a non-isolated function to `filter`. It is possible for an isolated function can take a function parameter that is not isolated: for example, it can store the value of the parameter somewhere, rather than calling it; it would be weird to special case parameters of function type here, because you can have e.g. records containing functions.
