### ISSUE TITLE
Syntax to make type of floating point literals explicit

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#6]
At the moment, a floating point literal is treated as float or decimal based on the contextually required type, as set by for example a type cast. It would be better to have a specific syntax so to allow all numeric values to be serialised unambiguously as literals.

Therefore we will allow suffixes of `d` and `f` to indicate decimal and float literals respectively.

We would also get rid of type casts from simple-const-expr.

**Comment by rdhananjaya** [comment]
Do we allow type coercion between decimal and float literals when it's safe, or is it an error?
```ballerina
decimal d = 1.0f;
```

**Comment by jclark** [comment]
@rdhananjaya We do not allow that. There are no implicit conversions between numeric types.

**Comment by rdhananjaya** [comment]
```ballerina
float|decimal a = 1.0f;
float|decimal b = 1.0d;
float|decimal c = 1.0; // do we consider this to be ambiguous type error or default to float?
```

**Comment by jclark** [comment]
@rdhananjaya Default to float: no change in that respect. (Please open a new issue for separate questions.)
