### ISSUE TITLE
Clarification regarding expression style string value for a `table` type value

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-spec#600]
**Description:**
According to the spec[[1](https://ballerina.io/spec/lang/master/#ToString)] the expression style string value of a `table` type value is `table key(k) [R1,R2]` where R1,R2 is in expression style.  
What should be the expression style string value for a keyless table?
`table key() [R1,R2]` or `table [R1,R2]`

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**
https://github.com/ballerina-platform/ballerina-spec/issues/499

**Comment by jclark** [comment]
I prefer the former (keyless tables are an unusual case, so it's good to make that explicit).
