### ISSUE TITLE
[On Fail] Clarification on handling error with loops

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-spec#603]
**Description:**
Please consider the three samples below. Should the loop and the retry continue after the failure ?

**(1) If an error is thrown within while, should the loop continue and get a output as A?**

```ballerina
function foo()  {
  int count = 0;
   while(count < 5) {
     count += 1;
     if(count == 3) {
        fail error("Custom Error");
     } else {
        io:println("Not 3");
     }
   } on fail var e {
       io:println("Error Caught ");
   }
   io:println("Execution continues after While");
}
```
Expected output:

(A). Not 3
       Not 3
       Error Caught
       Not 3
       Not 3
       Execution continues after While

(B). Not 3
    Not 3
    Error Caught
    Execution continues after While

**(2) If an error is thrown within retry and it's caught at on-fail, should the retry continue and get the output as A?**

```ballerina
function retryError() returns string|error {
    string str = "start";
    int count = 0;
    retry (3) {
        count = count+1;
        if (count < 3) {
            str += (" attempt " + count.toString() + ":error,");
            fail error("Throw error");
        }
        str += (" attempt "+ count.toString() + ":successful");
    } on fail error e {
         io:println("Error caught");
    }
    str += (" Execution continues");
    io:println(str);
    return str;
}
```
Expected output:

(A). Error caught
    Error caught
    start attempt 1:error, attempt 2:error, attempt 3:successful Execution continues

(B). Error caught
    start attempt 1:error, Execution continues

**(3) If the answer for (2) is _it should not retry again_, can we throw an error again from on fail to continue the retrying ?**

```ballerina
function retryError() returns string|error {
    string str = "start";
    int count = 0;
    retry (3) {
        count = count+1;
        if (count < 3) {
            str += (" attempt " + count.toString() + ":error,");
            fail error("Throw error");
        }
        str += (" attempt "+ count.toString() + ":successful");
    } on fail error e {
        io:println("Error caught");
        return error("Retry Error");
    }
    str += (" Execution continues");
    io:println(str);
    return str;
}
```
Expected output:

 Error caught
 Error caught
 start attempt 1:error, attempt 2:error, attempt 3:successful Execution continues

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
Are these questions not answered by https://ballerina.io/spec/lang/draft/v2020-09-22/#section_7.25 ?

Executing `X on fail Y` executes X exactly once.

**Comment by pcnfernando** [comment]
Understood. Thank you
