### ISSUE TITLE
Clarification on type resolving query expressions with XML

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-spec#604]
**Description:**
Consider the below code sample (source: https://github.com/ballerina-platform/ballerina-lang/issues/25949). Currently, the query expression within `${}` get type resolved to `xml:Element[]`. Because the static type of the expression in the initial from clause gets resolved to an `xml:Element`(NonSequenceType). Since `<doc/>` doesn't support `xml:Element[]` below sample will result in `expected '(int|float|decimal|string|boolean|xml)', found 'xml:Element[]'`.

So can you please clarify following;
1. Should this sample run without any errors?
2. Should this get type resolved to `xml` instead of `xml:Element[]`?
3. If so, if there's no contextually exprected type and the static type of the from clause is XML, XML_ELEMENT, XML_PI, XML_COMMENT or XML_TEXT, should we resolve the type of the query expression to `XML`?

**Suggested Labels:**
n/a

**Code sample that shows issue:**
```ballerina
    xml ax = xml `<doc> ${from var x in payload/<data>/<*> 
             let var year = <xml> x/<'field>[2]
             let var value = <xml> x/<'field>[3].name
             select xml `<entry>${<string> value}</entry>`} </doc>`;
```

**Related Issues:**
- https://github.com/ballerina-platform/ballerina-lang/issues/25949

**Comment by jclark** [comment]
The spec says:

> If there is no contextually expected type, then it is determined from the static type of the expression in the initial from clause; it is a compile-time error if this static type is not a subtype of one of the basic types that a query expression can construct.

This means that if you have an expression E `from var x in E1 select E2` and there's no contextually expected type for E, and E1's static type is a subtype of xml,  then you should produce a value of type xml.

In this case:

* `payload/<data>/<*>` has type `xml<xml:Element>`, which is a subtype of xml, so the result of the query expression should be a subtype of xml
* the type of the select expression is `xml:Element`, so the type of the query expression should be `xml<xml:Element>`

Note that `xml:Element` _is_ a sequence type: it's a sequence of length 1 and a subtype of xml (just as `"x"` is a string).

Does this answer your question?

**Comment by grainier** [comment]
I understand. But in the following scenario, what would be the resolved type of `outputNameString`? Should it be string, string[] or a compilation failure? 

```ballerina

type Person record {|
   string firstName;
   string lastName;
   int age;
|};
    
Person p1 = {firstName: "Alex", lastName: "George", age: 23};
Person p2 = {firstName: "Ranjan", lastName: "Fonseka", age: 30};
Person p3 = {firstName: "John", lastName: "David", age: 33};

Person[] personList = [p1, p2, p3];

var outputNameString =
            from var person in personList
            where person.age >= 30
            select (person.firstName).concat(" ");
```

**Comment by jclark** [comment]
`string[]`: the basic type of the value created by a query expression defaults to the basic type of the expression following `in` (in this case list, in the previous case xml).
