### ISSUE TITLE
Inherent type of tuple constructor expression

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#61]
Tuple constructor should always create a value with inherent type that is fixed length,  regardless of whether there is a contextually required type. Relates to issue #51.

When there is no contextually required type, inferred inherent type is fixed length and allows each field to have its own type.

When there  us a contextually required type, it is truncated to be of fixed length (the parts after the fixed length must be optional or it would not type check).

Consider whether to change terminology to better reflect semantics, e.g. fixed length list constructor.

**Comment by sanjiva** [comment]
+1 to a terminology change.
