### ISSUE TITLE
Usage of object constructor expression with `var`

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#621]
**Description:**
Section 6.8.1 says:
```
If there is no type-reference, then the applicable contextually expected type T must be definite, 
and the type-ids of the constructed object are the type-ids, if any, induced by T.
```

Does this mean object constructor expr (without type reference) are not allowed with `var` as in `var o = object { .... };`.
If this is the case I assume it is also not allowed when contextually expected type is a object union.

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
It doesn't mean that. It means that you can't say:

```
D1|D2 obj = object { ... };
```

if D1 and D2 are both distinct object types.

**Comment by rdhananjaya** [comment]
Ack thank you.
