### ISSUE TITLE
Subtyping relationship between plain objects and service objects

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#622]
**Description:**
Is it correct to assume that service objects are subtype of plain objects.

```ballerina
type Obj object {
    function foo() returns int;
};

type service Serv object {
    // remote methods ....
    function foo() returns int;
};
```

Is `Serv` a subtype of `Obj`?

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
Yes: the spec says so explicitly in https://ballerina.io/spec/lang/master/#section_5.5.3.3

> If object-network-qual is not present, then an object belongs to the type regardless of whether it is a client object or service object or neither.
