### ISSUE TITLE
Creation of the executable without an entry point

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-spec#626]
**Description:**
Currently if there's no entry point the build succeeds, but the generation of the executable(jar) file fails with the following message:
```
error: no entry points found in '/path/to/file.bal'.

```
The entry points are considered to be the presence of a listener declaration or a main method.
It is not clear in the "Module and program execution" section of the spec whether this should be the case. It could be argued that being able to execute a jar without an entry point is wrong which is the stance taken by the runtime team. Clarity on this section would be useful.
   
**Code sample that shows issue:**
```
public function aFunction() {
}
```
build  with
```
ballerina build file.bal
```
**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/18601

**Comment by jclark** [comment]
The relevant paragraph of the spec is this one:

> This specification does not define any mechanism for processing the program command-line arguments typically provided by an operating system. The Ballerina standard library provides a function to retrieve these command-line arguments. In addition, the Ballerina platform provides a convenient mechanism for processing these arguments. This works by generating a new command-line processing module from the specified root module. The init function of the generated module retrieves the command-line arguments, parses them, and calls a public function of the specified root module (typically the main function). The parsing of the command-line arguments is controlled by the declared parameter types, annotations and names of the public functions. The generated module, which imports the specified root module, becomes the new root module.

At the language level, the program execution model is to initialize all modules and then listen. Calling `main` is a platform-level concept. There is no error in your example as far as the language is concerned.

**Comment by sanjiva** [comment]
But as the compiler is a platform level component, its behavior should be to not build a package unless there's a main or a service.

That is not incompatible with the language spec and therefore acceptable and will satisfy users.

**Comment by jclark** [comment]
Is there an issue with the spec? I don't understand why this is reopened.

**Comment by sameerajayasoma** [comment]
in Ballerina Swan Lake, we now create executables even if there are no entry points in the default module of a package.
