### ISSUE TITLE
Minor clarification on Table 'map' function 

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-spec#627]
@jclark 

I have a confusion with the syntax related to the `map` function of table because it contradicts with the explanation given for the function.

As per the spec [1], it says that "The resulting table will have the same keys as the argument table.", but as per the syntax key type of the table return by the function is `never`. Is this correct? 

[1] https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/table.bal#L85

**Comment by jclark** [comment]
The comment is in the wrong place. Fixed now. Thanks!
