### ISSUE TITLE
Making object type a distinct type just by type inclusion of a distinct type

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#628]
**Description:**
```ballerina
type Foo distinct object {
    int i;
    string s;
};

class Bar {
    *Foo;

    int i = 1;
    string s = "str";
}

public function main() {
    Foo f = new Bar();
}
```

Is `Bar` a distinct object even though definition of `Bar` doesn't specify `distinct` keyword?
It seems without making it a distinct object we can't have a statement like `Foo f = new Bar();`.

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
In this case, the primary and secondary type-ids of Bar are those of Foo, as with object types:

> The set of type-ids induced by an object-type-descriptor is the union of the set of type-ids induced by the type descriptors that it includes. An induced type-id is primary in an object-type-descriptor if and only if it is primary in any of the included type descriptors. It is an error if the induced set of type-ids includes a non-public type-id from another module.

The spec should make it clear that this applies to class definitions as well.
