### ISSUE TITLE
Singleton tuples

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#63]
Singleton tuples could be supported using a trailing comma, as in Python, both for tuples types and for tuple constructors e.g. `(int,)` and `(1,)`.

**Comment by jclark** [comment]
@hasithaa Do you think this would cause any parse problems?

**Comment by hasithaa** [comment]
@jclark I hope after this change following will be the correct behavior. 

parentheses used only for grouping or to give precedence.
- `(int)` same as `int`.
- `(1)` the same as `1`.
- `(int,)` singleton tuple type with int.
-  `(1,)` singleton tuple value.
- `(2 + 3) * 5` a binary expression, where 2+3 is LHS expression and 5 is RHS

I modified the grammar and ran the unit tests, seems like grammar isn't causing any issue.

**Comment by jclark** [comment]
Yes. Correct.
