### ISSUE TITLE
Clarification regarding the `isolated`-ness of `StreamImplementor`'s `next` method

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#634]
**Description:**
Shouldn't the `StreamImplementor` object type's `next` method be `isolated`?

If it is not `isolated`, the iterator object returned for a stream created using such an object cannot be returned via the [`lang.stream:iterator()` method](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/stream.bal#L47) and it could also lead to non-isolated calls from `isolated` stream langlib methods?

The spec currently seems to have the following as the equivalent type - https://ballerina.io/spec/lang/master/#StreamImplementor.

```ballerina
    object {
       public next() returns record {| T value; |}|C;
    }
    | object {
       public next() returns record {| T value; |}|C;
       public close() returns C?;
    }
```

On a separate note, the methods also seem to be missing the `function` keyword.

**Comment by jclark** [comment]
Yes, I agree. Given that stream:iterator.next is isolated, this need to be isolated. Same goes for close (since stream:close is isolated).
