### ISSUE TITLE
Continue listening phase for dynamically started listeners

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-spec#635]
**Description:**
The spec states the following about module listeners

> If at the start of the listening phase of program execution there are no module listeners, then the listening phase immediately terminates successfully. Otherwise, the __start method of each module listener is called; if any of these calls returns an error value, then the listening phase terminates unsuccessfully with this error value as its return value.

> The listening phase of program execution continues until either the program explicitly exits, by calling a standard library function, or the user explicitly requests the termination of the program using an implementation-dependent operating system facility (such as a signal on a POSIX system). In the latter case, the __gracefulStop or __immediateStop method of each registered listener will be called before termination. 

Since it states that the `listening phase of program execution continues until ....` we would like to clarify if this has to happen only for `module listeners` or any dynamically started listeners. By dynamically started we meant the listeners which are not declared as module listeners, but are initiated as objects and the `__start` method is manually called. These can be created anywhere in the program, including inside the main method and resource functions.
If this does not apply to dynamically started listeners, there are listeners that are almost always dynamically started, like a WebSocket client. It listens for messages from the WebSocket server. In this case there has to be a way to let the listening phase of program execution to continue.
   
**Code sample that shows issue:**
Example of a WebSocket client declaration and usage can be found here:
https://ballerina.io/swan-lake/learn/by-example/websocket-client.html

**Comment by jclark** [comment]
This is addressed by #361. Sounds like we need this for Swan Lake. I'll bump the milestone.
