### ISSUE TITLE
Need platform spec for how to specify configurable items

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#636]
This is needed for #41 to work.

**Comment by sameerajayasoma** [comment]
We can't have a `configurable` variable name with the current design if there is a submodule with the same name. 

E.g., Say there are two packages named `x.y` and `x.y.z`. You can't have a `configurable` variable named `z` in module `x.y`.  

This should be recorded in the platform spec.

**Comment by jclark** [comment]
Could also go in language spec as a should: it relates only to language level features.

**Comment by sameerajayasoma** [comment]
The two modules `x.y` and `x.y.z` can be in two different packages. Therefore, we can only detect this if both these packages in the same dependency graph.

**Comment by sameerajayasoma** [comment]
This is not available: https://github.com/ballerina-platform/ballerina-spec/tree/master/configurable
