### ISSUE TITLE
Decide on functions to put in new lang.runtime module

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#637]
lang.runtime module is introduced in #361. We need to decide what else goes in that.

**Comment by hasithaa** [comment]
We need a set of functions to handle information about the authentication and authorization of users and related attributes such as user, scopes, etc.  

In the current implementation, we use `ballerina/auth:InvocationContext` for this, But this is more like a runtime concept, as this is useful in many cases. eg: The Log library want to log the current logged in user. This requirement came up when reviewing the current http auth handler design with @sanjiva.

**Comment by jclark** [comment]
I think lang.runtime should be restricted to things that are language level concepts. The language has no concept of authentication or authorization.

**Comment by jclark** [comment]
We decided on:

* sleep #674)
* get current call stack (#675)
