### ISSUE TITLE
Should type-id include version?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#638]
With #624, following on from #230, import no longer specifies a version. Should type-id continue to specify a version?

**Comment by jclark** [comment]
Conclusion of discussion today was that it should have a platform-specified *discriminator*, which (with the current platform design) would consist of a major version number and possible a repository URL.

**Comment by jclark** [comment]
Discussing with @sameerajayasoma today, we concluded that it would be best to make the type of the discriminator be an array of strings rather than just a string.

**Comment by jclark** [comment]
I am struggling to think of a good name for the corresponding field in `lang.typedesc:ModuleId` (to replace the current `version` field). Any ideas @sameerajayasoma?

**Comment by sameerajayasoma** [comment]
As per the discussion with @jclark, we decided to replace the current version field with an array of strings. The platform spec defines the contents of this array.  

At least, we need to capture the major version suffix and the repository path, in addition to the organization and module name, to identify a module in a program uniquely. I still couldn't come up with a proper name. I will get back to you soon.

**Comment by jclark** [comment]
The ideas I had were:

- `discriminator`
- `platformData`

**Comment by jclark** [comment]
@sameerajayasoma Further to our recent discussion, do we also need to capture the distinction between a package from a repository and from some local on-disk path?

**Comment by jclark** [comment]
Decision today to use `platformParts`.

**Comment by sameerajayasoma** [comment]
> @sameerajayasoma Further to our recent discussion, do we also need to capture the distinction between a package from a repository and from some local on-disk path?

As per today's discussion, we decide to use the repository path. If the package is available in a file system repository, we can use the repository path.
