### ISSUE TITLE
Clarification on bound methods and "isolated"

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#640]
**Description:**

Since the spec says "an isolated method has the same access to the object on which the method is invoked that it has to parameters" we currently consider a method-call as `isolated`, even when the object on which the method is invoked is not `isolated`.

e.g.,
```ballerina
class Foo {
    int[] arr = [];

    isolated function bar() returns int[] => self.arr;
}

isolated function func() {
    Foo f = new;

    int[] arr = f.bar(); // OK, since `bar` is `isolated`?
}
```

The [Bound methods](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/isolated/isolated.md#bound-methods) section of the proposal says

> With the proposed fix to #574, you can get a method bound to a particular object by accessing the method name like a field name. Since isolated methods treats the self variable like a special parameter, the bound method will be isolated only if the method and the object are isolated.

By `isolated` here, do we mean an "isolated expression" which would allow something like

```ballerina
isolated class Array {
    private int[] arr = [];

    isolated function add(int i) {
        lock {
            self.arr.push(i);
        }
    }
}

isolated class Arrays {
    private Array array = new;

    isolated function getAddMethod(int index) returns function (int) {
        lock {
            return self.array.add; // OK
        }
    }
}
```

Or is it related to the type? i.e., if the object or the method is not `isolated` we cannot assign the result to a variable of an `isolated function` type?

If this is the case, I wonder if it feels a bit contradictory with considering a method call to be `isolated` if just the method is `isolated` (even if the object is not). But I guess if this is allowed, we lose information about the object `isolated`-ness once the assignment is done.

Even with a non-`isolated function`-typed variable, since we do not have information about the object, and given that a function type is inherently immutable, isn't it possible that a non-isolated object may be exposed indirectly?

```ballerina
int count = 0;

class Array {
    int[] arr = [];

    function add(int i) {
        count += 1;
        self.arr.push(i);
    }
}

isolated class Arrays {
    private Array array = new;

    isolated function getAddMethod(int index) returns function (int) {
        lock {
            function (int) func = self.array.add;

            return func; // exposes a non-isolated object.
        }
    }
}
```

**Comment by jclark** [comment]
I’m away from my desk, so let me give a short answer to start with.  The bound method case is like this:

```
isolated class Array {
    private int[] arr = [];

    isolated function add(int i) {
        lock {
            self.arr.push(i);
        }
    }
}

class Arrays {
    private Array array = new;

    function getAddMethod(int index) returns isolated function (int) {
         return self.array.add; // OK
     }
}
```

We can treat the function value returned by getAddMethod as isolated because both the type of self.array is an isolated object and the type of add is an isolated function.

**Comment by jclark** [comment]
This is issue #98. Please ask further questions there.

**Comment by MaryamZi** [comment]
> I’m away from my desk, so let me give a short answer to start with. The bound method case is like this:
> 
> ```
> isolated class Array {
>     private int[] arr = [];
> 
>     isolated function add(int i) {
>         lock {
>             self.arr.push(i);
>         }
>     }
> }
> 
> class Arrays {
>     private Array array = new;
> 
>     function getAddMethod(int index) returns isolated function (int) {
>          return self.array.add; // OK
>      }
> }
> ```
> 
> We can treat the function value returned by getAddMethod as isolated because both the type of self.array is an isolated object and the type of add is an isolated function.

Got it, thank you.
