### ISSUE TITLE
Clarification regarding variable access and isolation 

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#644]
**Description:**

1. The spec says regarding "protected" variables

> Only one such variable can occur in the lock statement.

a) I assume the same protected variable can be accessed any number of times? And since in the isolated object case, it is `self` that is considered the protected variable, the following would be valid?

```ballerina
isolated class CurrentConfig {
    private int frequency = 1;
    private decimal factor = 1.0;

    isolated function updateConfig(int frequency, decimal factor) {
        lock {
            self.frequency = frequency; 
            self.factor = factor; 
        }
    }
}
```

b) But the following would be invalid?

```ballerina
isolated boolean accessed = false;

isolated class CurrentConfig {
    private int frequency = 1;

    isolated function updateConfig(int frequency) {
        lock {
            self.frequency = frequency; // access a protected variable.
            accessed = true; // access a different protected variable.
        }
    }
}
```

But wouldn't the same be allowed indirectly with something like

```ballerina
isolated boolean accessed = false;

isolated class CurrentConfig {
    private int frequency = 1;

    isolated function updateConfig(int frequency) {
        lock {
            self.frequency = frequency; // access a protected variable.
            setAccessed(); // `setAccessed` accesses a different protected variable.
        }
    }
}

isolated function setAccessed() {
    lock {
        accessed = true;
    }
}
```

I am not sure I get why we need this restriction. 

2. The spec also says for the body of a function or method declared as `isolated`

> Captured variables must be immutable: if the body is part of an anonymous-function-expr, then any captured variable references must refer to variables that are both final (either explicitly or implicitly) and have a static type that is a subtype of readonly.

a) Does this mean an isolated anonymous-function-expr cannot refer to isolated variables or final isolated objects, even though an isolated function/method can?

```ballerina
isolated int[] array = [];

isolated function getArray() returns int[] {
    lock {
        return array.clone(); 
    }
}

public function main() {
    isolated function() returns int[] fn1 = getArray; // OK

    isolated function() returns int[] fn2 = isolated function() returns int[] {
        lock {
            return array.clone(); // error?
        }
    };
}
```

b) Since the requirement for record default values is that the default value expression itself meets the requirements for an isolated function, this would not apply to record default value closures, right? 

**Related Issues:**
https://github.com/ballerina-platform/ballerina-spec/issues/145
https://github.com/ballerina-platform/ballerina-spec/issues/599

**Comment by jclark** [comment]
1(a) is valid because we need to maintain only the invariant the object (i.e. self) is an isolated root, not each field individually.

1(b) is invalid because the invariant is that each module level variable is an isolated root. The goal of the requirements is to be sufficient to maintain the invariants that each isolated object and each isolated variable is an isolated root. That doesn't mean that everything that they forbid would be a problem. Your example in 1(b) maintains the invariant. But if you don't have some restrictions on accessing multiple isolated variables in a single lock statement, then it is possible to mutate the storage graphs so that they references between them, causing the invariants to be violated.  The one isolated variable per lock statement is a simple requirement, which (I am moderately confident) is sufficient. We can have more complex and liberals rules later: but the important thing at this point is to be confident that the rules maintain the invariants.

2(a) No. Captured variables here means local variables.

2(b) Since we don't have local types, how can it happen for record defaults? There is a similar case with parameter defaults referring to previous parameters, but I don't think we need to count that as capturing.

**Comment by MaryamZi** [comment]
1 (a), (b) - Noted.

2 (a) How about a local final variable with a type that is a subtype of `isolated object {}`?

```ballerina
public function main() {
    final isolated object {
        isolated function add(int i);
        isolated function pop();
    } arr = new Array();

    isolated object {
        isolated function add(int i);
    } addArray = isolated object {
        isolated function add(int i) {
            lock {
                arr.add(i); // OK
            }
        }
    };

    isolated function (int i) fn1  = addArray.add;
    
    isolated function (int i) fn2 = isolated function (int i) {
                                        lock {
                                            arr.add(i); // error?
                                        }
                                    };

}

isolated class Array {
    private int[] arr = [];

    isolated function add(int i) {
        lock {
            self.arr.push(i);
        }
    }

    isolated function pop() {
        lock {
            _ = self.arr.pop();
        }
    }
}
```

2 (b) Can it not happen for record defaults of in-line record type-descriptors? 

```ballerina
public function getArray() returns any[] {
    final Accumulator defaultAccumulator = new Accumulator();

    record {
        int index = 0;
        Accumulator accumulator = defaultAccumulator; // local variable access
    }[] arr = [{index: 101}]; // uses the closure for `accumulator`

    return arr;
}

public function main() {
    record {|
        int index;
        Accumulator accumulator;
    |} rec2 = {index: 100, accumulator: new Accumulator()};

    any[] anyArray = getArray();

    anyArray[2] = rec2; // FillMember for index 1 calls the default value closures
}

isolated class Accumulator {
    private anydata[] arr = ["default"];

    isolated function accumulate(anydata val) {
        lock {
            self.arr.push(val.clone());
        }
    }
}
````

**Comment by jclark** [comment]
For 2(a), we should say final and subtype of `readonly|isolated object {}`
For 2(b), I made a separate issue #645.

**Comment by MaryamZi** [comment]
One more question regarding assignment to variables defined outside the lock statement;

The [7.14.4 Destructuring assignment statement](https://ballerina.io/spec/lang/master/#section_7.14.4) section of the spec says 

> A destructuring assignment with a binding pattern that refers to a variable declared by a module-var-decl that includes isolated is only allowed within a lock-stmt.

The [7.24 Lock statement](https://ballerina.io/spec/lang/master/#lock_statement) section says

> Transferring values out of the lock statement is constrained: the expression following a return statement must be an isolated expression; an assignment to a variable defined outside the lock statement is allowed only if left-hand side is just a variable name and the right hand side is an isolated expression.

Given that assignment to a variable defined outside the `lock` statement is allowed only when "left-hand side is just a variable name", is it possible for a destructuring assignment's binding pattern (`binding-pattern-not-variable-reference`) to refer to an `isolated` variable?

For example,

```ballerina
isolated int i = 1;

final [int, int] & readonly x = [1, 2];

public function main() {
    lock {        
        int j = 2;
        [i, j] = x; // OK according to 7.14.4 but not according to 7.24?
    }
}
```

**Comment by jclark** [comment]
The intended meaning is that your example is not OK: 7.24 says it's not, and 7.14.4 says nothing about this case. I will clarify the wording to be less obtuse.

We could allow some cases of this in the future, but in general it's hard to do.

**Comment by jclark** [comment]
Note that we'll want to do #629 at some point.

**Comment by MaryamZi** [comment]
Noted, thank you.
