### ISSUE TITLE
Defaults in inline local record types

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#645]
In #589, we removed local type definitions. But the discussion in https://github.com/ballerina-platform/ballerina-spec/issues/644#issuecomment-722431956 makes me wonder if we don't have a similar problem just from defaults in local inline record types, e.g.:

```ballerina
function test1(string s) returns function () {
    record { string name = s;}? person = ();
    var func = function () {
        person = {};
    };
    return func;
}
```

@hasithaa What do you think?

**Comment by hasithaa** [comment]
In the implementation, we have handled this (I would say using a hack) for records. But for object fields in an Object constructor, there is a complexity implementing this. 
When considering isolated variables, this feature may add more complexity to implement in the SL time frame.

**Comment by jclark** [comment]
Looks like the implementation can deal with this.
