### ISSUE TITLE
Inclusion of readonly classes

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#649]
**Description:**
The [object-constructor-expression](https://ballerina.io/spec/lang/master/#section_6.8.1) section of the spec says

> The object-constructor-expr is implicitly read-only if the applicable contextually expected type is a subtype of readonly or if the type-reference is present and references a type that is a subtype of readonly. If object-constructor-expr is implicitly read-only, then the object will be constructed with its read-only bit on.

In a scenario where "the type-reference is present and references a type that is a subtype of readonly", what if the object-constructor-expression has additional fields?

Case I - additional fields of types that are inherently or selectively immutable

Should the object be constructed with its read-only bit set, requiring the values specified for the additional fields to also be immutable?

```ballerina
readonly class Foo {
    int i;

    function init(int i) {
        self.i = i;
    }
}

public function main() {
    object { } x =  object Foo { 
        int i = 1;
        map<string> m = mp; // `mp` should be a subtype of `map<string> & readonly`
    }; 
}
```

Case II - additional fields of types that are neither inherently nor selectively immutable?

e.g.,

```ballerina
readonly class Foo {
    int i;

    function init(int i) {
        self.i = i;
    }
}

public function main() {
    object { } x =  object Foo { 
        int i = 1;
        stream<int> str; // can never be a subtype of `readonly`

        function init() {
            int[] arr = [1, 2, 3, 4];
            self.str = arr.toStream();
        }
    }; 
}
```

Would this
1. be allowed, and result in the construction of an object without its read-only bit on? or
2. should this result in a compilation error?

With explicit object-type-inclusion we allow this atm, and the `readonly` bit is never set based on the inclusion.

```ballerina
readonly class Foo {
    int i = 1;
}

class Bar {
    *Foo;

    int i = 2;
    string s = "hello";
}

public function main() {
    Bar bar = new;
    bar.i = 3; // this is also allowed, since only the type of the field is copied

    any val = bar;
    boolean res = val is readonly; // false
}
```

**Comment by jclark** [comment]
I think it's important to preserve the principle that when you use `*T` with objects, you get a subtype. So in your last example above, Bar should be a subtype of Foo (and Foo should be a subtype of `readonly & object { }`). On the other hand, I think it would be weird to make this work:

```
type R readonly & object { };
type O { *R; };
```

So I think we should say:
1. an object type descriptor cannot include (using *T) a readonly class
2. a class C can include a readonly class provided C is also readonly (we could say that it pulls in the readonly but that feels inconsistent with 1)
3. an object constructor can include a readonly class provided  it is creating a readonly object
4. doing `object T { xxx }` where T is a readonly class will make the object constructor create a readonly object (in addition to doing `*T`)

With this:
Case I - object constructed with read-only bit, forcing immutable of additional fields (as with `readonly class`).
Case II - compilation error

Last example: compilation error (which can be fixed by saying `readonly class Bar { }`).

This reminds of a similar problem: #650.

**Comment by MaryamZi** [comment]
Agreed, I also found it a bit inconsistent that `Bar` was not a subtype of `Foo` in the last example. 

+1 for the suggested set of rules, we will incorporate these changes.

**Comment by MaryamZi** [comment]
**Case I**
> I think it's important to preserve the principle that when you use `*T` with objects, you get a subtype. So in your last example above, Bar should be a subtype of Foo (and Foo should be a subtype of `readonly & object { }`). On the other hand, I think it would be weird to make this work:
> 
> ```
> type R readonly & object { };
> type O { *R; };
> ```

@jclark, according to the discussion here, I assume this should result in a compilation error? 

Would appreciate clarification since the previous comment specifically mentions `readonly` classes

> 1. an object type descriptor cannot include (using *T) a readonly class

The spec says

> Every type descriptor referenced directly or indirectly by a type-reference in an object-type-inclusion must be an object-type-descriptor, distinct-type-descriptor, intersection-type-descriptor or a class that is not readonly;

My initial understanding based on the spec was that the "not readonly" part applied only to classes.

**Case II**

Also, can we not allow the following?

```ballerina
public type Foo readonly & object {
    public function get() returns int;
};

readonly class Bar  { // The referencing class is `readonly`
    *Foo;

    public function get() returns int => 1;
}
```

I'm not sure if the spec currently allows this since it specifically mentions referencing a readonly class.

> If the class is readonly (i.e. class-type-quals includes readonly), then an object-type-inclusion in the class is allowed to directly or indirectly reference a readonly class.

**Comment by jclark** [comment]
**Case I**

The intended meaning is 

> an object-type-descriptor, distinct-type-descriptor, intersection-type-descriptor or a class that is not readonly;

It means "a class without a readonly qualifier".

**Case II**

I agree we should allow that.

**Comment by MaryamZi** [comment]
> **Case I**
> 
> > an object-type-descriptor, distinct-type-descriptor, intersection-type-descriptor or a class that is not readonly;
> 
> It means "a class without a readonly qualifier".
> 

Wouldn't this mean that using type inclusion with a `readonly` intersection `T & readonly`, where `T` is an object type descriptor, would be valid in an object type descriptor?

```ballerina
type Foo readonly & object { };
type Bar object { *Foo; };
```

If so, would we only consider objects with their `readonly` bit on as the objects that belong to `Bar` here?

**Comment by jclark** [comment]
No, because it would be referencing the type descriptor `readonly`.

**Comment by MaryamZi** [comment]
I'm afraid I still don't get how this is invalid.

```ballerina
type Foo readonly & object { };
type Bar object { *Foo; };
```

The spec says
> Every type descriptor referenced directly or indirectly by a type-reference in an object-type-inclusion must be an object-type-descriptor, distinct-type-descriptor, intersection-type-descriptor or a class that is not readonly; the referenced type descriptor will thus necessarily be definite and a subtype of object.

In this scenario (`type Bar object { *Foo; };`), the referenced type descriptor `Foo` is an `intersection-type-descriptor` which is a subtype of `object`. Since it is not a `class`, IIUC, the condition that it should not be `readonly` does not apply here.

**Comment by jclark** [comment]
The graph (constructed from the syntax tree by resolving references) of type descriptor Foo has three nodes:

1. an intersection type descriptor
2. an object type descriptor
3. a readonly type descriptor

where 1 refers to 2 and 3.

When you use *T in an object type descriptor, every node in the graph must be one of the following

* an object type descriptor
* a distinct type descriptor
* an intersection type descroptor
* a class without a readonly qualifier

`*Foo` is not valid, because node (3) is not one of the four types of allowed node.

**Comment by MaryamZi** [comment]
Thank you very much for the detailed explanation, this is clear now.

I assume this would apply differently for the inclusion of `Foo` in a class, if the following is to be allowed as discussed above? 

```ballerina
public type Foo readonly & object {
    public function get() returns int;
};

readonly class Bar  { // The referencing class is `readonly`
    *Foo;

    public function get() returns int => 1;
}
```

**Comment by jclark** [comment]
I will change this

> If the class is readonly (i.e. class-type-quals includes readonly), then an object-type-inclusion in the class is allowed to directly or indirectly reference a readonly class

to add “or readonly type descriptor”.

**Comment by MaryamZi** [comment]
Noted, we will allow this in the implementation too.
