### ISSUE TITLE
Inclusion of object type descriptor with qualifiers

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#650]
What happens if you do `object { *T; }` and T has a `isolated`/`service`/`client` qualifier?

We should preservice principle that `object { *T; xxx }` produces a type that is a subtype of T.

**Comment by jclark** [comment]
The most obvious approach is to say that `*T` copies the qualifiers.

But I think I prefer a different approach: if an object type descriptor D does *T and T has qualifier Q, then D must also have Q. For example, if you want to include an isolated object type in an object type descriptor, then you must explicitly make the type descriptor isolated. I prefer it because I think it will make for more explicit, understandable code and it feels more consistent with #649.

**Comment by jclark** [comment]
We approved this today.

**Comment by MaryamZi** [comment]
> But I think I prefer a different approach: if an object type descriptor D does *T and T has qualifier Q, then D must also have Q. For example, if you want to include an isolated object type in an object type descriptor, then you must explicitly make the type descriptor isolated. I prefer it because I think it will make for more explicit, understandable code and it feels more consistent with #649.

@jclark, just to confirm, these rules also apply to classes, right?

- inclusion with such qualifiers in a class

```ballerina
type Foo isolated object {
    isolated object {} x;
};

class Bar {
    *Foo; // error since `Bar` is not `isolated`.

    final isolated object {} x = isolated object {};
    int y = 2;
}
```

- the inclusion of classes with such qualifiers
 
```ballerina
service class Foo {
    resource function get xyz() {

    }
}

type Bar object {
    *Foo; // error since `Bar` does not have the `service` qualifier.
};
```

**Comment by jclark** [comment]
Yes. The spec tries to say both of these:

* module-class-defn references the object-type-inclusion production and so pulls in the semantics of that
* the text for object-type-inclusion explicitly mentions classes

**Comment by MaryamZi** [comment]
Noted, thank you.
