### ISSUE TITLE
Clarification on implicitly casting XML index access expression to string types

### ISSUE THREAD

**Issue by suleka96** [ballerina-platform/ballerina-spec#653]
**Description:**

The spec currently states that:

> "since Ballerina always requires programmers to make conversions explicit, even between different types of number. There is only one exception: a value of type xml:Text can be implicitly converted to a string".

thus we are currently allowing:
```
'xml:Text x1 = 'xml:createText("text");
string a = x1;
```
However should we also allow scenarios like:
```
'xml:Text x1 = 'xml:createText("text");
string a = x1[0];
```

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
If x1 is of type xml:Text, then `x1[0]` is valid without any conversion. You should only do a conversion to string if it would be a static type error without a conversion.
