### ISSUE TITLE
Inferred type is not representable as type descriptor

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-spec#663]
**Description:**
Let's consider we are going to check an expression which is readonly. How do we get the type after checking the expression?
In current implementation checking readonly value, throws a compile error.

We faced this issue, when implementing https://github.com/ballerina-platform/ballerina-spec/issues/489

**Comment by jclark** [comment]
I don't understand. Please explain more with an example.

**Comment by hasithaa** [comment]
I think the issue here is,  what is the type of the `x`. It is `readonly - error` But we can't represent it because readonly contains `selectively immutable basic types`.

```ballerina
function main() returns error? {
   readonly a = <some_readonly_value>;
   var x = check  a;
}
```

**Comment by jclark** [comment]
There will be other cases whether you need to infer a type that cannot be represented as a type descriptor in the language, because of the lack of set difference, for example, with narrowing in a match statement.

Ideally, at some point the language would get a set difference type operator. In the meantime, representing the inferred type will need to use a type descriptor for which there is no syntax in the language.

**Comment by hasithaa** [comment]
To handle the readonly case, I think the best solution is to bring a set difference as a type, at least for the implementation.

**Comment by MaryamZi** [comment]
Specifically for `readonly` though, isn't it equivalent to the following union?

```
()|boolean|int|float|decimal|string|error|function|typedesc|handle|readonly & xml|readonly & (any|error)[]|
readonly & map<any|error>|readonly & table<map<any|error>>|readonly & object {}
```

which would mean `readonly` without `error` is 

```
()|boolean|int|float|decimal|string|function|typedesc|handle|readonly & xml|readonly & (any|error)[]|
readonly & map<any|error>|readonly & table<map<any|error>>|readonly & object {}
```

**Comment by jclark** [comment]
Isn’t `readonly - error` the same as `readonly & any`?

**Comment by hasithaa** [comment]
`readonly & any` works. We will use that.
