### ISSUE TITLE
Union of service types in Listener parameters

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#664]
**Description:**
Considering `Listener<T>` is it possible for the `T` to be a union of service objects?

`public function attach(A|B svc, string[]? path = ()) returns error?;` where both A and B are subtype of `service object {}`.

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
Yes. The only restriction is that T is a subtype of `service object {}`.

In the case where it's a union then the service-decl will need to specify a type explicitly (otherwise the service-decl will desugar into something illegal).
