### ISSUE TITLE
Should we allow listener type to decide what type of absolute path it accept

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#665]
**Description:**
Should we allow the second parameter of `attach` method to be just `string`, `string[]`, `()`, or any combination of them, or do we require it to be `string[]|string|()`?

Related issue: https://github.com/ballerina-platform/ballerina-spec/issues/654
**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
The former. See #643. Until we do #643, we will need to use a compiler extension to check that it’s the right type for the Listener.
