### ISSUE TITLE
Add support for Unsigned48 in lang.int

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-spec#666]
**Description:**
Currently, Unsigned48 is not supported in `lang.int`. This is a requirement for the `uuid` standard library module[[1]](https://docs.google.com/document/d/1-iLJMDOJi9FIyS9CbEB6pwxTS15bSRKkBe5xJTqpXl0/edit#) since the `node` should be an Unsigned48 when representing a `UUID`.

[1] https://docs.google.com/document/d/1-iLJMDOJi9FIyS9CbEB6pwxTS15bSRKkBe5xJTqpXl0/edit#

**Comment by jclark** [comment]
This is a duplicate of #651.
