### ISSUE TITLE
Allow expression in listener declaration to return an error

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-spec#671]
**Description:**

Current implementation of `listener`s panics when there is an error such as port-binding error. 

But with the new design it is possible to return errors from the `listener`. However, doing so would result in having to use `check` expression every time the user instantiate a new `listener`.

```ballerina
listener http:Listener hl = check new (9095);
```

IMO, returning the error is the correct choice as it makes the users aware of the possible errors during the compile time. 

Any opinion on this ?

**Comment by jclark** [comment]
I think it's better if the Listener's init method returns an error for something like a port-binding error; this gives the right behaviour for when the Listener is new'ed outside a listener declaration and then registered explicitly (with runtime:registerListener).

The spec says for service-decl (https://ballerina.io/spec/lang/master/#section_8.3.2):

> Each expression in the expression-list must have a type Listener<T,A>|E where T is a subtype of service object {}, A is a subtype of string[]|string|() and E is a subtype of error

and then goes on to say:

> the expression is evaluated resulting in a value which is either an error or an object obj belonging to a listener object type; if it is an error, module initialization fails

So the service-decl already makes it easy for the Listener's init method to return an error.

We could make listener-decl do the same thing: allow the expression in a listener to be of type L|E, where L is a listener and E is an error; if the expression results in an error, then module initialization fails.

I don't think you gain much by forcing a user to write `check` in the listener declaration. If we really want to do that, we should do it in the service-decl also.

**Comment by shafreenAnfar** [comment]
Thanks for the response. 

Yes, we don't gain much by forcing a user to write `check` in the listener declaration. We will change the current implementation so that Listener's init method can return errors such as port-binding error instead of panicking.

**Comment by sanjiva** [comment]
James there's no desire to force users to write check in the listener-decl. So what you're suggesting is:
```ballerina
listener http:Listener hl = new(1234);
```
and for that to somehow work?? That seems wrong .. shouldn't we say `http:Listener|error` then?

**Comment by jclark** [comment]
A listener declaration is its own thing, not just a variable declaration, so it can have whatever semantics we want.

If the expression creating the listener results in an error e, then the semantics should be that module initialization fails with error e (just as happens with a service declaration or with the module `init` method).

**Comment by jclark** [comment]
Note that this would need a spec change for listener-decl.

**Comment by jclark** [comment]
We decided we are OK with this spec change.
