### ISSUE TITLE
Can there be resource-path-segment-param(s) in service absolute-resource-path

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#678]
**Description:**
From the grammar it seems there can be path params in absolute resource path, at the moment we don't support this in the implementation. Do we need to support this now or can be defer this?

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
The grammar does not allow this now:

https://ballerina.io/spec/lang/master/#absolute-resource-path

**Comment by rdhananjaya** [comment]
Ack. Thank you.
