### ISSUE TITLE
Clarification on `readonly & T` where `T` is a class

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#679]
**Description:**
Previously, the spec disallowed an intersection type if at least one of the types was a class (previously non-abstract object type).

IIUC, this is no longer the case in the current spec?

If so, I assume it should now be possible to define an intersection type `T & readonly` where `T` is a class.

e.g.,
where `Foo` and `Bar` are

```ballerina
class Foo {
    int[] x;

    function init() {
        self.x = [1, 2, 3];
    }
}

readonly class Bar {
    int[] x;

    function init(readonly & int[] x) {
        self.x = x;
    }
}
```

the following will be valid?

```ballerina
readonly & Foo a = new Bar([1, 2, 3]); // `Bar` is a `readonly class` and is a subtype of `Foo`
```

But the following would be invalid?

```ballerina
readonly & Foo b = new; // Error since `readonly & Foo` is not a class
```

**Comment by jclark** [comment]
There's nothing in the spec that disallows your first case, so it's valid.

Your second case is invalid because of this:

> A type descriptor T1&T2 is not a class and cannot be used with new, even if one or both of T1 and T2 are classes.

**Comment by MaryamZi** [comment]
Noted, thank you.

**Comment by MaryamZi** [comment]
> There's nothing in the spec that disallows your first case, so it's valid.
> 
> Your second case is invalid because of this:
> 
> > A type descriptor T1&T2 is not a class and cannot be used with new, even if one or both of T1 and T2 are classes.

What about when `T` in `readonly & T` is a `readonly` class ?

```ballerina
readonly class Foo {
    int[] x = [1, 2];
}

readonly & Foo = new; // is this valid?
```

Can we use `new` here because `readonly & Foo` can be considered as `Foo`?

**Comment by jclark** [comment]
No: the intersection operator creates a type that is not a class (same as union).

**Comment by MaryamZi** [comment]
Ack, thank you.
