### ISSUE TITLE
How to Read the Type Information of a Service Object Returning from a Resource Function

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-spec#680]
**Description:**
When there's a resource function, which is returning a service object, is there a way to obtain the type information of that returning service object?

Consider the following service:

```ballerina
import ballerina/graphql;

service /graphql on new graphql:Listener(9090) {
    isolated resource function get greet() returns service object {} {
        return service object {
            isolated resource function get common() returns string {
                return "Hello, world";
            }
        };
    }
}
```

When attaching this service to the Listener, we need the names, return types and input parameters of the resource functions inside the returning service object.

The issue here is that the return type of the parent resource does not have this information. We have to execute the resource to obtain them. But in GraphQL, we need this information before executing the resource, to generate the corresponding GraphQL schema, and also to validate the incoming GraphQL documents, before executing them.

Is there a way to get this information without executing the resource?

@rdhananjaya @shafreenAnfar @hasithaa

**Comment by jclark** [comment]
Use a class:

```
import ballerina/graphql;

service class Common {
      isolated resource function get common() returns string {
           return "Hello, world";
      }
}

service /graphql on new graphql:Listener(9090) {
    isolated resource function get greet() returns Common {
        return new;
    }
}
```

**Comment by jclark** [comment]
If you want to do it inline, then use a hierarchical resource name:

```
service /graphql on new graphql:Listener(9090) {
    isolated resource function get greet/common() returns string {
        return "Hello, world";
    }
}
```
