### ISSUE TITLE
Provide a general-purpose annotation to customize how Ballerina symbols displayed in a UI

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#681]
There is a requirement to specify localizable names, icons for Ballerina types, classes, methods, etc. We introduced the `@icon` annotation for a similar [requirement](https://github.com/ballerina-platform/ballerina-spec/issues/483).  

We should provide a series of annotations that let developers customize how Ballerina constructs are displayed in a UI environment. My suggestion is to introduce the `@display` annotation as the first one.  

```
@display { name: "Foo connector" }
public client class Foo {

     @display { name: "Perform bar" }
     public remote function performBar(@display {name: "Param bazz"} Bazz bazz) {
     }
}
```

Should we merge the current `@icon` annotation with the `@display` annotation?  E.g. `@display { icon: "/a/b/c.ico"}`

**Comment by sanjiva** [comment]
I'm ok with one annotation (@display) but a series of annotations seems a bit weird from the language point of view. 

The @display concept seems well aligned with @documentation, which is info for developers.

**Comment by hasithaa** [comment]
Related discussion for @Icon annotation https://github.com/ballerina-platform/ballerina-spec/issues/483

**Comment by sameerajayasoma** [comment]
We can start with the `@display` annotation. How about including `icon` inside the `@display` annotation?

**Comment by sameerajayasoma** [comment]
We (@sameerajayasoma, @hasithaa, @sanjiva) decided to go ahead with the `@display` annotation. 

```
public const annotation record {| string path; |} display on source type, source class, 
      source function, source return, source parameter, source field, source listener, 
      source var, source const, source annotation;

type DisplayData record {
    string label; 
    // Path to the icon
    string icon; 
};
```

Notes:
- `DisplayData` is an open record - that way if someone wants to put more stuff,  they can add additional fields - as long as the writer and the annotation processor are in agreement.
- We are not indicating the type of the image file format - most modern code can figure that out by sniffing the data, and older code can rely on the extension to indicate the type.

**Comment by sanjiva** [comment]
Sameera shall we make a small tweak:

```ballerina
type DisplayData record {
    string label; 
    string iconPath; 
};
```

We also need to say the path is relative to the resources path of the module.

Also there's a typo in the annotation definition - you haven't used DisplayData in it.

**Comment by sameerajayasoma** [comment]
Here is the updated definition with your suggestion @sanjiva 

```
public const annotation DisplayData display on source type, source class, 
      source function, source return, source parameter, source field, source listener, 
      source var, source const, source annotation;

type DisplayData record {
    string label; 
    string iconPath; 
};
```

**Comment by rdhananjaya** [comment]
As per comment https://github.com/ballerina-platform/ballerina-lang/pull/27626#issuecomment-754390738 should this be:
```ballerina
public const annotation record {
    # label for the Ballerina construct
    string label;
    # icon path relative to module's resouce directory
    string iconPath;
} display on source type, source class,
      source function, source return, source parameter, source field, source listener,
      source var, source const, source annotation;
```

**Comment by hasithaa** [comment]
I think we should make `iconPath` optional. Right now it is required.

**Comment by rdhananjaya** [comment]
We need to allow `service` attach point as well.

**Comment by sameerajayasoma** [comment]
This is completed with Ballerina Swan Lake Beta1
