### ISSUE TITLE
Rename the extension of the package distribution file from balo to bala

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#684]
We updated the distribution format to include a package instead of a module. Therefore the extension `balo` doesn't make sense anymore. We use the term `balo` to mean the Ballerina object file (binary format of a module). Even with modules, we did not store the binary format in a `balo`. It was just an archive of source files.  

A package contains one or more modules, and therefore, the distribution format of a package is an archive of modules. With these changes, let's change the extension to `balr`. It stands for `BALlerina aRchive`.

_Note that this was briefly discussed during a language design group meeting a few months ago._

**Comment by sanjiva** [comment]
Any particular reason for not using `.bala` instead?

**Comment by sameerajayasoma** [comment]
We briefly discussed the term `.balr` AFAIR, hence the suggestion. I am okay with `.bala` too.

**Comment by azinneera** [comment]
Changes in the following will be required in order to complete the implementation:
1. ballerina-lang code
2. Standard Libraries 
3. Distribution build
4. Ballerina Central APIs
5. Existing `.balo`s in Ballerina Central
