### ISSUE TITLE
Add langlib function to test whether one string contains another

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#687]
Java's version is here: https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#contains(java.lang.CharSequence)

JavaScript's is here: https://tc39.es/ecma262/#sec-string.prototype.includes

Two differences:

- Java calls it `contains`; JavaScript calls it `includes`
- JavaScript has an optional 2nd argument giving index to start looking from

I think we should have the optional 2nd argument: that's consistent with other string functions (`indexOf`, `startsWith`).

I don't have a strong preference on the name, but I marginally prefer to follow the lead of JavaScript rather than Java.

**Comment by jclark** [comment]
Note you can implement it with the optional 2nd argument in Ballerina as `s.indexOf(str, startIndex) != ()`.

**Comment by sanjiva** [comment]
+1 for going with `includes`.
