### ISSUE TITLE
ToString abstract operation on empty type-ids

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#688]
**Description:**
Does `D1&D2` become empty string when the error value contains an empty set of type-ids?
Example: `error D1&D2 (M,C,F1=V1,F2=V2)` becomes `error (M,C,F1=V1,F2=V2)` 

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
Yes
