### ISSUE TITLE
Typing with record type inclusion

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#690]
**Description:**
The implementation currently allows the following record type inclusions.

```ballerina
type Foo record {|
    int i;    
|};

type Bar record {|
    *Foo; // Closed record includes a closed record.
    int j;    
|};

type Baz record {
    *Foo; // Open record includes a closed record.
    int k;    
};
```

Even though `Bar` and `Baz` include `Foo`, they are not considered as subtypes of `Foo`.

Similar to object inclusion (as mentioned in https://github.com/ballerina-platform/ballerina-spec/issues/649#issuecomment-728617706), shouldn't record inclusion also result in subtypes?

**Comment by jclark** [comment]
Record inclusion is not designed to always result in subtypes.

**Comment by MaryamZi** [comment]
Noted!
