### ISSUE TITLE
Conflicts between multiple type inclusions

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-spec#696]
**Description:**
Please consider the below example.

```
type Foo record {|
   int i;
   string...;
|};

type Bar record {|
    byte i; 
    boolean...;
|};

type Baz record {|
    *Foo; 
    *Bar;
|};
```

What can be the rest type of `Baz`? If there is only one type ref, we can clearly get the rest type. But in this case, it is unclear.
  
**Related Issues:**
https://github.com/ballerina-platform/ballerina-spec/issues/75

**Comment by jclark** [comment]
`Bar` doesn't override `Foo`. Both the `i` field and the rest type of Foo and Bar conflict, so this is an error.

**Comment by jclark** [comment]
The spec should state that this is an error.

**Comment by KavinduZoysa** [comment]
@jclark, there is another confusion, please check below example. 
```
type Foo record {|
   int i;
   string...;
|};

type Bar record {|
    int i; 
    string...;
|};

type Baz record {|
    *Foo; 
    *Bar;
|};
```
Is this valid?

**Comment by jclark** [comment]
This is all quite tricky.

I think the rest type is relatively straightforward. We want this to work:

```
type Foo {
   int x;
};
type Bar {
  int y;
};
type Baz {|
  *Foo;
  *Bar;
|};
```

which implies this needs to work:

```
type Foo {|
   int x;
   string...;
|};
type Bar {|
  int y;
  string...;
|};
type Baz {|
  *Foo;
  *Bar;
|};
```

So for rest types, I think the rule should be that if you have multiple inclusions and they don't all have the same rest type, then you need to say explicitly in the including type what the rest type is.

We also need to think about object types. This I think this should be OK:

```
type A object {
   int foo();
};

type B object { *A; };
type C object { *A; };

type D object {
  *B;
  *C;
};
```

So I think the rule for methods of an object can be the same as for rest types.

It's less obvious to me what the rule for record and object fields should be. Let me think some more.

**Comment by jclark** [comment]
We discussed this today.  We agreed that the two cases in https://github.com/ballerina-platform/ballerina-spec/issues/696#issuecomment-762670338 should be OK.

We decided to make this be an error, at least for now:

```
type A record {|
  int i;
|};

type B record {|
  int i;
|};

type C record {|
   *A;
   *B;
|};
```
We can relax in future if it turns out to be unduly restrictive.  If the user needs this, they can define type C as:

```
type C record {|
   *A;
   *B;
   int i;
|};
```

They can also subtype as usual:

```
type C record {|
   *A;
   *B;
   byte i;
|};
```
