### ISSUE TITLE
Allow Examining the Original GraphQL Request for Dynamic Query Generation

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-spec#697]
**Description:**

Currently, the GraphQL requests are automatically mapped to a service's structure to execute its logic to query the data. In the way that the current resolver functions are implemented, it may be not possible to optimize data querying, where we may end up with situations such as over-fetching. 

Let's take the following example of looking up "Order" details. 

```ballerina
type OrderData record {|
   int id;
   int customerId;
   int shipperId;
   string date;
   string notes;
|};

type CustomerData record {|
   int id;
   string name;
   string address;
|};

type ShipperData record {|
   int id;
   string name;
   string phone;
|};

readonly service class Order {
   resource int id;
   resource string date;
   resource string notes;
   resource string customerId;
   private int shipperId;

   function init(OrderData data) {
      self.id = data.id;
      self.date = data.date;
      self.notes = data.notes;
      self.customerId = data.customerId;
      self.shipperId = data.shipperId;
   }

   resource function get customer() returns Customer|()|error {
      return check loadCustomer(self.customerId);
   }

   resource function get shipper() returns Customer|()|error {
      return check loadCustomer(self.customerId);
   }

}
   
service on gql:Listener(8080) {
  resource function get order(int id) returns Order?|error => loadOrder(id);
}

final sql:Client dbc = new sql:Client(XXX);

function loadOrder(int id) returns Order?|error {
   stream<OrderData,*> stm = dbc->query(`SELECT * FROM Order WHERE id = ${id}`);
   return new Order(stm.first());
}

function loadCustomer(int id) returns Order?|error {
   stream<CustomerData,*> stm = dbc->query(`SELECT * FROM Customer WHERE id = ${id}`);
   return new Customer(stm.first());
}

function loadShipper(int id) returns Order?|error {
   stream<ShipperData,*> stm = dbc->query(`SELECT * FROM Shipper WHERE id = ${id}`);
   return new Shipper(stm.first());
}
```

The above GraphQL service is implemented can server queries like the following:-

```graphql
{
   order(2001) {
      date
      notes
      customer {
         name
         address
      }
      shipper {
         name
         phone
      }
   }
}
```

With the above code, this will take 3 SQL statements to be executed to fulfill the above query. This is because we look up the other related object data on-demand in a lazy manner. We could have always done a bigger JOIN query to look up all the data in one go, but it will end up in an over-fetching scenario when the user is not querying objects such as "customer" and "shipper". 

So in order to efficiently do this, we need to be able to build up the SQL query dynamically according to the incoming GraphQL query. If the developer has access to the original GraphQL request information, we can do this similar to the following manner. This contains the basic algorithm that can be used to dynamically generate an SQL query with the incoming request information. 

```ballerina
function graphQLtoSQL(GQLObject obj) returns string {
    SQLQueryContext qctx = new(obj.name);
    processQuery(obj, qctx);
    return qctx.generateSQL();
}

function processQuery(GQLObject obj, SQLQueryContext qctx) {
    foreach var qfield in obj.fields() {
        if qfield.isScalar() {
            ctx.addTableField(obj.name, qfield.name);
        } else { // object
            ctx.addJoin(obj.name, qfield.name);
            processQuery(qfield, qctx);
        }
    }
}

class SQLQueryContext {

    private string rootTable;
    private string[] fields;
    private string[] joinStrings;

    public function init(string rootTable) {
        self.rootTable = rootTable;
        self.fields = [];
        self.joinStrings = [];
    }

    public function addTableField(string tableName, string fieldName) {
        self.fields.push(string `${tableName}.${fieldName}`);
    }

    public function addJoin(string tableLHS, string tableRHS) {
        self.joinStrings.push(string `INNER JOIN ${tableRHS} ON 
                                      ${tableLHS}.${foreignKey(tableLHS, tableRHS)}=${tableRHS}.${primaryKey(tableRHS)}`);
    }

    public function generateSQL() returns string {
        return string `SELECT ${",".'join(self.fields)} FROM ${self.rootTable} ${" ".'join(self.joinStrings)}`;
    }

}

public function primaryKey(string tableName) returns string { ... }

public function foreignKey(string parentTable, string targetTable) returns string { ... }
```

This type of functionality can be especially useful when we want to optimize scenarios such as the above, and also for creating other tools similar to [SuperGraph](https://supergraph.dev/docs/graphql) using Ballerina.

**Comment by jclark** [comment]
I see two rather different use cases:

1. Allow for smarter implementations of resource methods that can take into account everything the GraphQL query is requesting; the GraphQL schema is still generated from the Ballerina resource method definitions
2. Implement something like SuperGraph in Ballerina, where the GraphQL schema is not generated from Ballerina code

I would approach case 2 by factoring the GraphQL implementation into two layers each in its own module:
- an engine layer that implements a GraphQL engine, e.g. parsing and analyzing the GraphQL syntax
- a listener layer that implements a GraphQL listener using the engine 

You could implement something like SuperGraph by using the engine layer to implement an HTTP service class that would expose a GraphQL interface to an SQL database

I can see a couple of alternative approaches that have potential to solve case 1:
- allow the Listener to pass to the resource method an argument describing the resource paths that the query will access (this would be a distinct object type to distinguish it from other arguments)
- have an optional `prefetch` resource method, which would be called on all resources that define it before any `get` method is called

**Comment by lafernando** [comment]
> I see two rather different use cases:
> 
> 1. Allow for smarter implementations of resource methods that can take into account everything the GraphQL query is requesting; the GraphQL schema is still generated from the Ballerina resource method definitions
> 2. Implement something like SuperGraph in Ballerina, where the GraphQL schema is not generated from Ballerina code
> 
> I would approach case 2 by factoring the GraphQL implementation into two layers each in its own module:
> 
> * an engine layer that implements a GraphQL engine, e.g. parsing and analyzing the GraphQL syntax
> * a listener layer that implements a GraphQL listener using the engine
> 
> You could implement something like SuperGraph by using the engine layer to implement an HTTP service class that would expose a GraphQL interface to an SQL database

+1.

> 
> I can see a couple of alternative approaches that have potential to solve case 1:
> 
> * allow the Listener to pass to the resource method an argument describing the resource paths that the query will access (this would be a distinct object type to distinguish it from other arguments)

Describing the resource paths it will access means, will it basically be similar to the "GQLObject" I mentioned in the sample scenario? And I'm guessing then it basically becomes a "prefetch" method that is defined below?

> * have an optional `prefetch` resource method, which would be called on all resources that define it before any `get` method is called

In this case the "prefetch" will do the actual work of populating the data to be used later, and it also gets the request context information I guess? So the other resources are mainly there to express the GraphQL schema?

**Comment by jclark** [comment]
The service objects use the `prefetch` method to build up a representation of everything that needs to be fetched; the first call to a `get` method then uses that representation to fetch everything; other calls to `get` use the already fetched data.

**Comment by lafernando** [comment]
So yes, building the representation means, for example, generating the full SQL statement we need, and we can even execute and get the data there itself I guess. So subsequent `get` methods can return the already populated data.

**Comment by jclark** [comment]
No: it's the first call to `get` that would generate the SQL or fetch the data, using the information gathered during the prefetch stage.

**Comment by lafernando** [comment]
So it's just a convention, right? Is there any specific reason for that order, and any way of enforcing users to do it in that way?

**Comment by jclark** [comment]
I don't think I have succeeded in communicating the concept. No other order would solve the problem.

**Comment by lafernando** [comment]
My bad also, I may not have followed your explanation properly, hopefully, will get some clarifications in some concrete examples of the proposed design later :)

**Comment by ThisaruGuruge** [comment]
Will come up with a design for this after the SwanLake release. I hope that'd be okay.

**Comment by jclark** [comment]
Absolutely. The second use case is an optimization: we should get the implementation to a reasonable level of completeness before we start to optimize.

**Comment by ThisaruGuruge** [comment]
We have added functionality to retrieve the [`graphql:Field`](https://lib.ballerina.io/ballerina/graphql/latest#Field) object from the resolver (`resource`/`remote`) methods, which can be used to retrieve the information about the original request. Therefore, closing this issue.
