### ISSUE TITLE
Type descriptor for any function

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#7]
For most basic types, it is trivial to write a type descriptor that covers all values of that basic type. But for functions it is not possible. It feels like something that ought to be possible.

For example, if an annotation tag can only be attached to a function, then we might want to say that it is allowed only for a typedesc whose parameter is a subtype of any function.

I suspect we will have syntax ambiguities if we allow `function` by itself as a keyword to represent a type (we don't have anywhere else where we allow braces optionally).

We could allow `function returns T` to be the type of all functions returning type T no matter what their parameters; then `function returns any|error` would cover all functions.

Don't want to use `function<T>` since that is likely to conflict with syntax for parameterized types.

**Comment by sanjiva** [comment]
Hasitha, can you please check whether just using "function" can be made to work with the grammar?

**Comment by jclark** [comment]
The case that worries me is where you have

```
keyword expression { statements }
```
e.g. in an `if` statement.

I am not sure if there will be cases where the braces could be parsed either as surrounding the statements or as part of an anonymous function.

**Comment by jclark** [comment]
There is a similar issue with `object`, but I guess `object {}` will match any object (depending on our TBD subtyping rules), so it is probably less of an issue.

**Comment by hasithaa** [comment]
@sanjiva @jclark I tested with following parser rule. 
```
functionTypeName
    :   FUNCTION (LEFT_PARENTHESIS (parameterList | parameterTypeNameList)? RIGHT_PARENTHESIS )? returnParameter?
    ;
```
Following scenarios works. 
```
function returns int a = foo;
function b = bar;

function main() {
    if true {
        function c = bar;
        function returns T d = baz;
        function (function , function returns T) d = foo;
    }
    function returns T d = () => e;
    
    function x = function () {
        int i = 10;
    };
}

// in params
function test1(function a, function returns T b) returns function returns T {

}
```

**Comment by jclark** [comment]
When `returns` is allowed but omitted, the meaning elsewhere in the language is that it defaults to `returns ()`. So I think there are several plausible designs for how to change function-type-descriptor.

1. Allow `function` but not `function returns T`. All values of basic type `function` belong to the type `function`.
2. Allow 'function returns T` but not `function`. Thus the type to which all function values belong is `function returns any|error` .
3. Allow `function` and `function returns T`, and `function` means `function returns ()`.
4. Allow `function` and `function returns T` and `function` means `function returns any|error`. 

I prefer 1, and am OK with 2. I think 3 and 4 will both be confusingly inconsistent with other aspects of the language.

@sanjiva @hasithaa What do you think?

**Comment by hasithaa** [comment]
Ref Option 1: In some context, parenthesis are optional, so type `function ()` and `function` (which is equivalent to `function returns any|error`) may reduce readability IMO. 
e.g.: 
function () a = function () { ... };
function b = a;

Option 2 seems more powerful, but it will make the general case long, i.e. `function returns any|error`. I hope, the general case itself will be used rarely. So I like option 2.

**Comment by jclark** [comment]
That's a good point. It would be weird for `function ()` to mean a nil return value, but `function` to mean any return value.

It seems all choices involve some inconsistency.

`function ()` does not seem very readable to me. I wonder whether we should require return types for function type descriptors. That would be inconsistent with function declarations and definitions, but perhaps that would be the least bad type of inconsistency. I guess function-type-descriptors are much rarer than member/function declarations/definitions, so allowing omission of the return type is not all that useful.

**Comment by sanjiva** [comment]
I guess I don't understand the scope of the problem we want to solve: if its only to "write a type descriptor that covers all values" then why are we trying to make it complex?

Just allow "function" and have it mean function that takes any kind of values and returns any|error. I *think* that's option 1?

I don't understand why it makes sense to focus only on allowing the return type to be specified and for the absence of parameters to mean any parameters. Usually when we skip something it means there's nothing, not that anything is ok.

**Comment by jclark** [comment]
What you suggest (which is what I at first preferred) has the problem, which was pointed out by @hasithaa, that it would leave us in a situation where

- `function ()` means zero arguments and return type of nil, and
- `function` means any arguments and any return type

it does not seem intuitive to me that adding `()` should result in changing the return type from `any|error` to nil.

The reason why parameters and return type are different is variance. Parameters are contravariant and return type is covariant. So you can match any return type by using `any|error`, but you cannot do that with parameters.

I think it will sometimes be useful to constrain the return type, particularly to `error?`, but but allow any parameter type, e.g.

1. main function
2. resource functions

**Comment by sameerajayasoma** [comment]
`function (B) returns T` is the type descriptor for any function where B is the subtype of all types and T is the supertype of all the types.  

T -  `any|error`
B - Ballerina does not have a type descriptor for this. 

In the absence of B in Ballerina, any approach that we take will have inconsistencies

**Comment by sameerajayasoma** [comment]
In #74 @jclark has suggested a type that has no values. The proposed name is `impossible`. In that case `function (impossible) returns any|error` would be the type which is the supertype of all types. The name `impossible` is not finalized yet.

**Comment by jclark** [comment]
I don't think that works. In `function(T)`, `T` is giving a type for the first parameter not a type for the parameter list as a whole.

**Comment by sameerajayasoma** [comment]
Can we consider the function parameter type as a tuple? In that case in `function(T)`, `T` would be a tuple type.  Related to #131.

**Comment by jclark** [comment]
function(T) where T is a tuple type already has a meaning: it means the first argument is list belonging to that tuple type.

**Comment by jclark** [comment]
There's a parallel with `future<T>`, since that is just a reference to a strand with return type `T`.

**Comment by sanjiva** [comment]
So you're back to `function` as the way to refer to any value of type function? I'm good with that!

**Comment by jclark** [comment]
This would be useful for annotations whose value is a function. The testing framework uses this a lot, but uses a string with the name of the function rather than the function.
