### ISSUE TITLE
Use of `default` in inter-worker message send/receive

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#707]
We currently use the keyword `default` only with named workers to specify sending from or receiving to the default worker.

This feels really ugly to me and I wonder if we should revisit it:

- we don't use `default` when defining the named worker
- we don't use `default` in other cases in the language where we have a default (e.g. we use `_` for the `match` statement)
- if you don't read the spec, which introduces the term "default worker", there's really no clue that `default` refers to the function's strand

It seems to me it would be more consistent to instead use either `function` or the name of the function being defined (`<- A` gets something from code inside `worker A`; `<- foo` gets something from code inside `function foo`).

**Comment by jclark** [comment]
Another possibility would be also to allow `default` in `match` statements. This isn't the same as `_`, because `_` matches `any` rather than `any|error` (so that `_ = foo();` doesn't ignore errors).

**Comment by hasithaa** [comment]
Using  `default` for `wildcard-binding-pattern` or `wildcard-match-pattern` seem lengthy. Also in the spec, mention both `wild-*-pattern` match only if the value belongs to type `any`.  So behavior-wise `_ = foo()` is same.

**Comment by jclark** [comment]
I am not suggesting changing or getting rid of `_` as a match pattern or binding pattern. That’s fine as is.

The idea was to *add* `default` as a match pattern, which would work like `default` in a `switch` statement in C-like languages (i.e. match anything at all). My point was that `_` does not work like `default` because it does not match everything.

The simplest level of understanding of `match` is that it’s like a`switch` statement, with cases being constants. So I think there is an argument for having a `switch`-like way of specifying the default case.

**Comment by hasithaa** [comment]
Ok, I misunderstood the requirement.  I am +1 to introduce `default` behavior.

**Comment by jclark** [comment]
We decide to change from `default` to `function`.
