### ISSUE TITLE
Typing for query expressions in xml templates

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#708]
This ought to work:

```
int[] v = [1,2,3]
var x = xml`<doc>${from int i in v select xml`<num>${i}</num>`}</doc>`
```
and produce and make `x` be

```
xml`<doc><num>1</num><num>2</num><num>3</num></doc>`
```
Not clear from the spec that it does:

- query expression will determine what to create based first on contextually expected type, and then on type of thing being iterated over
- contextually expected type for insertion in an XML template is not exclusively xml since it will convert things to strings

So I think the spec arguably says that the select expression generates a list which the xml template will convert to a string and then insert (i.e. you would end up with the tags being escaped).

**Comment by jclark** [comment]
I think the solution is to say that in an xml-template-expr that the contextually expected type for an insertion in content (i.e. not in an attribute) is `xml`. 

This would create the unusual situation that it is not an error for the static type not to be the contextually expected type; but I don't think this is a problem,  and there are other situations where this can happen.  For example consider `x * y` when the contextually expected type is decimal; the contextually expected type for x and y should be decimal (so integer literals get the right interpretation) but it is not an error if one or x or y is an integer.

**Comment by lochana-chathura** [comment]
Small clarification. 

Shouldn't the contextually expected type(CET) for the interpolated expression be `xml` only when the expression is a `query-expr`? 

Otherwise, something like the below would be disallowed.
```bal
int rowNum = 3;
xml x = xml `<row>${rowNum + 1}</row>`;
io:println(x);
```

In the current implementation, we make CET `xml` only for `query-expr`. Otherwise, we infer the type for the interpolated expression and then check if it belongs to `int|float|decimal|string|boolean|xml` and log error.

**Comment by MaryamZi** [comment]
> I explained this to @MaryamZi in another issue (don't remember which). Perhaps she can explain this in terms of the jBallerina source.

The issue was https://github.com/ballerina-platform/ballerina-spec/issues/851 (https://github.com/ballerina-platform/ballerina-spec/issues/851#issuecomment-842938241). Discussed the type cast expression implementation with @lochana-chathura and I believe this is clear now.
