### ISSUE TITLE
How should *T interact with {| |}?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#71]
Currently the spec says that *T does not pull in any `X...` in T. That does not seem right for `{| |}` records, given our new approach in #60.

For example, given

```
type T record {| int...; |};
type R record {| *T |};
```

I think R should be equivalent to `record {| int...; |}`. If both T and R use `{ }`, then there is no issue.

The questions then are

1. What happens when T uses `{ }` and R uses `{| *T |}`?
2. What happens when T uses `{| X...; |}` and R uses `{ *T }`?

The spec will explain `record { F }` as being equivalent to `record {| F; (anydata|error)...; }`. So that implies that 

1. In case 1, R should pull in the implicit `(anydata|error)...;` field.
2. In case 2, the implicit `(anydata|error)...` field would override the `X...` in T, so in effect the *T would not pull in the `X...` as now.

So the net result would be:

- `record {| *T; |}` pulls in any `X...` from T, whether implied or explicit;
- `record { *T; }` is always  open to (anydata|error), regardless of T.

**Comment by jclark** [comment]
@sanjiva Do you agree?

**Comment by sanjiva** [comment]
Yep agreed.
