### ISSUE TITLE
Support encrypted values for Configurable variables

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-spec#712]
**Problem**
Configurations can contain passwords, secrets or any sensitive data. These will be encrypted when adding into Config.toml. ATM Configurable variables do not support encrypted values.

**Proposed solution**

***Encrypt a configuration value***

We do have encrypt command to encrypt configuration values.
```
$ bal encrypt
Enter value: 

Enter secret: 

Re-enter secret to verify: 

Add the following to the configuration file:
'<key>="@encrypted:{xSMtMw/exom7J2PQavwAHWwpLePbTUQsICxePoluWuM=}"'
```

This will ask for plain text value and secret output a encrypted value format of `@encrypted:{<encrypted>}`
ex.`@encrypted:{/9TKz+3bb++/TmHSrdwhk35K6tLetkWoQrSWA4LNLvQ=}`

***Adding encrypted text to configuration***

So we can add this encrypted value to the Config.toml as below.

[packagName]
dbPassword = `@encrypted:{/9TKz+3bb++/TmHSrdwhk35K6tLetkWoQrSWA4LNLvQ=}`

***Decryption of configurable value***
We can follow the similar approach we have used in config api.

1) When starting the ballerina program, it will either get the decryption secret from secret.txt file in current working directory (This will be removed once read)  or prompt for user to provide decryption secret.

2) Once the secret value is obtained, string values which prefix with `@encrypted:\\{(.*)\\}` will be decrypted and initialize the configurable variable.

**Security Consideration with approach**
Since we can only define global variables as configurable variable and initialize at the start up, those sensitive data will be in the memory until program dies. But when using old config api, it allows users to read configs to function variables.

***Approach 1***
Assign empty value once configurable variables are used.

```
configurable string username = ?;
configurable string password = ?;

function init() {
  jdbc:Client|sql:Error jdbcClient = new("jdbc:mysql://localhost:3306/testdb", username, password);
  username = "";
  password = "";
}
```

***Approach 2***
Define a runtime api to use them only inside functions.

```
function init() {
jdbc:Client|sql:Error jdbcClient = new("jdbc:mysql://localhost:3306/testdb", runtime:getConfig("username"), runtime:getConfig("password"));
}
```

**Comment by jclark** [comment]
That seems rather ugly and complicated to me.

What about this?

```
configurable string encryptedPassword = ?;
configurable string username = ?;

function init() returns error? {
    jdbc:Client jdbcClient = check new("jdbc:mysql://localhost:3306/testdb", username, config:decrypt(encryptedPassword));
}
```

**Comment by hasithaa** [comment]
80% of cases are encrypting string values. But it can support other simple basic types too. `decrypt` function can have a dependently-typed return type to support this use case.

**Comment by jclark** [comment]
Can you explain the use case for simple types? I can't think of a scenario.

The two types I can think of needing to encrypt are string and byte[]. So I would have two functions decryptString and decryptBytes, where decryptString is just decryptBytes followed by string:fromBytes.

I don't see a need for the flexibility of dependent types here.

**Comment by jclark** [comment]
Automatically removing a file after you've read it seems super-weird to me. Are there other widely used programs that do this?

Prompting the user is good. This should use /dev/tty and turn off echo. I guess in Java Console.readPassword does this.

**Comment by sanjiva** [comment]
That's part of a container deployment model. I don't think the Ballerina APIs need to do that .. I think K8s takes care of that as part of the secrets architecture.

Prompting is only useful in a very limited set of scenarios.

**Comment by warunalakshitha** [comment]
Yes. We need secret files for automated deployments. K8S secrets already has built-in secret management. I also agree ballerina apis does not need to do any removing or managing secrets.

So runtime can prompt users to provide the secret( We internally use Console.readPassword :))  or read the secret file path through an environment variable for any other automated deployment requirements.

We can introduce config lang lib for config decryption functionalities. For initial implementation I can go with decryptString and decryptBytes functions.

**Comment by jclark** [comment]
I had a look at the K8s secrets stuff here (which looks nice)

https://kubernetes.io/docs/concepts/configuration/secret/

To integrate well with that, shouldn't we be able to get a specific configurable item from a K8s secret?

**Comment by warunalakshitha** [comment]
AFAU we can create a k8s Secret and then add pod definition to read the value from secret key to env variable. So pod can consume the env variable which has secret value.  In that case, we might need to improve the configurable values to read from env variables too.
@anuruddhal any other suggestions :)?

https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

**Comment by hasithaa** [comment]
> Can you explain the use case for simple types? I can't think of a scenario.
> 
> The two types I can think of needing to encrypt are string and byte[]. So I would have two functions decryptString and decryptBytes, where decryptString is just decryptBytes followed by string:fromBytes.
> 
> I don't see a need for the flexibility of dependent types here.

It seems like encrypting int, float, decimal values are not used widely as I thought. But primarily strings and byte[]. So +1 to have decryptString and decryptBytes for now.

**Comment by warunalakshitha** [comment]
I am closing this issue since with the new spec, the ballerina platform does not provide a way to decrypt sensitive data which is part of the deployment. We have removed the old encryption and decryption code with https://github.com/ballerina-platform/ballerina-lang/pull/29634
