### ISSUE TITLE
Spec deviation `indexOf` and `lastIndexOf` methods in lang.array uses `PureType`

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-spec#715]
**Description:**

According to spec, we cannot call these two methods on an object type array. Is this the expected behaviour?

```Ballerina
# A type parameter that is a subtype of `anydata|error`.
# Has the special semantic that when used in a declaration
# all uses in the declaration must refer to same type.
@typeParam
type PureType anydata|error;
```

https://github.com/ballerina-platform/ballerina-spec/blob/90b7304832baa55d8d5585fc616d09dccafc75a2/lang/lib/array.bal#L133

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
Yes, because values are compared using `==` which is not defined on objects.

**Comment by KRVPerera** [comment]
Thank James.

**Comment by MaryamZi** [comment]
Now that we don't allow `==` with `error` shouldn't the parameters of `indexOf` and `lastIndexOf` be updated to work with only `anydata` instead of `PureType`?

https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/array.bal#L133

**Comment by jclark** [comment]
@MaryamZi I made a separate issue for this.
