### ISSUE TITLE
Index access on xml subtypes

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#727]
**Description:**
Are index access allowed on singleton xml items like xml:Element, xml:Comment, xml:Text, etc.

```ballerina
xml:Element e = xml `<e/>`;
var s = e[0]; // Should this be a syntax error, `index access not allowed on xml:Element`
```
**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
Yes: a singleton item is a sequence of length 1. Same rules applies to string and xml.

Just as `"x"[0]` evaluates to `"x"` (same as JavaScript), so ``xml`<p/>` `` evaluates to ``xml`<p/>` ``

**Comment by rdhananjaya** [comment]
Ack. Thanks

**Comment by rdhananjaya** [comment]
This also means member access on a `xml<T>` returns `xml` rather than a value with a static type of T right? 

```ballerina 
xml<xml:Element> elemS = getElementSeq();
xml:Element e = elemS[n]; // This should be an error as when `n` is larger than the size of `elemS` sequence, what get returned from member access is a `xml<never>`
```

**Comment by jclark** [comment]
The type of `elemS[n]` would be `xml:Element|xml<never>`, which is a subtype of `xml<xml:Element>`, which is a subtype of `xml`.

This is like how for a value m of type `map<T>`, `m["str"]` has type `T|()`.
