### ISSUE TITLE
Is xml<never> assignable to other xml sequences

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#729]
**Description:**
Is `xml<never>` a subtype of xml sequences like `xml<xml:Element>` where xml sequence is constrained by a xml subtype.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by jclark** [comment]
The only value that belongs to type `xml<never>` is the empty XML sequence. Since the empty XML sequence belongs to type `xml<xml:Element>`, `xml<never>` is a subtype of `xml<xml:Element>`.

**Comment by rdhananjaya** [comment]
Thank you.
