### ISSUE TITLE
Expected behavior of tuple reverse, filter and other langlib functions

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-spec#731]
**Description:**
All array functions exists for tuple type as well.
Currently the langlib definition for reverse is as in:
https://github.com/ballerina-platform/ballerina-spec/blob/b9805f8460ce1bed17475336efef746b3ab8b920/lang/lib/array.bal#L149
This causes unexpected behavior for tuple types. Same is for the filter function and other functions for which the return type is an array.

How are the array functions to be defined for the tuple type? 
   
**Code sample that shows issue:**
The following code causes unexpected behavior
```
public function main() {
    [int, string, float] tupleArr = [2,  "abc", 2.4];
    any[] y = tupleArr.reverse();
}
```

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/26820

**Comment by jclark** [comment]
A tuple is an array. The reverse function is a generic type defined for an array type. The most precise array type of which `[int, string, float]` is a subtype is `(int|string|float)[]`. So you instantiate the reverse function with that type. That means the static type of the result will be `(int|string|float)[]`, as will the inherent type of the newly created array, which will have three members.

**Comment by jclark** [comment]
This was also discussed in #551.

**Comment by riyafa** [comment]
@jclark there's one small issue in the suggestion.  According to this issue https://github.com/ballerina-platform/ballerina-lang/issues/26843 when we reverse an array we do it in place and return the same array. In the case of reversing a tuple this cannot be achieved because the types would be changed. For example if we reverse the following tuple:
    ```
[int, string, float] tupleArr = [2,  "abc", 2.4];
     (int|string|float)[] y = tupleArr.reverse();
```
if we try to make `y=== tupleArr` to true that is not possible, because the types would be different. 
My question is should the tuple reverse be done in place or is it okay to return a new array in this case? If we need not do it in place should the array reverse also return a new array without reversing in place.

**Comment by jclark** [comment]
None the functions that return their arg should modify it: that would be a terrible design.

I will create an issue to make fix the doc comments to make this clear.

**Comment by jclark** [comment]
See #749.

**Comment by riyafa** [comment]
@jclark thank you that makes more sense now 🙂
