### ISSUE TITLE
Minor changes required to isolation related content?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#733]
**Description:**
The ["Lock statement"](https://ballerina.io/spec/lang/master/#lock_statement) section says
> There are two cases where a variable is restricted to be used only within a lock statement:
> - when the variable is an isolated module-level variable; since module-level variables are not allowed to be public, this restriction applies to all functions in the module;

Since non-isolated module-level variables can now be public should this be 
> when the variable is an isolated module-level variable; since **isolated** module-level variables are not allowed to be public, this restriction applies to all functions in the module;

The ["Isolated Functions"](https://ballerina.io/spec/lang/master/#isolated_functions) section says
> Non-isolated module-level state can only be read in two cases, specifically a variable-reference can refer to an an identifier declared by a module-var-decl, listener-decl or service-decl only if:
> - the identifier is declared by a module-var-decl that includes final but does not include isolated, or is declared by a listener-decl or a service-decl, and ...

Should service-decl be removed here since a variable reference can no longer refer to a service-decl since there's no associated identifier?

**Comment by jclark** [comment]
Yes, right. Thanks.
