### ISSUE TITLE
Unused variable with inferred type including error

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#737]
Errors can too easily ignored like this:

```
function foo() {
     var x = int:fromString("xyz");
}
```

**Comment by MaryamZi** [comment]
Shouldn't this restriction apply in other scenarios where there may be such variables declared with `var` too? For example, the `match` statement, let variable declarations in let expressions and the `foreach` statement?

**Comment by MaryamZi** [comment]
Given that we cannot ignore errors with `_`, could this be too restrictive when `var` is used with non-capture binding patterns even in a variable declaration (where the error is part of a mapping, list, or another error value and not the value itself)? 

Just as an example, I want to use only the first and third members of the tuple in the following sample. I cannot ignore the second member of the tuple with `_` and I believe with the proposed restriction it will also be an error to not use `e`?

```ballerina
function tuple() returns [int, error, string] => [1, error("Error!"), "Hello"];

public function main() {
    var [i, e, s] = tuple();
}
```

**Comment by jclark** [comment]
I think `foreach` is not the same, because it does not allow you to ignore an error that is the result of an expression.

**Comment by jclark** [comment]
@MaryamZi Yes, the relevant type is the type of the expression on the RHS, not the type inferred for the variable.

**Comment by MaryamZi** [comment]
So, IIUC, this can result in an error only when the binding pattern is a capture binding pattern (that is not a member of another binding pattern)?

Agreed that the `foreach` statement is different.

**Comment by jclark** [comment]
Yes, I think that's right.

**Comment by jclark** [comment]
`from` and `join` in query-expr are like `foreach` statements.

**Comment by jclark** [comment]
@MaryamZi I redid the spec fix for this. Please check.

**Comment by MaryamZi** [comment]
+1. The changes that are being introduced to the implementation are in line with the updated spec.
