### ISSUE TITLE
Type that contains no shapes

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#74]
The language does not provide a way to describe the type that contains no shapes.  This would be useful for the return type of a function/worker that never terminates normally (which would be needed if we want to do something about #73).

This is not the same as the type `()` which contains exactly one value i.e. `()`.

At the moment, we have to say

```
function myPanic(error e) {
   panic e;
}
```

But this is not really right, because it is equivalent to saying `returns ()`, but in fact this function can never return nil.

The challenge is to find a name for this type that the unsophisticated user would not confuse with nil. Maybe something like `impossible`. (RELAX NG calls it `notAllowed`.)

Note that uses of this type would have some restrictions. For example, it would not make sense for a variable or a required parameter to be of type `impossible`.

**Comment by jclark** [comment]
This can also be used by a subtype to rule out an optional field.

```
type T1 record {
  string x;
  string y?;
};

type T2 record {
  string x;
  impossible y?;
};
```

**Comment by sameerajayasoma** [comment]
In Ballerina, we have any|error which represents all the values and singleton types: types with only one value. I think it'll be useful (especially for parameterized types) if we had a way to represent a type that has no values.

**Comment by jclark** [comment]
Also perhaps related to #119, since parameter types are contravariant.

**Comment by sameerajayasoma** [comment]
I think this is related to #7 as well. I created a duplicate issue(#126) and closed it.  #7 can be solved elegantly if we have a type that is a subtype of all types.

**Comment by jclark** [comment]
`never` might work nicely as the name for this type, particularly in the function type.

```
function foo() returns never { }
```

A value never belongs to the `never` type.

**Comment by jclark** [comment]
TypeScript uses `never` for this.

https://www.typescriptlang.org/docs/handbook/basic-types.html#never

**Comment by jclark** [comment]
The type of the empty xml sequence can be written as `xml<never>`.
