### ISSUE TITLE
Clarification regarding error constructor expression

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#740]
**Description:**
The [spec says](https://ballerina.io/spec/lang/master/#error-constructor-expr) the following regarding the error constructor expression.

> The type descriptor E implies a type descriptor D for the detail mapping. The arg-name of every named-arg must be specified as the field-name of an individual-field-descriptor occurring in D, unless there are no such field names.

Does "unless there are no such field names" here mean that we cannot pass additional fields even when `D` is an open record unless `D` has no individual field descriptors?

```ballerina
type Error error<record { int code; }>;
type ErrorTwo error<record { }>;

Error e1 = error Error("One", code = 1000); // OK

Error e2 = error Error("Two", code = 2000, additional = "additional field"); // Compilation error?

ErrorTwo e3 = error ErrorTwo("Three", code = 3000, additional = "additional field"); // OK
```

The spec also says
> The detail mapping is constructed as immutable, with its members being the result of applying the ImmutableClone abstract operation to the result of evaluating each named-arg and every defaultable arg.

Just to confirm that the mapping itself needs to be constructed as an immutable value, in addition to the fields being made immutable, rather than `error:detail()` creating an immutable clone of the mapping for each call?

```ballerina
error err = error("Error!", code = 1234);
boolean b = err.detail() === err.detail(); // Should be `true`?
```

**Comment by jclark** [comment]
> Just to confirm that the mapping itself needs to be constructed as an immutable value

There's no point in constructing it as mutable and then making an immutable copy every time. It's simpler just to construct as immutable to start with. Also `error` is supposed to be an immutable value and immutability is deep, so we shouldn't have error referring to something mutable.

**Comment by jclark** [comment]
"unless there are no such field names" means "unless there are no field names that are specified with individual-type-descriptors in D".

So `e2` is an error, but `e1` and `e3` are not. The point of `e2` is to stop typos with optional fields e.g.

```
type Error3 error<record { int code?; }>;

Error3 e3 = error Error3("whoops", coode=1); // want to get an error here
```

We could loosen this restriction, but I think the common cases are no error detail type at all, or the developer has specified a detail record which includes all the needed fields.

**Comment by MaryamZi** [comment]
> > Just to confirm that the mapping itself needs to be constructed as an immutable value
> 
> There's no point in constructing it as mutable and then making an immutable copy every time. It's simpler just to construct as immutable to start with. Also `error` is supposed to be an immutable value and immutability is deep, so we shouldn't have error referring to something mutable.

Noted, this is how the implementation does it too.



> "unless there are no such field names" means "unless there are no field names that are specified with individual-type-descriptors in D".
> 
> So `e2` is an error, but `e1` and `e3` are not. The point of `e2` is to stop typos with optional fields e.g.
> 
> ```
> type Error3 error<record { int code?; }>;
> 
> Error3 e3 = error Error3("whoops", coode=1); // want to get an error here
> ```
> 
> We could loosen this restriction, but I think the common cases are no error detail type at all, or the developer has specified a detail record which includes all the needed fields.

Understood, thank you.
