### ISSUE TITLE
Clarification on read-only bit of an object with all `final` fields but with field types that are not a subtype of `readonly`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#746]
**Description:**
The spec says 
> An object-constructor-expr will construct an object with its read-only bit set if every object-field is **declared** as final and has a type-descriptor that is a subtype of readonly. In this case, the static type of the object-constructor-expr will be intersected with readonly.

But what about a scenario where all the fields are declared as `final` and the type-descriptors are **not** subtypes of `readonly`, and at runtime, the values set to these fields are immutable values? In such a scenario, shouldn't the read-only bit be set to the constructed object also?

```ballerina
int[] arr = <readonly> [1, 2, 3];

object {} ob = object {
    final int[] x;

    function init() {
        self.x = arr; // `arr`'s read-only bit is set
    }
};

boolean b = ob is readonly; // shouldn't this be true?
```

**Comment by jclark** [comment]
That's coherent, but I think that's the start of a slippery slope. Suppose `x` was private, initialized with a read-only value, not declared as `final`, but in fact was not assigned to outside `init`.  I think the same logic would make it read-only in that case also.

**Comment by MaryamZi** [comment]
Yes, agreed. This would also require special analysis at runtime (when constructing the value), which I don't think we do anywhere else.
