### ISSUE TITLE
Can a record-type-descriptor or object-type-descriptor override fields pulled in with *T?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#75]
At the moment this is specified for `T...` only, but perhaps it should work more generally.

**Comment by jclark** [comment]
Probably should have constraint that override is a subtype.

**Comment by jclark** [comment]
The spec is now calling `*T;` type inclusion.

**Comment by jclark** [comment]
The rule should be that it's OK to override, provided the type of the overriding field is a subtype of the type of the overridden field.

**Comment by hasithaa** [comment]
This also means Type Inclusion can have cycles if an overriding field has the same type.

```ballerina
// Case 1 - OK, Same type,
// Both X and Y == record { int x; string y; int z;}
type X record {|
    int x;
    int z;
    *Y; 
|};


type Y record {|
    string y;
    int z;
    *X;
|};


// Case 2 -  Compile time error.
// Assume Student is a subtype of Person
type A record {|
    Person x;
    *B; // <- This is a compile time error. 
|};


type B record {|
    Student x;
    *A;
|};
```

**Comment by jclark** [comment]
Type inclusions should not allow cycles in my view.

**Comment by KRVPerera** [comment]
We currently give a helpful error to the user for duplicating type inclusions like below example.
```Ballerina
type B object {
    *T1;
    *T1;
}
```

With the changes, we are planning to introduce it is possible to have duplicate inclusion deep in a hierarchy. I am wondering whether we should silently ignore this. This can be a mistake done by the user. Since we are overriding and there are no cycles this is valid now. 

```Ballerina
type B object {
    *T1;
};

type C object {
    *T1;
};

type D object {
    *B;
    *C;
};
```

**Comment by jclark** [comment]
@KRVPerera I'm not sure if I have completely understood your point.

If you do:

```
type B object {
   int x;
};

type C object {
  int x;
};

type D object {
   *B;
   *C;
};
```

then that is (to me) clearly an error because you have attempted to declare two fields named `x` for D. Whether B and C have the same name or not makes no difference to whether it's valid (though it might affect the error message that you give).

Similarly your D would be an error unless T1 declares no fields and no methods.

**Comment by KRVPerera** [comment]
@jclark  Think I misunderstood the feature before. I interpreted that each type-inclusion copies field declarations and override them after. This means `*B` will include fields belong to `B`. Then the `*C` will override already included fields by `*B`.

**Comment by jclark** [comment]
@KRVPerera I see the confusion. For an object, think of `*T;` more like `extends T`. In the example, declarations in D can override declarations in B and C, but those C cannot override those in B.
