### ISSUE TITLE
Should prohibition of casting away error affect `toString`

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-spec#750]
**Description:**
With a prohibition of casting away error, now we have to write a few extra lines to call `toString` like method for a union.

eg: This is a boilerplate code we usually write for asserting.

```Ballerina
function assertEquality(any|error expected, any|error actual) {
    if expected is anydata && actual is anydata && expected == actual {
        return;
    }

    if expected === actual {
        return;
    }

    string expectedValAsString = expected is error ? expected.toString() : expected.toString();
    string actualValAsString = actual is error ? actual.toString() : actual.toString();
    panic error(string `expected '${expectedValAsString}', found '${actualValAsString}'`);
}
```

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
Yes, see #350.

That function is just not good at all. If you want some blend of `==` and `===`, then you should come up with a library function that does it properly.
