### ISSUE TITLE
!is operator

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#752]
Kotlin has a `!is` operator, which would be useful. It allows you to write

```
if x !is error {
}
```

instead of

```
if !(x is error) {
}
```

Not a big deal, but a nice, little improvement.

**Comment by senakafdo** [comment]
Alternatively, we could follow Python's approach of an ['is not' operator](https://docs.python.org/3/library/operator.html#operator.is_not).

**Comment by jclark** [comment]
Python has a `not` keyword: `not` applied to a boolean in Python does the same as our `!` operator.  So, while `is not` makes sense for Python, the right approach for Ballerina is `!is`. (Also `is` in Python is our `===`: our `is` is the same as Kotlin's `is`.)

**Comment by sameerajayasoma** [comment]
Can we get this for Beta @hasithaa? This is a useful operator.

**Comment by jclark** [comment]
@sameerajayasoma I think we should discuss priorities for additions to the language. There are lots of useful things that we could add.
