### ISSUE TITLE
Inconsistency in how constructors and binding patterns allow {| |}

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#76]
I have noticed that there is an inconsistency in our design, in that

1. Binding pattern syntax always mimics constructor syntax rather than type descriptor syntax
2. Record type descriptors use `{| |}` delimiters
3. Mapping constructors do not use `{| |}` delimiters
4. Binding patterns use `{| |}` delimiters

**Comment by jclark** [comment]
We have three options:

1. Allow mapping constructors to use `{| |}`
2. Do not allow binding patterns to use `{| |}`
3. Decide we prefer the inconsistency

The only disadvantage of (2) is that we lose a little functionality. We lose the ability in a pattern match to say that we want these fields and no other. But do we actually need that?  You could argue that we can handle that (if we need it) with a type test. There is also a complication in the current design, which I think is unavoidable of we have both flavours of mapping binding pattern: it is unclear whether a binding pattern using `{ }` should require unspecified fields to be of type `anydata|error`. With the two flavours of mapping binding pattern, it is unclear whether they should or not (I wrote it up that they should so require). With one flavour of mapping binding pattern, I think it is clear that they should not.

The disadvantage if option 1 is I think whatever semantics we choose for `{| |}` constructors, users will sometimes end up choosing the wrong one and getting confused.

Overall I think I favour option 2, even though it represents a small loss of functionality. @sanjiva what do you think?

**Comment by sanjiva** [comment]
I agree with going with option 2.  As you noted the loss of functionality is minimal and can in any case be dealt with a type test as part of the binding pattern.

**Comment by jclark** [comment]
Another disadvantage of 2 is that there's an inconsistency between tuples and records.  For tuples, the exclusive syntax (i.e round parentheses) work both for types and constructors/binding-patterns, whereas for records the exclusive syntax (i.e. record {| |}) works only for types.

**Comment by jclark** [comment]
Disadvantage 2 would be dealt with by #78.
