### ISSUE TITLE
Intersection in class definitions with multiple inclusions

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-spec#767]
**Description:**
Please refer the following scenario where a class definition has multiple inclusions (somewhat like a multiple inheritance scenario in Java).

```bal
type JObject object {
    handle jObj;
};

class A {
    *JObject;

    function init(handle obj) {
        self.jObj = obj;
    }
}

class B {
    *JObject;

    function init(handle obj) {
        self.jObj = obj;
    }
}

class C {
    *A;
    *B;

    function init(handle obj) {
        self.jObj = obj;
    }
}
```
Output:
```
ERROR [main.bal:(23:6,23:7)] redeclared symbol 'jObj'
```

Here, `class C` seems to inherit the `handle jObj` twice. However, in an instance of this sort, wouldn't it be more appropriate for `class C`  to inherit a single `handle jObj` field since both are of the same type and same variable name? Or in other words, would it be more appropriate to include the intersection of the inherited fields?

**Related Issues:**
https://github.com/ballerina-platform/ballerina-spec/issues/544 might be a related issue.

**Comment by jclark** [comment]
See https://github.com/ballerina-platform/ballerina-spec/issues/696#issuecomment-763312787

You can override in class C to make explicit what you want:

```
class C {
  *A;
  *B;
  handle jObj;
  function init(handle obj) {
      self.jObj = obj;
  }
}
```
