### ISSUE TITLE
value:isReadOnly is no longer needed

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#769]
**Description:**
https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/value.bal#L84

Is it intentional to restrict this function to `anydata`, it feels like I should be able to use `isReadOnly` with any value.

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
Do we still need isReadonly? Now that we have the readonly type, we can just do `is readonly` instead.

**Comment by jclark** [comment]
If we keep it, I agree it should be application to `any`.

**Comment by rdhananjaya** [comment]
`is readonly` work as expected for all types (at least for the types I tested with)

**Comment by jclark** [comment]
Do we have library code that depends on it? If not, I suggest we just remove it.

**Comment by hasithaa** [comment]
+1 to remove isReadOnly, I haven't seen any usages of this.

**Comment by jclark** [comment]
We agreed to remove this.
