### ISSUE TITLE
0-tuples vs nil

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#77]
We added singleton tuples, which raises the question of what about 0-tuples.

We can write a zero length array: `int[0]` or `string[0]`. But these are a bit weird because they are really the same: it doesn't matter what the member type is, if you can't have any members.

Given some function f, we can write a tuple type for the parameter list, such that if v is tuple of that type, the `f(...v)` will be well-typed, except for only one case: where f has no parameters.

At the moment we have two distinct values:

1. nil
2. a list whose inherent type allows no members

Confusingly the syntax for 1 looks like 2. But at the moment the spec makes them different. 1 is a simple type, whereas 2 is a reference type (of which you can have many instances).

It feels like these should be one thing not two. If so, how should these be unified?

**Comment by jclark** [comment]
Unfortunately unifying them would make `[] == ()` true, which would not be desirable. Argh.

**Comment by jclark** [comment]
@sanjiva Any thoughts?

One (radical) solution would be to write tuples types using square brackets (rather than round) and get rid of tuple constructors.

**Comment by hasithaa** [comment]
Seems like, flow [1], typescript [2] use square brackets for tuples. 

[1] - https://flow.org/en/docs/types/tuples/
[2] - https://www.typescriptlang.org/docs/handbook/basic-types.html

**Comment by jclark** [comment]
I have created issues #78 and #79 to capture the more fundamental issues that this raises.
