### ISSUE TITLE
Possible flexibility for using non-isolated methods within the isolated method contextually

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-spec#771]
**Description:**
Does the language provide the $subject based on the context? The following use case has been a blocker.

1. Some APIs provided by the ballerina io package are not isolated based on their context (https://github.com/ballerina-platform/ballerina-standard-library/issues/186)

2. HTTP client remote methods use those non-isolated IO APIs, hence client remote methods cannot be marked as isolated. 

3. If the user wants to do an HTTP call inside an isolated function, obviously it leads to a compilation error as the remote method is not isolated. One such blocker is reported here. (https://github.com/ballerina-platform/ballerina-lang/issues/29014)

@jclark We would like to know your thoughts on this.

@shafreenAnfar @daneshk @BuddhiWathsala

**Comment by jclark** [comment]
The io package APIs should be isolated.

**Comment by jclark** [comment]
If your concern is about concurrent modifications to the filesystem, then I wouldn't call that a thread-safety issue: you can get the same problem with two separate Ballerina programs writing a file. The solution to that is file locking.

**Comment by chamil321** [comment]
Thanks for the clarification. We'll proceed accordingly.

**Comment by jclark** [comment]
BTW, I would expect all public functions and methods in the standard library to be isolated. Please discuss with me any that aren’t.

**Comment by niveathika** [comment]
@jclark Should we make the DB operations API (Query & Execute) isolated? Since this is an external system we cannot guarantee immutability or same results always.

**Comment by jclark** [comment]
@niveathika Yes, you should: `isolated` does not imply anything about the effects on something outside the current process.
