### ISSUE TITLE
Clarification regarding the iterator type of empty closed record

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-spec#774]
**Description:**
**Question 1**
```ballerina
type Foo record{|
|};
public function main() {
    Foo f = {
    };
    foreach var x in f {
    }
}
```
**1.1** Is this a valid program?
**1.2** If it valid. What is the type of `x`?

**Question 2**
What is the type of return value  of `f.iterator()` (related to the above program)

**Comment by jclark** [comment]
Interesting question.

We need to ask: what is the smallest T such that `Foo` is a subtype of `map<T>`?  The answer is `never`. So this would mean that if we allow this the type of `x` would be never.

Usually you cannot have a variable of type `never`. See #510. I think you could make a case for allowing it here, but for now, I would suggest disallowing it.

**Comment by jclark** [comment]
Better fix is here: https://github.com/ballerina-platform/ballerina-spec/issues/510#issuecomment-797161161
