### ISSUE TITLE
Langlib function to iterate in decrementing order and/or with steps

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-spec#775]
**Description:**
As of now, there's no direct way to write a loop which decrements the looping variable or decrement/increment with a step. In other languages we have the traditional for loop which gives us the control to increment/decrement the variable accordingly.

Achieving the same in Ballerina requires us to either
1. write a while loop where we have to handle the iterating value manually
```ballerina
int i = 100;
while (i >0) {        
    i = i -2; 
}
```
2. Use a foreach with precalculated values which is not memory efficient
3. Use an iterator ([an example](https://play.ballerina.io/?gist=53822ec369443f62f066de1181ee8656&file=play.bal)) which is a bit complex IMO

It would be great if we can introduce such a loop as all the popular languages provide this out of the box.
Examples:

_Go_
```go
for j := 0; j <= 100; j+=2 {
        fmt.Println(j)
}
```
_Java_
```java
for(int i=100; i>0; i-=5) {
}
```
_Python_
```python
for i in range(0,10,2):
  print(i)
```

**Suggested Labels:**
lang, enhancement

**Comment by jclark** [comment]
We can do this by adding a langlib function to lang.int that takes three arguments and returns an `Iterable<int,()>`.  This is like Python. It is also what Swift does (we get the `..<` syntax from Swift); see https://developer.apple.com/documentation/swift/strideable

**Comment by IMS94** [comment]
That sounds good! Thanks!

**Comment by jclark** [comment]
Might be nicer for the object returned by `...` or `..<` to provide methods that return another range  i.e.

```
foreach int i in (0 ..< 10).reverse() { ... }
```

**Comment by jclark** [comment]
I think we can model this after the Python range constructor

https://docs.python.org/3.3/library/stdtypes.html#ranges

**Comment by jclark** [comment]
```
// Module lang.int
// Panics if step is 0.
public isolated function range(int start, int end, int step) returns object {
    public isolated function next() returns record {|
        int value;
    |}?;
} = external;
```

**Comment by hasithaa** [comment]
This should work. do we need something equivalent in float/decimal too?

**Comment by jclark** [comment]
> do we need something equivalent in float/decimal too?

We could add it, but I think it would be much less useful. Let's see if anybody needs it.

**Comment by sanjiva** [comment]
So will the `x..<y` syntax map to this function? The syntax is limited and if you want more use this langlib function instead?

**Comment by jclark** [comment]
> So will the x..<y syntax map to this function?

`x ..< y` is the same as `int:range(x, y, 1)`.

> The syntax is limited and if you want more use this langlib function instead?

Yes.

**Comment by gimantha** [comment]
> ```ballerina
> // Module lang.int
> // `end` is exclusive
> // next() returns members from set S where S is the set of integers { start + step*i where i >= 0 }
> // When step is > 0, the members of S that are < end are returned in increasing order.
> // When step is < 0, the members of S that are > end are returned in decreasing order.
> // When step is 0, the function panics.
> // It is not an error if S is empty.
> public isolated function range(int start, int end, int step) returns object {
>     public isolated function iterable() returns object {
>         *object:Iterable;
>         public isolated function next() returns record {|
>             int value;
>        |}?;
>     };
> } = external;
> ```
> 
> Edited: range needs to return an Iterable not an Iterator.

@jclark Is the return type of the `range` function correct? Here, the `range` function returns an object which has a function called `iterable`.

**Comment by jclark** [comment]
The function should be named `iterator` not `iterable`.

**Comment by jclark** [comment]
The inclusion of object:Iterable is in the wrong place also.

@gimantha Please check fixed version.
