### ISSUE TITLE
Use square brackets for tuples

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#78]
Our current approach to tuples feels unsatisfactory:

1. We have only one syntax to construct mapping values, but we have two syntaxes to construct list values.
2. We have two flavours of list type descriptor, one using parentheses and one using square brackets, and two flavours of list value constructor, one using parentheses and one using square brackets. The difference between the two flavours of type descriptor is that parentheses allow different member types. But the difference between the two flavours of value constructor is that parentheses makes the length fixed.
3. A value of a type defined using `(X, T…)` will become fixed length if it is constructed using `(x, y, z)` syntax.
4. No nice syntax for 0-length list type.
5. Trailing comma syntax hack needed for 1-length tuple

Both Flow and TypeScript use square brackets for tuples. We could consider doing the same. This would mean:

- Use square brackets for tuple type, so `[T1, T2]`, `[T1, T...]`, `[T1]`, `[T...]`, `[]` would all be allowed.
- Array types continue to be allowed as now.
- Only one way to construct list `[x, y, z]`; `(x, y, z)` syntax would go away.

We would have to decide how to infer the type of the list constructor. For example, what is the type of x in this:

```
var x = [1, "foo"];
```

There are at least 5 types that could be inferred:

1. `[int, string]`
2. `(int|string)[]`
3. `[int, string, (anydata|error)...]`
4. `[(int|string), (int|string)]`
5. `[(int|string), (int|string), (anydata|error)...]`

Case 3 is comparable to what the spec now says for records, but does not seem useful for arrays. Case 1 won't extend well to empty arrays. Case 2 will be wrong when lists are being used as tuples.

The most straightforward solution is to say that it is simply an error to use a list constructor without a contextually expected type. If we do this, then we should do the same for mapping constructors.

**Comment by jclark** [comment]
@hasithaa, @sameerajayasoma Thoughts? Will be have any grammar problems?

**Comment by hasithaa** [comment]
>The most straightforward solution is to say that it simply an error to use a list constructor without a contextually expected type. If we do this, then we should do the same for mapping constructors.

@jclark even in the current implementation, we don't allow this. So +1 for this behavior. 

I checked for possible grammar conflicts; it seems like new syntax won't cause an issue. Sounds like a lot of migration ahead, as we have used tuples in a lot of test cases.

**Comment by sameerajayasoma** [comment]
+1 for this change. 

I guess the syntaxes `int[2]` and `[int, int]` means the same thing.

**Comment by jclark** [comment]
@sameerajayasoma Correct.
