### ISSUE TITLE
Subtyping with `T|never`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#782]
**Description:**
For the `never` type, the spec says 
> Note that for any type T, the type T|never is the same as T.

But should subtype checks also consider `T|never` as `T`?

For example,

**Case I:**
```ballerina
function func() returns never {
    panic error("Error!");
}

function () returns int|never f1 = func; // Is this valid?
function () returns int? f2 = func; // Valid, since `never` is a subtype of `()`?
```

**Case II:**
```ballerina
function func(record {| never x; |} rec) { 
    record {| int|never x; |} y = rec; // Is this valid?
}
```

Although this function will never actually be executed, as discussed in #510, the parameter of type `record {| never x; |}` will be valid, so what about the compile-time checks for the `y` declaration?

**Related Issues:**
https://github.com/ballerina-platform/ballerina-spec/issues/510

**Comment by jclark** [comment]
`T|never` describes exactly the same type (set of shapes) as `T`. Subtyping is based on the set of shapes that a type denotes.

Your examples in Case I are all perfectly type-safe. Just as these are fine

```
function func() returns int? {
  // actual return type of body is ()
  return ();
}

function func() returns int {
  // actual return type of body is never
  panic error("do not call me");
}
```

Why is case II valid?  `record {| never x; |}` is equivalent to `never` and you cannot have a parameter of type `never`.

**Comment by MaryamZi** [comment]
> `T|never` describes exactly the same type (set of shapes) as `T`. Subtyping is based on the set of shapes that a type denotes.
> 

Understood. The implementation does allow 

```ballerina
function func() returns int {
  // actual return type of body is never
  panic error("do not call me");
}
```

but we don't seem to be allowing the following atm. We will fix this.

```ballerina
function func() returns never {
    panic error("Error!");
}

function () returns int x = func;
```

> 
> Why is case II valid? `record {| never x; |}` is equivalent to `never` and you cannot have a parameter of type `never`.

I misunderstood this, didn't realize the type itself would be considered as `never`. This is clear now. Thank you.
