### ISSUE TITLE
Allow destructing of lambda args

### ISSUE THREAD

**Issue by grahnj** [ballerina-platform/ballerina-spec#783]
**Description:**
As a user of the Ballerina language, I would like the ability to desctucture array/tuple parameter in a lambda. This would help Ballerina be used in a more functional and dynamic manner and remove some of the existing syntax bloat.

**Suggested Labels:**
lambda, destructure
   
**Code sample that shows issue:**
```
[int, string][] tupleArr = [[1, "val1"], [2, "val2"], [3, "val3"]]
map<any>[] mapped = tupleArr.'map([k, v] => {index: k, val: v});
```

**Related Issues:**
I would expect for any reasonable desctructuring that is available elsewhere in the language to also be available in a lambda shorthand. Some psuedo-code examples have been provided below.

`[first, ...rest] =>` where `...rest` represents the remaining elements (and returns an empty array when empty)
`[a, b, c] =>` where `a` `b` and `c` are the elements of a length three tuple.

**Comment by jclark** [comment]
I agree.  This is #107.
