### ISSUE TITLE
Clarification regarding relational expressions 

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-spec#787]
**Description:**
As per the spec, to test the relative order of two values using `relational expressions`, there must be an `ordered` type to which the static type of both operands belong.

`type OrderedType ()|boolean|int|float|decimal|string|OrderedType[];`

Consider the following.

1.
```
int a = 1;
float b = 12.5;
boolean x = a > b; // compilation error
```
2.
```
int|float a = 1;
int|float b = 12.5;
boolean x = a > b; 
```
Example 2 won't give a compilation error. Should this be allowed?

**Comment by hasithaa** [comment]
I think it should be a compile-time error, because `int|float` is not an ordered type. Maybe we can update the spec on this.

**Comment by jclark** [comment]
There is a confusion here.

The spec’s definition of when a type is ordered is here: https://ballerina.io/spec/lang/draft/v2020-12-17/#ordering . The only union type that is ordered is a union with nil: `float|int` is certainly not an ordered type. Note that the definition of when a type is ordered is not equivalent to being a subtype of some type.

```
# Any ordered type is a subtype of this.
public type OrderedType ()|boolean|int|float|decimal|string|OrderedType[];
```

This is in lang.array. This is the smallest type that any ordered type is a subtype of i.e. the best approximation as a type of the concept of an ordered type.  It is **not** the definition of an ordered type; it is not possible to define the concept an ordered type using a type definition: there is no type O such that a type is ordered if and only if it is subtype of O.

**Comment by jclark** [comment]
The implementation should have a special test to give an error if sort is used with a type that is not ordered.

**Comment by lasinicl** [comment]
@jclark    
``` 
int? x = 1;
int? y = ();
boolean a = x > y;
boolean b = x < y;
```
As per the spec this is `UN` since `Compare(x,()) is UN if x is not ()`

For a relational expression

<pre>
The result of relational-expr is true if and only if the result of the Compare(x,y) operation is

LT, if the operator is <
GT, if the operator is >
LT or EQ, if the operator is <=
GT or EQ, if the operator is >=
and <b>otherwise false</b>.
</pre>
Is the value of both `a` and `b`,  `false` then?

**Comment by jclark** [comment]
Yes: nil works the same as NaN.
