### ISSUE TITLE
Remove () syntax for nil

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#79]
At the moment we have two ways of writing nil: `()` and `null`.  The current status does not feel satisfactory for a number of reasons:

* having both null and `()` is confusing
* in languages that use `()` the rationale is that it is a zero-length tuple, but that does not apply for us (certainly not since lists and tuples were unified)
* parentheses are already overloaded: in particular for function parameters and function calls
*  `foo(())` is ugly and unreadable: `foo(null)` is better

The most straightforward solution is simply to get rid of `()` syntax, so that `null` would be only way to write the null value. The type would then be renamed from nil to null.

The disadvantage is that null is Ballerina is more general than null in Java, which might confuse people.

**Comment by sanjiva** [comment]
I'm +1 for s/()/null/g.

**Comment by hasithaa** [comment]
Another solution is to replace `()` with `nil`. Then we will end up with both `nil` and `null` (in JSON context) which might lead to another confusion.  So I am +1 for using `null` to represent null value. 

But this brings up another point where Ballerina nil/null used in both null and void contexts, while some languages have both null and void as a separate concept.  I think we can bring the void type to avoid that confusion, But I am not sure we are gaining anything from that seperation.

**Comment by jclark** [comment]
That's a good point about void. It does feel weird to use null for what C calls void.

**Comment by jclark** [comment]
We decided not to do this, because of the void problem.
