### ISSUE TITLE
Returning map from a GraphQL resource

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-spec#790]
**Description:**
When we returning a map from a GraphQL resource, what should be the output object look like?

For an example:

```ballerina
import ballerina/graphql;

public type Person record {|
    string name;
    int age;
|};

service graphql:Service on new graphql:Listener(9090) {
    resource function get people() returns map<Person> {
        Person p1 = {
            name: "John Doe",
            age: 20
        };
        Person p2 = {
            name: "Jane Doe",
            age: 30
        };

        return { "John": p1, "Jane": p2 };
    }
}
```

When there's a query on this resource, how are we going to validate the document?

A sample query will look like the following:
```
query {
    people {
        name
    }
}
```

There are two possible ways to handle this.

1. Return a JSON array. 
In this case, we just ignore the keys of the map, and create an array from all the items in the map, and return it. We can validate whether the query consists of correct fields from the `Person` record. 

```json
{
    "data": {
        "people": [
            {
                "name": "John Doe"
            },
            {
                "name": "Jane Doe"
            }
        ]
    }
}
```

2. Return a JSON map.
The issue here is that when we return a JSON map, it will look like this:

```json
{
    "data": {
        "John": {
            "name": "John Doe"
        },
        "Jane": {
            "name": "Jane Doe"
        }
    }
}
```

There's no way to validate this query since the map content (keys) are dynamic. 

WDYT? @jclark @shafreenAnfar 

**Related Issues:**
Related issue to track the feature: [ballerina-standard-library#999](https://github.com/ballerina-platform/ballerina-standard-library/issues/999)

**Comment by jclark** [comment]
I don't think that there is any GraphQL output type that is a reasonable representation of `map<T>`, so I would not support this. The case where `map<T>` does make sense with GraphQL is when it is a record field e.g.

```
type Members record {
   map<Person> personByName;
};
```

In a case like this `personByName` corresponds to a GraphQL field with a single parameter of type string. GraphQL requires the name of the parameter to be defined, which Ballerina does not give you explicitly.  Three possibilities to handle this:

1. annotation
2. fixed default name (e.g. `key`)
3. derive from name of field e.g. if name of field is `xxxByY` then make the name of the parameter `Y`.

**Comment by sanjiva** [comment]
Since we're auto generating I'd prefer option 2 as the default with option 1 being the way to override.

**Comment by ThisaruGuruge** [comment]
> I don't think that there is any GraphQL output type that is a reasonable representation of `map<T>`, so I would not support this. The case where `map<T>` does make sense with GraphQL is when it is a record field e.g.
> 
> ```
> type Members record {
>    map<Person> personByName;
> };
> ```
> 
> In a case like this `personByName` corresponds to a GraphQL field with a single parameter of type string. GraphQL requires the name of the parameter to be defined, which Ballerina does not give you explicitly. Three possibilities to handle this:
> 
> 1. annotation
> 2. fixed default name (e.g. `key`)
> 3. derive from name of field e.g. if name of field is `xxxByY` then make the name of the parameter `Y`.

Thanks for the clarification, @jclark. We will work on implementing this.

For the initial implementation, 

> Since we're auto generating I'd prefer option 2 as the default with option 1 being the way to override.

As the first step, we'll go for option 2, and then add the functionality to override using option 1.
