### ISSUE TITLE
Should organization/module name in an import declaration be restricted?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#791]
Currently it's an identifier, which allows (via escaping) arbitrary non-empty Unicode strings.

We could have restrictions at the language level or at the platform level (as a restriction imposed by Ballerina Central).

Possible restrictions:

- ASCII only
- length
- only characters that would be allowed without use of `\`
- no `_`
- case insensitive (map to upper or lower or preserve case) (easier with ASCII only)

**Comment by chalitha1989** [comment]
How about imposing the following restrictions on organization names to closely align them with GitHub orgname pattern and to provide a better experience in UIs? 

1. Case insensitive. Cannot create two orgs with the same name but with different cases. (ballerina = Ballerina)
2. Min character length is 3 (This is the current Bcentral min limit. Three characters can form more meaningful & readable orgnames)
3. Max character length is 39 (GH max limit).
4. Contain alphanumeric characters or hyphens only. Underscore is not allowed since it is not URL friendly. (GH policy)
5. Cannot begin or end with a hyphen (GH policy)
6. Cannot have multiple consecutive hyphens (GH policy)

**Comment by jclark** [comment]
We need to address this for nBallerina also.

The language does not allow underscores in identifiers without quoting, so I think it is better for the language to allow underscores but not hyphens, and the UI to map underscores to hyphens.

I am in favour of:

- ASCII only
- alphanumeric + underscore only
- no initial underscore
- no trailing underscore
- no consecutive underscores

Putting a length restriction in the language would be pretty weird.

Preventing two organizations with the same name but different cases is I think best done at Ballerina central.

@sameerajayasoma What are your thoughts?

**Comment by jclark** [comment]
We decided to do this for both organization names and module names.

The spec will have a separate grammar for these names that allows only the specified characters without any escaping.

**Comment by sameerajayasoma** [comment]
Let’s apply the same rules to modules names as discussed in the meeting

**Comment by azinneera** [comment]
> We need to address this for nBallerina also.
> 
> The language does not allow hyphens in identifiers without quoting, so I think it is better for the language to allow underscores but not hyphens, and the UI to map underscores to hyphens.
> 
> I am in favour of:
> 
> * ASCII only
> * alphanumeric + underscore only
> * no initial underscore
> * no trailing underscore
> * no consecutive underscores
> 
> Putting a length restriction in the language would be pretty weird.
> 
> Preventing two organizations with the same name but different cases is I think best done at Ballerina central.
> 
> @sameerajayasoma What are your thoughts?

When we implemented this, the mentioned restrictions were added which means a module name can have any alphanumeric value as the initial character including digits. But as per the spec, names of organizations and modules are supposed to start with an ASCII letter [1]. I think we should include this restriction to the validation as well.

@sameerajayasoma @jclark thoughts please.

[1] https://ballerina.io/spec/lang/2022R1/#RestrictedIdentifier

**Comment by jclark** [comment]
Before these restrictions, these names were identifiers and identifiers cannot start with an unescaped digit.  So the restricted identifier syntax doesn't allow this either.

Is there something unclear in the spec?

**Comment by azinneera** [comment]
> Before these restrictions, these names were identifiers and identifiers cannot start with an unescaped digit. So the restricted identifier syntax doesn't allow this either.
> 
> Is there something unclear in the spec?

Thanks for the clarification. The spec is clear. When implementing the points in the comment, we have missed considering the restrictions that apply to an identifier at first.
