### ISSUE TITLE
Should the TokenWhiteSpace be disallowed in absolute and relative resource path?

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-spec#792]
**Description:**
[absolute-resource-path](https://ballerina.io/ballerina-spec/spec.html#absolute-resource-path),  [resource-path](https://ballerina.io/ballerina-spec/spec.html#resource-path) being started with a lower case letter,  and according to [TokenWhiteSpace](https://ballerina.io/ballerina-spec/spec.html#TokenWhiteSpace) section in the spec,
> TokenWhiteSpace is implicitly allowed on the right hand side of productions for non-terminals whose names start with a lower-case letter.

below sample is allowed.

```bal
service / foo / bar on foobar {
    
}
```

**Comment by jclark** [comment]
This is allowed: `/ ` is a separate token, and space is allowed between tokens.
