### ISSUE TITLE
String template expression should mention string as a valid static type for an expression in an interpolation

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#795]
**Description:**
The [spec](https://ballerina.io/ballerina-spec/spec.html#string-template-expr) currently requires the static type of an expression in an interpolation of a string template expression to "be a simple type and must not be nil".

But given that `string` is no longer a simple type, support for string needs to be mentioned.

Also the implementation currently does not allow in an interpolation an expression with a static type that is a union of two or more of the allowed types because the requirement is that it is a simple type.

Should this be allowed?

```ballerina
public function main() {
    int|boolean x = 1;
    string s = string `Value ${x}`;
}
```

**Comment by jclark** [comment]
We should allow a union: the spec's wording was sloppy here.
