### ISSUE TITLE
Clarification: multiple references to named workers

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#799]
**Description:**
1) Section 7.3.2 of the spec says:
```
A strand can initiate a wait on another strand by using a wait-action with a value of type future. 
Only one wait on a strand can succeed; this wait receives the value returned by the strand. 
Any other waits on that strand fail. It is a compile-time error if for any named worker it is 
possible for the name of that worker to be evaluated as a variable-reference more than
 once for any execution of that worker. 
```

Does this mean it's a compile time error to have one reference to a named worker in a wait-action and any other reference to the same worker but not in a wait-action.

```ballerina
function foo() {
    worker name returns string {
        return "name";
    }

    worker w {
        
    }

    string stringResult = wait name;
    future<string> f = name; 
}
```

2) Is the static type of `wait f` for the `f` of above sample is `string|error` ?

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
1. Yes: because the wait-future-expr is treating the name as a variable-reference-expr


2. Yes: this is covered by:

>In addition to a static type, a wait-future-expr has a compile-time eventual type. If a wait-future-expr is a variable-reference-expr referring to the worker-name of a named worker with return type T, then the eventual type of the wait-future-expr is T. Otherwise, the eventual of a wait-future-expr with static type future<T> is T|error. The result of a wait operation that completes normally will belong to the eventual type of the wait-future-expr, since the compiler ensures that a wait for a wait-future-expr that is a variable reference to a named worker cannot fail.

**Comment by rdhananjaya** [comment]
Thank you will create issues to improve these in the compiler
