### ISSUE TITLE
How should json type deal with Ballerina's multiple numeric types?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#8]
Problem is how should json type deal with existence in Ballerina of multiple numeric types, in particular the existence of both decimal and float.

We believe that different applications will want to use different Ballerina numeric types to represent numbers in JSON; the Ballerina json type should therefore allow control over which numeric types are used; this can be done by making the numeric type a parameter to json.

Thus `json<decimal>` would mean that JSON numbers are represented by Ballerina decimals, and `json<float>` would mean that JSON numbers are represented by Ballerina floats; `json` without a parameter would mean j`son<float|decimal|int>`, and so have the same semantic as now.

The json parser, which converts from bytes/characters into Ballerina values, would be parameterized in the numeric type. If a resource function declares that a parameter is, for example, `json<decimal>`, the parser would get supplied with a parameter that tells it to convert JSON number syntax into Ballerina decimal values.

**Comment by jclark** [comment]
This relates to protocol buffers support because well known type Value corresponds to `json<double>`.

**Comment by jclark** [comment]
One approach is to make `value:fromJsonString` use decimals; more specifically use `int` if the number is syntactically an integer in JSON (no `.` and no exponent) and fits in an int, and decimal otherwise.

These decimal/int value can get converted automatically to float in a type cast or as discussed in #487.

There's a problem, though. Our decimals use the simplified arithmetic of ANSI X3.274 as described [here](http://speleotrove.com/decimal/dax3274.html). The differences are:

- no infinities, no NaN: not a problem since JSON doesn't allow these either
- -0 and +0 are not distinct values: this may be a problem
- no subnormals: this may also be a problem (can all binary64 subnormal numbers be represented by normal decimal128 numbers?)

Note [I-JSON](https://tools.ietf.org/html/rfc7493) specifically links JSON to IEEE 754 binary 64-bit floating point.

**Comment by jclark** [comment]
Floating formats are defined in terms of parameters, b, p, emax:

* binary64 has b=2,  p=53, emax=1023
* decimal128 has b=10, p=34, emax=6144

emin is 1 - emax.

Smallest magnitude normal floating point number is b<sup>emin</sup>. For decimal128, this is 10<sup>-6143</sup>.

Smallest magnitude subnormal floating point is b<sup>emin</sup>x b<sup>1 - p</sup>. For binary64, this is 2<sup>-1022</sup> x 2<sup>-52</sup>, which is 2<sup>-1074</sup>, which is about  5 x 10<sup>-324</sup>.

So this means that all subnormal binary64 values can be represented by normal decimal128 values. Phew!

That leaves only -0 as a problem.

**Comment by jclark** [comment]
One solution to the -0 problem is to say that `fromJsonString` returns

- float -0.0 for a number that starts with a `-` and is numerically equal to 0
- int for a number that is syntactically an integer and fits in a Ballerina int
- decimal, otherwise

I think this (in conjunction with numeric conversions) will allow us to handle all Ballerina numbers without loss of information.

We should also have a way to do fromJsonString that produces either all float numbers or all decimal numbers. Since the precise return type in each case is a different subtype of json, I think these should be separate functions e.g. `fromJsonStringFloat` and `fromJsonStringDecimal`.

**Comment by jclark** [comment]
We approved this proposal https://github.com/ballerina-platform/ballerina-spec/issues/8#issuecomment-673981836 in today's meeting.

**Comment by jclark** [comment]
`fromJsonFloatString` and `fromJsonDecimalString` are more consistent with current langlib naming conventions (cf  `fromHexString` `fromCodePointInt`).  Also return value would be subtype of json, which could be consistently named `JsonFloat` and `JsonDecimal`.

**Comment by chiranSachintha** [comment]
```
string s = "{\"a\":-0.0}";
map<json> l = <map<json>> s.fromJsonDecimalString();
```
Does it convert the value of  `-0.0` to `0.0` with the function of `fromJsonDecimalString`?

**Comment by jclark** [comment]
@chiranSachintha Yes:  the decimal type (like int, but unlike float) does not distinguish between 0.0 and -0.0.
