### ISSUE TITLE
Redundant to have record with {| |}

### ISSUE THREAD

**Issue by sanjiva** [ballerina-platform/ballerina-spec#80]
With the latest changes, `record { }` means `record {| anydata|error... |}`. 

I'm wondering whether we can simply drop the word `record` in the latter case and keep it only for the first case:

`{| record-fields |}`

Syntactically the keyword `record` is redundant there as we can parse without it. 

Behavioral types have a word like that (object, service) but no other anydata type has a keyword - lists are declared with `[]` (especially with #78) and so are mapping types (`map<T>` is a shortcut for `record {| T... |}`).

Thoughts @sameerajayasoma, @hasithaa, @jclark?

**Comment by jclark** [comment]
In `record { }`, the `record` keyword is not needed for parsing: it is just there for clarity.

I think it will be confusing to have `record` in one case but not the other, when they are both equally records.

**Comment by hasithaa** [comment]
@sanjiva `table` type-descriptor has `table` keyword with it, and both record and table type-descriptors have some similarity.  (Both use curly brackets and field syntax).  
Recently we have identified some issues with Table type-descriptors, and still, that is in preview. So we can fix that later.
