### ISSUE TITLE
Supplying values to configurable variables with mapping types via TOML syntax

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#800]
The current [spec](https://github.com/ballerina-platform/ballerina-spec/blob/master/configurable/spec.md) does not allow supplying configurable variables with mapping types via TOML syntax. Configurable variables with mapping types can create ambiguities. e.g., submodule names vs. mapping values.

But mapping values allows a much nicer way to group a set of configurable variagles. Several users have requested this feature. Creating this issue to explore ways to support this feature.

**Comment by jclark** [comment]
Last time we discussed this, we decided not to do it because it was easy to use Ballerina tables for this. Can you explain the use cases for this?

**Comment by sameerajayasoma** [comment]
Here is a sample code snippet that uses mapping types.
```
// http:BearerTokenConfig is a record type
configurable http:BearerTokenConfig & readonly gitHubTokenConfig = ?;

// http:OAuth2DirectTokenConfig is a record type
configurable http:OAuth2DirectTokenConfig & readonly sheetOauthConfig = ?;

configurable string & readonly gitHubCallbackUrl = ?;
configurable string & readonly githubRepoURL = ?;

@websub:SubscriberServiceConfig {
    target: [webhook:HUB, githubRepoURL + "/events/*.json"],
    callback: gitHubCallbackUrl,
    httpConfig: {auth: gitHubTokenConfig}
}
service / on new webhook:Listener(8090) {
    remote function onIssuesOpened(webhook:IssuesEvent event) returns error? {
        googleapis_sheets:SpreadsheetConfiguration spreadsheetConfig = {oauthClientConfig: sheetOauthConfig};
        googleapis_sheets:Client spreadsheetClient = check new (spreadsheetConfig);   
        // ... 
    }
}
```

Here is the updated code with Ballerina tables:
```
configurable table<http:BearerTokenConfig & readonly> key(accessToken) & readonly gitHubTokenConfigTable = ?;

configurable table<http:OAuth2DirectTokenConfig & readonly> key(accessToken) & readonly sheetOauthConfigTable = ?;

configurable string & readonly gitHubCallbackUrl = ?;
configurable string & readonly githubRepoURL = ?;

listener webhook:Listener githubListener = new (8090);

@websub:SubscriberServiceConfig {
    target: [webhook:HUB, githubRepoURL + "/events/*.json"],
    callback: gitHubCallbackUrl,
    httpConfig: {auth: gitHubTokenConfigTable.toArray[0]}
}
service / on githubListener {
    remote function onIssuesOpened(webhook:IssuesEvent event) returns error? {
        googleapis_sheets:SpreadsheetConfiguration spreadsheetConfig = {oauthClientConfig: sheetOauthConfigTable.toArray[0]};
        googleapis_sheets:Client spreadsheetClient = check new (spreadsheetConfig);   
        // ... 
    }
}
```

This is not straightforward for many users and looks hacky.

**Comment by jclark** [comment]
Ack, I see the problem.

**Comment by warunalakshitha** [comment]
@sameerajayasoma  Do we need to support configurable variables with mapping type via command line args?

**Comment by sameerajayasoma** [comment]
Not right now IMO. Currently, we support these types `boolean | int | float | decimal | string | xml`. Let’s keep this behavior as is for now. We can improve the command line args syntax to support arrays, tables, and mapping types later.

**Comment by HindujaB** [comment]
@sameerajayasoma 
Regarding the limitation that can be caught at compile time, 

> A configurable variable and an immediate child module cannot have the same name

Should we provide these as errors for the imported modules from a non-default package? 
As the user may not have the control for the variables from these imported modules. 

Or is it preferred to be a warning instead?

**Comment by sameerajayasoma** [comment]
This should be an error.
