### ISSUE TITLE
Clarification: Send-receive correspondence

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#803]
**Description:**
Asking because current implementation only support worker interactions on a top-level of a worker.
I think it's correct for worker receive but we should allow scenarios like below.

Following Ballerina program is valid since worker sends (1, and (2 (in the same send-set) have a corresponding receive action?

```ballerina
function foo() returns any|error {
    worker w {
        map<int> m = {};
        if (m.length() > 0) {
            m -> w1; // 1 
        } else {
            m -> w1; // 2
        }
    }

    worker w1 returns map<int> {
        map<int> i = <- w;
        return i;
    }
}
```

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
Yes, that's valid.  https://ballerina.io/spec/lang/master/#section_7.8.4 says explicitly "It is allowed for a send set to have more than one member" (which is exactly this case)
