### ISSUE TITLE
Can `self` be considered an isolated expression?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#805]
**Description:**
For example, can a method call on `self` or a function/method call with `self` as an argument be considered an isolated expression (if the other requirements are met)?

Can the expressions used in the return statements in the following examples be considered isolated expressions?

```ballerina
isolated class IsolatedClass {
    private int[][] arr = [[], []];

    isolated function getMember(boolean bool) returns int[] {
        lock {
            if bool {
                return getMember(self); // `self` as an argument
            }

            return self.getMemberInternal(); // method call on `self`
        }
    }

    private isolated function getMemberInternal() returns int[] {
        lock {
            return self.arr[0].clone();
        }
    }
}

isolated function getMember(IsolatedClass foo) returns int[] {
    return foo.getMember(false);
}
```

```ballerina
isolated int[][] arr = [[], []];

class NonIsolatedClass {
    isolated function getMember(int i) returns int[] {
        lock {
            if i == 0 {
                return getMember(self); // `self` as an argument
            }

            if i == 1 {
                return arr[1].clone(); // "protected variable" acccess
            }

            return self.getMemberInternal(); // method call on `self`
        }
    }

    private isolated function getMemberInternal() returns int[] {
        lock {
            return arr[0].clone();
        }
    }
}

isolated function getMember(NonIsolatedClass foo) returns int[] {
    return foo.getMember(1);
}
```

**Comment by jclark** [comment]
The spec says:

> If the static type of an expression is immutable, i.e. a subtype of readonly, or an isolated object, i.e. a subtype of isolated object {}, then the expression is isolated.

An expression `self` will satisfy this condition when `self` is used in a method of an object that is readonly or isolated.

It also says:

> a method-call-expr is isolated if the expression preceding `.` is isolated, the expression for each argument in the arg-list is isolated and the type of the method being called is isolated

So I think the spec's answer to your first question is: yes if `self` is referring to an isolated or readonly object.

Do you see a problem with this?

In your first example, the object is isolated, so `self` is referring to an isolated object, so `self` will be an isolated expression.

In your second example, the object is not explicitly isolated, but it has no fields. In this case, I think we should treat the static type of `self` as an isolated object (similarly to how an object-constructor-expr creates an *implicitly isolated* object).

**Comment by MaryamZi** [comment]
> The spec says:
> 
> > If the static type of an expression is immutable, i.e. a subtype of readonly, or an isolated object, i.e. a subtype of isolated object {}, then the expression is isolated.
> 
> An expression `self` will satisfy this condition when `self` is used in a method of an object that is readonly or isolated.
> 
> It also says:
> 
> > a method-call-expr is isolated if the expression preceding `.` is isolated, the expression for each argument in the arg-list is isolated and the type of the method being called is isolated
> 
> So I think the spec's answer to your first question is: yes if `self` is referring to an isolated or readonly object.
> 
> Do you see a problem with this?
> 

Sorry, missed that this would satisfy "If the static type of an expression is immutable, i.e. a subtype of readonly, or an isolated object, i.e. a subtype of isolated object {}, then the expression is isolated"

No issues, the implementation does allow this already.

> In your first example, the object is isolated, so `self` is referring to an isolated object, so `self` will be an isolated expression.
> 
> In your second example, the object is not explicitly isolated, but it has no fields. In this case, I think we should treat the static type of `self` as an isolated object (similarly to how an object-constructor-expr creates an _implicitly isolated_ object). This needs a spec change.

+1

**Comment by MaryamZi** [comment]
Also, shouldn't the following assignment (`arr[0] = self.m`) be disallowed?

```ballerina
isolated int[][] arr = [];

class NonIsolatedClass {
    int[] m = [];

    isolated function setMember() {
        lock {
            arr[0] = self.m;
        }
    }

    isolated function getMember() returns int[] {
        return self.m;
    }
}
```

The spec says
> - Transferring values out of the lock statement is constrained: the expression following a return statement must be an isolated expression; an assignment to a variable defined outside the lock statement is allowed only if left-hand side is just a variable name and the right hand side is an isolated expression. An assignment to the isolated variable is not subject to this constraint.
> - Transferring values into the lock statement is constrained: a variable-reference-expr within the lock statement that refers to a variable or parameter defined outside the lock statement is allowed only if the variable-reference-expr occurs within an expression that is isolated. A variable-reference-expr that refers to the restricted variable is not subject to this constraint.

I'm not sure if the spec disallows this atm?

**Comment by jclark** [comment]
This is disallowed because a value is being transferred into the lock statement and self.m isn’t an isolated expression. How could I rephrase to make this clear?

**Comment by MaryamZi** [comment]
This is still an invalid attempt to copy something out, right? 

> an assignment to a variable defined outside the lock statement is allowed only if left-hand side is just a variable name and the right hand side is an isolated expression. An assignment to the isolated variable is not subject to this constraint.

Would the RHS being an isolated expression apply even when the assignment involves an update to an isolated variable?

Or would this apply specifically to `self`? As in any usage of `self` within the lock statement that is not part of an isolated expression?

The implementation currently allows the following
```ballerina
isolated int[][] arr = [];

class NonIsolatedClass {
    int[] m = [];

    isolated function setMember() {
        lock {
            int[] x = [];
            arr[0] = x;
        }
    }

    isolated function getMember() returns int[] {
        return self.m;
    }
}
```

which I guess also allows
```ballerina
isolated int[][] arr = [];

class NonIsolatedClass {
    int[] m = [];

    isolated function setMember() {
        lock {
            int[] x = self.m;
            arr[0] = x;
        }
    }

    isolated function getMember() returns int[] {
        return self.m;
    }
}
```

Related issue: https://github.com/ballerina-platform/ballerina-spec/issues/732

**Comment by jclark** [comment]
```
isolated int[][] arr = [];

class NonIsolatedClass {
    int[] m = [];

    isolated function setMember() {
        lock {
            int[] x = [];
            arr[0] = x;
        }
    }

    isolated function getMember() returns int[] {
        return self.m;
    }
}
```
The above is fine.

```
isolated int[][] arr = [];

class NonIsolatedClass {
    int[] m = [];

    isolated function setMember() {
        lock {
            int[] x = self.m;
            arr[0] = x;
        }
    }

    isolated function getMember() returns int[] {
        return self.m;
    }
}
```
This is not OK.  Why do you think it's OK? You are transferring in `self.m` which is not an isolated expression.

I am obviously failing to explain this clearly...I get the sense that there is a key point that I have failed to communicate properly, but I'm not sure what it is.

**Comment by MaryamZi** [comment]
Sorry, I wasn't clear. I agree the second example is wrong, what I wanted to say is that if an isolated variable is accessed within a lock statement, accessing `self` of a non-isolated object anywhere within the same lock statement can cause issues.

> This is not OK. Why do you think it's OK? You are transferring in self.m which is not an isolated expression.

I think the confusion on my part is that I did not consider `self` to be transferring in. Considering an expression with `self` as an attempt to transfer in clears up the initial concern I had too.

**Comment by jclark** [comment]
OK, I see the confusion. Would it help if the section of spec about transferring in/out said something like “for a non-isolated object, `self` behaves like an implicit parameter”?

**Comment by MaryamZi** [comment]
+1, that will help.

**Comment by jclark** [comment]
I made the change to the static type of self be a separate issue.
