### ISSUE TITLE
Stream's next method

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#808]
Implementation has a next method, which is coming from the Query V2 proposal. 

https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.stream/src/main/ballerina/stream.bal#L53

But this is not added back to the spec.

**Comment by jclark** [comment]
OK, I'll add this.

**Comment by jclark** [comment]
@hasithaa The implementation is not right: in `stream<T,C>`, C is the completion type not the error type. This was #453.

**Comment by hasithaa** [comment]
@jclark We missed this change, @grainier Shall we fix these gaps for Alpha5?
