### ISSUE TITLE
Including platform specific names in compilation errors

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-spec#809]
**Description:**
The commandline options and operands are platform features. Will it be okay to add these terms in compile time errors when validating the main function? For example we have the following errors for invalid main parameters:
```
'main' function parameter 't' has invalid type 'typedesc'
'main' function parameter 't' via included record X has invalid type 'typedesc'
```
We wanted to clarify if adding the words `option` and `operand` to these errors is correct: 
```
'main' function option parameter 't' has invalid type 'typedesc'
'main' function operand parameter 't' via included record X has invalid type 'typedesc'
```
The confusion is because `option` and `operand` are not language level features.

**Code sample that shows issue:**

**Related Issues:**

https://github.com/ballerina-platform/ballerina-lang/issues/29829

**Comment by sameerajayasoma** [comment]
Any third-party compiler plugin can generate compilation errors. I don't see this as a problem.

**Comment by riyafa** [comment]
+1 will continue with this design.
