### ISSUE TITLE
Spec is not clear on what to pass to the `attach` methods second parameter when absolute-resource-path is `/`

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#810]
**Description:**
As I remember, when the absolute-resource-path is `/` on a service-decl, array with single member `/` was required to pass to the second parameter of the `attach` method of the listener. Current spec doesn't seems to specify that anymore, it seems we need to pass an empty array when the absolute-path of a service is `/`.

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
The spec does say that:

> The attach-point determines the second argument passed to the attach method: if the attach-point is absent, then the argument is nil; if it is a string-literal, then the argument is a string; otherwise, it is an absolute-resource-path and the argument is an array of strings, with one string for each resource-path-segment.

Since / is an absolute-resource-path with no resource-path-segment (should say resource-path-segment-name), you pass an empty array.
