### ISSUE TITLE
Relax restriction on accessing `self` of an `isolated` object only within a `lock` statement 

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#824]
**Description:**
The [spec](https://ballerina.io/ballerina-spec/spec.html#lock_statement) says

> There are two cases where a variable is restricted to be used only within a lock statement:
>
> - when the variable is an isolated module-level variable; since isolated module-level variables are not allowed to be public, this restriction applies to all functions in the module;
> - when the variable is self within an isolated object, **unless self is being used only to read an isolated field**; since non-isolated fields are required to be private, this restriction applies only to the object's methods.

But does this restriction have to apply when `self` is used for bound method access, when calling a method on `self`, or when `self` is an argument to another function?

```ballerina
isolated class IsolatedClass {
    private int[] arr = [];

    isolated function getPushFunction() returns isolated function (int i) {
        return self.push; // (1)
    }

    isolated function incrementAndPush(int i) {
        self.push(i + 1); // (2)
    }

    isolated function push(int i) {
        lock {
            self.arr.push(i);
        }
    }
}
```

Currently both (1) and (2) result in errors since `self` is used outside a lock statement.

**Comment by jclark** [comment]
I think we can loosen the cases when `lock` is needed.

**Comment by jclark** [comment]
Can the rule be "self needs to be locked when it is used to access a field that is either not final or whose type is not a subtype of readonly"?

**Comment by shafreenAnfar** [comment]
By any chance would it be possible to get it implemented for the beta1 release. 

In the standard library implementation, it is common to do the below. However, at the moment, those classes cannot be isolated without a lock which could have an adverse effect on performance. 

```Ballerina
public isolated client class SomeClient {   
    isolated remote function someAction() {
        lock {
            externSomeAction(self);
        }
    }
}

isolated function externSomeAction(SomeClient c) = @java:Method {
    'class: "org.ballerinalang.someclient.NativeSomeAction"
} external;
```

**Comment by jclark** [comment]
@shafreenAnfar I can see why this restriction is painful.

I can add it to the spec, but I don't know if @hasithaa or @MaryamZi have time to add it for beta1.

On further reflection, I think the rule should be: "self needs to be locked when it is used to access a field that is either not final or whose type is not a subtype of readonly|isolated object{}" i.e. the second bullet should be

* when the variable is self within an isolated object and self occurs in a field-access-expr self.x, unless the field x is both final and has a type that is readonly or a subtype of `solated object { }`

**Comment by hasithaa** [comment]
@jclark, @MaryamZi did a fix https://github.com/ballerina-platform/ballerina-lang/pull/30663, We should be able to add this to beta1.

**Comment by shafreenAnfar** [comment]
Thanks @jclark @hasithaa @MaryamZi

**Comment by jclark** [comment]
Note that the "unless the field x is both final and has a type that is readonly or a subtype of isolated object { }" is the same as "unless the field x is isolated" as defined in 6.8.1.1.
