### ISSUE TITLE
Specific format to serialize lang.transaction Info record

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-spec#831]
**Description:**

Assume the below `bal` files are run in two instances.

1. **Transaction Initiator instance**

```ballerina
import ballerina/http;

public function main() returns error? {
    transaction {
        boolean successful = callBusinessService();
        if (successful) {
            check commit;
        } else {
            rollback;
        }
    }
}

transactional function callBusinessService() returns @tainted boolean {
    FooClient participantEP = new;

    var result = participantEP->foo();

    if (result is http:Response) {
        return result.statusCode == http:STATUS_OK;
    } else {
        return false;
    }
}

public client class FooClient {

    public http:Client httpClient;

    public function init() {
        self.httpClient = checkpanic new ("http://localhost:8889/stockquote/update/updateStockQuote", {});
    }

    transactional remote function foo() returns @tainted any|error {
        http:Request req = new;
        return self.httpClient->post("", req);
    }
}

```

2. **Transaction Participant instance**

```ballerina
import ballerina/http;
import ballerina/io;

service /stockquote on new http:Listener(8889) {
    transactional resource function post update/updateStockQuote(http:Caller conn, http:Request req) {

        var onCommitFunc = isolated function(transaction:Info? info) {
                               io:println(" trxCommited in participant");
                           };

        transaction:onCommit(onCommitFunc);
        http:Response res = new;
        checkpanic conn->respond(res);
    }
}

```

In this case, we need to propagate the `Info` record created while initializing the transaction block in the initiator instance to the participant instance.
We can pass the fields as headers in the transactional services.
Currently, the `xid` is propagated as a header. 

With regard to https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/transaction.bal#L23

Below are my concerns
1. If we are to propagate the `Info` record, should we define a specific format for this?
2. If we are to serialize the `Info` record, how should we handle the Timestamp as it's a behavioral type? Should we handle it as an int and recreate it as a Timestamp?

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
You will need to serialize the Info record (presumably as JSON): I would do it as a list with one member for each attempt, most recent first.

At the language level, we are trying to avoid committing to a particular representation of timestamp for the moment, since it is likely to change.  But at the protocol level (in the headers), you will need to commit to a representation. I suggest you use RFC 3339 format (as a JSON string).

**Comment by sanjiva** [comment]
@pcnfernando please check with @afkham to see what we did earlier.
