### ISSUE TITLE
Clarification on included record parameter

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-spec#832]
**Description:**
Does the following program valid?
In this program there  is a default value for each field of include record parameter.
```ballerina
type Student record {|
    string firstName = "Chiran";
    string lastName = "Sachintha";
|};

function printStudentDetails(int admissionNo, *Student student, int... marks) {

}  

public function main() {
    printStudentDetails(1002, 80, 80); //here
}
```

**Comment by jclark** [comment]
Yes, it's valid. What is unclear?

**Comment by chiranSachintha** [comment]
In the spec it mentioned as,

`
 The result of evaluating the i-th positional-arg becomes the i-th member of the argument list. The static type of the expression for the i-th positional-arg must be a subtype of the type declared for the i-th parameter that is not a rest-param, if there is such a parameter; otherwise, there must be a rest-param and the static type must be a subtype of the type declared for the rest-param.
`

According to this in the above program, the second argument can be matched with the second parameter of the function(Here it should give an `incompatible type` error). isn't it?

**Comment by jclark** [comment]
I didn't think carefully enough before I answered.

Let's consider a simpler case first:

```
function printStudentDetails(int admissionNo, string? student = (), int... marks) {

}  

public function main() {
    printStudentDetails(1002, 90, 80); //here
}
```

In this case, `90` would be treated as specifying argument `student`, and so would be a compile error.

An included-record-param all of whose fields are defaultable should be treated consistently with a defaultable parameter; so in your example I think the first `80` has to be treated as specifying the `student` parameter, which makes it an error.

So I agree it should be an error.
