### ISSUE TITLE
Compiler resets type narrowing of a variable upon assignment to the narrowed variable, spec doesn't seems to specify this resetting behavior

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#841]
**Description:**
```ballerina
public function main() {
    int|string s = 2;
    if (s is int) {
        int i = s;
        s = "hello";
        string d = s; // incompatible types: expected 'string', found '(int|string)'
    }
}
```

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
The spec says

> the narrowed type for a variable x no longer applies as soon as there is a possibility of x being assigned to

**Comment by rdhananjaya** [comment]
Thank you missed that part.

**Comment by jclark** [comment]
But I think you've identified a potential improvement: assigning a value that belongs to the narrowed type shouldn't reset the type.
