### ISSUE TITLE
Ambiguity in `destructuring-assignment-stmt` parsing

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-spec#844]
**Description:**
Consider the following stmt:
`_ = 10;`

This matches with both [destructuring-assignment-stmt](https://ballerina.io/ballerina-spec/spec.html#section_7.14.4) and [assignment-stmt](https://ballerina.io/ballerina-spec/spec.html#section_7.14.2) grammar in the spec. 
i.e. `_` can either be a `variable-reference` or a `wildcard-binding-pattern`.

Note that: `variable-reference := identifier` and `identifier` can be `UnquotedIdentifier := (IdentifierInitialChar) (IdentifierFollowingChar)*` which makes `_` a valid identifier.

**Comment by jclark** [comment]
`_` is a keyword, and so not a variable-reference
