### ISSUE TITLE
Clarification regarding `lang.table` spec 

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-spec#849]
**Description:**
According to https://ballerina.io/spec/lang/master/#tables, 
`The type specified by a row-type-parameter must be a subtype of map<any|error>`.

But in https://ballerina.io/spec/lang/master/#lang.table, the `table` types are given as `table<Type>`/`table<any|error>`
Shouldn't the constrained type be `map<any|error>` here?

**Comment by jclark** [comment]
You're right: that's a mistake in lang.table.
