### ISSUE TITLE
Specify semantics of field access and indexed access 

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#85]
Need to properly specify semantics of both `E.x` and `E1[E2]` both in expressions and on the LHS of assignments.

**Comment by jclark** [comment]
Specific things to think about:

- nil lifting
- when are you allowed to use `x.field` as opposed to `x["field"]`?
- how does `E.x` work when x doesn't exist in the value (either because optional or untyped)?

**Comment by hasithaa** [comment]
Implementation support error lifting operator `!`. i.e `x!y` Here, `x` is an expression whose type is a  T1|error or T1?|error (supports sub-type of error as well) and `y` is a field of T1 which is the type of `T2`.

```balerina
T1|error|() x = getT1Value();
T2|error|() y = x!y
```

Which is desugared into, 

```
T1|error|() x = getValue();
T2|error|() y = {
  T2|error|() $var;
  if ( x is T1)
    $var = x.y;
  } else {
    $ var = x;
  }
  $var // result of expression statement.
];
```

The same expression extended to support function calls as well. `x!y()`

**Comment by jclark** [comment]
@hasithaa Adding an operator for error lifting is issue #109. Please add your comment there.

**Comment by jclark** [comment]
We also need to specify how this works with user-defined collection objects that have __get and __put methods

**Comment by jclark** [comment]
We should also ensure that lang.* remove method is consistent with this.

**Comment by jclark** [comment]
Also need to think about prefixed names for XML case. If the prefix ns is defined by a Ballerina xmlns declaration to be some URI `http://www.example.com/ns`, then `x.getAttributes().ns:myAtt` is supposed to turn into `x.getAttributes()["{http://www.example.com/ns}myAtt"]`.

**Comment by hasithaa** [comment]
Following explains the current implementation semantics. 

`field-access-expr = expression . field-name`

Semantics: 
* Compile time error
  * If the static type of `expression` T is not a map, record or object.
  * If T is an object type and `field-name` is not defined in `object-type-descriptor`
  * If T is a close record and `field-name` is not defined in `record-type-descriptor`
* Type of the field `R` is derived as follows
   * If `field-name` matches to a field in record or object type descriptor, then R's type is matched field's type.
   * else, R will be record-rest field type or map member type.
* The type of `field-access-expr` is 
   * `R` - if T is not optional/not include nil
   * `R?` -if T is optional/include nil
* Evaluate `expression` resulting `v` 
   * If `v` is `nil`, `field-access-expr` results `v`
   * If `v` is not `nil` and access field `field-name` in `v`. If `field-name` exists return field value, if not exist panic with `error: {ballerina}KeyNotFound`.
* Semantic when `field-access-expr` in LHS in an assignment, Evaluate `expression` resulting `v`,
  * If `v` is `nil`, panic when accessing `field-name`
  * if If `v` is not `nil` and put given value into field `field-name`

**Comment by sameerajayasoma** [comment]
Btw we haven't handled the `E.x` as an l-value case properly yet.  If `E` has type `T?`, the `E.x` panic with NPE at the moment.

**Comment by sameerajayasoma** [comment]
Here is the current semantics in the implementation of `E.x` when E has the union type `json`.

`E.x` in r-value context: `E.x` returns `()` except when E is a map<json> and there exists a field `x`;

`E.x` in l-value context:
- If `E` has type `map<json>`, then add the field `x` or update the value of field 'x' if it already exists.
- Else silently ignore.

**Comment by jclark** [comment]
Yesterday we decided (as part of #133) not to do nil lifting for object/field access i.e in E.x, if the static type of E intersects with object then the static type of E must be a subtype of object and not of object?. In other words, object-field will be compile-time guaranteed to succeed at runtime.

**Comment by jclark** [comment]
Separating this out:

- #201 LHS of assignments
- #196 for json
- #202 for E.x expressions
- #203 for E[x] expressions

**Comment by jclark** [comment]
The main parts of this are now done.
