### ISSUE TITLE
Provide filler values for intersection types

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-spec#850]
**Description:**
As per the current spec, the filler value for array/map type descriptors are available,
> if that is a valid constructor for the type

But, the spec does not mention about the filler value for an intersection type.

Consider the following example of an array of intersection type [1],
``` ballerina
type Person readonly & record {|
    string name = "default";    
|};

public function main() {
    Person p1 = {name: "Hinduja"};
    Person[] arr = [];
    arr[2] = p1;
}
```
In this case, we have a valid constructor for the intersection type `Person`. 
Do we need to support filler values for intersection types when there is a valid constructor?

[1] https://ballerina-platform.slack.com/archives/CAXS256RX/p1621243803134900

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
Yes. I cannot see any reason why this should not work.
