### ISSUE TITLE
Contextually-expected type for the expression in a type cast expression

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#851]
**Description:**
The [spec](https://ballerina.io/ballerina-spec/spec.html#type-cast-expr) says

```
type-cast-expr := < type-cast-param > expression
type-cast-param := [annots] type-descriptor | annots
```

> The contextually expected type for expression is the intersection of the contextually expected type of the type-cast-expr and the type described by the type-descriptor.

But wouldn't this disallow the following, since the contextually expected type for the `func()` call would be `int`?

```ballerina
int x = <int> func();

function func() returns any => 1;
```

The implementation currently uses a contextually-expected type for the expression (in a type cast expression) only with constructor expressions. Otherwise it takes the type of the expression and checks if it can be cast to the target type. But this doesn't work anyway with dependently-typed functions. The following doesn't compile atm.

```ballerina
function func(typedesc<anydata> td = <>) returns td|error = external;

public function main() returns error? {
    any x = <int> check func();
}
```

**Comment by jclark** [comment]
We need to distinguish

1. The contextually expected type: this passes down the AST and is used by constructors.
2. The static type that a subexpression must have in order for an expression to be correctly typed

Considering:

```
T1 x = <T2>E;
```

The contextually expected type for building E is T1&T2. Once you have built E, you find out what it's static type is. Suppose this is T; T must be such that T & T2 is non-empty. The static type of `<T2>E` is then `T & T2`. Now consider the assignment. The static type of the RHS (i.e. T & T2) must be a subtype of `T1`, in order for the assignment to be correctly typed.

**Comment by MaryamZi** [comment]
Got it, thank you.
