### ISSUE TITLE
Clarification on table keys

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-spec#853]
**Description:**
Consider the following example given in [Language Introduction Slides](https://ballerina.io/learn/language-guide/#language-introduction-slides) for `readonly type`(Slide No 144)
```ballerina
readonly & string[] s = [
   "foo", "bar"
];

type Row record {
   readonly string[] k;
   int value;
};

table<Row> key(k) t = table [
   { k: s, value: 17 }
];
```
This results in a compilation error (`ERROR [main.bal:(11:4,11:23)] field 'k' used in key specifier must have a literal value`) ATM since we only allow `literals` as a key field value in tables. Should we allow variable references too?

**Comment by mohanvive** [comment]
I could recall that we had some verbal discussions on this in the past and decided to allow only literals. But the current spec does not say anything on this restriction. @jclark Do you recall anything as such?

**Comment by jclark** [comment]
Fortunately we have a spec, which says:

> For every field-name in the key sequence of the inherent type every mapping-constructor-expr in the row-list must include a specific-field that has a value-expr that is a const-expr

Note that `const-expr` isn't the same as literal.  But the example in the slides is wrong: it needs to say

```
const s =  [
   "foo", "bar"
];
```

which I think isn't supported yet in the compiler. In the BBE, I suggest using `add`.
