### ISSUE TITLE
`distinct` keyword used within intersection type 

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#864]
**Description:**
```ballerina
type E2 distinct FreeError & error<Detail>;
```

This get parsed as `type E2 (distinct FreeError) & error<Detail>;`, but I think when a user writes something like this, they expect the `distinct` to be associated with the full intersection. Are we parsing this correct? 

In any case if the user writes `type E2 (distinct FreeError) & error<Detail>;`, what are the type-ids that `E2` get, does it get anything more than what `FreeError` have?

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
I think there is some misunderstanding or something not clear in the spec. These all mean the same:

```
(distinct E) & error<Detail>
error<Detail> & (distinct E)
distinct (E & error<Detail>)
E & (distinct error) & (error<Detail>)
```

In all cases, the result is a type which is a subtype of E
- with an additional distinct id
- detail type Detail

**Comment by rdhananjaya** [comment]
Need a bit of clarification regarding how the `local id` part of the type-id is selected when:

1. `type E distinct error` - in the compiler we use string "E" as the local ID
2. `type E (distinct error)` - should we generate a local-id here? And type `E` should have that as it's type-id

**Comment by jclark** [comment]
The spec says:

> if the distinct keyword is part of a distinct-type-descriptor that is the only distinct-type-descriptor occurring within a module-type-defn, then the local id is the name of the type defined by the module-type-defn

So in both of your cases the local-id of the type descriptor is E.

This is all covered by the spec (I believe).  Relevant sections are:

https://ballerina.io/spec/lang/2021R1/#section_5.1.5
https://ballerina.io/spec/lang/2021R1/#section_5.5.3.6
https://ballerina.io/spec/lang/2021R1/#section_5.6.8
https://ballerina.io/spec/lang/2021R1/#distinct_types
https://ballerina.io/spec/lang/2021R1/#section_6.17
https://ballerina.io/spec/lang/2021R1/#section_6.8.1

**Comment by rdhananjaya** [comment]
Oh my fault, I was under the impression that the quoted text was only referring to something like below. (I think I have missed the part about `only distinct-type-descriptor`)
`type E distinct error<D>` 
And `distinct` keyword in constituent parts of intersection meant each of those constituent type was distinct.

Will create an issue in the compiler to align this deviation.
