### ISSUE TITLE
Does reduce function in table.bal always have to return a MapType?

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-spec#867]
According to https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/table.bal#L110 , reduce function always returns a subtype of map<any|error>. This forces the users to create a map in the body of reduce function and return it, for the cases where we really don't need a map. 

Consider the following example. Here i am trying to get the sum of all `marks` values

```
int sum = tab.reduce(function (int accum, Student val) returns int {
    return accum + val.marks;
 }, 0);
```

**Comment by jclark** [comment]
That's a mistake by me. I messed it up in this change https://github.com/ballerina-platform/ballerina-spec/commit/4d46a48bee7d0473d21bb8f15fc15286a108e7e3

MapType1 should have been left as Type1 and any|error.
