### ISSUE TITLE
Determine contextually expected numeric type in binary expressions

### ISSUE THREAD

**Issue by rpjayasekara** [ballerina-platform/ballerina-spec#868]
How to determine contextually expected type of following binary expressions

`float a = 2.0;`
`boolean b = 1 == a;`
`boolean b = a == 1;`
`var c = 3.5 + 1;`

**Comment by jclark** [comment]
Contextually expected types flow down the tree from expressions to subexpressions. So in your example 1, the type of `a` does not affect the contextually expected type for the literal `1`, which means that example 1 is a compile-time error (operands of `+` need to have the same basic type). Same for example 2 and 3.

```
float a = 2.0;
boolean b = 1 == a; // 1
boolean b = a == 1; // 2
var c = 3.5 + 1; //3
```

There is no context
