### ISSUE TITLE
Clarification on error handling within query-expr

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-spec#871]
**Description:**
In this code sample, do we consider `select check add(val)` clause to "complete early with an error value" as mentioned below; or should it complete abruptly with a panic? 

`If a next operation causes the execution of a clause that completes early with an error value, then the error value is returned by the next operation;`[1].

[1] https://ballerina.io/spec/lang/master/#section_6.35
   
**Code sample that shows issue:**
```ballerina
public function main() returns error? {
    stream<int, error> arr2 = stream from var val in [1]
        select check add(val); // fail here and panic?
    var val = arr2.next(); // or propagate here and result in an error?
}

function add(int a) returns int|error {
    return error("Invalid value");
}
```

**Related Issues:**
- https://github.com/ballerina-platform/ballerina-lang/issues/31008
- https://github.com/ballerina-platform/ballerina-lang/issues/31041

**Comment by jclark** [comment]
The drafting isn't quite right here. It needs to say something like: the execution of a clause *completes early* with error value e, if its execution results in the evaluation of an expression that completes abruptly with a check-fail with associated error value e. (And remove the sentence that says "If the next operation results in the evaluation of an expression within the query-expr completing abruptly with a check-fail, the associated error value will be returned as the result of the next operation.")

So in your case the `next` operation would return the error value  that was created by `add`.

**Comment by grainier** [comment]
Got it. Thank you for the clarification.

**Comment by grainier** [comment]
Just to get it clarified for all the cases (i.e returning an error, check-fail, panic); this is what I understood. Is it correct?

**Normal Queries**

1. The execution of a clause may complete early with an error value, in which case this error value is the result of the query (i.e int[]|error).
2. If the evaluation of an expression within the query-expr completing abruptly with a check-fail, that error will get propagated to the query result level (this is more of an implementation detail since `check-fail` can happen within desugared closure).
3. If there's an expression within the query-expr completing abruptly with a panic, evaluation of the whole query-expr will complete abruptly with panic. 

**Query to a stream**
1. If a next operation causes the execution of a clause that completes early with an error value, then the error value is returned by the next operation.
2. If the next operation results in the evaluation of an expression within the query-expr completing abruptly with a check-fail, the associated error value will be returned as the result of the next operation.
3. If the next operation results in the evaluation of an expression within the query-expr completely abruptly with panic, then the next operation will complete abruptly with a panic.

**Comment by jclark** [comment]
Yes.

I see 1 and 2 as the same thing: evaluation of expr in clause completing abruptly leads to execution of that clause completing early.

**Comment by jclark** [comment]
The behaviour spelled out for the normal case in https://github.com/ballerina-platform/ballerina-spec/issues/871#issuecomment-861127156
requires code like https://github.com/ballerina-platform/nballerina/pull/1045/commits/38c76bd8e722aa30243db8fb40a0f056f46560d4 , which is not good.

The problematic sentence in the spec is this:

> The execution of a clause may complete early with an error value, in which case this error value is the result of the query, except when constructing a stream.

**Comment by jclark** [comment]
Ahh, I see the problem now. The first paragraph of my answer at

https://github.com/ballerina-platform/ballerina-spec/issues/871#issuecomment-860152745

is wrong and misunderstood the spec!

The cases when a clause "completes early with an error value" is defined in https://ballerina.io/spec/lang/master/#section_6.35.1 and
https://ballerina.io/spec/lang/master/#section_6.35.4 ("if r is an error, then complete execution of the from-clause early with error r").  It is only the cases when a call to `next()` returns an error.

The sentence about

> The execution of a clause may complete early with an error value, in which case this error value is the result of the query, except when constructing a stream.

only refers to those cases case.  For the non-stream case, a check fail is handled as a usual (check fail of subexpression of E results in check fail of E).

**Comment by jclark** [comment]
With  "completes early" as explained in https://github.com/ballerina-platform/ballerina-spec/issues/871#issuecomment-1191452836, the only point of @grainer's summary in https://github.com/ballerina-platform/ballerina-spec/issues/871#issuecomment-861127156 that is incorrect is Normal case, point 2, which should say: If the evaluation of an expression within the query-expr completing abruptly with a check-fail, then the query-expr completes abruptly with a check-fail.
