### ISSUE TITLE
Syntax confusion with compound operator

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#872]
There is a possibility someone can make a typo like this. 

```
    int i = 2;
    i += 1;
    i =+ 1;
```

We can detect such usages from the compiler and warn them. Created this to discuss anything we can do from the language design to avoid such mistakes.

**Comment by jclark** [comment]
You could see if clang does anything. If you have format on save in VSCode, then this should be shown as `1 = +1;`, which would hopefully make the error clear.

**Comment by hasithaa** [comment]
Checked this using java too, they accept it. We can make this a linter warning and the formatter can help to arrange this in the correct order.
