### ISSUE TITLE
Allow to update transitive dependancies

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-spec#881]
**Description:**
Consider the following use case where package A depend on Package B and package B depend on package C. Here C is a transitive dependency of package A.

A -> B -> C

If C releases a new compatible version ( Can be a patch or a miner ) possibly with a security fix. 

Current behavior:
It is not possible to use the latest version of C from package A. To use the latest version of C there should be a new version of package B pushed to central. 

Expected Behavior:
The user should be able to use the latest package of C with the security fix without waiting for a release of package B.  

Possible workaround in current implementation:
You can add a import in package A to package C ie. `import hevayo/C as _;` and specify the latest dependency version in Dependencies.toml will allow you to use the latest of Package C.

**Comment by azinneera** [comment]
In Swan Lake versions, this limitation is not present. 

If the latest version is a patch version bump, then it will be resolved automatically. If it is a minor or major version bump, then the user can add the dependency with the required version it in the Ballerina.toml file. The specified version is considered to be the minimum version required to compile the package.
