### ISSUE TITLE
Inferring `isolated` for object constructor expressions

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#884]
**Description:**
The [isolated inference](https://ballerina.io/ballerina-spec/spec.html#section_8.3.3) section of the spec mentions inferring `isolated` for 
- service-decl
- module-var-decl
- module-class-defn 
- function-defn
- method-defn

Shouldn't we infer `isolated` for object constructor expressions too? I believe this would be useful with transfer in/out restrictions.

Just as an example, if we infer the object constructor expression below to be creating an `isolated` object, the `Foo` class can also be inferred as `isolated`.

```ballerina
public int i = 2;

class Foo {
    private int[] a = [0, 1];

    function func() returns object { function val() returns int; } {
        lock {
            final int j = self.a[0];
            return object {
                private int v;

                function init() {
                    self.v = i + j;
                }

                function val() returns int {
                    lock {
                        return self.v;
                    }
                }
            };
        }
    }
}
```

**Comment by jclark** [comment]
Yes, that would probably be useful.  I don't know to what extent the target audience for isolated inference would be likely to use object constructors.

**Comment by MaryamZi** [comment]
Missed this previously, but inferring isolated is useful with service object constructors?
