### ISSUE TITLE
`check Expr` as a field-initializer/default-expression

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#886]
**Description:**
Shouldn't we disallow `check Expr` as the field-initializer of a field of an object or the default-expression of a field of a record?

```ballerina
type Foo record {|
    int i = check func();
|};

class Bar {
    int i = check func();
}

class Baz {
    int i = check func();

    function init() returns error? {
        // Instead, can initialize here.
        // self.i = check func();
    }
}

function func() returns int|error => error("not an int!");
```

Wonder if we can allow this for objects, when the `init` method has an error `E` in its return type, and the error `Expr` may evaluate to belongs to `E`. But I don't think this adds value since the same can be initialized within the `init` method anyway.

**Comment by jclark** [comment]
For records, I would have thought this should work like `new`.

**Comment by MaryamZi** [comment]
But with records we do not have a way of making this information available explicitly, do we? Unlike with objects, where for `new`, the `init` method specifies whether or not an error value may be returned and the type(s) of the error(s).

**Comment by jclark** [comment]
Oh yes, you're right. I guess it has to be a compile error then.

**Comment by MaryamZi** [comment]
Just to clarify, I assume this would be an error for classes/object constructor expressions also?

```ballerina
configurable string str = "";

class Foo {
    // error
    int i = check int:fromString(str);
}

class Bar {
    int i;

    // Instead, can add an init method and initialize with `check`.
    function init() returns error? {
        self.i = check int:fromString(str);
    }
}
```

**Comment by jclark** [comment]
Given what we are doing with isolated "If the object-constructor-expr is explicitly isolated, then every field-initializer must be an isolated expression and any field that is not isolated must be declared as private." I would be inclined to allow the following:

```
class foo {
  int i = check int:fromString(str);
  function init() returns error? {
  }
}
```

i.e. an initializer can use `check` provided the type of the constructor function allows it.
