### ISSUE TITLE
Unreachability

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#887]
The spec needs to define when a statement is unreachable and make it an error. Related to the concept of unreachability is the concept of whether the execution of a statement can complete normally, which is needed in order to be able to define #73.

Fer background see See Java Language Specification on [Unreachable statements](https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.21).

There also needs to be a way for a programmer to express their intent that a place in the code should be unreachable, for example, following a match statement that the programmer intends to be exhaustive.

**Comment by jclark** [comment]
The basic approach is to follow Java and make 

Design summary:
1. Unreachability for `if`/`else` is done in the obvious way, consistently with `while`, not like Java, which does it specially in order to allow `if` to support conditional compilation. Instead for Ballerina, we can at a future time add specific support for conditional compilation, probably based on extending `configurable` to handle compile-time configuration.
2. Java does not have match statements, so we will need to specify when `match` can complete normally and when the RHS side of a `match` clause is unreachable.
3. A function call statement to a function with a return type of `never` cannot complete normally.
4. We add a langlib function `error:unreachable` with return type `never`, with the special semantics that a function call statement consisting of a call to error:unreachable is allowed if and only if that function call statement is unreachable.
5. Apart from point 4, any unreachable [statement](https://ballerina.io/spec/lang/2021R1/#statement) is an error.
6. A [statement-block](https://ballerina.io/spec/lang/2021R1/#statement-block) is not a statement; if a statement-block is unreachable, then every statement in it is unreachable. So an unreachable statement-block will be an error unless each of its statements is a function call statement calling `error:unreachable`.
7. `if` statements with constant conditions are not errors except in so far as they lead to statements being unreachable.
8. Types are narrowed following an `if` statement without an `else` clause if its statement-block cannot complete normally (e.g. it ends with `return`).
9. An `is-expr` is constant true if the static type of its LHS is a subtype of the type specified in the RHS.

**Comment by jclark** [comment]
I found this in the TypeScript handbook, which relies on `never` to test exhaustiveness.

```
function assertNever(x: never): never {
  throw new Error("Unexpected object: " + x);
}

function logger(s: NetworkState): string {
  switch (s.state) {
    case "loading":
      return "loading request";
    case "failed":
      return `failed with code ${s.code}`;
    case "success":
      return "got response";
    default:
      return assertNever(s);
Argument of type 'NetworkFromCachedState' is not assignable to parameter of type 'never'.
  }
}
```

I wonder if this might be a better approach than `error:unreachable`.

**Comment by jclark** [comment]
One of the main cases that `error:unreachable()` is designed to solve is this:

```
type T int|float|string;

function foo(T x) {
   if x is int {
      intFoo();
   }
  else if x is float {
     floatFoo();
  }
  else  {
     stringFoo();
  }
}
```

The above is not robust when another member may added to the T union.

With `error:unreachable()`, you can write it as

```
  if x is int {
      intFoo();
  }
  else if x is float {
     floatFoo();
  }
  else if x is string {
      stringFoo();
  }
  else {
     error:unreachable();
  }
```

But there's a better to write this, with no changes to the language, by using the following idiom:

```
 if x is int {
      intFoo();
   }
  else if x is float {
     floatFoo();
  }
  else  {
     string _ = x;
     stringFoo();
  }
```

The `string _ = x;`  allows the programmer to assert that `x` has been narrowed as they expected.

This currently gets an error from jBallerina `no new variables on left side`, but as far as I can see that's a bug in jBallerina.

You can use this idiom with match: 

```
enum Fruit { Apple, Orange };

function foo(Fruit f) {
  match fruit {
  Apple => { fooApple(); }
  _ => {
    Orange _ = fruit; 
    fooOrange();
  }
}
```

It's a bit ugly, and does not allow you to destructure in the default case.

But we could extend the idiom as follows:

```
enum Fruit { Apple, Orange };

function foo(Fruit fruit) {
  match fruit {
  Apple => { fooApple(); }
  Orange => { fooOrange(); }
  _ => { never _ = fruit; }
  }
}
```

or

```
enum Fruit { Apple, Orange };

function foo(Fruit fruit) {
  match fruit {
  Apple => { return fooApple(); }
  Orange => { return fooOrange(); }
  }
  never _ = fruit;
}
```

This is no new syntax and no changes to what constructs mean. But it requires adjusting the unreachability rules in this issue to say:

i.e. the only kind of statement that is allowed in unreachable code is a LocalVarDeclStmt that has a typed-binding-pattern with a type-descriptor with a type of never and an initializer that is a variable reference

We would need to adjust the rules relating to never from https://github.com/ballerina-platform/ballerina-spec/issues/510#issuecomment-796368278

1. The type in a typed-binding-pattern can be `never` if the binding pattern is `_`.
2. Expressions of type `never` are allowed within the initializer of a LocalVarDeclStmt with a typed-binding-pattern (1)
3. A variable-reference-expr can have type `never` when it is referring to a narrowed variable and occurs as (2)

We could do this `never` bit later.

@hasithaa, @MaryamZi Please review.

**Comment by hasithaa** [comment]
Hi there,

Hasitha Aravinda is inviting you to a scheduled Zoom meeting.

Topic: [ballerina-platform/ballerina-spec] Unreachability (#887)
Time: Aug 19, 2021 11:00 PM Midway Island, Samoa

Join from PC, Mac, Linux, iOS or Android:
https://wso2.zoom.us/j/8736393011?pwd=b050TldIRGVsOG5CSUNlK0JuanBkUT09
Password: 3hsTmy

Or iPhone one-tap :
US: +14086380968,,8736393011# or +16468769923,,8736393011#
Or Telephone:
Dial(for higher quality, dial a number based on your current location):
US: +1 408 638 0968 or +1 646 876 9923 or +1 669 900 6833 or +1 253 215
8782 or +1 301 715 8592 or +1 312 626 6799 or +1 346 248 7799
The United Kingdom: +44 208 080 6591 or +44 208 080 6592 or +44 330 088
5830 or +44 131 460 1196 or +44 203 481 5237 or +44 203 481 5240 or +44 203
901 7895
Brazil: +55 21 3958 7888 or +55 11 4632 2236 or +55 11 4632 2237 or +55 11
4680 6788 or +55 11 4700 9668

Password: 175902
International numbers available: https://wso2.zoom.us/u/adqPyRVnJo

**Comment by MaryamZi** [comment]
+1 for this approach.

I believe the changes based on `never` would also allow writing the if-else example as follows, separating out the assertion (of unreachability) if required.

```ballerina
    if x is int {
        intFoo();
    } else if x is float {
        floatFoo();
    } else if x is string {
        stringFoo();
    } else {
        never _ = x;
    }
```

The `no new variables on left side` error has been fixed for slbeta3, and the following will compile.

```ballerina
    if x is int {
        intFoo();
    } else if x is float {
        floatFoo();
    } else {
        string _ = x;
        stringFoo();
    }
```

**Comment by jclark** [comment]
Conclusion is not to do `error:unreachable`.

Use of `never` will become a separate issue.

**Comment by hasithaa** [comment]
Ternary expression is a valid use case, If we are allowing this, we should do this for both conditional expressions.

**Comment by jclark** [comment]
I agree

**Comment by hasithaa** [comment]
Sorry, I mistakenly deleted my previous comment. 

Ternary expression is a valid use case; we should enable this for both conditional expressions if we allow this.

**Comment by pcnfernando** [comment]
Should we handle unreachability checking for `where` clause as well?

```ballerina
public function main() {
    int[] _ = from var item in 1 ... 5
        where 4 != 4
        select item; 
}
```

**Comment by jclark** [comment]
@hasithaa I am not sure what you mean. Unreachability is something that applies to statements not expressions.

An expression `true ? 1 : 2` is allowed: const-expr allows a conditional-expr, but in a const-expr all expressions will be constant, so it wouldn't make any sense to disallow the first operand in a conditional-expr from being constant.The rules on singleton typing means that the static type of `true ? 1 : 2` will be singleton `1`.

**Comment by jclark** [comment]
@pcnfernando The reachability requirement applies to statements, so a where-clause with an expression that is singleton `false` would be an error in query-action, assuming the do-clause had a non-empty statement block.
