### ISSUE TITLE
Object type inclusion with a class that has `private` fields/methods

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#892]
**Description:**
IINM, the spec doesn't currently disallow inclusion with a class that has `private` fields/methods explicitly.

The implementation currently allows the following, but I believe this should be an error? 
```ballerina
class Foo {
    private int i = 0;
}

class Bar {
    *Foo; // Shouldn't this result in an error?

    function init(int x) {
        self.i = x;
    }
}
```

Should the spec mention this?

**Comment by jclark** [comment]
This shouldn't be allowed.
