### ISSUE TITLE
Add gRPC Any type support using Ballerina anydata

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-spec#896]
**Description:**
In gRPC, we have a requirement to support Any data type. The behaviour of gRPC Any data type is as follows. 

##### gRPC Any Data
`Any` contains an arbitrary serialized protocol buffer message along with a URL that describes the type of the serialized message [1, 2, 3].

```proto
message Any {
  string type_url = 1;
  bytes value = 2;
}
```

We can represent gRPC Any type using Ballerina anydata. Also, when we encode and decode a protobuf message, we need to infer the gRPC message URL from the given Ballerina record, similar to other languages [2]. When we allow users to pass `anydata` values, the users might create messages in the following ways:

```ballerina
Person p1 = {name: "John", id: 1}; // 1st way
anydata p2 = {name: "John", id: 1}; // 2nd way
```

When a user creates a message in a 2nd way, we cannot infer its type as a Person. To solve that, we can ask the user to explicitly specify the record type, but it won't be an ideal design approach.

@jclark any idea on this?.

##### References
[1] https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Any
[2] https://developers.google.com/protocol-buffers/docs/proto3#any
[3] https://github.com/protocolbuffers/protobuf/blob/b90ec9c242b303e90811deebaa2e3e684b63de91/src/google/protobuf/any.proto

**Related Issues:**
- https://github.com/ballerina-platform/ballerina-spec/issues/281
- https://github.com/ballerina-platform/ballerina-standard-library/issues/1647

**Comment by jclark** [comment]
I need to do more about how the gRPC support works to offer an opinion. Can you point me to a doc?

**Comment by BuddhiWathsala** [comment]
Here are the documentations:
- [gRPC documentation](https://grpc.io/docs/languages/java/basics/)
- [Protobuf types documentation](https://developers.google.com/protocol-buffers/docs/proto3)
- [Ballerina gRPC design doc](https://docs.google.com/document/d/1UDPm9bRZ9DS97W5tvZOnolYQsohKYLXLAfrofQJXitI/edit?usp=sharing)

Hope these docs would help.

**Comment by jclark** [comment]
Where is the user-level documentation for Ballerina support for gRPC?

**Comment by BuddhiWathsala** [comment]
- [Ballerina gRPC API documentation](https://docs.central.ballerina.io/ballerina/grpc/latest) 
- [Ballerina gRPC examples](https://ballerina.io/learn/by-example/grpc-simple.html?is_ref_by_example=true)
- [Ballerina implementation of the gRPC route guide example](https://github.com/ballerina-platform/module-ballerina-grpc/tree/master/examples/routeguide)

**Comment by jclark** [comment]
How is the URL supposed to describe the type? Is it supposed to work between different languages?

Some examples look like they are just using part of the URL as the name of the type.

What are typical use cases for `Any`?

**Comment by BuddhiWathsala** [comment]
The URL can be defined as:
```
type.googleapis.com/<package_name>.<message_type>
```

**Packing and Unpacking**
During the packaging phase, the URL will be specified. After the message received, the unpacking phase will unpack the message using the specified URL. The message type specified in the message could be a predefined Protobuf type(e.g Timestamp, Duration) or a custom type shared through the protobuf definition.
 
Packing and unpacking happen as follows [4].

> The pack methods provided by protobuf library will by default use `type.googleapis.com/full.type.name` as the type URL and the unpack methods only use the fully qualified type name after the last `/` in the type URL, for example `foo.bar.com/x/y.z` will yield type name `y.z`.

**Use Cases of Any Type**
- An authentication service where we cannot share the exact protobuf message definition [6]
- Filtering or routing service that allows multiple protobuf definitions [5, 6] 

**References**
[4] https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Any
[5] https://codeburst.io/protocol-buffers-part-2-the-untold-parts-of-using-any-6a328560048d
[6] https://blog.envoyproxy.io/dynamic-extensibility-and-protocol-buffers-dcd0bf0b8801

**Comment by jclark** [comment]
I think `Struct` is a better fit for the Ballerina world view. Do you support that? I think you can use that to represent `map<anydata>`

I would support `Any` as a `distinct class`. The class would have an `init` method that would allow it to be built from the serialized form, and another method to convert to the serialized form. The URL would encode the Ballerina module and type name within the module.

**Comment by BuddhiWathsala** [comment]
We are not supporting the `Struct` type ATM, so we can start off with that. 

When it comes to the `Any` type support, using a `distinct class` would be a much better solution. However, the only concern is, we support all other protobuf types using Ballerina records, but here we are going to use a `distinct class` to represent `Any` type. This may confuse the end-users.

**Comment by BuddhiWathsala** [comment]
The `Any` type support has been given using the following record. 

```ballerina
# Represent protobuf `Any` type.
#
# + typeUrl - The URL identifier of the message  
# + value - The message  
public type Any record {|
    string typeUrl;
    ValueType value;
|};
```

We introduce two generic `pack` and `unpack` APIs to serialize and deserialize the `Any` typed messages.

Proposal - https://github.com/ballerina-platform/ballerina-standard-library/issues/2365
