### ISSUE TITLE
Require preserving insertion order of fields in mapping with inherent type `map<T>`

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#897]
The shape of a mapping value does not contain information about the order of the fields. However, as a practical matter if you suck some JSON in, slightly modify it, and then write it out again, it will be annoying if Ballerina changes the order of fields in the JSON. On the other hand, we want to make sure that we do not prevent efficient implementation of records, which are fundamental to Ballerina performance.

I think a compromise approach is as follows. When the inherent type of the mapping value is `map<T>`, then the implementation is required to maintain the insertion order for the fields. When you iterate or serialize over the fields, you will get the fields in the order they were inserted. When you parse JSON, the result will have mappings with inherent type `map<json>` and the fields will be in the order they were in the JSON. Mutating an existing field would not change the field ordering. This will also lead to preserving the order of XML attributes.

Java has LinkedHashMap that does this. Python also has a clever implementation (similar to what V8 uses) that will allow [nBallerina to do this efficiently](https://github.com/ballerina-platform/nballerina/issues/170#issuecomment-872666780) also.

**Comment by jclark** [comment]
@hasithaa jBallerina already uses LinkedHashMap, right?

**Comment by hasithaa** [comment]
> @hasithaa jBallerina already uses LinkedHashMap, right?

Yes, That is correct. https://github.com/ballerina-platform/ballerina-lang/blob/b295b069f366a3202a930a6f3e5be0684f8e3423/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/MapValueImpl.java#L87

**Comment by jclark** [comment]
This would apply only to mutable values (immutable values don't have an inherent type).

**Comment by MaryamZi** [comment]
Just for the record, preserving the insertion order for records has previously been raised in the context of included record parameters (https://github.com/ballerina-platform/ballerina-lang/issues/27447, https://github.com/ballerina-platform/ballerina-lang/issues/29551).

For example, the log module uses included record parameters as follows.

```ballerina
public type KeyValues record {|
    never msg?;
    never 'error?;
    Value...;
|};

public isolated function printError(string msg, error? 'error = (), *KeyValues keyValues) {
    ...
}
```
