### ISSUE TITLE
New basic type representing external opaque handle

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#90]
Can be returned from an extern function and passed to an extern function.

Maybe also allow ===

**Comment by jclark** [comment]
Main design point is the name. We could just use `external`. Although that is an adjective, other of our types are named as adjectives (boolean, decimal).

**Comment by sameerajayasoma** [comment]
Do we need to allow developers to declare variables/parameters of this type? Can we use `any` type to reference this value?  In this model, developers cannot declare a variable of this type explicitly.

**Comment by sameerajayasoma** [comment]
I think `external` can be quite confusing.    

`public function doSomething(string path) returns external = external;`

**Comment by jclark** [comment]
Yes, that is confusing. Any suggestions for something less confusing? Here are some random suggestions:

1. extref
2. externalref
3. externref
4. opaque
5. handle

It needs to be a separate basic type so that the value returned by one external function can be passed to another external function.

**Comment by sanjiva** [comment]
How about "foreign"?

**Comment by sameerajayasoma** [comment]
IMO, it is an opaque type where Ballerina doesn't have any information about its structure. It is a black box to Ballerina programs. Calling external functions or methods is the only way to manipulate the value referenced by a variable of the opaque type.

**Comment by jclark** [comment]
@sameerajayasoma Yes. You still need to declare the type of a variable that can contain only of the opaque handles; the type declaration will not give any further information about it other than that it is of this distinct basic type.

**Comment by jclark** [comment]
@sanjiva foreign seems to me just another way to say external; we could have called external functions foreign functions

**Comment by sameerajayasoma** [comment]
How about `opaqueref` or just `opaque` (you've suggested this earlier)?

**Comment by jclark** [comment]
I see Flow uses opaque for something rather different:

https://flow.org/en/docs/types/opaque-types/

The thing we are trying to name is not merely opaque but also created by an external function.

**Comment by jclark** [comment]
Windows uses HANDLE for this:

https://docs.microsoft.com/en-us/windows/desktop/winprog/windows-data-types

**Comment by sanjiva** [comment]
@jclark Its possible a Ballerina function can return an opaque value too. Of course the value originates externally and it can only be used meaningfully externally only.

Anyway I don't see a magic answer. I'm ok with `externref` given we're using extern.

**Comment by jclark** [comment]
I like `pointer`.

**Comment by sanjiva** [comment]
IMO we should avoid the word `pointer` like the plague :-). 

We're using `external` so we could go with `externalref` as then its clear about the origin and what it is.

**Comment by jclark** [comment]
Three things I don't like about `externalref`:

1. too long
2. two words (although `typedesc` is a precedent for this)
3. inclusion of `ref` in the name is inconsistent with other references types; none of the existing reference types include anything about their being references; for example, tables are references, but the type is table not tableref

How about `handle`? It seems a good fit semantically:

https://en.wikipedia.org/wiki/Handle_(computing)

**Comment by sanjiva** [comment]
I'm good with `handle`.
