### ISSUE TITLE
Type of expression when operands have singleton type

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#902]
The spec says that the type of -E is the basic type of E, but that really doesn't work when E is a singleton type.

If the type of the expression `1` is singleton `1`, then the type of expression `-1` surely has to be singleton `-1`. In which case, shouldn't we do the same for all constant expressions?

This would, for example, make the type of `1 + 2` be singleton `3` rather than `int`.

**Comment by jclark** [comment]
@hasithaa What do you think?

**Comment by hasithaa** [comment]
I think that makes sense. https://github.com/ballerina-platform/ballerina-spec/issues/836 is related to this as well.

**Comment by jclark** [comment]
This relates to unreachability #887 . It would be cleaner if the rule for unreachability was

```
if E { S }
```

S is unreachable if E has type singleton `false` rather having to introduce a new similar (but very slightly different) concept of an expression being constant (which is not the same as a const-expr).

There are some complications here.

First problem is what to do about `===` and `!==` because these distinguish values with the same shape. Even if the operands have singleton type, the result may not have singleton type. e.g.

```
type Float0 0.0f;

function foo(Float0 x, Float0 y) {
   var b = x === y;
}
```

`b` has to be boolean rather than a singleton.

Another problem is with float:

```
type Float1 1.0f;
type Float0 0.0f; // type contains both positive and negative 0

function foo(Float1 x, Float0 y) {
   var inf = x/y;
}
```

The value `inf` may be positive or negative infinity, depending of type of `y`.

**Comment by jclark** [comment]
Going back to the example in #836 

```
int | string a = 5;
if a == 4 + 1 { // should type of a get narrowed with singleton 5
}
```

If I had said

```
const FIVE = 4 + 1;
int | string a = 5;
if a == FIVE { 
}
```

Then type would be narrowed, because a const has a singleton type. So this has the nice effect that (at least for non-structured values) with

```
const X = E;
```

the type of X is the type of E, which I think is intuitive.

**Comment by jclark** [comment]
I am now wondering whether we should have `===` and `!==` in const expressions. What does that do with structured values?  Do we want the compiler to keep multiple copies of structured constants that are == in order to preserve ===-ness?

**Comment by jclark** [comment]
The issues with float, decimal and structured types are making this all rather complicated.

An alternative approach is a much more limited fix to unary plus/minus only: if the operand has singleton type, then the unary minus or plus expression has singleton type. The justification for special casing this is:

- although unary minus and plus are formally expressions, when they are used with a numeric literal, one really thinks of the sign as being part of the literal (i.e. it's a signed literal)
- langlib int/float/decimal:fromString functions allow the sign in front of the literal
- it's already special cased in https://ballerina.io/spec/lang/2021R1/#simple-const-expr

Other things would remain as proposed elsewhere.
1. Unreachability is based on whether the expression is a constant expression
2. Narrowing continues to be based on type

Difficulty with this is how to make constant expressions work consistently in const definitions and contexts where they affect unreachability (i.e. conditional expressions). In particular, list/mapping constructors are different because in the const definition case they are implicitly readonly.

Fundamental question here is whether unreachability should be based on types or on constant evaluation.

**Comment by jclark** [comment]
I think it's not going to be possible to make "const expressions" work in a conditional context in the same way as they do in a const definition, because mapping and list constructors necessarily work differently.

Therefore I think unreachability should be based on type (is it the type singleton true or singleton false). That means that expressions should generally have a singleton type whenever all their operands have a singleton type.

The exceptions will be:
* `===` and `!==` : type will always be boolean not singleton
* float / operator when right hand side is 0 (looks like `%` does not produce non-singleton result from singleton operands, but need to double check https://ballerina.io/spec/lang/2021R1/#section_6.23): I think we should make this float rather than trying to do extend typing of all floating points operations  to unions of positive and negative infinity

**Comment by jclark** [comment]
Conclusion of today's discussion is to go with https://github.com/ballerina-platform/ballerina-spec/issues/902#issuecomment-887136996 unless we discover a problem in the next 24 hours.

**Comment by jclark** [comment]
Consider the following:

```
type Sign 1|-1;
type Zero 0f;

function zero(Sign sign) returns Zero {
   return sign < 0 ? -0f : 0f;
}

function foo(Sign sign) {
  // type of the expression is singleton false
  if zero(Sign) + 1f != 1f {
     io:println("unreachable"); // @error
  }
}
```

This example is a pain because we cannot deal with it via constant folding (because the result of `zero` is not a constant)

**Comment by manuranga** [comment]
Does this mean `-9223372036854775808` needs to be a valid literal?

**Comment by jclark** [comment]
No.

**Comment by jclark** [comment]
The following cases need fixing:

* unary-expr
* multiplicative-expr
* additive-expr
* shift-expr
* relational-expr
* binary-bitwise-expr
* string-template-expr
* equality-expr
