### ISSUE TITLE
Should we restrict how a loop can use a variable that has been narrowed outside the loop?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#904]
Consider:

```
public function main() {
   foo(1);
}

function foo(any v) {
   any x = v;
   if x is int {
      int i = 2;
      while i > 0 {
         x = x + 1; // not allowed
	 x = ();
	 i = i - 1;
      }
   }
}
```

This should get a compile time error, since there is an execution path in which `x = ()` is executed before `x = x + 1`, so x cannot be narrowed on the RHS of the assignment.

However, slbeta2 doesn't handle this and instead gives a runtime error. I am also finding this hard to implement in nBallerina.

I am wondering if we can put some restriction in the spec to simplify things.

_Originally posted by @jclark in https://github.com/ballerina-platform/ballerina-lang/issues/31935#issuecomment-888803079_

**Comment by hasithaa** [comment]
Yes, It seems like current type narrowing rules don't handle this situation.

**Comment by jclark** [comment]
@MaryamZi Any thoughts?

**Comment by jclark** [comment]
Another complication is if you do

```
var x = n;
```

where `n` is a narrowed variable. You don't know what the type of `x` is until you know whether the narrowing of `n` still applies.  Then `x` itself could be used in a condition and then narrowed.

**Comment by jclark** [comment]
I gave it a try with Kotlin, and it has the same rules as the spec currently does, and appears to implement everything correctly including the complication I mentioned in https://github.com/ballerina-platform/ballerina-spec/issues/904#issuecomment-889078486. So I guess we need to do some quite serious data flow analysis.

**Comment by MaryamZi** [comment]
I was wondering if we can stick to not doing https://github.com/ballerina-platform/ballerina-spec/issues/842 and additionally say if within a loop an assignment may happen to a narrowed variable, narrowing wouldn't hold for that variable anywhere within the loop, unless the loop itself does the narrowing.

This would mean that in addition to the original example even the following will not be allowed (due to not doing https://github.com/ballerina-platform/ballerina-spec/issues/842).

```ballerina
function foo(any v) {
    any x = v;
    if x is int {
        int i = 2;
        while i > 0 {
            x = x + 1; // not allowed
            i = i - 1;
        }
    }
}
```

Not doing https://github.com/ballerina-platform/ballerina-spec/issues/842 would disallow even the following anyway (even outside a loop).

```ballerina
function foo(any v, boolean b1) {
    any x = v;
    if x is int {
        x += 1; // resets narrowing

        if b1 {
            x += 2; // error, x is no longer int
        }
    }
}
```

Alternatively, if we support https://github.com/ballerina-platform/ballerina-spec/issues/842, maybe we can make type narrowing not apply for the variable anywhere in the loop only if the assignment resets the narrowing.

The following (similar to the example in https://github.com/ballerina-platform/ballerina-spec/issues/840) will still be allowed since the loop does the narrowing.

```ballerina
type Employee record {|
    string name;
|};

function getNames(stream<Employee, error> employees) {
    string[] names = [];
    record {| Employee value; |}|error next = employees.next();

    while next is record {| Employee value; |} {
        names.push(next.value.name);
        next = employees.next();
    }
}
```

Any attempt to use `next` as the narrowed type after the assignment will still result in an error.

```ballerina
while next is record {| Employee value; |} {
    names.push(next.value.name);
    next = employees.next();
    next.name = ""; // error: invalid operation: type '(record {| Employee value; |}|error)' does not support field access
}
```

**Comment by jclark** [comment]
After reading up a little about data flow analysis, it looks to me like this can be implemented using fairly standard data flow analysis tools. This data flow analysis is pretty similar to what needs to be done for definite assignment (I have found the C# spec on [definite assignment](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/variables#definite-assignment) easier to understand, and no less precise, than the Java spec).

So I think if we are going to have a restriction, there needs to be a principled justification other than implementation difficulty.

I think it's a good principle that the type of a reference to a local variable in a function should only be influenced by things that occur lexically before the reference. This means that if you read a function linearly from start to finish, you will always know what type each variable has when you see a reference to it. Now we violate this slightly with `var`, but the lookahead required is only a single expression. However, the current situation with assignment in loops to narrowed variables requires arbitrary lookahead: the type of a reference to a narrowed variable may be "unnarrowed" by a subsequent assignment that can be arbitrarily far ahead.

There are two possible approaches we could take to making the language consistent with this principle:

1. say that a variable narrowing that happens outside a loop does not apply within a loop, or
2. restrict assignments to narrowed variables within loop

With 2, the restriction would be that you cannot make an assignment to a narrowed variable that can flow backwards. In others words, at the end of the loop body and at every `continue`, there must be no possible assignment to a variable that was narrowed outside the loop.

I prefer 2 to 1, because it will give the user a clearer error: with 1 the narrowing won't be applied, so if the user expects the narrowing to be applied, they will get a confusing type error later on.

Is the restriction in 2 going to a problem or not? I don't know.  So my proposal would be to put in the restriction 2 for now, and if it turns out to be a problem we can take it out and do the work to implement the necessary data flow analysis.

**Comment by hasithaa** [comment]
I think Option 2 is good, will improve this in JBallerina.

**Comment by MaryamZi** [comment]
+1 for approach 2. 

> We could also disallow the use of a narrowed variable in the initializer of a variable declared with `var`.

I'm not sure I get why we need this restriction though. With approach 2, wouldn't we know that for any variable narrowed outside the loop narrowing still holds while for any variable narrowed in the loop we will know whether narrowing still holds when we get to the declaration?

**Comment by jclark** [comment]
@MaryamZi Sorry, I wasn't clear. We don't need this with approach 2. But if we found approach 2 to be too restrictive, we could drop the restriction and then add the restriction on `var` (but only for narrowed variables that are assigned to).

**Comment by jclark** [comment]
@hasithaa Note this has to apply to a query-action as well as a while-stmt or foreach-stmt.
