### ISSUE TITLE
Problems from trailing `.` in floating point literal

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#905]
Spec allows a [floating pointer literal](https://ballerina.io/spec/lang/2021R1/#floating-point-literal) to end with a `.`.

Assuming normal lexical disambiguation (return longest string that is a token) this results in a number of things not parsing, e.g.

```
foreach int i in 0..<max { }
io:println(0.toHexString());
io:println(0xff.toHexString())
```

This seems not OK to me. So I think we need to

1. specify lexical disambiguation differently, and/or
2. not allow this

Does anybody really need the trailing dot format? C and Java allow it, but I see JSON doesn't.

**Comment by jclark** [comment]
Swift doesn't allow it https://docs.swift.org/swift-book/ReferenceManual/LexicalStructure.html#grammar_floating-point-literal

**Comment by lochana-chathura** [comment]
As of now, we have special-cased above scenarios in the lexer. For example, in `0..<max`  when there's more than one dot follow a numeric, we capture the numeric-only(`0`) not `0.` We have done the same kind of thing for `0.toHexString()` as well.

Another place, we have special-cased is, `-3 x = <-3> -3;`, when `<-` is followed by a digit we capture only the `<`. not `<-`.

**Comment by jclark** [comment]
Decide not to allow trailing `.`.
