### ISSUE TITLE
Support construct Parameterized Query(Raw Template) by appending two or more queries

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-spec#918]
**Description:**
In the current implementation, we can write parameterized queries like below,

```ballerina
sql:ParameterizedQuery query = `SELECT registrationId, firstName, lastName FROM Customers WHERE country LIKE ${country}`;
```
is it possible to give support to append two or more parameterized queries into one, for example,

```ballerina
sql:ParameterizedQuery query = `SELECT registrationId, firstName, lastName FROM Customers`;

if !(country is ()) {
    query = query + ` WHERE country LIKE ${country}`;
}
```
So we can dynamically construct queries based on the condition.

**Comment by jclark** [comment]
A ParameterizedQuery is an object that you can manipulate with normal language features. So the sql module can just provide a

```
function sql:queryConcat(sql:ParameterizedQuery... queries) returns sql:ParameterizedQuery;
```

function.
