### ISSUE TITLE
Make it more convenient to work with optional fields

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#926]
In some schema languages fields are optional by default. When Ballerina types are generated from schemas in these languages, almost all fields in the generated type are optional. Accessing these is inconvenient, because it requires both `?.` to access the field and then `?:` to specify the result when the field is nil.

#191 helps with this to a limited extent.

Is there anything else we can do at the language level to help?

**Comment by jclark** [comment]
Some ideas (not thought through yet).

**Idea 1**

If a record R has a field f of type T and type T does not include (), then if r is of type R, allow `r.f` and give it a type of `T?`. (This is pretty similar to what we are doing in #191.)

For example, if we have field

```
   decimal amount?;
```

then it's safe to allow `x.amount`, because the type will be `decimal?`, so the optionality is not getting ignored. You would only need `?.` when the field is of a type `T` such that `T` and `T?` are the same (i.e. T includes nil).

**Idea 2**

Allow records to specify a default for optional fields, which is applied at access time 

```
type Foo record {
  int amount? = 0;
};

Foo foo = {}; // foo does not have an amount field
int n = foo.amount; // n will be 0
```

**Idea 3**

With arrays we have a concept of filler values (0 for int, empty string for string, empty array for arrays etc) etc.  Can we apply this to records somehow?

@hasithaa @sanjiva

**Comment by hasithaa** [comment]
Option 1 simplifies the access. We still have to use another operator (Elvis) to remove the nil from the value. 

With option 2 and 3, we will have a behaviour, `foo.hasKey("amount")` returns `false`, but `foo.amount` returns some value, which sounds not correct.

**Comment by jclark** [comment]
I think we should do Idea 1 for Swan Lake GA.

**Comment by jclark** [comment]
Fleshing out Idea 3, we could have a variant of `.` that returned the filler value for any missing field. For example, suppose the operator is `!.`. Then 

```
type Foo record {
  int amount?;
};

Foo foo = {};
// n will get 0, because the amount field is missing and the filler value for `int` is 0
int n = foo!.amount; 
```

We could even go a step further and (instead of Idea 1) say that `.` on a missing optional field returns the filler value (and is an error if the type doesn't have a filler value).   Then

```
type Foo record {
  int amount?;
};

Foo foo = {};
// n will get 0, because the amount field is missing and the filler value for `int` is 0
int n = foo.amount; 
```

This is effectively doing a bunch of implicit conversions on field access, so is perhaps a step too far.  On the other hand, users who don't want this behaviour can use `?.` on optional fields. Depends on how much we want to go in the direction of making things easy for unsophisticated users.

**Comment by sameerajayasoma** [comment]
@jclark In idea 1, why do we need to use `?.` when the field is of a type T (T includes nil)?

**Comment by hasithaa** [comment]
> Is #191 also part of Swan Lake?
Yes, The PR needs little bit more testing. We should be able to merge this for Beta4. 

> If so, when we do Idea 1, then we will be able to do this:
> 
> ```
> type Person record {
>   int xxx?;
> }
> 
> Person p  = { xxx: 10 };
> int? a = p.x;
> int? aPlus10 = p.x + 10;
> ```
> 
> Right? Eventually to get rid of `?` we'll have to do `?:` of course.

Yes.

**Comment by sanjiva** [comment]
OK great then I'm +1 for getting Idea 1 into Swan Lake. That will be sooo much better.

**Comment by jclark** [comment]
@sameerajayasoma The idea is to avoid hiding the optionality of the field. The design in Idea 1 ensures that the optionality of the field results in a change to the type of the field access expression. This is the same principle used for #191. We could go further, but that has both positives and negatives, whereas (as far as I can tell) there are no negatives to Idea 1. We could extend this further in a future version. But for Swan Lake, I think it's better to start with a more conservative change.
