### ISSUE TITLE
Wrap a ParameterizedQuery Array with a ParameterizedQuery

### ISSUE THREAD

**Issue by SuKSW** [ballerina-platform/ballerina-spec#927]
Hi Team,

We have a requirement to execute a batch of queries as a single transaction which also includes a table lock. These are smaller batches and therefore we want to prevent any partial insertions or updates.

It would be great if there was a way to wrap our already existing array of ParameterizedQuery, in another ParameterizedQuery where we could define the transaction and the lock.

**Comment by hasithaa** [comment]
I am not sure, I got your exact requirement. but it seems like you need to concatenate or modify ParameterizedQuery objects. (raw templates). is it correct? Could you provide an example code.

**Comment by jclark** [comment]
How is this different from #918?

**Comment by SuKSW** [comment]
Some like the following can be an example. 
```
sql:ParameterizedQuery[] qArrayForTableOne = 
        from var result in arrayOfResults
        select `INSERT ..`;
					
sql:ParameterizedQuery[] qArrayForTableTwo = 
        from var result in arrayOfResults
        select `UPDATE ..
	            IF @@rowcount = 0
	            INSERT ..`;
					
sql:ParameterizedQuery q = `SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
				BEGIN transaction 
					${qArrayForTableOne}
					${qArrayForTableTwo}
				COMMIT transaction`;
												
dbClient->execute(q);
```
@hasithaa The above can be the example for the usage of this. It is to insert an array at the time of creation itself (creation of the ParameterizedQuery)

@jclark It differs due to the usage of an array and that we would not have to explicitly concatenate. In fact it is a combination of https://github.com/ballerina-platform/ballerina-spec/issues/918 and https://github.com/ballerina-platform/ballerina-spec/issues/923

**Comment by jclark** [comment]
Why can't you do this?

```
sql:ParameterizedQuery q = sql:concatQuery(
`SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
 BEGIN transaction`,
...qArrayForTableOne,
...qArrayForTableTwo,
`COMMIT transaction`);
```

**Comment by SuKSW** [comment]
Yes, That would do. Thanks! Closing this issue with reference to https://github.com/ballerina-platform/ballerina-spec/issues/918
