### ISSUE TITLE
Introduce a new `bal` command to print the package dependency graph in text form

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#928]
This command should print the package dependency graph to the terminal. I would prefer to call it `bal graph` and it will be part of the following package commands.
```
   Package Commands:
        new             Create a new Ballerina package
        init            Initialise a new Ballerina package in the current directory
        pull            Pull a package from Ballerina Central
        push            Upload a package to Ballerina Central
        Search          Ballerina Central for packages
        graph           Print package dependency graph   
```

**Comment by sameerajayasoma** [comment]
IMO, the textual representation of the dependency graph should be intuitive. Also, It would be useful if that textual format can be visualized (via a tool) as a graph. 

My preference is to use the graph description language called "DOT" as the textual representation. There are several tools such as `graphviz` to covert this format to a visual representation. 

Here is a sample Ballerina package dependency graph:
```
digraph "samejs/app:0.1.0" {
    "samejs/app:0.1.0" -> "ballerina/http:1.3.1"
    "samejs/app:0.1.0" -> "samjs/foo:1.2.1"
    "samejs/app:0.1.0" -> "samtest/io:1.5.1"
    "ballerina/http:1.3.1" -> "ballerina/cache:1.2.1"
    "ballerina/http:1.3.1" -> "ballerina/io:1.0.2"
    "samjs/foo:1.2.1" -> "samjs/bar:1.3.4"
    "samjs/foo:1.2.1" -> "samjs/bazz:1.4.4"
    "samtest/io:1.5.1" -> "ballerina/http:1.3.1"
    "samtest/io:1.5.1" -> "samjs/c:0.4.6"
    "samtest/io:1.5.1" -> "samjs/q:1.4.4"
    "samjs/b:1.3.4" -> "samjs/c:0.4.6"
    "samjs/bar:1.3.4" -> "samjs/bazz:1.4.4"
    "samjs/bar:1.3.4" -> "samjs/p:1.3.5"
    "samjs/bar:1.3.4" -> "samjs/q:1.4.4"
    "samjs/bazz:1.4.4" -> "samjs/b:1.3.4"
    "samjs/bazz:1.4.4" -> "samjs/c:0.4.6"
    "samjs/c:0.4.6" -> "samjs/t:4.6.1"
    "samjs/p:1.3.5" -> "samjs/t:4.6.1"
}
```
You can visualize this using the command-line tool `dot` or using online sites.  

```
bal graph | dot -T png > graph.png
```
![graph](https://user-images.githubusercontent.com/2637328/132917964-abe9ebaa-bc0e-4469-abc2-1ed7c9ffe8a7.png)

We can even use this format to troubleshoot any package dependency-related issues. 

We are anyway using this format to write unit tests to test the package resolution engine.

**Comment by sameerajayasoma** [comment]
This command should also accept `--offline` and `--sticky` options

**Comment by azinneera** [comment]
We introduced `bal graph` command in Swan Lake Update 2 which prints the textual representation of the dependency graph using the dot graph language.
