### ISSUE TITLE
[Clarification] Destination format and source format

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-spec#932]
Please refer to https://ballerina.io/ballerina-spec/spec.html#multiplicative-expr.

```
float, decimal
* performs the multiplication operation with the destination format being the same as the source format, 
 as defined by IEEE 754-2008; this never causes a panic to occur
* / performs the division operation with the destination format being the same as the source format, 
as defined by IEEE 754-2008; this never causes a panic to occur
```

Does **_format_** here mean the binary and decimal floating point data representation in IEEE-754-2008 and are the two operands involve in multiplicative-expr called destination and source(as in `MUL` in assembly)?

**Comment by jclark** [comment]
IEEE 754-2008 defines several different binary and decimal formats e.g. binary32 binary64 binary128 and it defines a variety of multiplication operations involving combinations of these formats.  This is saying that we are using the IEEE operation where the operands and the result all have the same format.  See 5.4.1 of the IEEE spec.
