### ISSUE TITLE
array<T> as synonym for T[]

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#94]
The current `T[]` syntax is familiar, but not readable for some cases, particularly with new tuple syntax. For example: `[int, string][]` is an array of `[int, string]` tuples. It might be clearer (and more consistent with map) to also allow `array<[int, string]>` for this. On the other hand this is two ways to do the same thing.

**Comment by jclark** [comment]
@sanjiva What do you think?

**Comment by sanjiva** [comment]
The synonym nature does not bother me as we already have shortcut syntax for a variety of cases (e.g., map<T> (== record {| T...; |}).

However, I think `[T,U][]` is sufficiently clear. Plus one can always do `type foo [T,U];` and then do `foo[]` if its bothering them. 

Plus this is an easy add on if it feels not nice. So I propose pushing it to Rn consideration.

**Comment by jclark** [comment]
I am fine with pushing it to a later version.

Also it's not obvious how to make `array<T>` deal with fixed lengths.

A related issue is multi-dimensional arrays (i.e. arrays with more than 1 dimension as a single container, rather than arrays of arrays). So it might be good to keep array in reserve for that.
