### ISSUE TITLE
Type of floating-point-literal when contextually expected type is `int|decimal`

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#943]
The spec https://ballerina.io/spec/lang/2021R1/#section_6.5 doesn't appear to handle this case sensibly:

```
decimal|int n = 1.2;
```

This should interpret 1.2 as decimal, but the spec says to interpret it as a float, which would make this a compile error.  Relates to #939, #940

**Comment by MaryamZi** [comment]
The jBallerina implementation allows this at the moment, but it also allows cases like

```ballerina
float|decimal x = 2; // considered to be the same as `2f`
```

and

```ballerina
type Foo 1f|1d|2d;

public function main() {
    Foo f1 = 2; // considered to be the same as `2d`
    Foo f2 = 1; // considered to be the same as `1f`
}
```

Basically it checks against the expected type if the literal is valid if it were of a particular numeric type, prioritizing int over float and float over decimal.

https://github.com/ballerina-platform/ballerina-lang/issues/32698 was created for the deviation from the spec.

**Comment by jclark** [comment]
If we allow

```
float|decimal x = 1.2;
```

and treat it as 1.2f, then it seems consistent to allow

```
float|decimal x = 1;
```

and treat it as 1f.

**Comment by jclark** [comment]
This would combine with saying for #939, that if the value is out of range, it's a compile-time error.

**Comment by MaryamZi** [comment]
@jclark, we are currently working on fixing the jBallerina deviations, and would appreciate confirmation that "use the most preferred such type." in point 2 means the most preferred basic type and not the intersection, which would mean the following would result in a compilation error.

```ballerina
type Foo 1|2f;

Foo f = 2; // Considered to be `int` `2`?
```

**Comment by jclark** [comment]
Yes: "such" refers to "possible basic type".

**Comment by MaryamZi** [comment]
> Yes: "such" refers to "possible basic type".

Noted, thank you.
