### ISSUE TITLE
Determining the inherent type from applicable contextually expected type, in list constructor

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-spec#949]
**Description:**
Consider `int[]|boolean[] arr = [1, 2, 3];`

 As per the spec, applicable contextually expected type here is, intersection of `int[]|boolean[]` and list, which is again `int[]|boolean[]`.

How do we determine the inherent type from that? In the current implementation, it is `int[]`. Can it also be `(int|boolean)[]`?

Under [list-constructor-expr](https://ballerina.io/ballerina-spec/spec.html#list-constructor-expr) spec says following, I'm not sure if it's enough to make the above determination. 

> If there is a contextually expected type, then the inherent type of the newly created list is derived from the applicable contextually expected type. If the applicable contextually expected type is a list type descriptor, then that used as the inherent type. If the applicable contextually expected type is a union type descriptor, then any members of the union that do not contain list shapes of length N will be ignored, where N is the number of expressions in the expr-list; it is a compile-time error if this does not leave a single list type descriptor, which is then used as the inherent type. The static type of the list-constructor-expr will be the same as the inherent type.

**Comment by manuranga** [comment]
They are the same thing.

**Comment by manuranga** [comment]
`int[]|boolean[]` and `(int|boolean)[]` are not the same thing. So it has to be `int[]|boolean[]`

**Comment by rdulmina** [comment]
As per my understanding applicable contextually expected type is `int[]|boolean[]` which is a union. According to the spec, then we eliminate `boolean[]` since the shape of [1,2, 3] is not belonging to `boolean[]`. Then we left with `int[]` which is the inherent type

**Comment by jclark** [comment]
> it is a compile-time error if this does not leave a single list type descriptor

So it's a compile-time error.  The inherent type cannot be a union type descriptor.

**Comment by jclark** [comment]
> then we eliminate boolean[] since the shape of [1,2, 3] is not belonging to boolean[]

But the spec says

> any members of the union that do not contain list shapes of length N will be ignored

`boolean[]` does contain list shapes of length 3.

**Comment by rdulmina** [comment]
> > then we eliminate boolean[] since the shape of [1,2, 3] is not belonging to boolean[]
> 
> But the spec says
> 
> > any members of the union that do not contain list shapes of length N will be ignored
> 
> `boolean[]` does contain list shapes of length 3.

Yeah, It's clear with me now thanx
