### ISSUE TITLE
Clarification on inherent type of a mapping value with readonly fields

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-spec#955]
**Description:**
Consider the below sample
```bal
    map<any> var1 = {readonly fieldC: 4343};
```
according to spec 

> If there is a contextually expected type, then the inherent type of the newly created mapping is derived from the applicable contextually expected type. If the applicable contextually expected type is a mapping type descriptor, then that used as the inherent type.

So the inherent type of the mapping value will be `map<any>`. But currently, in the implementation, it is `typedesc record {| readonly int fieldC; any...; |}`. With that the current implementation gives the panic for `var1["fieldC"] = 4;` as expected. So what should be the correct inherent type here?

**Comment by jclark** [comment]
@rdulmina I created a new issue #957 for this.
