### ISSUE TITLE
Allow some keywords as method names

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#958]
As a step towards #34, a possible approach is to allow a method-name in a https://ballerina.io/spec/lang/2021R1/#method-call-expr to be particular keywords, specifically `map`, `join` and `start`. 

`map` and `join` are used as langlib function names; `start` is currently special-cased by jBallerina.

**Comment by jclark** [comment]
Decided to do this.

**Comment by jclark** [comment]
I think we should do this in method-decl and method-defn also i.e. change the method-name production to allow this.

**Comment by hasithaa** [comment]
> I think we should do this in method-decl and method-defn also i.e. change the method-name production to allow this. These additional places occur after `function`, so there is no parsing problem.
> 
> I wouldn't do this for remote methods since they are in a separate symbol space and use different calling syntax. So I would use a different production for these (i.e. remote-method-name).

+1 for the approach.

**Comment by jclark** [comment]
Turns out `start` is also used in langlib in DynamicListener.

**Comment by pubudu91** [comment]
In 9cea65c580ccd3023ac3ed1b37d51a2e2d3fb4a2 the quotes are removed even in `map()` and `join()` functions. But according to the discussion above and the current spec, we can omit the quote only in a method decl or def isn't it?

**Comment by jclark** [comment]
@pubudu91 Yes, you're right. I put them back in the function definitions.
