### ISSUE TITLE
`bal build`: Remove `--skip-tests` option

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#966]
For Swan Lake Beta4, we decided to improve the default behavior of `bal build` by not executing tests. With that, we will be removing the `--skip-tests` option. 

This is the first step towards preparing `bal` commands for upcoming optimizations to improve compilation times. These changes will most probably happen after Swan Lake GA. 

In Swan Lake Beta4 and all previous releases, both `bal build` and `bal test` commands execute tests. The former command builds both the executable and test executables. Test executables are used to run tests. Also, both these commands have a similar set of test-related options. 

With this change, `bal build` command's primary focus will be on building the executable and `bal test` command's focus will be on building test executables and running them. 

However, we decided to introduce another option called `--with-tests` to instruct `bal build` to executes tests. This option is useful in scenarios where a developer wants to build an executable with tests. But this new option will execute all tests in the package and we don't have plans to introduce any other options to control test execution,

**Comment by ThisaruGuruge** [comment]
> However, we decided to introduce another option called `--with-tests` to instruct `bal build` to executes tests. This option is useful in scenarios where a developer wants to build an executable with tests. But this new option will execute all tests in the package and we don't have plans to introduce any other options to control test execution,

This might be an issue in some of the cases. In standard library builds we use bal build with tests, we have some scenarios where we need to disable some tests while building. For example, some test cases are disabled in the Windows environment as they can't run on windows. We have to have a way to achieve that.

One solution I can think of is to run tests separately, and then build the package again. But in that case, test coverage information will be lost. I think we should have a way to skip or include selected tests.

**Comment by sameerajayasoma** [comment]
I don't think you are going to lose test coverage when run `bal test` after `bal build`. @hevayo @azinneera @Dilhasha  please confirm.

**Comment by Dilhasha** [comment]
@ThisaruGuruge We can update the workflows in the following order to achieve the requirement right?
- `bal test` with filters to run only the required tests 
- publish Codecov report
- `bal build`
