### ISSUE TITLE
Are module aliases and XML namespace names in a separate symbol space?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#97]
Implementation puts them in a separate symbol space. Spec is not clear.

**Comment by sameerajayasoma** [comment]
I think we need to decide whether it is okay to allow annotation tags to conflict with module aliases and XML namespace names. 

I prefer to keep annotation tags in a separate symbol space from module aliases and XML namespace names. However, I don't have a strong reason for it.

**Comment by jclark** [comment]
The spec is clear that annotation tags are in a separate symbol space from the main symbol space, and that matches the implementation. I see no reason to change at this point.

The issue is whether module aliases together with XML namespace names are in the main symbol space or in a third separate space. It would be very strange to put them into the annotation tags symbol space.

**Comment by sameerajayasoma** [comment]
+1 to have three symbol spaces. 

1) Main symbol space
2) Annotation tags
3) Module aliases and XML namespaces

**Comment by jclark** [comment]
We agreed on this. Spec needs to clarify what symbol space is used for module aliases and XML namespaces.

**Comment by hasithaa** [comment]
According to the #98, we have another symbol space for methods in an object.

Having Module aliases and XML namespaces in different symbol space has an impact on referring public XML namespace from a different module.  `X:` refers to the main symbol space of X, In order to lookup in XML namespace symbol space, we need something special syntax.  

This problem doesn't arise for annotations because We start `@`.

**Comment by jclark** [comment]
You don't get to refer to XML namespace names outside the current module (any more than you refer to module aliases outside the current module).

An XML namespace name is an local name in the module for the namespace URI. If you want to define the namespace URI in a single place, then it should be defined as a string constant.

**Comment by hasithaa** [comment]
For me, it is more natural to define all SOAP ns in the SOAP module and then refer them when accesing an element of a SOAP payload. Otherwise, the user has to repeat the same ns at a consumer module.
Current spec supports having public XML ns in a module, which can be used to support the said use case.

**Comment by jclark** [comment]
It works in Ballerina just like in XML: you must have a namespace prefix declared using xmlns in scope in each place that you use the namespace prefix. In Ballerina, XML namespace declarations work in a uniform way with import declarations (and thus have a similar syntax): they create a name that is local to the module in which they occur, and is in a distinct symbol space from the module's main symbol space.

**Comment by hasithaa** [comment]
This raises the question of, what is semantic of a public `xmlns` statement in a module. Since it allowed in the current version of the spec. Maybe spec should explain, `xmlns` can't be public, like a global variable.

**Comment by jclark** [comment]
The grammar doesn't allow `public` on xmlns.

**Comment by hasithaa** [comment]
Actually, it does in Section 9 Module-level declarations.

```
module-part := import-decl* other-decl*
other-decl := metadata other-decl-item
other-decl-item :=
   module-type-defn
   | module-const-decl
   | module-var-decl
   | listener-decl
   | function-defn
   | outside-method-defn
   | service-decl
   | xmlns-decl-stmt
   | annotation-decl
```

**Comment by jclark** [comment]
You're right. That is a mistake, because all the *-decl and *-defn, such as module-var-decl also allow metadata explicitly. So it should be just

```
other-decl :=
   module-type-defn
   | module-const-decl
   | etc
```
