### ISSUE TITLE
Direct access to bound method that preserves annotations

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#98]
**Description:**
In the current design, object methods live in a sperate namespace, which can be only accessed using method invocation syntax and we can't actually refer method references.  But this is required to get annotation attachments of a method. 

**Code sample that shows the issue:**
```ballerina
type Foo object {
  function bar() {}
}

function main() {
  Foo f = new;
  typedesc t = typeof f.bar; // Not supported now. 
}
```

**Comment by jclark** [comment]
You can get typedesc's for the fields and methods via built-in methods of the typedesc for the object (these methods have not been defined yet); that in turn gives you access to the annotations.

**Comment by jclark** [comment]
It would be nice though to have a syntax to do this.  Without the annotations, there was no need (because you can use return a closure); but now, if you create your own closure, this won't have the right type. In a typical implementation, this will need to allocate new storage (for a closure of the method with the object), so it should be a syntax that suggests that. Suggestions welcome.

**Comment by jclark** [comment]
I will also just explain here why objects have methods and fields in different namespaces:

- we want mappings to be able to arbitrary field names
- we want mappings to have built-in methods
- this implies methods and fields need to be in different namespaces for records
- we want objects to be consistent with records as regards whether fields and methods are in the same namespace

**Comment by hasithaa** [comment]
@jclark @sanjiva, How about,  using `*` at the end.  e.g:  

```ballerina

type Foo object {
  function bar() {}
}

function main() {
  Foo f = new;
  function () ff = f.bar*;
  typedesc t = typeof f.bar*;
}
```

**Comment by jclark** [comment]
I think I would prefer to put something after the `.` which would have the meaning to look the following symbol in the method symbol space rather than the field symbol space, rather like with `.@` now.

**Comment by hasithaa** [comment]
@jclark In the spec, we have Annotation access expression as `@.`  But the operator is defined as `.@` Seems like a bug.

**Comment by jclark** [comment]
I made an issue for that #113.

**Comment by jclark** [comment]
With #574, an expression `x.foo` where `foo` is a method of `x` will result in a bound method.

**Comment by jclark** [comment]
Note that with #145, the type of the bound method does not have `isolated` even if the unbound method does, unless the object is also `isolated` as in #599.

**Comment by jclark** [comment]
More on isolated: in an expression E.foo where E evaluates to an object o and foo is a method of the object, the result of the expression is a function value; this function value will have its isolated bit set if and only if o has its isolated bit set and the foo method of o has its isolated bit set. The static type rules follow from this.
