### ISSUE TITLE
Introduce `icon` field to the `[package]` section in `Ballerina.toml`

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#981]
There is a requirement to associate an icon with the package in Ballerina central. The proposed `icon` field value should be a URL to the icon

**Comment by azinneera** [comment]
> Agreed my intention was user should be able to pack the icon in to the bala.
> 
> Another similar case is we need a way to pack images used for documentation in Package.md and Module.md.
> 
> One approach is we identify the paths of images and pack them in the bala. Or we can introduce a separate directory to keep package specific resources.

We added support for `includes` field in the Ballerina.toml as described in #988. Would that cater to this requirement?
