### ISSUE TITLE
Rest paramter semantic for error constructor

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#99]
**Description:**
Is it allowed to use named arguments in error constructor which are not specified in error detail record of the error type, when the error detail is a open record.

```ballerina
type FooErrorData record {
    string name;
};

type FooError error<string, FooErrorData>;

FooError er1 = error("blah", name = "k", b = "b");

```

**Related Issues:**
https://github.com/ballerina-platform/ballerina-spec/issues/67
https://github.com/ballerina-platform/ballerina-spec/issues/2

**Comment by jclark** [comment]
Yes, just as it would be OK in a mapping constructor.
