### ISSUE TITLE
Clarify whether the int overflow value is `-9,2 ...808` or ` -9,2 ...809`

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-spec#990]
**Description:**
The language spec says 
```
The int type consists of integers between -9,223,372,036,854,775,808 and 9,223,372,036,854,775,807
```
Which indicates the `MAX_VALUE` would be 9,223,372,036,854,775,807 (`2^63 -1`) and `MIN_VALUE` would be -9,223,372,036,854,775,808  (`-2^63`). So the overflow value would be `-2^63 - 1` = -9,223,372,036,854,775,809.

But the `int` langlib specifies the value -9,223,372,036,854,775,808 would overflow. 
https://github.com/ballerina-platform/ballerina-spec/blob/11277d73b77f5f0c2871c7e7f04cc803ca9f31b2/lang/lib/int.bal#L57

What should be the int overflow value ?  -9,223,372,036,854,775,808 or  -9,223,372,036,854,775,809?

**Related Issues:**
[#32590](https://github.com/ballerina-platform/ballerina-lang/issues/32590)

**Comment by jclark** [comment]
`-9223372036854775808` is a unary minus expression i.e. `-` applied to `9223372036854775808`.
