### ISSUE TITLE
`bal build`: Introduce a flag to generate JSON schema for configurable variables

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-spec#992]
We have developed a compiler plugin to generate a JSON schema for the configurable variables defined in a package at the path `target/bin/config-schema.json`.  Currently, this is not packed in the Ballerina Beta4 distribution.

We are planning to expose this functionality to users using a flag for `bal build`.

We are yet to finalize the flag name. Here are some suggestions:
`--generate-config-schema`
`--config-schema-json`

**Comment by sameerajayasoma** [comment]
As per my understanding, the use case is to validate `*.toml` files that supply values for configurable variables in a Ballerina program. 

`--generate-config-schema` is better IMO.

**Comment by Dilhasha** [comment]
Added flag implementation with https://github.com/ballerina-platform/ballerina-lang/pull/33866. Hence, closing.
