### ISSUE TITLE
Clarification on inferring array size from the context

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-spec#993]
**Description:**
$title. Spec explains the [inferred-array-length](https://ballerina.io/ballerina-spec/spec.html#inferred-array-length) as below. 
```
An array length of * means that the length of the array is to be inferred from the context; this is allowed only within a type descriptor occurring in a context that is specified to be inferable; its meaning is the same as if the length was specified explicitly. 
```
There are many possible situations which can (or cannot) be used to infer the array size from the context as follows (currently identified).

1. 
```ballerina
int[*][*] x = [[1], [2]]; // Proposed behaviour: int[1][2] x = [[1], [2]];
```
2. 
```ballerina
int[3] a = [1, 2, 3];
int[*] x = a; // Proposed behaviour: int[3] x = a;
```
3. 
```ballerina
map<int[1][*]> a = {“1” : [[1], [2]]}; // Proposed behaviour: map<int[1][2]> a = {“1” : [[1], [2]]};
```
4. 
```ballerina
map<int[1][2]> a = {“1” : [[1], [2]]};
int[1][*] x = a[“1”]; // Proposed behaviour: int[1][2] x = a["1"];
```
5. 
```ballerina
type T record {|
    int[2] a;
|}
T x = {a: [1, 2]};
int[*] y = x.a; // Proposed behaviour: int[2] y = x.a;
```
6. 
```ballerina
int[*][3] | int[1][2] x = [[1], [2], [3]]; // Proposed behaviour: int[1][3] | int[1][2] x = [[1], [2], [3]];
```
7. 
```ballerina
int[1][2] a =  [[1], [2]];
int[*][2] | string[*][3] x = a; // Proposed behaviour: error since string[*][3] cannot be resolved
```
8. 
```ballerina
[int, int] a = [1, 2];
int[*] x = a; // Proposed behaviour: int[2] x = a;
```
9. 
```ballerina
function foo1() returns int[*] { // Proposed behaviour: error since there can be confictions
        boolean b = false;
        if b {
            return [1, 2];
        }
        return [1, 2, 3]; 
}

function foo2() returns int[*] { // Proposed behaviour: error since there can be confictions
        boolean b = false;
        if b {
            return [3, 2, 1];
        }
        return [1, 2, 3]; 
}
```
10. 
```ballerina
function foo() returns int[3] { 
        boolean b = false;
        if b {
            return [3, 2, 1];
        }
        return [1, 2, 3]; 
}
int[*] x = foo(); // Proposed behaviour: int[3] x = foo();
```
10. 
```ballerina
int[1][2] a = [[1], [2]]; 
int[1][*] | int[*][*] x = [[1], [2]]; 
// Proposed behaviour: int[1][2] | int[1][2] x = [[1], [2]];
```
11. 
```ballerina
int[] a = [[1], [2]]; 
int[*] x = a; // Proposed behaviour: error, since `a` is an opened array.
```
Needed to clarify which scenarios should be allowed to infer the array size from the context?

**Related Issues:**
[#32396](https://github.com/ballerina-platform/ballerina-lang/issues/32396)

**Comment by jclark** [comment]
The point is to be able to infer the length from the number of members of a constructor in the initializer.  I think it's simpler to restrict it to that specific situation.  I don't see the benefit of supporting any of the above situations.

**Comment by hasithaa** [comment]
> The point of `*` for array types is to be able to infer the length from the number of members of a constructor in the initializer. I think it's simpler to restrict it to that specific situation. I don't see the benefit of supporting any of the above situations.

if we do so, better to allow only this in the context of [`local-var-decl-stmt`](https://ballerina.io/ballerina-spec/spec.html#local-var-decl-stmt) and [`module-init-var-decl`](https://ballerina.io/ballerina-spec/spec.html#module-init-var-decl). Other cases can be complicated. 
Btw, this is a breaking change.

**Comment by jclark** [comment]
Also `module-const-decl`.

**Comment by lochana-chathura** [comment]
Re-opened the issue as the spec is not updated with the conclusion drawn.

**Comment by jclark** [comment]
I think the only useful case is the first dimension. Given #1001, we can now do this restrict it to the first dimension syntactically.

I can't think of any use case for other than the first dimension. @hasithaa Can you?

**Comment by hasithaa** [comment]
> I think the only useful case is the first dimension. Given #1001, we can now do this restrict it to the first dimension syntactically.
> 
> I can't think of any use case for other than the first dimension. @hasithaa Can you?

+1 for the suggestions. I believe writing the exact length is clean when it comes to arrays of arrays.
