### ISSUE TITLE
The return type of the lang.table's map function when argument is an anonymous function expr.

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-spec#994]
Consider the following code.  The inferred type of the anonymous function expressions, are derived from the contextually expected type. In below case, What should be the return type of the anonymous function expr? is it the typeParam `map<MapType1>` (which is `map<any|error>)` or do we consider as there is no contextually expected type?

```ballerina
import ballerina/io;

type Employee record {
    int id;
    string name;
};

public function main() {
    table<Employee> tb = table [];
    
    var a = tb.map(r => {x: r.id});
    io:println(a is table<record {| int x; |}>);  // prints true
    io:println(a is table<map<any|error>>);  //prints true
}
```

**Comment by hasithaa** [comment]
I had a discussion with @gimantha and clarified issue.
