### ISSUE TITLE
Clarification on bitwise expression with numeric literal

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-spec#997]
**Description:**
**Program 1**
```ballerina
public function main() {
    byte x = 0xA & 10;
}
```
**Program 2**
```ballerina
public function main() {
    byte x =10 & 10;
}
```
In the current behaviour of the compiler, we allow `program 1` and we disallow `program 2`. 

In the `binary bitwise expression` section of the spec, it is mentioned as below
```
for AND, if the type of either operand is a subtype of int:UnsignedK when K is 8, 16 or 32, then the static type of the result is int:UnsignedN where N is the smallest such K; otherwise, the static type of the result is int;
```
According to that, we need to allow both of these two cases. right?
In this BBE(https://ballerina.io/learn/by-example/binary-data) also we used hexadecimal as numeric. Is there any special reason for that?

**Comment by jclark** [comment]
It should not make any difference whether you use decimal or hex to write an integer constant.

**Comment by MaryamZi** [comment]
To allow 

```ballerina
byte x = 10 & 10; // or `0xA & 10`
```

shouldn't the static types of the literals be determined as `byte` (as opposed to `int`)?

To do so, shouldn't the spec define how the contextually-expected type is determined for the operands of each kind of expression under [6.30 Binary bitwise expression](https://ballerina.io/ballerina-spec/spec.html#section_6.30)?

**Comment by jclark** [comment]
The static type of `10` is a singleton, which is a subtype of `byte`.  All we need is for contextually expected type to be `int` (or rather not `float`) so that it's a singleton that's a subtype of `int`.

I think I'm missing your point...

Contextually expected type flows down and influences the choice of static type which flows back up, but they aren't the same thing.

**Comment by MaryamZi** [comment]
My bad, I did not consider https://github.com/ballerina-platform/ballerina-spec/issues/902 here correctly. I thought the static types of the operands here would be non-singleton types (derived based on the rules for numeric literals) and was comparing this to how we make use of the contextually-expected type with multiplicative and additive expressions. 

I see now why we don't need that. Thank you!
